package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunSucceedsWithExactlyPackageFileLimit(t *testing.T) {
	t.Parallel()

	repoRoot := t.TempDir()
	writePackageFiles(t, repoRoot, "pkg/service", 15)

	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	err := run(config{
		root:             repoRoot,
		packageRoot:      defaultScanRoot,
		packageFileLimit: defaultPackageFileLimit,
	}, stdout, stderr)
	if err != nil {
		t.Fatalf("run() error = %v, want nil", err)
	}
	if got := stdout.String(); !strings.Contains(got, "package file-count passed (package files <= 15)") {
		t.Fatalf("run() stdout = %q, want success message with default limit", got)
	}
	if got := stderr.String(); got != "" {
		t.Fatalf("run() stderr = %q, want empty", got)
	}
}

func TestRunFailsWhenPackageExceedsPackageFileLimit(t *testing.T) {
	t.Parallel()

	repoRoot := t.TempDir()
	writePackageFiles(t, repoRoot, "pkg/service", 16)

	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	err := run(config{
		root:             repoRoot,
		packageRoot:      defaultScanRoot,
		packageFileLimit: defaultPackageFileLimit,
	}, stdout, stderr)
	if err == nil {
		t.Fatal("run() error = nil, want package file-count violation")
	}
	if got := stdout.String(); got != "" {
		t.Fatalf("run() stdout = %q, want empty", got)
	}

	errOutput := stderr.String()
	wantOutput := strings.Join([]string{
		"[agent-factory:pkg-file-count] oversized package: pkg/service",
		"  package files: 16",
		"  limit: 15",
		"  counted files:",
		"    - pkg/service/file_01.go",
		"    - pkg/service/file_02.go",
		"    - pkg/service/file_03.go",
		"    - pkg/service/file_04.go",
		"    - pkg/service/file_05.go",
		"    - pkg/service/file_06.go",
		"    - pkg/service/file_07.go",
		"    - pkg/service/file_08.go",
		"    - pkg/service/file_09.go",
		"    - pkg/service/file_10.go",
		"    - pkg/service/file_11.go",
		"    - pkg/service/file_12.go",
		"    - pkg/service/file_13.go",
		"    - pkg/service/file_14.go",
		"    - pkg/service/file_15.go",
		"    - pkg/service/file_16.go",
		"",
	}, "\n")
	if errOutput != wantOutput {
		t.Fatalf("run() stderr = %q, want deterministic package count details %q", errOutput, wantOutput)
	}
	if got := err.Error(); got != "[agent-factory:pkg-file-count] found 1 package file-count violation(s)" {
		t.Fatalf("run() error = %q, want violation count", got)
	}
}

func TestRunCountsPackageTestFiles(t *testing.T) {
	t.Parallel()

	repoRoot := t.TempDir()
	writePackageFiles(t, repoRoot, "pkg/service", 14)
	writeGoFile(t, repoRoot, "pkg/service/service_test.go", "package service\n\nfunc TestService(t *testing.T) {}\n")

	err := run(config{
		root:             repoRoot,
		packageRoot:      defaultScanRoot,
		packageFileLimit: defaultPackageFileLimit,
	}, &bytes.Buffer{}, &bytes.Buffer{})
	if err != nil {
		t.Fatalf("run() error = %v, want nil with 15 files including _test.go", err)
	}

	writeGoFile(t, repoRoot, "pkg/service/extra_test.go", "package service\n\nfunc TestExtra(t *testing.T) {}\n")
	err = run(config{
		root:             repoRoot,
		packageRoot:      defaultScanRoot,
		packageFileLimit: defaultPackageFileLimit,
	}, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil {
		t.Fatal("run() error = nil, want _test.go files to count toward package limit")
	}
}

func TestRunExcludesGeneratedVendorAndFixtureRoots(t *testing.T) {
	t.Parallel()

	repoRoot := t.TempDir()
	writePackageFiles(t, repoRoot, "pkg/service", 15)
	writePackageFiles(t, repoRoot, "pkg/api/generated", 16)
	writePackageFiles(t, repoRoot, "pkg/generatedclient", 16)
	writePackageFiles(t, repoRoot, "pkg/service/testdata/fixture", 16)
	writePackageFiles(t, repoRoot, "vendor/example", 16)
	writeGoFile(t, repoRoot, "pkg/service/generated.go", strings.Join([]string{
		"// Code generated by test fixture. DO NOT EDIT.",
		"package service",
		"",
		"func Generated() {}",
	}, "\n"))

	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	err := run(config{
		root:             repoRoot,
		packageRoot:      defaultScanRoot,
		packageFileLimit: defaultPackageFileLimit,
	}, stdout, stderr)
	if err != nil {
		t.Fatalf("run() error = %v, want nil when only excluded roots exceed limit", err)
	}
	if got := stderr.String(); got != "" {
		t.Fatalf("run() stderr = %q, want empty", got)
	}
}

func TestRunReportsMultiplePackagesDeterministically(t *testing.T) {
	t.Parallel()

	repoRoot := t.TempDir()
	writePackageFiles(t, repoRoot, "pkg/zeta", 16)
	writePackageFiles(t, repoRoot, "pkg/alpha", 16)

	stderr := &bytes.Buffer{}
	err := run(config{
		root:             repoRoot,
		packageRoot:      defaultScanRoot,
		packageFileLimit: defaultPackageFileLimit,
	}, &bytes.Buffer{}, stderr)
	if err == nil {
		t.Fatal("run() error = nil, want package file-count violations")
	}

	errOutput := stderr.String()
	alphaIndex := strings.Index(errOutput, "[agent-factory:pkg-file-count] oversized package: pkg/alpha")
	zetaIndex := strings.Index(errOutput, "[agent-factory:pkg-file-count] oversized package: pkg/zeta")
	if alphaIndex < 0 || zetaIndex < 0 || alphaIndex > zetaIndex {
		t.Fatalf("run() stderr = %q, want packages reported in path order", errOutput)
	}
	if got := strings.Count(errOutput, "  counted files:\n"); got != 2 {
		t.Fatalf("run() stderr = %q, want counted file section for each package", errOutput)
	}
	if got := err.Error(); got != "[agent-factory:pkg-file-count] found 2 package file-count violation(s)" {
		t.Fatalf("run() error = %q, want two violation count", got)
	}
}

func TestMakePkgFileCountTargetFailsForOversizedOwnedPackage(t *testing.T) {
	repoRoot := filepath.Clean(filepath.Join("..", ".."))
	fixtureRoot := t.TempDir()
	writePackageFiles(t, fixtureRoot, "pkg/service", 16)

	cmd := exec.Command("make", "pkg-file-count", "PACKAGE_FILE_COUNT_ROOT="+fixtureRoot)
	cmd.Dir = repoRoot
	output, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("make pkg-file-count succeeded, want oversized package failure; output:\n%s", output)
	}

	got := string(output)
	for _, want := range []string{
		"go run ./cmd/pkgfilecountcheck -root " + fixtureRoot,
		"[agent-factory:pkg-file-count] oversized package: pkg/service",
		"  package files: 16",
		"  limit: 15",
		"[agent-factory:pkg-file-count] found 1 package file-count violation(s)",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("make pkg-file-count output = %q, want substring %q", got, want)
		}
	}
}

func TestMakeLintPathFailsForOversizedOwnedPackage(t *testing.T) {
	repoRoot := filepath.Clean(filepath.Join("..", ".."))
	fixtureRoot := t.TempDir()
	writePackageFiles(t, fixtureRoot, "pkg/service", 16)

	cmd := exec.Command("make", "lint", "LINT_TARGETS=pkg-file-count", "PACKAGE_FILE_COUNT_ROOT="+fixtureRoot)
	cmd.Dir = repoRoot
	output, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("make lint succeeded, want oversized package failure through lint path; output:\n%s", output)
	}

	got := string(output)
	for _, want := range []string{
		"go run ./cmd/pkgfilecountcheck -root " + fixtureRoot,
		"[agent-factory:pkg-file-count] oversized package: pkg/service",
		"  package files: 16",
		"  limit: 15",
		"[agent-factory:pkg-file-count] found 1 package file-count violation(s)",
		"*** [pkg-file-count]",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("make lint output = %q, want substring %q", got, want)
		}
	}
}

func TestRunRejectsNonPositivePackageFileLimit(t *testing.T) {
	t.Parallel()

	err := run(config{root: t.TempDir(), packageRoot: defaultScanRoot, packageFileLimit: 0}, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil || err.Error() != "package file limit must be positive, got 0" {
		t.Fatalf("run() error = %v, want package file limit validation", err)
	}
}

func writePackageFiles(t *testing.T, repoRoot string, packagePath string, count int) {
	t.Helper()

	for i := 1; i <= count; i++ {
		writeGoFile(t, repoRoot, filepath.ToSlash(filepath.Join(packagePath, fmt.Sprintf("file_%02d.go", i))), "package fixture\n\nfunc File() {}\n")
	}
}

func writeGoFile(t *testing.T, repoRoot string, relativePath string, content string) {
	t.Helper()

	absolutePath := filepath.Join(repoRoot, filepath.FromSlash(relativePath))
	if err := os.MkdirAll(filepath.Dir(absolutePath), 0o755); err != nil {
		t.Fatalf("create parent directory for %s: %v", relativePath, err)
	}
	if err := os.WriteFile(absolutePath, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", relativePath, err)
	}
}
