package validation

const (
	CodeDuplicateIdentifier                     = "factory.duplicateIdentifier"
	CodeDanglingWorkerReference                 = "factory.worker.danglingReference"
	CodeDanglingPlaceReference                  = "factory.route.danglingPlaceReference"
	CodeDanglingResourceReference               = "factory.resource.danglingReference"
	CodeWorkstationMissingOutputRoutes          = "factory.workstation.missingOutputRoutes"
	CodeWorkstationMissingFailureRoute          = "factory.workstation.missingFailureRoute"
	CodeWorkstationMissingRejectionRoute        = "factory.workstation.missingRejectionRoute"
	CodeWorkstationConflictingOutputs           = "factory.workstation.conflictingWorkStateOutputs"
	CodeWorkTypeMissingCompletionState          = "factory.workType.missingCompletionState"
	CodeWorkTypeMissingFailureState             = "factory.workType.missingFailureState"
	CodeWorkStateMissingTerminalPath            = "factory.workState.missingTerminalCompletionPath"
	CodeWorkTypeHandlingBehaviorValue           = "work-type-handling-behavior-value"
	CodeWorkTypeHandlingBehaviorDuplicate       = "work-type-handling-behavior-duplicate"
	CodeWorkTypeHandlingBehaviorUniqueDefault   = "work-type-handling-behavior-unique-default"
	CodeWorkTypeHandlingBehaviorRequiredDefault = "work-type-handling-behavior-required-default"
	CodeInvocationReturnUnsupportedPolicy       = "factory.invocationReturn.unsupportedPolicy"
	CodeInvocationReturnMissingWorkTypeName     = "factory.invocationReturn.missingWorkTypeName"
	CodeInvocationReturnMissingTerminalState    = "factory.invocationReturn.missingTerminalState"
	CodeInvocationReturnUnknownWorkTypeName     = "factory.invocationReturn.unknownWorkTypeName"
	CodeInvocationReturnInvalidTerminalState    = "factory.invocationReturn.invalidTerminalState"
	CodeManagedRuntimeUnsupportedIdentity       = "factory.managedRuntime.unsupportedIdentity"
	CodeManagedRuntimeInvalidBackend            = "factory.managedRuntime.invalidBackend"
	CodeManagedRuntimeInvalidLoadPolicy         = "factory.managedRuntime.invalidLoadPolicy"
	CodeManagedRuntimeWorkerMissingModel        = "factory.managedRuntime.workerMissingModel"
	CodeManagedRuntimeWorkerMissingDep          = "factory.managedRuntime.workerMissingDependency"
	CodeManagedRuntimeWorkerModelMismatch       = "factory.managedRuntime.workerModelMismatch"
	CodeLayoutUnknownNodeReference              = "factory.layout.unknownNodeReference"
	CodeLayoutUnknownEdgeReference              = "factory.layout.unknownEdgeReference"
	CodeLayoutUnknownGroupMemberReference       = "factory.layout.unknownGroupMemberReference"
	CodeLayoutUnsupportedSchemaVersion          = "factory.layout.unsupportedSchemaVersion"
	CodeLayoutInvalidGeometry                   = "factory.layout.invalidGeometry"
	CodeOrchestratorUnsupportedKind             = "factory.orchestrator.unsupportedKind"
	CodeOrchestratorIncompatiblePetriConfig     = "factory.orchestrator.incompatiblePetriConfig"
	CodeOrchestratorIncompatibleJavaScriptConfig = "factory.orchestrator.incompatibleJavaScriptConfig"
	CodeOrchestratorIncompatiblePetriField      = "factory.orchestrator.incompatiblePetriField"
	CodeOrchestratorJavaScriptMissingConfig     = "factory.orchestrator.javascriptMissingConfig"
	CodeOrchestratorJavaScriptMissingSource     = "factory.orchestrator.javascriptMissingSource"
	CodeOrchestratorJavaScriptConflictingSource = "factory.orchestrator.javascriptConflictingSource"
	CodeOrchestratorJavaScriptInvalidInlineEncoding = "factory.orchestrator.javascriptInvalidInlineEncoding"
)
