package climanifestgen

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/portpowered/infinite-you/internal/contractjoiner"
	"github.com/portpowered/infinite-you/pkg/transports/cli/climanifest"
)

const (
	// ProductionManifestPath is the authored CLI command manifest input.
	ProductionManifestPath = climanifest.ProductionManifestPath

	// RepresentativeFamilyJSONPath is the generated representative-family metadata artifact.
	RepresentativeFamilyJSONPath = "pkg/transports/cli/generated/representative_family.json"

	// RepresentativeFamilyCommandIDsPath is the generated stable command ID list.
	RepresentativeFamilyCommandIDsPath = "pkg/transports/cli/generated/command_ids_gen.go"
)

// Artifact returns the deterministic generated representative-family metadata bytes.
func Artifact(repositoryRoot string) ([]byte, error) {
	manifestPath := filepath.Join(repositoryRoot, filepath.FromSlash(ProductionManifestPath))
	manifest, err := climanifest.LoadProduction(manifestPath)
	if err != nil {
		return nil, err
	}
	family, err := ExtractRepresentativeFamily(manifest)
	if err != nil {
		return nil, err
	}
	return contractjoiner.MarshalCanonicalJSON(family)
}

// Generate writes the representative-family metadata artifacts for review and drift checks.
func Generate(repositoryRoot string) error {
	payload, err := Artifact(repositoryRoot)
	if err != nil {
		return err
	}

	jsonTarget := filepath.Join(repositoryRoot, filepath.FromSlash(RepresentativeFamilyJSONPath))
	if err := os.MkdirAll(filepath.Dir(jsonTarget), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", RepresentativeFamilyJSONPath, err)
	}
	if err := os.WriteFile(jsonTarget, payload, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", RepresentativeFamilyJSONPath, err)
	}

	idsTarget := filepath.Join(repositoryRoot, filepath.FromSlash(RepresentativeFamilyCommandIDsPath))
	if err := os.WriteFile(idsTarget, commandIDsSource(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", RepresentativeFamilyCommandIDsPath, err)
	}
	return nil
}

func commandIDsSource() []byte {
	return []byte(`// Code generated by climanifestgen. DO NOT EDIT.

package generated

// RepresentativeFamilyCommandIDs lists the stable command IDs emitted from
// contracts/cli/commands.json for the representative root/session-show family.
var RepresentativeFamilyCommandIDs = []string{
	"you",
	"you.session",
	"you.session.show",
}
`)
}
