package climanifestgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/portpowered/infinite-you/internal/contractjoiner"
	"github.com/portpowered/infinite-you/pkg/transports/cli/climanifest"
)

const (
	// ProductionManifestPath is the authored CLI command manifest input.
	ProductionManifestPath = climanifest.ProductionManifestPath

	// RepresentativeFamilyJSONPath is the generated representative-family metadata artifact.
	RepresentativeFamilyJSONPath = "pkg/transports/cli/generated/representative_family.json"

	// WorkFamilyJSONPath is the generated work-family metadata artifact.
	WorkFamilyJSONPath = "pkg/transports/cli/generated/work_family.json"

	// RepresentativeFamilyCommandIDsPath is the generated stable command ID list.
	RepresentativeFamilyCommandIDsPath = "pkg/transports/cli/generated/command_ids_gen.go"
)

// Artifact returns the deterministic generated representative-family metadata bytes.
func Artifact(repositoryRoot string) ([]byte, error) {
	manifestPath := filepath.Join(repositoryRoot, filepath.FromSlash(ProductionManifestPath))
	manifest, err := climanifest.LoadProduction(manifestPath)
	if err != nil {
		return nil, err
	}
	family, err := ExtractRepresentativeFamily(manifest)
	if err != nil {
		return nil, err
	}
	return contractjoiner.MarshalCanonicalJSON(family)
}

// WorkArtifact returns the deterministic generated work-family metadata bytes.
func WorkArtifact(repositoryRoot string) ([]byte, error) {
	manifestPath := filepath.Join(repositoryRoot, filepath.FromSlash(ProductionManifestPath))
	manifest, err := climanifest.LoadProduction(manifestPath)
	if err != nil {
		return nil, err
	}
	family, err := ExtractWorkFamily(manifest)
	if err != nil {
		return nil, err
	}
	return contractjoiner.MarshalCanonicalJSON(family)
}

// Generate writes the representative- and work-family metadata artifacts for review and drift checks.
func Generate(repositoryRoot string) error {
	representativePayload, err := Artifact(repositoryRoot)
	if err != nil {
		return err
	}
	workPayload, err := WorkArtifact(repositoryRoot)
	if err != nil {
		return err
	}

	representativeTarget := filepath.Join(repositoryRoot, filepath.FromSlash(RepresentativeFamilyJSONPath))
	if err := os.MkdirAll(filepath.Dir(representativeTarget), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", RepresentativeFamilyJSONPath, err)
	}
	if err := os.WriteFile(representativeTarget, representativePayload, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", RepresentativeFamilyJSONPath, err)
	}

	workTarget := filepath.Join(repositoryRoot, filepath.FromSlash(WorkFamilyJSONPath))
	if err := os.MkdirAll(filepath.Dir(workTarget), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", WorkFamilyJSONPath, err)
	}
	if err := os.WriteFile(workTarget, workPayload, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", WorkFamilyJSONPath, err)
	}

	idsTarget := filepath.Join(repositoryRoot, filepath.FromSlash(RepresentativeFamilyCommandIDsPath))
	if err := os.WriteFile(idsTarget, commandIDsSource(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", RepresentativeFamilyCommandIDsPath, err)
	}
	return nil
}

func commandIDsSource() []byte {
	var builder strings.Builder
	builder.WriteString(`// Code generated by climanifestgen. DO NOT EDIT.

package generated

`)
	writeCommandIDVar(&builder, "RepresentativeFamilyCommandIDs", "representative root/session-show family", RepresentativeFamilyCommandIDs)
	builder.WriteString("\n")
	writeCommandIDVar(&builder, "WorkFamilyCommandIDs", "work inspection/control family", WorkFamilyCommandIDs)
	return []byte(builder.String())
}

func writeCommandIDVar(builder *strings.Builder, varName, familyLabel string, ids []string) {
	fmt.Fprintf(builder, "// %s lists the stable command IDs emitted from\n", varName)
	fmt.Fprintf(builder, "// contracts/cli/commands.json for the %s.\n", familyLabel)
	fmt.Fprintf(builder, "var %s = []string{\n", varName)
	for _, id := range ids {
		fmt.Fprintf(builder, "\t%q,\n", id)
	}
	builder.WriteString("}\n")
}
