// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package composition

import (
	"context"
	"github.com/portpowered/infinite-you/pkg/service"
)

// Injectors from wire.go:

// BuildFactoryService is the Wire injector for the factory CLI composition root.
func BuildFactoryService(ctx context.Context, cfg *service.FactoryServiceConfig) (*service.FactoryService, error) {
	factoryServiceBuildContext, err := service.ProvideFactoryServiceBuildContext(ctx, cfg)
	if err != nil {
		return nil, err
	}
	registry := service.ProvideFactorySessionsRegistry()
	localModelDomain := service.ProvideStartupLocalModelDomainPtr(cfg)
	runtimebuildService := service.ProvideRuntimeBuildService(cfg, factoryServiceBuildContext, localModelDomain)
	factoryServiceCollaborators := service.ProvideFactoryServiceCollaborators(registry, localModelDomain, runtimebuildService)
	factoryRuntimeBundle, err := service.ProvideFactoryRuntimeBundle(ctx, cfg, factoryServiceBuildContext, factoryServiceCollaborators)
	if err != nil {
		return nil, err
	}
	config := service.ProvideHostedWorkersConfig(cfg, factoryRuntimeBundle, factoryServiceBuildContext)
	factoryServiceShell, err := service.ProvideFactoryServiceShell(cfg, factoryServiceBuildContext, factoryServiceCollaborators, factoryRuntimeBundle, config)
	if err != nil {
		return nil, err
	}
	factorySaveSaver := service.ProvideFactorySaveCollaborator(factoryServiceShell, cfg)
	factoryService := service.AttachFactorySaveCollaborator(factoryServiceShell, factorySaveSaver)
	return factoryService, nil
}
