package customer_workflows_test

import "testing"

// TestWorkflowContractJourneys owns its immutable fixture until all customer scenarios finish.
func TestWorkflowContractJourneys(t *testing.T) {
	t.Parallel()
	initializeContractsFixture(t)
	t.Run("TestJavaScriptInvocationReceivesStringNumberBooleanObjectAndArrayInputs", testContractsJavaScriptInvocationReceivesStringNumberBooleanObjectAndArrayInputs)
	t.Run("TestJavaScriptMissingRequiredInputFailsBeforeChildDispatch", testContractsJavaScriptMissingRequiredInputFailsBeforeChildDispatch)
	t.Run("TestJavaScriptReturnValueMapsToPrimaryInvocationResult", testContractsJavaScriptReturnValueMapsToPrimaryInvocationResult)
	t.Run("TestJavaScriptStructuredArtifactsMapToPublicResult", testContractsJavaScriptStructuredArtifactsMapToPublicResult)
	t.Run("TestJavaScriptUnsupportedReturnValueFailsWithoutPrivateVMDetails", testContractsJavaScriptUnsupportedReturnValueFailsWithoutPrivateVMDetails)
	t.Run("TestJavaScriptChildProgressPublishesCanonicalResponseEvents", testContractsJavaScriptChildProgressPublishesCanonicalResponseEvents)
	t.Run("TestJavaScriptTerminalResultFollowsFinalResponseEvent", testContractsJavaScriptTerminalResultFollowsFinalResponseEvent)
	t.Run("TestJavaScriptPhaseCheckpointLifecyclePublishesCanonicalFactoryEvents", testContractsJavaScriptPhaseCheckpointLifecyclePublishesCanonicalFactoryEvents)
}
