// Package run implements the agent-factory run command behavior.
package run

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/portpowered/infinite-you/pkg/services/work"

	"github.com/portpowered/infinite-you/pkg/transports/cli/clidiag"
	"github.com/portpowered/infinite-you/pkg/transports/cli/dashboard"
	"github.com/portpowered/infinite-you/pkg/transports/cli/runconfig"
	"github.com/portpowered/infinite-you/pkg/transports/cli/terminalpolicy"
	"github.com/portpowered/infinite-you/pkg/transports/cli/timedisplay"
	factoryapi "github.com/portpowered/infinite-you/pkg/transports/http/generated"

	"github.com/portpowered/infinite-you/pkg/initializer"
	platformfilesystem "github.com/portpowered/infinite-you/pkg/platform/filesystem"
	"github.com/portpowered/infinite-you/pkg/platform/runtimeartifact"
	interfaces "github.com/portpowered/infinite-you/pkg/services/factory_definitions"
	state "github.com/portpowered/infinite-you/pkg/services/factory_runtime"
	factorysessions "github.com/portpowered/infinite-you/pkg/services/factory_sessions"
	factoryvisualization "github.com/portpowered/infinite-you/pkg/services/factory_visualization"
	"github.com/portpowered/infinite-you/pkg/services/recordings"
	"github.com/portpowered/infinite-you/pkg/services/workers"
	"go.uber.org/zap"
)

type RunConfig = runconfig.Config

// ModelCacheDirEnvironment selects the managed local-model cache root at the
// customer process boundary.
const ModelCacheDirEnvironment = "INFINITE_YOU_OMNIVOICE_CACHE_DIR"

type factoryServiceRunner interface {
	Run(ctx context.Context) error
}

// RuntimeRunner is the local in-process runtime seam used by CLI startup.
type RuntimeRunner = factoryServiceRunner

type engineStateSnapshotProvider interface {
	GetEngineStateSnapshot(context.Context) (*interfaces.EngineStateSnapshot[state.PetriMarkingSnapshot, *state.Net], error)
}

type cleanInvocationSuccess struct {
	Output       string `json:"output"`
	WorkID       string `json:"workId"`
	WorkTypeName string `json:"workTypeName"`
	TraceID      string `json:"traceId,omitempty"`
	SessionID    string `json:"sessionId,omitempty"`
}

type cleanInvocationWorkTarget struct {
	WorkID       string
	WorkTypeName string
}

// RuntimeRunnerBuilder is the CLI edge adapter for one owner-bounded Factory
// Sessions request. Wire converts the request and presentation sink into an
// initializer.ApplicationOpeningOperation before invoking the neutral
// Initializer builder.
type RuntimeRunnerBuilder func(
	context.Context,
	factorysessions.ApplicationOpeningRequest,
	*zap.Logger,
	factoryvisualization.Sink,
) (initializer.LocalRuntimeRunner, error)

// RuntimeOpeningRequestFactory is the Wire-selected mapping from CLI values
// to one immutable Factory Sessions operation request.
type RuntimeOpeningRequestFactory func(
	RunConfig,
	*workers.MockWorkersConfig,
	factorysessions.RuntimeHostObserver,
) factorysessions.ApplicationOpeningRequest

type Opener func(
	context.Context,
	RunConfig,
	RuntimeRunnerBuilder,
	InvocationOperation,
	factoryvisualization.ResponsePresentation,
) (*Operation, error)

const (
	completedPlaceIDSuffix  = "completed"
	failedPlaceIDSuffix     = "failed"
	defaultFactorySessionID = "~default"
)

func bootstrapFactoryWithInitializer(
	dir string,
	initialize interfaces.ScaffoldInitializer,
	resolve interfaces.CurrentFactoryDirectoryResolver,
	directories platformfilesystem.DirectoryCreator,
) error {
	if resolve == nil {
		return fmt.Errorf("bootstrap Factory Definition at %q: current Factory resolver is required", dir)
	}
	resolvedDir, err := resolve(dir)
	if err != nil {
		if errors.Is(err, interfaces.ErrFactoryLayoutNotFound) {
			if initialize == nil {
				return fmt.Errorf("bootstrap Factory Definition at %q: scaffold initializer is required", dir)
			}
			return initialize(interfaces.ScaffoldConfig{Dir: dir})
		}
		return err
	}

	defaultInputDir := filepath.Join(resolvedDir, interfaces.InputsDir, interfaces.DefaultFactoryInputType, interfaces.DefaultChannelName)
	if directories == nil {
		return fmt.Errorf("bootstrap Factory Definition at %q: directory creator is required", dir)
	}
	return directories.MkdirAll(defaultInputDir, 0o755)
}

type resolvedRunRecordPath struct {
	servicePath   string
	reportedPath  string
	autoGenerated bool
}

// Operation is one invocation-local run selected by the customer command.
// Its runtime state is opened through injected service operations.
type Operation struct {
	cfg               RunConfig
	logger            *zap.Logger
	runner            RuntimeRunner
	invocationRequest *factoryapi.InvocationRequest
	invocationTarget  factorysessions.InvocationTarget
	invocation        InvocationOperation
	presentation      factoryvisualization.ResponsePresentation
	prepareWorkTarget work.SingleWorkTargetPreparation
	invocationMode    bool
	recordPath        resolvedRunRecordPath
}

// Open resolves run inputs and opens invocation-local runtime state without
// starting its transport, sidecars, or runtime loop.
func Open(
	ctx context.Context,
	cfg RunConfig,
	buildRunner RuntimeRunnerBuilder,
	invocation InvocationOperation,
	presentation factoryvisualization.ResponsePresentation,
	prepareWorkTarget work.SingleWorkTargetPreparation,
	loadMockWorkers workers.MockWorkersConfigLoader,
	buildRuntimeRequest RuntimeOpeningRequestFactory,
) (*Operation, error) {
	cfg = normalizeRunInvocationMode(cfg)
	logger := cfg.Logger
	if logger == nil {
		logger = zap.NewNop()
	}
	cfg, invocationRequest, invocationMode, recordPath, err := prepareRunConfig(cfg)
	if err != nil {
		return nil, err
	}

	mockWorkersConfig, err := loadSelectedMockWorkersConfig(cfg, loadMockWorkers)
	if err != nil {
		return nil, err
	}

	requestedPort := cfg.Port
	emitNamedFactoryResolutionDiagnostics(cfg, logger)

	if invocationMode {
		emitVerboseStartupDiagnostics(cfg, recordPath, requestedPort)
		return openInvocation(
			ctx,
			cfg,
			logger,
			invocationRequest,
			recordPath,
			invocation,
			presentation,
			mockWorkersConfig,
		)
	}

	if buildRunner == nil {
		return nil, errors.New("construct local runtime: injected runtime runner builder is required")
	}
	if buildRuntimeRequest == nil {
		return nil, errors.New("construct local runtime: runtime opening request factory is required")
	}
	var factorySvc initializer.LocalRuntimeRunner
	onBound := func(binding factorysessions.RuntimeHostBinding) {
		resolved := cfg
		resolved.Port = binding.Port
		emitVerboseStartupDiagnostics(resolved, recordPath, requestedPort)
		if emitStartupMessages(resolved, runtimeLogDiagnosticsForRunner(factorySvc)) {
			openDashboardAtBoundEndpoint(ctx, resolved, cfg.BrowserOpener)
		}
	}
	openingRequest := buildRuntimeRequest(cfg, mockWorkersConfig, onBound)
	if cfg.Port <= 0 {
		emitVerboseStartupDiagnostics(cfg, recordPath, requestedPort)
	}
	var visualizationSink factoryvisualization.Sink
	if !cfg.SuppressDashboardRendering && cfg.Output != nil {
		visualizationSink = factoryvisualization.SinkFunc(func(input factoryvisualization.View) {
			renderSimpleDashboard(cfg.Output, input)
		})
	}
	factorySvc, err = buildRunner(ctx, openingRequest, logger, visualizationSink)
	if err != nil {
		return nil, err
	}
	if factorySvc == nil {
		return nil, fmt.Errorf("construct local runtime: builder returned nil runner")
	}

	return &Operation{
		cfg: cfg, logger: logger, runner: factorySvc, recordPath: recordPath,
		prepareWorkTarget: prepareWorkTarget,
	}, nil
}

// Run activates an operation that was opened successfully.
func (operation *Operation) Run(ctx context.Context) error {
	if operation == nil {
		return fmt.Errorf("run local operation: operation is required")
	}
	if operation.invocationMode {
		return runFactoryInvocation(
			ctx, operation.cfg, operation.invocationTarget, *operation.invocationRequest,
			operation.invocation, operation.presentation,
		)
	}

	if operation.cfg.Port <= 0 {
		emitStartupMessages(operation.cfg, runtimeLogDiagnosticsForRunner(operation.runner))
	}

	return runFactoryServiceAndEmitResult(
		ctx,
		operation.cfg,
		operation.runner,
		operation.prepareWorkTarget,
		operation.recordPath,
	)
}

func normalizeRunInvocationMode(cfg RunConfig) RunConfig {
	if !cfg.CleanInvocation {
		return cfg
	}
	cfg.SuppressDashboardRendering = true
	cfg.StartupOutput = nil
	cfg.OpenDashboard = false
	return cfg
}

func prepareRunConfig(cfg RunConfig) (RunConfig, *factoryapi.InvocationRequest, bool, resolvedRunRecordPath, error) {
	if cfg.Bootstrap {
		if err := bootstrapFactoryWithInitializer(cfg.Dir, cfg.FactoryScaffoldInitializer, cfg.ResolveCurrentFactoryDir, cfg.DirectoryCreator); err != nil {
			return RunConfig{}, nil, false, resolvedRunRecordPath{}, err
		}
	}

	recordPath, err := resolveRecordPathForRun(cfg)
	if err != nil {
		return RunConfig{}, nil, false, resolvedRunRecordPath{}, err
	}
	cfg.RecordPath = recordPath.servicePath

	invocationRequest, invocationMode, err := resolveFactoryInvocationRequest(cfg)
	if err != nil {
		return RunConfig{}, nil, false, resolvedRunRecordPath{}, err
	}
	if err := validateInvocationOutputMode(cfg, invocationMode); err != nil {
		return RunConfig{}, nil, false, resolvedRunRecordPath{}, err
	}
	return cfg, invocationRequest, invocationMode, recordPath, nil
}

func loadSelectedMockWorkersConfig(
	cfg RunConfig,
	load workers.MockWorkersConfigLoader,
) (*workers.MockWorkersConfig, error) {
	if !cfg.MockWorkersEnabled {
		return nil, nil
	}
	if load == nil {
		return nil, fmt.Errorf("load mock workers config: Workers config loader is required")
	}
	return load(cfg.MockWorkersConfigPath)
}

func resolveRecordPathForRun(cfg RunConfig) (resolvedRunRecordPath, error) {
	if cfg.DisableDefaultRecording && strings.TrimSpace(cfg.RecordPath) != "" {
		return resolvedRunRecordPath{}, fmt.Errorf("--no-record cannot be used with --record")
	}
	if strings.TrimSpace(cfg.RecordPath) != "" {
		return resolvedRunRecordPath{servicePath: cfg.RecordPath}, nil
	}
	if cfg.DisableDefaultRecording || strings.TrimSpace(cfg.ReplayPath) != "" {
		return resolvedRunRecordPath{}, nil
	}
	if cfg.RecordingTargetPlanner == nil {
		return resolvedRunRecordPath{}, fmt.Errorf("Recordings live recording target planner is required")
	}
	target, err := cfg.RecordingTargetPlanner.PlanLiveRecordingTarget(recordings.LiveRecordingTargetRequest{
		HomeDir:           cfg.HomeDir,
		ReportedSessionID: defaultFactorySessionID,
	})
	if err != nil {
		return resolvedRunRecordPath{}, fmt.Errorf("resolve default replay record path: %w", err)
	}
	return resolvedRunRecordPath{
		servicePath:   target.ServicePath,
		reportedPath:  target.ReportedPath,
		autoGenerated: true,
	}, nil
}

func runtimeModeForRun(cfg RunConfig) interfaces.RuntimeMode {
	if cfg.Continuously {
		return interfaces.RuntimeModeService
	}
	return interfaces.RuntimeModeBatch
}

func runFactoryServiceAndEmitResult(
	ctx context.Context,
	cfg RunConfig,
	factorySvc factoryServiceRunner,
	prepareWorkTarget work.SingleWorkTargetPreparation,
	recordPath resolvedRunRecordPath,
) error {
	var startedAt time.Time
	if cfg.CleanInvocation {
		if cfg.Clock == nil {
			return fmt.Errorf("run clock is required")
		}
		startedAt = cfg.Clock.Now().UTC()
		recordCleanInvocationAttempt()
	}
	err := factorySvc.Run(ctx)
	reportRecordingPathOnShutdown(cfg.StartupOutput, recordPath)
	if cfg.CleanInvocation {
		return emitCleanInvocationOutcome(ctx, cfg, factorySvc, prepareWorkTarget, err, cfg.Clock.Now().Sub(startedAt))
	}
	if err != nil {
		return err
	}
	return nil
}

func emitVerboseStartupDiagnostics(cfg RunConfig, recordPath resolvedRunRecordPath, requestedPort int) {
	resolvedFactoryDir := resolveFactoryDirForDiagnostics(cfg.Dir, cfg.ResolveCurrentFactoryDir)
	diagnosticsEnabled := terminalpolicy.DiagnosticsEnabled(cfg.TerminalPolicy, cfg.Verbose)
	clidiag.Printf(
		cfg.Diagnostics,
		diagnosticsEnabled,
		"run startup factoryDir=%q configuredDir=%q runtimeMode=%s workflow=%q mockWorkers=%t mockWorkersConfigPath=%q recording=%s runtimeLogDir=%q runtimeLogRoll=%s runtimeMetricsDir=%q runtimeMetricsRoll=%s dashboardPort=%d requestedDashboardPort=%d autoPort=%s",
		resolvedFactoryDir,
		cfg.Dir,
		runtimeModeForRun(cfg),
		workflowLabel(cfg.Workflow),
		cfg.MockWorkersEnabled,
		cfg.MockWorkersConfigPath,
		recordingDiagnostics(recordPath, cfg.ReplayPath),
		runtimeLogDirLabel(cfg.RuntimeLogDir),
		rollingPolicyDiagnostics(cfg.RuntimeLogConfig.MaxSize, cfg.RuntimeLogConfig.MaxBackups, cfg.RuntimeLogConfig.MaxAge, cfg.RuntimeLogConfig.Compress),
		runtimeMetricsDirLabel(cfg.RuntimeMetricsDir),
		rollingPolicyDiagnostics(cfg.RuntimeMetricsConfig.MaxSize, cfg.RuntimeMetricsConfig.MaxBackups, cfg.RuntimeMetricsConfig.MaxAge, cfg.RuntimeMetricsConfig.Compress),
		cfg.Port,
		requestedPort,
		autoPortDiagnostics(cfg.AutoPort, requestedPort, cfg.Port),
	)
	clidiag.Printf(cfg.Diagnostics, diagnosticsEnabled, "%s", cfg.OperatorDefaults.DiagnosticsLine())
}

func emitNamedFactoryResolutionDiagnostics(cfg RunConfig, logger *zap.Logger) {
	resolution := cfg.NamedFactoryResolution
	if resolution == nil {
		return
	}

	clidiag.Printf(
		cfg.Diagnostics,
		terminalpolicy.DiagnosticsEnabled(cfg.TerminalPolicy, cfg.Verbose),
		"run named-factory resolution name=%q source=%s resolvedFactoryDir=%q projectRoot=%q globalRoot=%q precedence=%s",
		resolution.Name,
		resolution.Source,
		resolution.FactoryDir,
		resolution.ProjectRoot,
		resolution.GlobalRoot,
		resolution.PrecedenceDecision,
	)
	logger.Info(
		"named factory resolved",
		zap.String("named_factory_name", resolution.Name),
		zap.String("named_factory_resolution_source", string(resolution.Source)),
		zap.String("named_factory_dir", resolution.FactoryDir),
		zap.String("named_factory_project_root", resolution.ProjectRoot),
		zap.String("named_factory_global_root", resolution.GlobalRoot),
		zap.String("named_factory_precedence_decision", string(resolution.PrecedenceDecision)),
	)
	if resolution.PrecedenceDecision == interfaces.NamedFactoryPrecedenceDecisionProjectOverGlobal {
		logger.Info(
			"named factory precedence selected",
			zap.String("named_factory_name", resolution.Name),
			zap.String("named_factory_precedence_decision", string(resolution.PrecedenceDecision)),
			zap.String("named_factory_resolution_source", string(resolution.Source)),
		)
	}
}

func resolveFactoryDirForDiagnostics(
	dir string,
	resolve interfaces.CurrentFactoryDirectoryResolver,
) string {
	if resolve == nil {
		return "unresolved"
	}
	resolved, err := resolve(dir)
	if err != nil {
		return "unresolved"
	}
	return resolved
}

func workflowLabel(workflow string) string {
	if strings.TrimSpace(workflow) == "" {
		return "all"
	}
	return workflow
}

func runtimeLogDirLabel(dir string) string {
	if strings.TrimSpace(dir) == "" {
		return "default"
	}
	return dir
}

func runtimeMetricsDirLabel(dir string) string {
	if strings.TrimSpace(dir) == "" {
		return "default"
	}
	return dir
}

func rollingPolicyDiagnostics(maxSize, maxBackups, maxAge int, compress bool) string {
	return fmt.Sprintf("size_mb=%d backups=%d age_days=%d compress=%t", maxSize, maxBackups, maxAge, compress)
}

func recordingDiagnostics(recordPath resolvedRunRecordPath, replayPath string) string {
	switch {
	case strings.TrimSpace(replayPath) != "":
		return "replay"
	case strings.TrimSpace(recordPath.servicePath) == "":
		return "disabled"
	case recordPath.autoGenerated:
		return "default"
	default:
		return "explicit"
	}
}

func autoPortDiagnostics(autoPort bool, requestedPort, resolvedPort int) string {
	switch {
	case requestedPort <= 0:
		return "dashboard-disabled"
	case !autoPort:
		return "disabled"
	case requestedPort == resolvedPort:
		return "preferred-available"
	default:
		return "fallback"
	}
}

func renderSimpleDashboard(output io.Writer, input factoryvisualization.View) {
	fmt.Fprint(output, dashboard.FormatSimpleDashboardWithRenderData(
		input.EngineState,
		input.RenderData,
		input.ObservedAt,
	))
}

func bindDashboardHost(cfg RunConfig) string {
	if strings.TrimSpace(cfg.BindHost) != "" {
		return cfg.BindHost
	}
	return "localhost"
}

// DashboardURL returns the embedded browser dashboard URL for the configured
// local factory server host and port.
func DashboardURL(host string, port int) string {
	if port <= 0 {
		return ""
	}
	if strings.TrimSpace(host) == "" {
		host = "localhost"
	}
	authority := net.JoinHostPort(host, strconv.Itoa(port))
	return "http://" + authority + "/dashboard/ui"
}

func emitStartupMessages(
	cfg RunConfig,
	runtimeLog runtimeartifact.Diagnostics,
) bool {
	if cfg.StartupOutput == nil {
		return false
	}

	fmt.Fprintf(cfg.StartupOutput, "Factory initiated: %s\n", cfg.Dir)
	if cfg.Bootstrap {
		fmt.Fprintf(cfg.StartupOutput, "Factory directory ready: %s\n", cfg.Dir)
	}
	if cfg.Continuously {
		fmt.Fprintln(cfg.StartupOutput, "Runtime mode: continuous")
	}
	if strings.TrimSpace(runtimeLog.Path) != "" {
		fmt.Fprintf(cfg.StartupOutput, "Runtime log: %s\n", runtimeLog.Path)
		fmt.Fprintf(cfg.StartupOutput, "Runtime log start (UTC): %s\n", timedisplay.Timestamp(runtimeLog.StartTimeUTC))
	}
	if strings.TrimSpace(runtimeLog.MetricsPath) != "" {
		fmt.Fprintf(cfg.StartupOutput, "Runtime metrics: %s\n", runtimeLog.MetricsPath)
		fmt.Fprintf(cfg.StartupOutput, "Runtime metrics start (UTC): %s\n", timedisplay.Timestamp(runtimeLog.MetricsStartTimeUTC))
	}
	if cfg.Port <= 0 {
		fmt.Fprintln(cfg.StartupOutput, "Dashboard server disabled")
		return false
	}

	url := DashboardURL(bindDashboardHost(cfg), cfg.Port)
	fmt.Fprintf(cfg.StartupOutput, "Dashboard URL: %s\n", url)
	if !cfg.OpenDashboard || !cfg.OutputIsTTY {
		fmt.Fprintf(cfg.StartupOutput, "Dashboard auto-open disabled; open %s\n", url)
		return false
	}
	return true
}

func reportRecordingPathOnShutdown(output io.Writer, recordPath resolvedRunRecordPath) {
	if output == nil || !recordPath.autoGenerated || strings.TrimSpace(recordPath.reportedPath) == "" {
		return
	}
	fmt.Fprintf(output, "Recording saved: %s\n", recordPath.reportedPath)
}

func openDashboardAtBoundEndpoint(
	ctx context.Context,
	cfg RunConfig,
	openDashboard func(context.Context, string) error,
) {
	url := DashboardURL(bindDashboardHost(cfg), cfg.Port)
	if openDashboard == nil {
		fmt.Fprintf(cfg.StartupOutput, "Dashboard auto-open unavailable: browser opener is required\nOpen the dashboard at %s\n", url)
		return
	}
	if err := openDashboard(ctx, url); err != nil {
		fmt.Fprintf(cfg.StartupOutput, "Dashboard auto-open unavailable: %v\nOpen the dashboard at %s\n", err, url)
		return
	}
	fmt.Fprintf(cfg.StartupOutput, "Opening dashboard: %s\n", url)
}

// CountTokenStates counts tokens by their state category based on place ID conventions.
// Place IDs follow the pattern '{work_type_id}:{state_value}'.
// Terminal states contain "completed", failed states contain "failed".
func CountTokenStates(snap *state.PetriMarkingSnapshot) (wip, completed, failed int) {
	for _, t := range snap.Tokens {
		placeID := t.PlaceID
		// Extract state from place ID (after the last ':').
		state := placeID
		if idx := strings.LastIndexByte(placeID, ':'); idx >= 0 {
			state = placeID[idx+1:]
		}

		switch {
		case isFailedState(state):
			failed++
		case isTerminalState(state):
			completed++
		default:
			wip++
		}
	}
	return
}

func isTerminalState(state string) bool {
	return state == completedPlaceIDSuffix
}

func isFailedState(state string) bool {
	return state == failedPlaceIDSuffix
}

// FormatDuration formats a duration as "Xm" or "Xh Ym".
func FormatDuration(d time.Duration) string {
	return dashboard.FormatDuration(d)
}
