package factorydefinitions

import (
	contracts "github.com/portpowered/infinite-you/pkg/services/factory_definitions/contracts"
	resource "github.com/portpowered/infinite-you/pkg/services/factory_definitions/resource"
	workerconfig "github.com/portpowered/infinite-you/pkg/services/factory_definitions/workers"
)

// Root-owned aliases expose the Factory Definition vocabulary without making
// peer services import implementation subpackages.
type FactoryConfig = contracts.FactoryConfig
type SaveMode = contracts.SaveMode
type NamedFactoryPersistenceMode = contracts.NamedFactoryPersistenceMode
type NamedFactoryPersistenceRequest = contracts.NamedFactoryPersistenceRequest
type NamedFactoryPersistenceResult = contracts.NamedFactoryPersistenceResult
type NamedFactoryPersistenceOperation = contracts.NamedFactoryPersistenceOperation
type EditableFactory = contracts.EditableFactory
type ValidationProfile = contracts.ValidationProfile
type WorkflowSourceReader = contracts.WorkflowSourceReader
type ValidationSeverity = contracts.ValidationSeverity
type ValidationSubjectType = contracts.ValidationSubjectType
type ValidationSubjectLocation = contracts.ValidationSubjectLocation
type ValidationResult = contracts.ValidationResult
type TopologyFinding = contracts.TopologyFinding
type TopologyValidationResult = contracts.TopologyValidationResult
type Service = contracts.Service
type BlockingFactoryLoadError = contracts.BlockingFactoryLoadError
type ValidationTopologyError = contracts.ValidationTopologyError
type FactorySessionSyncPreflightOptions = contracts.FactorySessionSyncPreflightOptions
type FactoryOrchestratorJavaScriptConfig = contracts.FactoryOrchestratorJavaScriptConfig
type FactoryGuardConfig = contracts.FactoryGuardConfig
type FactoryWorkstationConfig = contracts.FactoryWorkstationConfig
type FactoryWorkerConfig = workerconfig.Config
type HostedLinearWorkerConfig = workerconfig.HostedLinearWorkerConfig
type HostedLinearWorkerClaimConfig = workerconfig.HostedLinearWorkerClaimConfig
type HostedLinearWorkerMappingConfig = workerconfig.HostedLinearWorkerMappingConfig
type HostedWorkerAuthConfig = workerconfig.HostedWorkerAuthConfig
type AgentToolsConfig = workerconfig.AgentToolsConfig
type ModelOperation = workerconfig.ModelOperation
type ModelOperationSlot = workerconfig.ModelOperationSlot
type ResourceConfig = resource.Config
type InvocationSignatureConfig = contracts.InvocationSignatureConfig
type InvocationExampleConfig = contracts.InvocationExampleConfig
type InvocationOutputContractConfig = contracts.InvocationOutputContractConfig
type InvocationParameterConfig = contracts.InvocationParameterConfig
type ModelOperationBinding = contracts.ModelOperationBinding
type ModelOperationBindingSelector = contracts.ModelOperationBindingSelector
type ModelProvider = contracts.ModelProvider
type RuntimeConfigLookup = contracts.RuntimeConfigLookup
type RuntimeDefinitionLookup = contracts.RuntimeDefinitionLookup
type RuntimeFactoryConfigLookup = contracts.RuntimeFactoryConfigLookup
type WorkstationKind = contracts.WorkstationKind
type WorkstationLimits = contracts.WorkstationLimits
type Workstation = contracts.Workstation
type GuardMatchConfig = contracts.GuardMatchConfig
type GuardType = contracts.GuardType
type InputGuardConfig = contracts.InputGuardConfig
type InputTypeConfig = contracts.InputTypeConfig
type IOConfig = contracts.IOConfig
type StateConfig = contracts.StateConfig
type StateType = contracts.StateType
type WorkTypeConfig = contracts.WorkTypeConfig
type WorkerWorkstationBehaviorClass = contracts.WorkerWorkstationBehaviorClass
type PendingFactoryGraphTopology = contracts.PendingFactoryGraphTopology
type ValidationTarget = contracts.ValidationTarget
type ValidationSubject = contracts.ValidationSubject

const (
	SaveModeReplaceCurrent             = contracts.SaveModeReplaceCurrent
	SaveModeUpsertNamedAndActivate     = contracts.SaveModeUpsertNamedAndActivate
	NamedFactoryPersistenceModeCreate  = contracts.NamedFactoryPersistenceModeCreate
	NamedFactoryPersistenceModeReplace = contracts.NamedFactoryPersistenceModeReplace
	ValidationProfileTopology          = contracts.ValidationProfileTopology
	ValidationProfilePrePersist        = contracts.ValidationProfilePrePersist
	DefaultTopologyValidationMessage   = contracts.DefaultTopologyValidationMessage

	FactoryAgentsFileName                 = contracts.FactoryAgentsFileName
	WorkersDir                            = contracts.WorkersDir
	WorkstationsDir                       = contracts.WorkstationsDir
	BundledFileTypeRootHelper             = contracts.BundledFileTypeRootHelper
	SystemTimeDashboardExpiryTransitionID = contracts.SystemTimeDashboardExpiryTransitionID
)

var (
	ErrCurrentFactoryNotFound = contracts.ErrCurrentFactoryNotFound
	ErrFactoryVersionStale    = contracts.ErrFactoryVersionStale
)

var (
	NewFactoryEvent                              = contracts.NewFactoryEvent
	CanonicalFactoryGraphWorkstationID           = contracts.CanonicalFactoryGraphWorkstationID
	PublicWorkerModelProviderFromInternal        = contracts.PublicWorkerModelProviderFromInternal
	PermissivePublicFactoryRunnerID              = contracts.PermissivePublicFactoryRunnerID
	PermissivePublicFactoryRunnerSelectionSource = contracts.PermissivePublicFactoryRunnerSelectionSource
)

type PortableBundledFileReplacement = contracts.PortableBundledFileReplacement
type MutableLoadedFactorySource = contracts.MutableLoadedFactorySource
type DefinitionSession = contracts.DefinitionSession
type SessionHost = contracts.SessionHost

const (
	ResourceStateAvailable                               = contracts.ResourceStateAvailable
	ResourceTypeModel                                    = resource.TypeModel
	ResourceTypeProviderQuota                            = resource.TypeProviderQuota
	ResourceTypeInvocationSlot                           = resource.TypeInvocationSlot
	WorkerTypeAgent                                      = contracts.WorkerTypeAgent
	WorkerTypeInference                                  = contracts.WorkerTypeInference
	WorkerTypeModel                                      = contracts.WorkerTypeModel
	WorkerTypeScript                                     = contracts.WorkerTypeScript
	ModelLocalityLocal                                   = workerconfig.ModelLocalityLocal
	ModelLocalityCloud                                   = workerconfig.ModelLocalityCloud
	AgentToolPolicyDisabled                              = workerconfig.AgentToolPolicyDisabled
	AgentToolPolicyEnabled                               = workerconfig.AgentToolPolicyEnabled
	AgentToolPolicyReadOnly                              = workerconfig.AgentToolPolicyReadOnly
	ModelOperationContentTypeAudio                       = workerconfig.ModelOperationContentTypeAudio
	ModelOperationContentTypeBinary                      = workerconfig.ModelOperationContentTypeBinary
	ModelOperationContentTypeImage                       = workerconfig.ModelOperationContentTypeImage
	ModelOperationContentTypeJSON                        = workerconfig.ModelOperationContentTypeJSON
	ModelOperationContentTypeText                        = workerconfig.ModelOperationContentTypeText
	WorkerModelProviderDefault                           = contracts.WorkerModelProviderDefault
	WorkstationTypeLogical                               = contracts.WorkstationTypeLogical
	WorkstationTypePoller                                = contracts.WorkstationTypePoller
	WorkstationTypeInference                             = contracts.WorkstationTypeInference
	WorkstationTypeModel                                 = contracts.WorkstationTypeModel
	WorkerWorkstationBehaviorInference                   = contracts.WorkerWorkstationBehaviorInference
	WorkerWorkstationBehaviorAgent                       = contracts.WorkerWorkstationBehaviorAgent
	WorkerWorkstationBehaviorScript                      = contracts.WorkerWorkstationBehaviorScript
	WorkerWorkstationBehaviorPoller                      = contracts.WorkerWorkstationBehaviorPoller
	ValidationCodeFactorySessionField                    = contracts.ValidationCodeFactorySessionField
	ValidationCodeFactorySessionTarget                   = contracts.ValidationCodeFactorySessionTarget
	ValidationCodeFactoryPayloadInvalid                  = contracts.ValidationCodeFactoryPayloadInvalid
	ValidationCodeFactoryNameInvalid                     = contracts.ValidationCodeFactoryNameInvalid
	ValidationCodeFactoryVersionStale                    = contracts.ValidationCodeFactoryVersionStale
	ValidationCodeFactoryRuntimeNotIdle                  = contracts.ValidationCodeFactoryRuntimeNotIdle
	ValidationCodeLayoutUnknownNodeReference             = contracts.ValidationCodeLayoutUnknownNodeReference
	ValidationCodeWorkerWorkstationBehaviorCompatibility = contracts.ValidationCodeWorkerWorkstationBehaviorCompatibility
	ValidationSeverityError                              = contracts.ValidationSeverityError
	ValidationSeverityWarning                            = contracts.ValidationSeverityWarning
	ValidationSeverityHint                               = contracts.ValidationSeverityHint
	ValidationSubjectTypeFactory                         = contracts.ValidationSubjectTypeFactory
	ValidationSubjectTypeWorkstation                     = contracts.ValidationSubjectTypeWorkstation
	ValidationSubjectTypeWorkType                        = contracts.ValidationSubjectTypeWorkType
	ValidationSubjectTypeWorkState                       = contracts.ValidationSubjectTypeWorkState
	ValidationSubjectTypeWorker                          = contracts.ValidationSubjectTypeWorker
	ValidationSubjectTypeResource                        = contracts.ValidationSubjectTypeResource
	ValidationSubjectTypeRoute                           = contracts.ValidationSubjectTypeRoute
	ValidationSubjectLocationOnRejection                 = contracts.ValidationSubjectLocationOnRejection
	ValidationSubjectLocationOnFailure                   = contracts.ValidationSubjectLocationOnFailure
	ValidationSubjectLocationOutputs                     = contracts.ValidationSubjectLocationOutputs
	ValidationSubjectLocationInputs                      = contracts.ValidationSubjectLocationInputs
	ValidationSubjectLocationStates                      = contracts.ValidationSubjectLocationStates
	ValidationSubjectLocationTerminal                    = contracts.ValidationSubjectLocationTerminal
	ValidationSubjectLocationReference                   = contracts.ValidationSubjectLocationReference
	ValidationSubjectLocationDefinition                  = contracts.ValidationSubjectLocationDefinition
)

var CanonicalEventTime = contracts.CanonicalEventTime
var CanonicalizeReasoningEffort = contracts.CanonicalizeReasoningEffort
var CanonicalizeOperatorWorkerModelProviderInput = contracts.CanonicalizeOperatorWorkerModelProviderInput
var IsSymbolicWorkerModelProviderDefault = contracts.IsSymbolicWorkerModelProviderDefault
var UsesModelhostLease = contracts.UsesModelhostLease
var IsAgentRunWorkstationType = contracts.IsAgentRunWorkstationType
var IsAgentWorkerType = contracts.IsAgentWorkerType
var IsInferenceRunWorkstationType = contracts.IsInferenceRunWorkstationType
var IsInferenceWorkerType = contracts.IsInferenceWorkerType
var IsScriptWorkerType = contracts.IsScriptWorkerType
var ExemptFromWorkerWorkstationCompatibility = contracts.ExemptFromWorkerWorkstationCompatibility
var EffectiveWorkstationTypeForCompatibility = contracts.EffectiveWorkstationTypeForCompatibility
var WorkerBehaviorClass = contracts.WorkerBehaviorClass
var ExpectedWorkerBehaviorClassForWorkstation = contracts.ExpectedWorkerBehaviorClassForWorkstation
var WorkerMatchesWorkstationBehavior = contracts.WorkerMatchesWorkstationBehavior
var PublicWorkerTypeForFactoryUsage = contracts.PublicWorkerTypeForFactoryUsage
var EffectiveWorkstationBehaviorClass = contracts.EffectiveWorkstationBehaviorClass
var IsLegacyGrandfatheredWorkerWorkstationPair = contracts.IsLegacyGrandfatheredWorkerWorkstationPair
var RequiresWorkerWorkstationBehaviorCompatibility = contracts.RequiresWorkerWorkstationBehaviorCompatibility
var CompatibleWorkerWorkstationBehavior = contracts.CompatibleWorkerWorkstationBehavior
var RuntimeBehaviorClassLabel = contracts.RuntimeBehaviorClassLabel
var WorkerWorkstationBehaviorMismatchMessage = contracts.WorkerWorkstationBehaviorMismatchMessage
var AgentToolsAllowExecution = workerconfig.AgentToolsAllowExecution
var EffectiveAgentToolPolicy = workerconfig.EffectiveAgentToolPolicy
var IsKnownAgentToolPolicy = workerconfig.IsKnownAgentToolPolicy
var NormalizeAgentToolPolicy = workerconfig.NormalizeAgentToolPolicy
var CloneWorkerConfig = workerconfig.Clone

type (
	ActiveThrottlePause                              = contracts.ActiveThrottlePause
	ArcMode                                          = contracts.ArcMode
	ArtifactCreatedEventPayload                      = contracts.ArtifactCreatedEventPayload
	BundledFileConfig                                = contracts.BundledFileConfig
	CheckpointResumabilityStatus                     = contracts.CheckpointResumabilityStatus
	CompletedDispatch                                = contracts.CompletedDispatch
	CronConfig                                       = contracts.CronConfig
	DispatchConsumedWorkRef                          = contracts.DispatchConsumedWorkRef
	DispatchEntry                                    = contracts.DispatchEntry
	DispatchInterruptedEventPayload                  = contracts.DispatchInterruptedEventPayload
	DispatchQueuedEventPayload                       = contracts.DispatchQueuedEventPayload
	DispatchReconciledEventPayload                   = contracts.DispatchReconciledEventPayload
	DispatchReconciliationSource                     = contracts.DispatchReconciliationSource
	DispatchRecord                                   = contracts.DispatchRecord
	DispatchRequestEventMetadata                     = contracts.DispatchRequestEventMetadata
	DispatchRequestEventPayload                      = contracts.DispatchRequestEventPayload
	DispatchResourceRef                              = contracts.DispatchResourceRef
	EnabledTransition                                = contracts.EnabledTransition
	EngineStateSnapshot[TMarking any, TTopology any] = contracts.EngineStateSnapshot[TMarking, TTopology]
	FactoryArtifact                                  = contracts.FactoryArtifact
	FactoryArtifactCaptureMetadata                   = contracts.FactoryArtifactCaptureMetadata
	FactoryArtifactRedactionCounts                   = contracts.FactoryArtifactRedactionCounts
	FactoryArtifactRef                               = contracts.FactoryArtifactRef
	FactoryChangeEventPayload                        = contracts.FactoryChangeEventPayload
	FactoryCompletionRecord                          = contracts.FactoryCompletionRecord
	FactoryConstraint                                = contracts.FactoryConstraint
	FactoryDispatchKind                              = contracts.FactoryDispatchKind
	FactoryDispatchRecord                            = contracts.FactoryDispatchRecord
	FactoryDispatchStatus                            = contracts.FactoryDispatchStatus
	FactoryDispatchUsage                             = contracts.FactoryDispatchUsage
	FactoryDispatchWarning                           = contracts.FactoryDispatchWarning
	FactoryEvent                                     = contracts.FactoryEvent
	FactoryEventContext                              = contracts.FactoryEventContext
	FactoryEventReconnectCursor                      = contracts.FactoryEventReconnectCursor
	FactoryEventReconnectScope                       = contracts.FactoryEventReconnectScope
	FactoryEventStream                               = contracts.FactoryEventStream
	FactoryEventType                                 = contracts.FactoryEventType
	FactoryInvocationResult                          = contracts.FactoryInvocationResult
	FactoryLayoutBoundsConfig                        = contracts.FactoryLayoutBoundsConfig
	FactoryLayoutAnnotationConfig                    = contracts.FactoryLayoutAnnotationConfig
	FactoryLayoutConfig                              = contracts.FactoryLayoutConfig
	FactoryLayoutEdgeConfig                          = contracts.FactoryLayoutEdgeConfig
	FactoryLayoutEmptyStateConfig                    = contracts.FactoryLayoutEmptyStateConfig
	FactoryLayoutGroupConfig                         = contracts.FactoryLayoutGroupConfig
	FactoryLayoutImageConfig                         = contracts.FactoryLayoutImageConfig
	FactoryLayoutImageSourceConfig                   = contracts.FactoryLayoutImageSourceConfig
	FactoryLayoutNodeConfig                          = contracts.FactoryLayoutNodeConfig
	FactoryLayoutNoteConfig                          = contracts.FactoryLayoutNoteConfig
	FactoryLayoutPointConfig                         = contracts.FactoryLayoutPointConfig
	FactoryLayoutPreferencesConfig                   = contracts.FactoryLayoutPreferencesConfig
	FactoryLayoutSizeConfig                          = contracts.FactoryLayoutSizeConfig
	FactoryLayoutViewportConfig                      = contracts.FactoryLayoutViewportConfig
	FactoryOrchestratorJavaScriptAgent               = contracts.FactoryOrchestratorJavaScriptAgent
	FactoryPlace                                     = contracts.FactoryPlace
	FactoryPlaceOccupancy                            = contracts.FactoryPlaceOccupancy
	FactoryResource                                  = contracts.FactoryResource
	FactoryResourceUnit                              = contracts.FactoryResourceUnit
	FactorySessionArtifactState                      = contracts.FactorySessionArtifactState
	FactorySessionChildDispatchCounts                = contracts.FactorySessionChildDispatchCounts
	FactorySessionCompletedEventPayload              = contracts.FactorySessionCompletedEventPayload
	FactorySessionDispatchFailureDetail              = contracts.FactorySessionDispatchFailureDetail
	FactorySessionDispatchJavaScriptState            = contracts.FactorySessionDispatchJavaScriptState
	FactorySessionDispatchPetriState                 = contracts.FactorySessionDispatchPetriState
	FactorySessionDispatchState                      = contracts.FactorySessionDispatchState
	FactorySessionDispatchUsage                      = contracts.FactorySessionDispatchUsage
	FactorySessionDispatchWarning                    = contracts.FactorySessionDispatchWarning
	FactorySessionJavaScriptCheckpointEventRef       = contracts.FactorySessionJavaScriptCheckpointEventRef
	FactorySessionJavaScriptCheckpointRef            = contracts.FactorySessionJavaScriptCheckpointRef
	FactorySessionJavaScriptRuntimeState             = contracts.FactorySessionJavaScriptRuntimeState
	FactorySessionJavaScriptScriptStatus             = contracts.FactorySessionJavaScriptScriptStatus
	FactorySessionLifecycleControlEventPayload       = contracts.FactorySessionLifecycleControlEventPayload
	FactorySessionLifecycleControlKind               = contracts.FactorySessionLifecycleControlKind
	FactorySessionLifecycleControlOutcome            = contracts.FactorySessionLifecycleControlOutcome
	FactorySessionLifecycleStatus                    = contracts.FactorySessionLifecycleStatus
	FactorySessionLogicalResolveHint                 = contracts.FactorySessionLogicalResolveHint
	FactorySessionPausedEventPayload                 = contracts.FactorySessionPausedEventPayload
	FactorySessionResultStatus                       = contracts.FactorySessionResultStatus
	FactorySessionResultUpdatedEventPayload          = contracts.FactorySessionResultUpdatedEventPayload
	FactorySessionResumedEventPayload                = contracts.FactorySessionResumedEventPayload
	FactorySessionStartedEventPayload                = contracts.FactorySessionStartedEventPayload
	FactorySnapshot                                  = contracts.FactorySnapshot
	FactoryState                                     = contracts.FactoryState
	FactoryStateDefinition                           = contracts.FactoryStateDefinition
	FactoryStateResponseEventPayload                 = contracts.FactoryStateResponseEventPayload
	FactoryTerminalWork                              = contracts.FactoryTerminalWork
	FactoryVersion                                   = contracts.FactoryVersion
	FactoryWorkType                                  = contracts.FactoryWorkType
	FactoryWorker                                    = contracts.FactoryWorker
	FactoryWorkstation                               = contracts.FactoryWorkstation
	FactoryWorkstationRef                            = contracts.FactoryWorkstationRef
	FactoryWorldActiveExecution                      = contracts.FactoryWorldActiveExecution
	FactoryWorldActivity                             = contracts.FactoryWorldActivity
	FactoryWorldAgentRunResponse                     = contracts.FactoryWorldAgentRunResponse
	FactoryWorldDispatch                             = contracts.FactoryWorldDispatch
	FactoryWorldDispatchCompletion                   = contracts.FactoryWorldDispatchCompletion
	FactoryWorldFailureDetail                        = contracts.FactoryWorldFailureDetail
	FactoryWorldInferenceAttempt                     = contracts.FactoryWorldInferenceAttempt
	FactoryWorldJavaScriptChildDispatchCounts        = contracts.FactoryWorldJavaScriptChildDispatchCounts
	FactoryWorldJavaScriptProjection                 = contracts.FactoryWorldJavaScriptProjection
	FactoryWorldPlaceRef                             = contracts.FactoryWorldPlaceRef
	FactoryWorldProviderSessionRecord                = contracts.FactoryWorldProviderSessionRecord
	FactoryWorldRuntimeView                          = contracts.FactoryWorldRuntimeView
	FactoryWorldScriptRequest                        = contracts.FactoryWorldScriptRequest
	FactoryWorldScriptResponse                       = contracts.FactoryWorldScriptResponse
	FactoryWorldSessionBracketProjection             = contracts.FactoryWorldSessionBracketProjection
	FactoryWorldSessionBracketState                  = contracts.FactoryWorldSessionBracketState
	FactoryWorldSessionRuntime                       = contracts.FactoryWorldSessionRuntime
	FactoryWorldState                                = contracts.FactoryWorldState
	FactoryWorldSubmitWorkType                       = contracts.FactoryWorldSubmitWorkType
	FactoryWorldThrottlePause                        = contracts.FactoryWorldThrottlePause
	FactoryWorldTopologyView                         = contracts.FactoryWorldTopologyView
	FactoryWorldTrace                                = contracts.FactoryWorldTrace
	FactoryWorldView                                 = contracts.FactoryWorldView
	FactoryWorldWorkItemRef                          = contracts.FactoryWorldWorkItemRef
	FactoryWorldWorkStateChangeRecord                = contracts.FactoryWorldWorkStateChangeRecord
	FactoryWorldWorkstationEdge                      = contracts.FactoryWorldWorkstationEdge
	FactoryWorldWorkstationNode                      = contracts.FactoryWorldWorkstationNode
	FiringDecision                                   = contracts.FiringDecision
	GuardConfig                                      = contracts.GuardConfig
	InitialStructurePayload                          = contracts.InitialStructurePayload
	InitialStructureRequestEventPayload              = contracts.InitialStructureRequestEventPayload
	InvocationParameterBindingConfig                 = contracts.InvocationParameterBindingConfig
	InvocationReturnConfig                           = contracts.InvocationReturnConfig
	JavaScriptCheckpointArtifactRef                  = contracts.JavaScriptCheckpointArtifactRef
	JavaScriptCheckpointRecord                       = contracts.JavaScriptCheckpointRecord
	JavaScriptCheckpointRefEventPayload              = contracts.JavaScriptCheckpointRefEventPayload
	JavaScriptPhaseChangeEventPayload                = contracts.JavaScriptPhaseChangeEventPayload
	MarkingMutation                                  = contracts.MarkingMutation
	OrchestratorCheckpointWrittenEventPayload        = contracts.OrchestratorCheckpointWrittenEventPayload
	OrchestratorPhaseChangedEventPayload             = contracts.OrchestratorPhaseChangedEventPayload
	OrchestratorPhaseStatus                          = contracts.OrchestratorPhaseStatus
	PortableResourceManifestConfig                   = contracts.PortableResourceManifestConfig
	ReplayArtifact                                   = contracts.ReplayArtifact
	ReplayDiagnostics                                = contracts.ReplayDiagnostics
	ReplayWallClockMetadata                          = contracts.ReplayWallClockMetadata
	RequestValidationError                           = contracts.RequestValidationError
	RequiredToolConfig                               = contracts.RequiredToolConfig
	RunEventWallClock                                = contracts.RunEventWallClock
	RunRequestEventPayload                           = contracts.RunRequestEventPayload
	RunResponseEventPayload                          = contracts.RunResponseEventPayload
	RuntimeMode                                      = contracts.RuntimeMode
	RuntimeStatus                                    = contracts.RuntimeStatus
	RuntimeWorkstationLookup                         = contracts.RuntimeWorkstationLookup
	SubmissionHookContext[TSnapshot any]             = contracts.SubmissionHookContext[TSnapshot]
	SubmissionHookResult                             = contracts.SubmissionHookResult
	TickResult                                       = contracts.TickResult
	TokenMutationRecord                              = contracts.TokenMutationRecord
	WorkPropagationMode                              = contracts.WorkPropagationMode
	WorkRequestPayload                               = contracts.WorkRequestPayload
	WorkStateChangeEventPayload                      = contracts.WorkStateChangeEventPayload
	WorkstationInput                                 = contracts.WorkstationInput
	WorkstationLoader                                = contracts.WorkstationLoader
	WorkstationResult                                = contracts.WorkstationResult
	BundledFileContentConfig                         = contracts.BundledFileContentConfig
	ClassificationRouteConfig                        = contracts.ClassificationRouteConfig
	FactoryOrchestratorConfig                        = contracts.FactoryOrchestratorConfig
	FactoryOrchestratorJavaScriptInlineSource        = contracts.FactoryOrchestratorJavaScriptInlineSource
	FactoryOrchestratorPetriConfig                   = contracts.FactoryOrchestratorPetriConfig
	FactoryStateChangePayload                        = contracts.FactoryStateChangePayload
	FactoryTraceData                                 = contracts.FactoryTraceData
	InputKind                                        = contracts.InputKind
	InvocationTerminalStatus                         = contracts.InvocationTerminalStatus
	RelationshipChangePayload                        = contracts.RelationshipChangePayload
	WorkInputPayload                                 = contracts.WorkInputPayload
	WorkPropagationConfig                            = contracts.WorkPropagationConfig
	WorkstationOutput                                = contracts.WorkstationOutput
	WorkstationRequestPayload                        = contracts.WorkstationRequestPayload
	WorkstationResponsePayload                       = contracts.WorkstationResponsePayload
)

const (
	ArcModeObserve                                = contracts.ArcModeObserve
	ArcModeConsume                                = contracts.ArcModeConsume
	ArtifactsDirectory                            = contracts.ArtifactsDirectory
	DefaultChannelName                            = contracts.DefaultChannelName
	DispatchReconciliationSourceStreamReplay      = contracts.DispatchReconciliationSourceStreamReplay
	FactoryConfigFile                             = contracts.FactoryConfigFile
	FactoryDir                                    = contracts.FactoryDir
	FactoryDispatchKindJavaScriptScript           = contracts.FactoryDispatchKindJavaScriptScript
	FactoryDispatchKindJavaScriptSynthesize       = contracts.FactoryDispatchKindJavaScriptSynthesize
	FactoryDispatchKindJavaScriptSystem           = contracts.FactoryDispatchKindJavaScriptSystem
	FactoryDispatchKindJavaScriptTool             = contracts.FactoryDispatchKindJavaScriptTool
	FactoryDispatchKindJavaScriptVerify           = contracts.FactoryDispatchKindJavaScriptVerify
	FactoryDispatchKindPetriTransition            = contracts.FactoryDispatchKindPetriTransition
	FactoryDispatchStatusCompleted                = contracts.FactoryDispatchStatusCompleted
	FactoryDispatchStatusFailed                   = contracts.FactoryDispatchStatusFailed
	FactoryDispatchStatusInterrupted              = contracts.FactoryDispatchStatusInterrupted
	FactoryDispatchStatusQueued                   = contracts.FactoryDispatchStatusQueued
	FactoryDispatchStatusRunning                  = contracts.FactoryDispatchStatusRunning
	FactoryEventSchemaVersionV1                   = contracts.FactoryEventSchemaVersionV1
	FactoryEventTypeAgentRunResponse              = contracts.FactoryEventTypeAgentRunResponse
	FactoryEventTypeArtifactCreated               = contracts.FactoryEventTypeArtifactCreated
	FactoryEventTypeDispatchInterrupted           = contracts.FactoryEventTypeDispatchInterrupted
	FactoryEventTypeDispatchQueued                = contracts.FactoryEventTypeDispatchQueued
	FactoryEventTypeDispatchReconciled            = contracts.FactoryEventTypeDispatchReconciled
	FactoryEventTypeDispatchRequest               = contracts.FactoryEventTypeDispatchRequest
	FactoryEventTypeDispatchResponse              = contracts.FactoryEventTypeDispatchResponse
	FactoryEventTypeFactoryChange                 = contracts.FactoryEventTypeFactoryChange
	FactoryEventTypeFactoryStateResponse          = contracts.FactoryEventTypeFactoryStateResponse
	FactoryEventTypeInferenceRequest              = contracts.FactoryEventTypeInferenceRequest
	FactoryEventTypeInferenceResponse             = contracts.FactoryEventTypeInferenceResponse
	FactoryEventTypeInitialStructureRequest       = contracts.FactoryEventTypeInitialStructureRequest
	FactoryEventTypeJavaScriptCheckpointRef       = contracts.FactoryEventTypeJavaScriptCheckpointRef
	FactoryEventTypeJavaScriptPhaseChange         = contracts.FactoryEventTypeJavaScriptPhaseChange
	FactoryEventTypeModelRequest                  = contracts.FactoryEventTypeModelRequest
	FactoryEventTypeModelResponse                 = contracts.FactoryEventTypeModelResponse
	FactoryEventTypeOrchestratorCheckpointWritten = contracts.FactoryEventTypeOrchestratorCheckpointWritten
	FactoryEventTypeOrchestratorPhaseChanged      = contracts.FactoryEventTypeOrchestratorPhaseChanged
	FactoryEventTypeRelationshipChangeRequest     = contracts.FactoryEventTypeRelationshipChangeRequest
	FactoryEventTypeRunRequest                    = contracts.FactoryEventTypeRunRequest
	FactoryEventTypeRunResponse                   = contracts.FactoryEventTypeRunResponse
	FactoryEventTypeScriptRequest                 = contracts.FactoryEventTypeScriptRequest
	FactoryEventTypeScriptResponse                = contracts.FactoryEventTypeScriptResponse
	FactoryEventTypeSessionCompleted              = contracts.FactoryEventTypeSessionCompleted
	FactoryEventTypeSessionLifecycleControl       = contracts.FactoryEventTypeSessionLifecycleControl
	FactoryEventTypeSessionPaused                 = contracts.FactoryEventTypeSessionPaused
	FactoryEventTypeSessionResultUpdated          = contracts.FactoryEventTypeSessionResultUpdated
	FactoryEventTypeSessionResumed                = contracts.FactoryEventTypeSessionResumed
	FactoryEventTypeSessionStarted                = contracts.FactoryEventTypeSessionStarted
	FactoryEventTypeWorkRequest                   = contracts.FactoryEventTypeWorkRequest
	FactoryEventTypeWorkStateChange               = contracts.FactoryEventTypeWorkStateChange
	FactorySessionJavaScriptScriptStatusFailed    = contracts.FactorySessionJavaScriptScriptStatusFailed
	FactorySessionJavaScriptScriptStatusFinished  = contracts.FactorySessionJavaScriptScriptStatusFinished
	FactorySessionJavaScriptScriptStatusIdle      = contracts.FactorySessionJavaScriptScriptStatusIdle
	FactorySessionJavaScriptScriptStatusPaused    = contracts.FactorySessionJavaScriptScriptStatusPaused
	FactorySessionJavaScriptScriptStatusRunning   = contracts.FactorySessionJavaScriptScriptStatusRunning
	FactorySessionLifecycleControlOutcomeAccepted = contracts.FactorySessionLifecycleControlOutcomeAccepted
	FactorySessionLifecycleControlPause           = contracts.FactorySessionLifecycleControlPause
	FactorySessionLifecycleControlResume          = contracts.FactorySessionLifecycleControlResume
	FactorySessionLifecycleStatusFailed           = contracts.FactorySessionLifecycleStatusFailed
	FactorySessionLifecycleStatusPaused           = contracts.FactorySessionLifecycleStatusPaused
	FactorySessionLifecycleStatusRunning          = contracts.FactorySessionLifecycleStatusRunning
	FactorySessionLifecycleStatusSucceeded        = contracts.FactorySessionLifecycleStatusSucceeded
	FactorySessionResultStatusFailedWithPartial   = contracts.FactorySessionResultStatusFailedWithPartial
	FactorySessionResultStatusFinal               = contracts.FactorySessionResultStatusFinal
	FactorySessionResultStatusPartial             = contracts.FactorySessionResultStatusPartial
	FactoryStateCompleted                         = contracts.FactoryStateCompleted
	FactoryStateFailed                            = contracts.FactoryStateFailed
	FactoryStateIdle                              = contracts.FactoryStateIdle
	FactoryStatePaused                            = contracts.FactoryStatePaused
	FactoryStateRunning                           = contracts.FactoryStateRunning
	HostedWorkerProviderLinear                    = contracts.HostedWorkerProviderLinear
	InputsDir                                     = contracts.InputsDir
	InvocationErrorCodeCanceled                   = contracts.InvocationErrorCodeCanceled
	InvocationErrorCodeRuntimeFailure             = contracts.InvocationErrorCodeRuntimeFailure
	InvocationErrorCodeTimedOut                   = contracts.InvocationErrorCodeTimedOut
	InvocationParameterBindingKindPositional      = contracts.InvocationParameterBindingKindPositional
	InvocationTerminalStatusCanceled              = contracts.InvocationTerminalStatusCanceled
	InvocationTerminalStatusCompleted             = contracts.InvocationTerminalStatusCompleted
	InvocationTerminalStatusFailed                = contracts.InvocationTerminalStatusFailed
	InvocationTerminalStatusTimedOut              = contracts.InvocationTerminalStatusTimedOut
	JavaScriptCheckpointArtifactKind              = contracts.JavaScriptCheckpointArtifactKind
	JavaScriptCheckpointArtifactVisibility        = contracts.JavaScriptCheckpointArtifactVisibility
	MutationConsume                               = contracts.MutationConsume
	MutationCreate                                = contracts.MutationCreate
	MutationMove                                  = contracts.MutationMove
	OrchestratorKindJavaScript                    = contracts.OrchestratorKindJavaScript
	OrchestratorKindPetri                         = contracts.OrchestratorKindPetri
	OrchestratorPhaseStatusActive                 = contracts.OrchestratorPhaseStatusActive
	OrchestratorPhaseStatusCompleted              = contracts.OrchestratorPhaseStatusCompleted
	OrchestratorPhaseStatusSkipped                = contracts.OrchestratorPhaseStatusSkipped
	RejectionFeedback                             = contracts.RejectionFeedback
	RuntimeModeBatch                              = contracts.RuntimeModeBatch
	RuntimeModeService                            = contracts.RuntimeModeService
	RuntimeStatusActive                           = contracts.RuntimeStatusActive
	RuntimeStatusFinished                         = contracts.RuntimeStatusFinished
	RuntimeStatusIdle                             = contracts.RuntimeStatusIdle
	StateTypeInitial                              = contracts.StateTypeInitial
	SystemTimeExpiryTransitionID                  = contracts.SystemTimeExpiryTransitionID
	SystemTimePendingState                        = contracts.SystemTimePendingState
	SystemTimeWorkTypeID                          = contracts.SystemTimeWorkTypeID
	TimeWorkSourceCron                            = contracts.TimeWorkSourceCron
	TimeWorkTagKeyCronWorkstation                 = contracts.TimeWorkTagKeyCronWorkstation
	TimeWorkTagKeyDueAt                           = contracts.TimeWorkTagKeyDueAt
	TimeWorkTagKeyExpiresAt                       = contracts.TimeWorkTagKeyExpiresAt
	TimeWorkTagKeyJitter                          = contracts.TimeWorkTagKeyJitter
	TimeWorkTagKeyNominalAt                       = contracts.TimeWorkTagKeyNominalAt
	TimeWorkTagKeySource                          = contracts.TimeWorkTagKeySource
	WorkPropagationModeOutputAsPayload            = contracts.WorkPropagationModeOutputAsPayload
	WorkPropagationModePreserveInput              = contracts.WorkPropagationModePreserveInput
	WorkstationKindCron                           = contracts.WorkstationKindCron
	GuardTypeAllChildrenComplete                  = contracts.GuardTypeAllChildrenComplete
	GuardTypeInferenceThrottle                    = contracts.GuardTypeInferenceThrottle
	GuardTypeMatchesFields                        = contracts.GuardTypeMatchesFields
	GuardTypeSameName                             = contracts.GuardTypeSameName
	GuardTypeSameTraceID                          = contracts.GuardTypeSameTraceID
	GuardTypeVisitCount                           = contracts.GuardTypeVisitCount
	InputKindDefault                              = contracts.InputKindDefault
	StateTypeFailed                               = contracts.StateTypeFailed
	StateTypeProcessing                           = contracts.StateTypeProcessing
	StateTypeTerminal                             = contracts.StateTypeTerminal
	SystemTimePendingPlaceID                      = contracts.SystemTimePendingPlaceID
	WorkflowsDir                                  = contracts.WorkflowsDir
	WorkID                                        = contracts.WorkID
	WorkTypeID                                    = contracts.WorkTypeID
	TraceID                                       = contracts.TraceID
	ParentID                                      = contracts.ParentID
	WorkstationKindPoller                         = contracts.WorkstationKindPoller
	WorkstationKindRepeater                       = contracts.WorkstationKindRepeater
	WorkstationKindStandard                       = contracts.WorkstationKindStandard
	WorkstationTypeClassify                       = contracts.WorkstationTypeClassify
	WorkstationOutcomeFormatDecisionEnvelope      = contracts.WorkstationOutcomeFormatDecisionEnvelope
	BundledFileEncodingUTF8                       = contracts.BundledFileEncodingUTF8
	BundledFileTypeDoc                            = contracts.BundledFileTypeDoc
	BundledFileTypeInput                          = contracts.BundledFileTypeInput
	BundledFileTypeScript                         = contracts.BundledFileTypeScript
	CheckpointResumabilityStatusResumable         = contracts.CheckpointResumabilityStatusResumable
	CurrentFactoryPointerFile                     = contracts.CurrentFactoryPointerFile
	DispatchReconciliationSourceProviderSession   = contracts.DispatchReconciliationSourceProviderSession
	FactoryDispatchKindJavaScriptAgent            = contracts.FactoryDispatchKindJavaScriptAgent
	GuardTypeAnyChildFailed                       = contracts.GuardTypeAnyChildFailed
	OrchestratorInlineEncoding                    = contracts.OrchestratorInlineEncoding
	SupportedFactoryLayoutSchemaVersion           = contracts.SupportedFactoryLayoutSchemaVersion
	SystemTimeDashboardPendingPlaceID             = contracts.SystemTimeDashboardPendingPlaceID
	SystemTimeDashboardWorkTypeID                 = contracts.SystemTimeDashboardWorkTypeID
	WorkerTypeHosted                              = contracts.WorkerTypeHosted
	WorkerTypePoller                              = contracts.WorkerTypePoller
	WorkstationTypeAgent                          = contracts.WorkstationTypeAgent
	WorkstationTypeInvoke                         = contracts.WorkstationTypeInvoke
	WorkstationTypeScript                         = contracts.WorkstationTypeScript
	WorkTypeHandlingBehaviorDefault               = contracts.WorkTypeHandlingBehaviorDefault
)

var (
	ErrInvalidNamedFactory                = contracts.ErrInvalidNamedFactory
	ErrNamedFactoryAlreadyExists          = contracts.ErrNamedFactoryAlreadyExists
	ErrInvalidNamedFactoryName            = contracts.ErrInvalidNamedFactoryName
	ErrFactoryLayoutNotFound              = contracts.ErrFactoryLayoutNotFound
	ErrNamedFactoryNotFound               = contracts.ErrNamedFactoryNotFound
	ErrNamedFactoryIsCurrent              = contracts.ErrNamedFactoryIsCurrent
	NewBlockingFactoryLoadError           = contracts.NewBlockingFactoryLoadError
	AsBlockingFactoryLoadError            = contracts.AsBlockingFactoryLoadError
	NewValidationTopologyError            = contracts.NewValidationTopologyError
	FormFactoryPayloadValidationTarget    = contracts.FormFactoryPayloadValidationTarget
	InvalidFactoryNameValidationTarget    = contracts.InvalidFactoryNameValidationTarget
	StaleFactoryVersionValidationTarget   = contracts.StaleFactoryVersionValidationTarget
	FactoryRuntimeNotIdleValidationTarget = contracts.FactoryRuntimeNotIdleValidationTarget
	FactorySessionFieldValidationTarget   = contracts.FactorySessionFieldValidationTarget
	FactorySessionTargetValidationTarget  = contracts.FactorySessionTargetValidationTarget
	ResolveValidationProfile              = contracts.ResolveValidationProfile
	IsLayoutValidationCode                = contracts.IsLayoutValidationCode

	CanonicalBundledFileID                                 = contracts.CanonicalBundledFileID
	CanonicalPublicWorkstationKind                         = contracts.CanonicalPublicWorkstationKind
	CloneFactoryWorldDispatchCompletion                    = contracts.CloneFactoryWorldDispatchCompletion
	CloneFactoryWorldInferenceAttemptsByDispatchID         = contracts.CloneFactoryWorldInferenceAttemptsByDispatchID
	CloneFactoryWorldProviderSessionRecord                 = contracts.CloneFactoryWorldProviderSessionRecord
	CloneFactoryConfig                                     = contracts.CloneFactoryConfig
	CloneGuardMatchConfig                                  = contracts.CloneGuardMatchConfig
	CloneIOConfigs                                         = contracts.CloneIOConfigs
	CloneModelOperationBindings                            = contracts.CloneModelOperationBindings
	CloneModelOperations                                   = contracts.CloneModelOperations
	CloneWorkstationConfig                                 = contracts.CloneWorkstationConfig
	CloneWorkstationInputs                                 = contracts.CloneWorkstationInputs
	EffectiveOrchestratorKind                              = contracts.EffectiveOrchestratorKind
	ErrFactoryActivationRequiresIdle                       = contracts.ErrFactoryActivationRequiresIdle
	FirstRuntimeDefinitionLookup                           = contracts.FirstRuntimeDefinitionLookup
	IsJavaScriptOrchestratorFactory                        = contracts.IsJavaScriptOrchestratorFactory
	IsPollerWorkerType                                     = contracts.IsPollerWorkerType
	IsSystemTimePlace                                      = contracts.IsSystemTimePlace
	IsSystemTimeToken                                      = contracts.IsSystemTimeToken
	IsSystemTimeWorkType                                   = contracts.IsSystemTimeWorkType
	NewFactorySnapshot                                     = contracts.NewFactorySnapshot
	PermissivePublicFactoryWorkerModelProvider             = contracts.PermissivePublicFactoryWorkerModelProvider
	PermissivePublicFactoryWorkerProvider                  = contracts.PermissivePublicFactoryWorkerProvider
	PublicWorkerModelProviderFromInternalRuntime           = contracts.PublicWorkerModelProviderFromInternalRuntime
	PublicWorkerProviderFromInternalRuntime                = contracts.PublicWorkerProviderFromInternalRuntime
	PublicWorkerTypeFromInternalRuntime                    = contracts.PublicWorkerTypeFromInternalRuntime
	PublicWorkstationTypeFromInternalRuntime               = contracts.PublicWorkstationTypeFromInternalRuntime
	StrictPublicFactoryOrchestratorKind                    = contracts.StrictPublicFactoryOrchestratorKind
	StrictPublicFactoryWorkstationType                     = contracts.StrictPublicFactoryWorkstationType
	StrictPublicFactoryWorkerModelProvider                 = contracts.StrictPublicFactoryWorkerModelProvider
	InternalModelProviderFromPublicWorkerModelProvider     = contracts.InternalModelProviderFromPublicWorkerModelProvider
	AcceptedPublicWorkerModelProviderSummary               = contracts.AcceptedPublicWorkerModelProviderSummary
	BuildPendingFactoryGraphTopology                       = contracts.BuildPendingFactoryGraphTopology
	InternalRuntimeWorkerTypeFromPublic                    = contracts.InternalRuntimeWorkerTypeFromPublic
	InternalRuntimeWorkstationTypeFromPublic               = contracts.InternalRuntimeWorkstationTypeFromPublic
	IsPollerWorkerPublicType                               = contracts.IsPollerWorkerPublicType
	PermissivePublicFactoryHostedWorkerProvider            = contracts.PermissivePublicFactoryHostedWorkerProvider
	PermissivePublicFactoryResourceType                    = contracts.PermissivePublicFactoryResourceType
	PermissivePublicFactoryWorkerModelLocality             = contracts.PermissivePublicFactoryWorkerModelLocality
	PermissivePublicFactoryWorkerModelOperationContentType = contracts.PermissivePublicFactoryWorkerModelOperationContentType
	PermissivePublicFactoryWorkstationOutcomeFormat        = contracts.PermissivePublicFactoryWorkstationOutcomeFormat
	PermissivePublicFactoryWorkstationType                 = contracts.PermissivePublicFactoryWorkstationType
	StrictPublicFactoryHostedWorkerProvider                = contracts.StrictPublicFactoryHostedWorkerProvider
	StrictPublicFactoryResourceType                        = contracts.StrictPublicFactoryResourceType
	StrictPublicFactoryRunnerID                            = contracts.StrictPublicFactoryRunnerID
	StrictPublicFactoryWorkerModelLocality                 = contracts.StrictPublicFactoryWorkerModelLocality
	StrictPublicFactoryWorkerModelOperationContentType     = contracts.StrictPublicFactoryWorkerModelOperationContentType
	StrictPublicFactoryWorkerProvider                      = contracts.StrictPublicFactoryWorkerProvider
	StrictPublicFactoryWorkerType                          = contracts.StrictPublicFactoryWorkerType
	StrictPublicFactoryWorkstationOutcomeFormat            = contracts.StrictPublicFactoryWorkstationOutcomeFormat
	StrictPublicWorkstationKind                            = contracts.StrictPublicWorkstationKind
	StrictPublicWorkTypeHandlingBehavior                   = contracts.StrictPublicWorkTypeHandlingBehavior
)
