package factorydefinitions

import contracts "github.com/portpowered/infinite-you/pkg/services/factory_definitions/internal/contracts"

type CurrentFactoryPointerReader = contracts.CurrentFactoryPointerReader
type CurrentFactoryPointerWriter = contracts.CurrentFactoryPointerWriter

type FactoryLayoutPayloadMapper = contracts.FactoryLayoutPayloadMapper
type FactoryLayoutPayloadPreparer = contracts.FactoryLayoutPayloadPreparer
type NamedFactoryPersister = contracts.NamedFactoryPersister
type FactoryLayoutReplacer = contracts.FactoryLayoutReplacer
type FactoryLayoutFlattener = contracts.FactoryLayoutFlattener
type FactoryLayoutExpander = contracts.FactoryLayoutExpander
type FactoryConfigJSONDecoder = contracts.FactoryConfigJSONDecoder
type FactoryConfigJSONEncoder = contracts.FactoryConfigJSONEncoder
type CanonicalFactoryJSONLoader = contracts.CanonicalFactoryJSONLoader
type PortableFactoryConfigPreparer = contracts.PortableFactoryConfigPreparer
type FactoryConfigCloner = contracts.FactoryConfigCloner
type PortableBundledFilesApplier = contracts.PortableBundledFilesApplier
type FactoryStarterWorkApplier = contracts.FactoryStarterWorkApplier
type PortableBundledFilesMaterializer = contracts.PortableBundledFilesMaterializer
type PortableBundledFileWritesValidator = contracts.PortableBundledFileWritesValidator
type PortableBundledFilesCopier = contracts.PortableBundledFilesCopier
type PortableBundledDocsPruner = contracts.PortableBundledDocsPruner
type PortableBundledFileSourceResolver = contracts.PortableBundledFileSourceResolver
type FactorySnapshotCapturer = contracts.FactorySnapshotCapturer
type LoadedFactorySnapshotCapturer = contracts.LoadedFactorySnapshotCapturer
type FactorySnapshotObjectMapper = contracts.FactorySnapshotObjectMapper
