package packagedfactorycatalog

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

const (
	// CatalogManifestPath is the package-relative catalog index location.
	CatalogManifestPath = "generated/manifest.json"
	generatedNoticePath = "generated/README.md"
	generatedNotice     = "<!-- Code generated by packagedfactorycataloggenerate. DO NOT EDIT. -->\n\n" +
		"# Generated Factory catalog\n\n" +
		"Run `make packaged-factory-catalog-generate` from the repository root to regenerate this directory.\n"
)

// Catalog is a complete, validated package-relative output plan.
type Catalog struct {
	Files map[string][]byte
}

// BuildCatalogDependencies exposes the complete projection pass for
// determinism and changing-input tests.
type BuildCatalogDependencies struct {
	BuildOnce func(context.Context, fs.FS, string, string) (map[string][]byte, error)
}

// ReplaceCatalogDependencies lets tests force a staging failure before the
// generated directory swap.
type ReplaceCatalogDependencies struct {
	WriteFile func(string, []byte, fs.FileMode) error
}

// BuildCatalog plans the whole generated catalog in memory and rejects output
// that is not identical across two independent projection passes.
func BuildCatalog(
	ctx context.Context,
	source fs.FS,
	root string,
	schemaPath string,
) (Catalog, error) {
	return BuildCatalogWithDependencies(ctx, source, root, schemaPath, BuildCatalogDependencies{})
}

// BuildCatalogWithDependencies plans the catalog with caller-controlled
// projection behavior.
func BuildCatalogWithDependencies(
	ctx context.Context,
	source fs.FS,
	root string,
	schemaPath string,
	requested BuildCatalogDependencies,
) (Catalog, error) {
	buildOnce := requested.BuildOnce
	if buildOnce == nil {
		buildOnce = buildCatalogOnce
	}
	first, err := buildOnce(ctx, source, root, schemaPath)
	if err != nil {
		return Catalog{}, err
	}
	if err := validateOutputPlan(first); err != nil {
		return Catalog{}, err
	}
	second, err := buildOnce(ctx, source, root, schemaPath)
	if err != nil {
		return Catalog{}, fmt.Errorf("catalog determinism validation pass: %w", err)
	}
	if err := validateOutputPlan(second); err != nil {
		return Catalog{}, err
	}
	if err := compareOutputPlans(first, second); err != nil {
		return Catalog{}, err
	}
	return Catalog{Files: cloneFiles(first)}, nil
}

func buildCatalogOnce(
	ctx context.Context,
	source fs.FS,
	root string,
	schemaPath string,
) (map[string][]byte, error) {
	artifacts, err := GenerateArtifacts(ctx, source, root, schemaPath)
	if err != nil {
		return nil, err
	}
	schemaIdentity, err := readSchemaIdentity(source, schemaPath)
	if err != nil {
		return nil, err
	}
	manifest, err := ProjectManifest(artifacts, schemaIdentity)
	if err != nil {
		return nil, err
	}
	files := make(map[string][]byte, len(artifacts)*2+2)
	files[CatalogManifestPath] = manifest.JSON
	files[generatedNoticePath] = []byte(generatedNotice)
	for _, artifact := range artifacts {
		jsonPath, yamlPath, err := artifactLocators(artifact.Slug)
		if err != nil {
			return nil, fmt.Errorf("catalog collision: %s: %w", artifact.SourcePath, err)
		}
		files[jsonPath] = artifact.JSON
		files[yamlPath] = artifact.YAML
	}
	if err := validateManifestHashes(manifest.Manifest, files); err != nil {
		return nil, err
	}
	return files, nil
}

func validateManifestHashes(manifest Manifest, files map[string][]byte) error {
	for _, entry := range manifest.Factories {
		for _, artifact := range []ManifestArtifact{entry.JSON, entry.YAML} {
			payload, ok := files[artifact.Locator]
			if !ok {
				return fmt.Errorf("catalog hashing: manifest locator %s has no planned artifact", artifact.Locator)
			}
			if computed := integrity(artifact.Locator, payload); computed.SHA256 != artifact.SHA256 {
				return fmt.Errorf(
					"catalog hashing: manifest hash for %s is %s, computed %s",
					artifact.Locator,
					artifact.SHA256,
					computed.SHA256,
				)
			}
		}
	}
	return nil
}

func validateOutputPlan(files map[string][]byte) error {
	if len(files) == 0 {
		return errors.New("catalog output planning: output set is empty")
	}
	owners := make(map[string][]string, len(files))
	for target := range files {
		if !fs.ValidPath(target) || path.Clean(target) != target ||
			!strings.HasPrefix(target, "generated/") {
			return fmt.Errorf("catalog output planning: unsafe package-relative target %q", target)
		}
		normalized := strings.ToLower(target)
		owners[normalized] = append(owners[normalized], target)
		for parent := path.Dir(target); parent != "."; parent = path.Dir(parent) {
			if _, exists := files[parent]; exists {
				return fmt.Errorf(
					"catalog collision: output target %q conflicts with parent file %q",
					target,
					parent,
				)
			}
		}
	}
	var collisions []string
	for normalized, targets := range owners {
		if len(targets) < 2 {
			continue
		}
		sort.Strings(targets)
		collisions = append(collisions, fmt.Sprintf("%q: %s", normalized, strings.Join(targets, ", ")))
	}
	if len(collisions) > 0 {
		sort.Strings(collisions)
		return fmt.Errorf("catalog collision: normalized output targets conflict:\n- %s", strings.Join(collisions, "\n- "))
	}
	return nil
}

func compareOutputPlans(first, second map[string][]byte) error {
	paths := make(map[string]struct{}, len(first)+len(second))
	for target := range first {
		paths[target] = struct{}{}
	}
	for target := range second {
		paths[target] = struct{}{}
	}
	ordered := make([]string, 0, len(paths))
	for target := range paths {
		ordered = append(ordered, target)
	}
	sort.Strings(ordered)
	for _, target := range ordered {
		left, leftOK := first[target]
		right, rightOK := second[target]
		if !leftOK || !rightOK {
			return fmt.Errorf("catalog serialization nondeterminism: output set changed at %s", target)
		}
		if !bytes.Equal(left, right) {
			return fmt.Errorf("catalog serialization nondeterminism: bytes changed at %s", target)
		}
	}
	return nil
}

func cloneFiles(files map[string][]byte) map[string][]byte {
	cloned := make(map[string][]byte, len(files))
	for target, payload := range files {
		cloned[target] = append([]byte(nil), payload...)
	}
	return cloned
}

// Generate builds and atomically replaces the checked-in generated catalog.
func Generate(repositoryRoot string) error {
	absoluteRoot, err := filepath.Abs(repositoryRoot)
	if err != nil {
		return fmt.Errorf("catalog write: resolve repository root: %w", err)
	}
	packageRoot := filepath.Join(absoluteRoot, "packages", "packaged-factories")
	catalog, err := BuildCatalog(
		context.Background(),
		os.DirFS(packageRoot),
		"factories",
		"schemas/factory.schema.json",
	)
	if err != nil {
		return err
	}
	return ReplaceGeneratedDirectory(packageRoot, catalog)
}

// ReplaceGeneratedDirectory stages every output before replacing the prior
// generated directory, so a planning or staging failure leaves it untouched.
func ReplaceGeneratedDirectory(packageRoot string, catalog Catalog) error {
	return ReplaceGeneratedDirectoryWithDependencies(
		packageRoot,
		catalog,
		ReplaceCatalogDependencies{},
	)
}

// ReplaceGeneratedDirectoryWithDependencies replaces the generated directory
// with caller-controlled staging IO.
func ReplaceGeneratedDirectoryWithDependencies(
	packageRoot string,
	catalog Catalog,
	requested ReplaceCatalogDependencies,
) error {
	if err := validateOutputPlan(catalog.Files); err != nil {
		return err
	}
	writeFile := requested.WriteFile
	if writeFile == nil {
		writeFile = os.WriteFile
	}
	absoluteRoot, err := filepath.Abs(packageRoot)
	if err != nil {
		return fmt.Errorf("catalog write: resolve package root: %w", err)
	}
	stage, err := os.MkdirTemp(absoluteRoot, ".generated-stage-*")
	if err != nil {
		return fmt.Errorf("catalog write: create staging directory: %w", err)
	}
	stageExists := true
	defer func() {
		if stageExists {
			_ = os.RemoveAll(stage)
		}
	}()

	targets := make([]string, 0, len(catalog.Files))
	for target := range catalog.Files {
		targets = append(targets, target)
	}
	sort.Strings(targets)
	for _, target := range targets {
		relative := strings.TrimPrefix(target, "generated/")
		stagedTarget := filepath.Join(stage, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(stagedTarget), 0o755); err != nil {
			return fmt.Errorf("catalog write: create directory for %s: %w", target, err)
		}
		if err := writeFile(stagedTarget, catalog.Files[target], 0o644); err != nil {
			return fmt.Errorf("catalog write: stage %s: %w", target, err)
		}
	}

	destination := filepath.Join(absoluteRoot, "generated")
	backup := stage + "-previous"
	hadDestination := false
	if _, err := os.Stat(destination); err == nil {
		hadDestination = true
		if err := os.Rename(destination, backup); err != nil {
			return fmt.Errorf("catalog write: preserve previous generated directory: %w", err)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("catalog write: inspect previous generated directory: %w", err)
	}
	if err := os.Rename(stage, destination); err != nil {
		if hadDestination {
			if rollbackErr := os.Rename(backup, destination); rollbackErr != nil {
				return fmt.Errorf(
					"catalog write: install complete generated directory: %w; rollback failed: %v",
					err,
					rollbackErr,
				)
			}
		}
		return fmt.Errorf("catalog write: install complete generated directory: %w", err)
	}
	stageExists = false
	if hadDestination {
		if err := os.RemoveAll(backup); err != nil {
			return fmt.Errorf("catalog write: remove previous generated directory: %w", err)
		}
	}
	return nil
}
