package providercatalog

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Drift describes committed generated outputs that differ from the output plan.
type Drift struct {
	Stale      []string
	Missing    []string
	Unexpected []string
}

func (drift Drift) Empty() bool {
	return len(drift.Stale) == 0 && len(drift.Missing) == 0 && len(drift.Unexpected) == 0
}

// Generate validates all inputs before atomically replacing the generated directory.
func Generate(repositoryRoot string) error {
	catalog, err := Build(os.DirFS(repositoryRoot))
	if err != nil {
		return err
	}
	return replaceGenerated(repositoryRoot, catalog)
}

// Check compares generated bytes without writing to the worktree.
func Check(repositoryRoot string) (Drift, error) {
	catalog, err := Build(os.DirFS(repositoryRoot))
	if err != nil {
		return Drift{}, err
	}
	drift := Drift{}
	for target, expected := range catalog.Files {
		actual, err := os.ReadFile(filepath.Join(repositoryRoot, filepath.FromSlash(target)))
		switch {
		case errors.Is(err, os.ErrNotExist):
			drift.Missing = append(drift.Missing, target)
		case err != nil:
			return Drift{}, fmt.Errorf("read generated output %s: %w", target, err)
		case !bytes.Equal(actual, expected):
			drift.Stale = append(drift.Stale, target)
		}
	}
	generatedRoot := filepath.Join(repositoryRoot, "packages", "model-providers", "generated")
	err = filepath.WalkDir(generatedRoot, func(current string, entry fs.DirEntry, walkErr error) error {
		if errors.Is(walkErr, os.ErrNotExist) {
			return nil
		}
		if walkErr != nil || entry.IsDir() {
			return walkErr
		}
		relative, err := filepath.Rel(repositoryRoot, current)
		if err != nil {
			return err
		}
		target := filepath.ToSlash(relative)
		if _, expected := catalog.Files[target]; !expected {
			drift.Unexpected = append(drift.Unexpected, target)
		}
		return nil
	})
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return Drift{}, fmt.Errorf("inspect generated provider outputs: %w", err)
	}
	sort.Strings(drift.Stale)
	sort.Strings(drift.Missing)
	sort.Strings(drift.Unexpected)
	return drift, nil
}

func replaceGenerated(repositoryRoot string, catalog Catalog) error {
	packageRoot := filepath.Join(repositoryRoot, "packages", "model-providers")
	stage, err := os.MkdirTemp(packageRoot, ".generated-stage-*")
	if err != nil {
		return fmt.Errorf("create provider catalog staging directory: %w", err)
	}
	defer os.RemoveAll(stage)
	for target, payload := range catalog.Files {
		name := strings.TrimPrefix(target, "packages/model-providers/generated/")
		if name == target || filepath.Base(name) != name {
			return fmt.Errorf("unsafe provider catalog output target %q", target)
		}
		if err := os.WriteFile(filepath.Join(stage, name), payload, 0o644); err != nil {
			return fmt.Errorf("stage provider catalog output %s: %w", target, err)
		}
	}
	destination := filepath.Join(packageRoot, "generated")
	backup := stage + "-previous"
	if err := installStagedDirectory(stage, destination, backup); err != nil {
		return err
	}
	return os.RemoveAll(backup)
}

func installStagedDirectory(stage, destination, backup string) error {
	hadDestination := false
	if _, err := os.Stat(destination); err == nil {
		hadDestination = true
		if err := os.Rename(destination, backup); err != nil {
			return fmt.Errorf("preserve previous provider catalog outputs: %w", err)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect previous provider catalog outputs: %w", err)
	}
	if err := os.Rename(stage, destination); err != nil {
		if hadDestination {
			_ = os.Rename(backup, destination)
		}
		return fmt.Errorf("install generated provider catalog outputs: %w", err)
	}
	return nil
}
