package cli_test

import (
	"bytes"
	"context"
	"errors"
	"strings"
	"testing"

	recordingscli "github.com/portpowered/infinite-you/pkg/services/recordings/transports/cli"
	"github.com/portpowered/infinite-you/pkg/services/recordings"
)

func TestAdapterReportRecordingPathOnShutdownPreservesAcceptedPresentation(t *testing.T) {
	t.Parallel()

	adapter := recordingscli.New()
	var out bytes.Buffer

	adapter.ReportRecordingPathOnShutdown(&out, recordingscli.ResolvedRecordPath{
		ServicePath:   "/tmp/template.json",
		ReportedPath:  "/tmp/resolved.json",
		AutoGenerated: true,
	})
	if got := out.String(); got != "Recording saved: /tmp/resolved.json\n" {
		t.Fatalf("shutdown output = %q, want accepted recording saved presentation", got)
	}
}

func TestAdapterReportRecordingPathOnShutdownSkipsNonGeneratedPaths(t *testing.T) {
	t.Parallel()

	adapter := recordingscli.New()
	var out bytes.Buffer

	adapter.ReportRecordingPathOnShutdown(&out, recordingscli.ResolvedRecordPath{
		ServicePath: "explicit.replay.json",
	})
	if out.Len() != 0 {
		t.Fatalf("shutdown output = %q, want empty for explicit record path", out.String())
	}
}

func TestAdapterRecordingDiagnosticsLabelPreservesAcceptedModes(t *testing.T) {
	t.Parallel()

	adapter := recordingscli.New()
	tests := []struct {
		name       string
		resolved   recordingscli.ResolvedRecordPath
		replayPath string
		want       string
	}{
		{
			name:       "replay",
			replayPath: "existing.replay.json",
			want:       "replay",
		},
		{
			name: "disabled",
			want: "disabled",
		},
		{
			name: "default",
			resolved: recordingscli.ResolvedRecordPath{
				ServicePath:   "/tmp/template.json",
				AutoGenerated: true,
			},
			want: "default",
		},
		{
			name: "explicit",
			resolved: recordingscli.ResolvedRecordPath{
				ServicePath: "explicit.replay.json",
			},
			want: "explicit",
		},
	}

	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			got := adapter.RecordingDiagnosticsLabel(test.resolved, test.replayPath)
			if got != test.want {
				t.Fatalf("RecordingDiagnosticsLabel() = %q, want %q", got, test.want)
			}
		})
	}
}

func TestAdapterFailurePathsPreserveExitRelevantErrors(t *testing.T) {
	t.Parallel()

	adapter := recordingscli.New()
	tests := []struct {
		name    string
		request recordingscli.InvocationRequest
		wantErr string
	}{
		{
			name: "missing planner",
			request: recordingscli.InvocationRequest{
				HomeDir: "",
			},
			wantErr: "Recordings live recording target planner is required",
		},
		{
			name: "planner failure",
			request: recordingscli.InvocationRequest{
				RecordingTargetPlanner: recordings.LiveRecordingTargetPlannerFunc(
					func(recordings.LiveRecordingTargetRequest) (recordings.LiveRecordingTarget, error) {
						return recordings.LiveRecordingTarget{}, errors.New("target planning failed")
					},
				),
			},
			wantErr: "resolve default replay record path",
		},
		{
			name: "no-record with record",
			request: recordingscli.InvocationRequest{
				RecordPath:              "run.replay.json",
				DisableDefaultRecording: true,
			},
			wantErr: "--no-record cannot be used with --record",
		},
		{
			name: "record with replay",
			request: recordingscli.InvocationRequest{
				RecordPath: "run.replay.json",
				ReplayPath: "existing.replay.json",
			},
			wantErr: "--record and --replay cannot be used together",
		},
	}

	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			request := test.request
			if strings.TrimSpace(request.HomeDir) == "" {
				request.HomeDir = t.TempDir()
			}

			_, err := adapter.ResolveRecordPath(request)
			if err == nil {
				t.Fatal("expected failure")
			}
			if !strings.Contains(err.Error(), test.wantErr) {
				t.Fatalf("error = %v, want substring %q", err, test.wantErr)
			}
		})
	}
}

func TestAdapterResolveRecordPathWithContextHonorsCancellation(t *testing.T) {
	t.Parallel()

	plannerCalled := false
	planner := recordings.LiveRecordingTargetPlannerFunc(
		func(recordings.LiveRecordingTargetRequest) (recordings.LiveRecordingTarget, error) {
			plannerCalled = true
			return recordings.LiveRecordingTarget{
				ServicePath:  "/tmp/template.json",
				ReportedPath: "/tmp/resolved.json",
			}, nil
		},
	)
	adapter := recordingscli.New()
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	_, err := adapter.ResolveRecordPathWithContext(ctx, recordingscli.InvocationRequest{
		HomeDir:                t.TempDir(),
		RecordingTargetPlanner: planner,
	})
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("ResolveRecordPathWithContext() error = %v, want context.Canceled", err)
	}
	if plannerCalled {
		t.Fatal("expected canceled request to fail before planner invocation")
	}
}

func TestAdapterShutdownReportingUnaffectedByCanceledRequestContext(t *testing.T) {
	t.Parallel()

	adapter := recordingscli.New()
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	resolved, err := adapter.ResolveRecordPathWithContext(ctx, recordingscli.InvocationRequest{
		RecordPath: "explicit.replay.json",
	})
	if err != nil {
		t.Fatalf("explicit record path should not depend on canceled context: %v", err)
	}

	var out bytes.Buffer
	adapter.ReportRecordingPathOnShutdown(&out, resolved)
	if out.Len() != 0 {
		t.Fatalf("shutdown output = %q, want empty for explicit record path", out.String())
	}

	resolved, err = adapter.ResolveRecordPath(recordingscli.InvocationRequest{
		HomeDir: t.TempDir(),
		RecordingTargetPlanner: recordings.LiveRecordingTargetPlannerFunc(
			func(recordings.LiveRecordingTargetRequest) (recordings.LiveRecordingTarget, error) {
				return recordings.LiveRecordingTarget{
					ServicePath:  "/tmp/template.json",
					ReportedPath: "/tmp/resolved.json",
				}, nil
			},
		),
	})
	if err != nil {
		t.Fatalf("ResolveRecordPath() error = %v", err)
	}

	adapter.ReportRecordingPathOnShutdown(&out, resolved)
	if got := out.String(); got != "Recording saved: /tmp/resolved.json\n" {
		t.Fatalf("shutdown output after canceled context = %q, want accepted presentation", got)
	}
}
