package cli

import (
	"errors"
	"path/filepath"
	"strings"
	"testing"

	"github.com/portpowered/infinite-you/pkg/services/recordings"
	factoryapi "github.com/portpowered/infinite-you/pkg/transports/http/generated"
)

func TestAdapterResolveRecordPathModes(t *testing.T) {
	t.Parallel()

	homeDir := t.TempDir()
	plannedPath := filepath.Join(homeDir, "recordings", "planned.json")
	planner := recordings.LiveRecordingTargetPlannerFunc(func(request recordings.LiveRecordingTargetRequest) (recordings.LiveRecordingTarget, error) {
		if request.HomeDir != homeDir || request.ReportedSessionID != DefaultReportedFactorySessionID {
			t.Fatalf("recording request = %#v", request)
		}
		return recordings.LiveRecordingTarget{
			ServicePath:  plannedPath,
			ReportedPath: plannedPath,
		}, nil
	})
	adapter := New()

	tests := []struct {
		name          string
		request       InvocationRequest
		wantService   string
		wantReported  string
		wantGenerated bool
	}{
		{
			name: "default live mode",
			request: InvocationRequest{
				HomeDir:                homeDir,
				RecordingTargetPlanner: planner,
			},
			wantService:   plannedPath,
			wantReported:  plannedPath,
			wantGenerated: true,
		},
		{
			name: "resume plans live successor recording",
			request: InvocationRequest{
				ResumePath:             "existing.recording.json",
				HomeDir:                homeDir,
				RecordingTargetPlanner: planner,
			},
			wantService:   plannedPath,
			wantReported:  plannedPath,
			wantGenerated: true,
		},
		{
			name: "resume with explicit successor recording",
			request: InvocationRequest{
				ResumePath: "existing.recording.json",
				RecordPath: "successor.recording.json",
			},
			wantService: "successor.recording.json",
		},
		{
			name: "explicit record path",
			request: InvocationRequest{
				RecordPath: "run.replay.json",
			},
			wantService: "run.replay.json",
		},
		{
			name: "replay disables default recording",
			request: InvocationRequest{
				ReplayPath: "existing.replay.json",
			},
		},
		{
			name: "no-record disables default recording",
			request: InvocationRequest{
				DisableDefaultRecording: true,
			},
		},
	}

	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			resolved, err := adapter.ResolveRecordPath(test.request)
			if err != nil {
				t.Fatalf("ResolveRecordPath() error = %v", err)
			}
			if resolved.ServicePath != test.wantService {
				t.Fatalf("ServicePath = %q, want %q", resolved.ServicePath, test.wantService)
			}
			if resolved.ReportedPath != test.wantReported {
				t.Fatalf("ReportedPath = %q, want %q", resolved.ReportedPath, test.wantReported)
			}
			if resolved.AutoGenerated != test.wantGenerated {
				t.Fatalf("AutoGenerated = %t, want %t", resolved.AutoGenerated, test.wantGenerated)
			}
		})
	}
}

func TestAdapterResolveRecordPathRejectsIncompatibleFlags(t *testing.T) {
	t.Parallel()

	adapter := New()
	tests := []struct {
		name    string
		request InvocationRequest
		wantErr string
	}{
		{
			name: "no-record with record",
			request: InvocationRequest{
				RecordPath:              "run.replay.json",
				DisableDefaultRecording: true,
			},
			wantErr: "--no-record cannot be used with --record",
		},
		{
			name: "record with replay",
			request: InvocationRequest{
				RecordPath: "run.replay.json",
				ReplayPath: "existing.replay.json",
			},
			wantErr: "--record and --replay cannot be used together",
		},
		{
			name: "resume with replay",
			request: InvocationRequest{
				ResumePath: "existing.recording.json",
				ReplayPath: "existing.replay.json",
			},
			wantErr: "--resume cannot be used with --replay",
		},
		{
			name: "resume with no-record",
			request: InvocationRequest{
				ResumePath:              "existing.recording.json",
				DisableDefaultRecording: true,
			},
			wantErr: "--resume cannot be used with --no-record",
		},
	}

	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			_, err := adapter.ResolveRecordPath(test.request)
			if err == nil {
				t.Fatal("expected incompatible flag combination to fail")
			}
			if !strings.Contains(err.Error(), test.wantErr) {
				t.Fatalf("error = %v, want substring %q", err, test.wantErr)
			}
		})
	}
}

func TestAdapterResolveRecordPathRequiresPlannerForDefaultMode(t *testing.T) {
	t.Parallel()

	_, err := New().ResolveRecordPath(InvocationRequest{HomeDir: "home"})
	if err == nil || err.Error() != "Recordings live recording target planner is required" {
		t.Fatalf("ResolveRecordPath() error = %v, want required planner", err)
	}
}

func TestAdapterResolveDefaultRecordPathRejectsEmptyPlannedServicePath(t *testing.T) {
	t.Parallel()

	_, err := New().ResolveRecordPath(InvocationRequest{
		HomeDir: t.TempDir(),
		RecordingTargetPlanner: recordings.LiveRecordingTargetPlannerFunc(
			func(recordings.LiveRecordingTargetRequest) (recordings.LiveRecordingTarget, error) {
				return recordings.LiveRecordingTarget{}, nil
			},
		),
	})
	if err == nil || err.Error() != "resolve default replay record path: planner returned an empty service path" {
		t.Fatalf("ResolveRecordPath() error = %v, want empty default service path failure", err)
	}
}

func TestAdapterResolveRecordPathPropagatesPlannerFailure(t *testing.T) {
	t.Parallel()

	_, err := New().ResolveRecordPath(InvocationRequest{
		HomeDir: t.TempDir(),
		RecordingTargetPlanner: recordings.LiveRecordingTargetPlannerFunc(
			func(recordings.LiveRecordingTargetRequest) (recordings.LiveRecordingTarget, error) {
				return recordings.LiveRecordingTarget{}, errors.New("target planning failed")
			},
		),
	})
	if err == nil {
		t.Fatal("expected default record path resolution to fail")
	}
	if !strings.Contains(err.Error(), "resolve default replay record path") {
		t.Fatalf("error = %v, want planner failure wrapper", err)
	}
}

func TestAdapterResolveResumeRecordPathPropagatesPlannerFailure(t *testing.T) {
	t.Parallel()

	_, err := New().ResolveRecordPath(InvocationRequest{
		ResumePath: "existing.recording.json",
		HomeDir:    t.TempDir(),
		RecordingTargetPlanner: recordings.LiveRecordingTargetPlannerFunc(
			func(recordings.LiveRecordingTargetRequest) (recordings.LiveRecordingTarget, error) {
				return recordings.LiveRecordingTarget{}, errors.New("target planning failed")
			},
		),
	})
	if err == nil {
		t.Fatal("expected resume successor record path resolution to fail")
	}
	if !strings.Contains(err.Error(), "resolve resume successor recording path") {
		t.Fatalf("error = %v, want resume planner failure wrapper", err)
	}
}

func TestAdapterResolveResumeRecordPathRequiresNonEmptyPlannedServicePath(t *testing.T) {
	t.Parallel()

	_, err := New().ResolveRecordPath(InvocationRequest{
		ResumePath: "existing.recording.json",
		HomeDir:    t.TempDir(),
		RecordingTargetPlanner: recordings.LiveRecordingTargetPlannerFunc(
			func(recordings.LiveRecordingTargetRequest) (recordings.LiveRecordingTarget, error) {
				return recordings.LiveRecordingTarget{}, nil
			},
		),
	})
	if err == nil || !strings.Contains(err.Error(), "planner returned an empty service path") {
		t.Fatalf("error = %v, want empty planned service path failure", err)
	}
}

func TestMapStructuralReplayFailurePreservesSafeCodedDiagnostic(t *testing.T) {
	t.Parallel()

	cause := errors.New(`open C:\private\recordings\legacy.jsonl`)
	diagnostic := recordings.ReplayArtifactDiagnostic{
		Code:    recordings.ReplayArtifactDiagnosticInvalidIdentity,
		Area:    "events",
		Path:    "events[3]",
		Message: "event \"event-bad\" has\tduplicate\nidentity",
	}
	inputErr := &recordings.ReplayInputError{
		Family:     recordings.ReplayInputFamilyLegacy,
		Diagnostic: diagnostic,
		Cause:      cause,
	}
	mapped := MapStructuralReplayFailure(inputErr)
	if mapped == nil {
		t.Fatal("MapStructuralReplayFailure() = nil, want legacy structural diagnostic")
	}
	type codedError interface {
		error
		CLIErrorCode() string
		CLIErrorFamily() factoryapi.ErrorFamily
		CLIErrorMessage() string
	}
	var coded codedError
	if !errors.As(mapped, &coded) {
		t.Fatalf("mapped error %T does not implement the coded CLI error contract", mapped)
	}
	if coded.CLIErrorCode() != string(recordings.ReplayArtifactDiagnosticInvalidIdentity) ||
		coded.CLIErrorFamily() != factoryapi.ErrorFamilyBadRequest {
		t.Fatalf("coded error = %q / %q, want invalid identity / bad request", coded.CLIErrorCode(), coded.CLIErrorFamily())
	}
	want := `Error: INVALID_RECORDING_IDENTITY area=events path=events[3] event="event-bad" action="REPLACE_OR_REGENERATE_RECORDING": event "event-bad" has duplicate identity`
	if mapped.Error() != want || coded.CLIErrorMessage() != want {
		t.Fatalf("mapped error = %q, coded message = %q, want %q", mapped.Error(), coded.CLIErrorMessage(), want)
	}
	if strings.Contains(mapped.Error(), `C:\private\recordings\legacy.jsonl`) || !errors.Is(mapped, cause) {
		t.Fatalf("mapped error leaked its local source or lost its cause: %q", mapped)
	}
}

func TestMapReplayInputFailurePreservesExistingCodesAndRedactsSourceDetails(t *testing.T) {
	t.Parallel()

	codes := []recordings.ReplayArtifactDiagnosticCode{
		recordings.ReplayArtifactDiagnosticMalformed,
		recordings.ReplayArtifactDiagnosticUnsupportedVersion,
		recordings.ReplayArtifactDiagnosticUnsupportedSchema,
		recordings.ReplayArtifactDiagnosticInvalidIdentity,
		recordings.ReplayArtifactDiagnosticInvalidSummary,
		recordings.ReplayArtifactDiagnosticInvalidIntegrity,
		recordings.ReplayArtifactDiagnosticInvalidOrder,
		recordings.ReplayArtifactDiagnosticMissingReference,
		recordings.ReplayArtifactDiagnosticForeignReference,
		recordings.ReplayArtifactDiagnosticRecordingNotFound,
		recordings.ReplayArtifactDiagnosticRecordingNotFinalized,
		recordings.ReplayArtifactDiagnosticDependencyFailure,
		recordings.ReplayArtifactDiagnosticCancelled,
	}
	for _, code := range codes {
		code := code
		t.Run(string(code), func(t *testing.T) {
			t.Parallel()

			cause := errors.New(`open C:\private\recording.json payload=TOPSECRET`)
			inputErr := &recordings.ReplayInputError{
				Family: recordings.ReplayInputFamilyPortable,
				Diagnostic: recordings.ReplayArtifactDiagnostic{
					Code: code, Area: "recording", Path: "recording", Message: "TOPSECRET source bytes",
				},
				Cause: cause,
			}
			mapped := MapReplayInputFailure(inputErr)
			if mapped == nil {
				t.Fatal("MapReplayInputFailure() = nil, want a coded Recordings diagnostic")
			}
			type codedError interface {
				error
				CLIErrorCode() string
				CLIErrorFamily() factoryapi.ErrorFamily
				CLIErrorMessage() string
			}
			var coded codedError
			if !errors.As(mapped, &coded) {
				t.Fatalf("mapped error %T does not implement the coded CLI error contract", mapped)
			}
			if coded.CLIErrorCode() != string(code) || coded.CLIErrorFamily() != factoryapi.ErrorFamilyBadRequest {
				t.Fatalf("coded error = %q / %q, want %q / bad request", coded.CLIErrorCode(), coded.CLIErrorFamily(), code)
			}
			if strings.Contains(mapped.Error(), "TOPSECRET") || strings.Contains(mapped.Error(), `C:\private`) ||
				strings.Contains(coded.CLIErrorMessage(), "recording.json") {
				t.Fatalf("mapped error exposed source details: %q / %q", mapped, coded.CLIErrorMessage())
			}
			if !errors.Is(mapped, cause) {
				t.Fatalf("mapped error %v lost its cause", mapped)
			}
		})
	}
}

func TestMapReplayInputFailureUsesMalformedGuidanceAndKnownFallbackCode(t *testing.T) {
	t.Parallel()

	malformed := MapReplayInputFailure(&recordings.ReplayInputError{
		Family: recordings.ReplayInputFamilyLegacy,
		Diagnostic: recordings.ReplayArtifactDiagnostic{
			Code: recordings.ReplayArtifactDiagnosticMalformed,
			Area: "recording", Path: "recording", Message: "untrusted source text",
		},
	})
	type codedError interface {
		error
		CLIErrorCode() string
		CLIErrorMessage() string
	}
	var malformedCoded codedError
	if !errors.As(malformed, &malformedCoded) {
		t.Fatalf("malformed error %T does not implement the coded CLI error contract", malformed)
	}
	if malformedCoded.CLIErrorCode() != string(recordings.ReplayArtifactDiagnosticMalformed) ||
		malformedCoded.CLIErrorMessage() != "preserve the recording and replace it from a trusted backup before retrying" {
		t.Fatalf("malformed CLI diagnostic = %q / %q", malformedCoded.CLIErrorCode(), malformedCoded.CLIErrorMessage())
	}

	unknown := MapReplayInputFailure(&recordings.ReplayInputError{
		Family: recordings.ReplayInputFamilyLegacy,
		Diagnostic: recordings.ReplayArtifactDiagnostic{
			Code: recordings.ReplayArtifactDiagnosticCode("UNSAFE_SOURCE_CODE"),
		},
	})
	var unknownCoded codedError
	if !errors.As(unknown, &unknownCoded) ||
		unknownCoded.CLIErrorCode() != string(recordings.ReplayArtifactDiagnosticDependencyFailure) {
		t.Fatalf("unknown diagnostic = %#v, want the existing dependency-failure code", unknown)
	}
	if MapReplayInputFailure(errors.New("ordinary error")) != nil {
		t.Fatal("MapReplayInputFailure(ordinary error) != nil")
	}
}

func TestMapStructuralReplayFailureAcceptsEachStructuralCode(t *testing.T) {
	t.Parallel()

	codes := []recordings.ReplayArtifactDiagnosticCode{
		recordings.ReplayArtifactDiagnosticMalformed,
		recordings.ReplayArtifactDiagnosticInvalidIdentity,
		recordings.ReplayArtifactDiagnosticInvalidOrder,
		recordings.ReplayArtifactDiagnosticMissingReference,
		recordings.ReplayArtifactDiagnosticForeignReference,
	}
	for _, code := range codes {
		code := code
		t.Run(string(code), func(t *testing.T) {
			t.Parallel()

			mapped := MapStructuralReplayFailure(&recordings.ReplayArtifactError{
				Diagnostic: recordings.ReplayArtifactDiagnostic{
					Code: code, Area: "events", Path: "events[4]", Message: `event "bad-event" is invalid`,
				},
			})
			if mapped == nil {
				t.Fatal("MapStructuralReplayFailure() = nil, want structural diagnostic")
			}
			if !strings.Contains(mapped.Error(), "event=\"bad-event\"") || !strings.Contains(mapped.Error(), "path=events[4]") {
				t.Fatalf("mapped error = %q, want safe first-corrupt event context", mapped)
			}
		})
	}
}

func TestMapStructuralReplayFailureUsesFallbackEventGuidance(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		message    string
		wantDetail string
	}{
		{name: "unrecognized event context", message: "recording event is invalid", wantDetail: "recording event is invalid"},
		{name: "missing closing quote", message: `event "`, wantDetail: `event "`},
		{name: "empty event identity", message: `event "" is invalid`, wantDetail: `event "" is invalid`},
		{name: "empty diagnostic", wantDetail: "recording event is structurally invalid"},
	}
	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			mapped := MapStructuralReplayFailure(&recordings.ReplayArtifactError{
				Diagnostic: recordings.ReplayArtifactDiagnostic{
					Code: recordings.ReplayArtifactDiagnosticMalformed,
					Area: "events", Path: "events[0]", Message: test.message,
				},
			})
			if mapped == nil {
				t.Fatal("MapStructuralReplayFailure() = nil, want malformed event diagnostic")
			}
			wantPrefix := `Error: MALFORMED_REPLAY_ARTIFACT area=events path=events[0] event="unknown" action="REPLACE_OR_REGENERATE_RECORDING": `
			if !strings.HasPrefix(mapped.Error(), wantPrefix) || !strings.HasSuffix(mapped.Error(), test.wantDetail) {
				t.Fatalf("mapped error = %q, want prefix %q and detail %q", mapped.Error(), wantPrefix, test.wantDetail)
			}
		})
	}
}

func TestMapStructuralReplayFailureIgnoresOtherFamiliesAndFailures(t *testing.T) {
	t.Parallel()

	diagnostic := recordings.ReplayArtifactDiagnostic{
		Code: recordings.ReplayArtifactDiagnosticInvalidIdentity,
		Area: "events", Path: "events[3]", Message: `event "event-bad" is invalid`,
	}
	tests := []struct {
		name  string
		cause error
	}{
		{name: "nil"},
		{name: "ordinary error", cause: errors.New("not a replay diagnostic")},
		{
			name: "portable structural diagnostic",
			cause: &recordings.ReplayInputError{
				Family: recordings.ReplayInputFamilyPortable, Diagnostic: diagnostic,
			},
		},
		{
			name: "legacy non-event diagnostic",
			cause: &recordings.ReplayInputError{
				Family: recordings.ReplayInputFamilyLegacy,
				Diagnostic: recordings.ReplayArtifactDiagnostic{
					Code: diagnostic.Code, Area: "recording", Path: "header", Message: diagnostic.Message,
				},
			},
		},
		{
			name: "legacy dependency failure",
			cause: &recordings.ReplayInputError{
				Family: recordings.ReplayInputFamilyLegacy,
				Diagnostic: recordings.ReplayArtifactDiagnostic{
					Code: recordings.ReplayArtifactDiagnosticDependencyFailure,
					Area: diagnostic.Area, Path: diagnostic.Path, Message: diagnostic.Message,
				},
			},
		},
		{
			name: "artifact integrity failure",
			cause: &recordings.ReplayArtifactError{
				Diagnostic: recordings.ReplayArtifactDiagnostic{
					Code: recordings.ReplayArtifactDiagnosticInvalidIntegrity,
					Area: diagnostic.Area, Path: diagnostic.Path, Message: diagnostic.Message,
				},
			},
		},
		{
			name: "artifact diagnostic outside event area",
			cause: &recordings.ReplayArtifactError{
				Diagnostic: recordings.ReplayArtifactDiagnostic{
					Code: diagnostic.Code, Area: "recording", Path: "header", Message: diagnostic.Message,
				},
			},
		},
	}
	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			if mapped := MapStructuralReplayFailure(test.cause); mapped != nil {
				t.Fatalf("MapStructuralReplayFailure(%v) = %v, want nil", test.cause, mapped)
			}
		})
	}
}

func TestReplayStructuralCLIErrorNilAndEmptyValueDefaults(t *testing.T) {
	t.Parallel()

	var nilError *replayStructuralCLIError
	if nilError.Error() != "" || nilError.Unwrap() != nil ||
		nilError.CLIErrorCode() != string(recordings.ReplayArtifactDiagnosticMalformed) {
		t.Fatal("nil structural CLI error did not return empty message, nil cause, and malformed code")
	}
	if nilError.CLIErrorFamily() != factoryapi.ErrorFamilyBadRequest {
		t.Fatalf("nil structural CLI error family = %q, want bad request", nilError.CLIErrorFamily())
	}

	emptyError := &replayStructuralCLIError{}
	want := `Error: MALFORMED_REPLAY_ARTIFACT area=events path=events event="unknown" action="REPLACE_OR_REGENERATE_RECORDING": recording event is structurally invalid`
	if emptyError.Error() != want || emptyError.CLIErrorMessage() != want ||
		emptyError.CLIErrorCode() != string(recordings.ReplayArtifactDiagnosticMalformed) || emptyError.Unwrap() != nil {
		t.Fatalf("zero-value structural CLI error = %q / %q / %q", emptyError.Error(), emptyError.CLIErrorMessage(), emptyError.CLIErrorCode())
	}
}
