package cli_test

import (
	"errors"
	"path/filepath"
	"strings"
	"testing"

	recordingscli "github.com/portpowered/infinite-you/pkg/services/recordings/transports/cli"
	"github.com/portpowered/infinite-you/pkg/services/recordings"
)

func TestAdapterResolveRecordPathModes(t *testing.T) {
	t.Parallel()

	homeDir := t.TempDir()
	plannedPath := filepath.Join(homeDir, "recordings", "planned.json")
	planner := recordings.LiveRecordingTargetPlannerFunc(func(request recordings.LiveRecordingTargetRequest) (recordings.LiveRecordingTarget, error) {
		if request.HomeDir != homeDir || request.ReportedSessionID != recordingscli.DefaultReportedFactorySessionID {
			t.Fatalf("recording request = %#v", request)
		}
		return recordings.LiveRecordingTarget{
			ServicePath:  plannedPath,
			ReportedPath: plannedPath,
		}, nil
	})
	adapter := recordingscli.New()

	tests := []struct {
		name          string
		request       recordingscli.InvocationRequest
		wantService   string
		wantReported  string
		wantGenerated bool
	}{
		{
			name: "default live mode",
			request: recordingscli.InvocationRequest{
				HomeDir:                homeDir,
				RecordingTargetPlanner: planner,
			},
			wantService:   plannedPath,
			wantReported:  plannedPath,
			wantGenerated: true,
		},
		{
			name: "explicit record path",
			request: recordingscli.InvocationRequest{
				RecordPath: "run.replay.json",
			},
			wantService: "run.replay.json",
		},
		{
			name: "replay disables default recording",
			request: recordingscli.InvocationRequest{
				ReplayPath: "existing.replay.json",
			},
		},
		{
			name: "no-record disables default recording",
			request: recordingscli.InvocationRequest{
				DisableDefaultRecording: true,
			},
		},
	}

	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			resolved, err := adapter.ResolveRecordPath(test.request)
			if err != nil {
				t.Fatalf("ResolveRecordPath() error = %v", err)
			}
			if resolved.ServicePath != test.wantService {
				t.Fatalf("ServicePath = %q, want %q", resolved.ServicePath, test.wantService)
			}
			if resolved.ReportedPath != test.wantReported {
				t.Fatalf("ReportedPath = %q, want %q", resolved.ReportedPath, test.wantReported)
			}
			if resolved.AutoGenerated != test.wantGenerated {
				t.Fatalf("AutoGenerated = %t, want %t", resolved.AutoGenerated, test.wantGenerated)
			}
		})
	}
}

func TestAdapterResolveRecordPathRejectsIncompatibleFlags(t *testing.T) {
	t.Parallel()

	adapter := recordingscli.New()
	tests := []struct {
		name    string
		request recordingscli.InvocationRequest
		wantErr string
	}{
		{
			name: "no-record with record",
			request: recordingscli.InvocationRequest{
				RecordPath:              "run.replay.json",
				DisableDefaultRecording: true,
			},
			wantErr: "--no-record cannot be used with --record",
		},
		{
			name: "record with replay",
			request: recordingscli.InvocationRequest{
				RecordPath: "run.replay.json",
				ReplayPath: "existing.replay.json",
			},
			wantErr: "--record and --replay cannot be used together",
		},
	}

	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			_, err := adapter.ResolveRecordPath(test.request)
			if err == nil {
				t.Fatal("expected incompatible flag combination to fail")
			}
			if !strings.Contains(err.Error(), test.wantErr) {
				t.Fatalf("error = %v, want substring %q", err, test.wantErr)
			}
		})
	}
}

func TestAdapterResolveRecordPathRequiresPlannerForDefaultMode(t *testing.T) {
	t.Parallel()

	_, err := recordingscli.New().ResolveRecordPath(recordingscli.InvocationRequest{HomeDir: "home"})
	if err == nil || err.Error() != "Recordings live recording target planner is required" {
		t.Fatalf("ResolveRecordPath() error = %v, want required planner", err)
	}
}

func TestAdapterResolveRecordPathPropagatesPlannerFailure(t *testing.T) {
	t.Parallel()

	_, err := recordingscli.New().ResolveRecordPath(recordingscli.InvocationRequest{
		HomeDir: t.TempDir(),
		RecordingTargetPlanner: recordings.LiveRecordingTargetPlannerFunc(
			func(recordings.LiveRecordingTargetRequest) (recordings.LiveRecordingTarget, error) {
				return recordings.LiveRecordingTarget{}, errors.New("target planning failed")
			},
		),
	})
	if err == nil {
		t.Fatal("expected default record path resolution to fail")
	}
	if !strings.Contains(err.Error(), "resolve default replay record path") {
		t.Fatalf("error = %v, want planner failure wrapper", err)
	}
}
