// Package cli defines the Recordings service's CLI adapter.
package cli

import (
	"context"
	"fmt"
	"io"
	"strings"

	"github.com/portpowered/infinite-you/pkg/services/recordings"
)

// DefaultReportedFactorySessionID is the customer-visible session token used
// when planning default live recording targets for normal you run invocations.
const DefaultReportedFactorySessionID = "~default"

// InvocationRequest captures Recordings-relevant CLI inputs for record-path
// policy resolution.
type InvocationRequest struct {
	RecordPath              string
	ReplayPath              string
	DisableDefaultRecording bool
	HomeDir                 string
	RecordingTargetPlanner  recordings.LiveRecordingTargetPlanner
	ReportedSessionID       string
}

// ResolvedRecordPath is the adapter-owned record-path resolution outcome.
type ResolvedRecordPath struct {
	ServicePath   string
	ReportedPath  string
	AutoGenerated bool
}

// Adapter owns Recordings CLI record/replay/--no-record invocation policy.
type Adapter interface {
	ResolveRecordPath(InvocationRequest) (ResolvedRecordPath, error)
	ResolveRecordPathWithContext(context.Context, InvocationRequest) (ResolvedRecordPath, error)
	ReportRecordingPathOnShutdown(io.Writer, ResolvedRecordPath)
	RecordingDiagnosticsLabel(ResolvedRecordPath, string) string
}

type defaultAdapter struct{}

// New constructs the Recordings CLI adapter injected into Cobra composition.
func New() Adapter {
	return defaultAdapter{}
}

func (defaultAdapter) ResolveRecordPath(request InvocationRequest) (ResolvedRecordPath, error) {
	return defaultAdapter{}.ResolveRecordPathWithContext(context.Background(), request)
}

func (defaultAdapter) ResolveRecordPathWithContext(
	ctx context.Context,
	request InvocationRequest,
) (ResolvedRecordPath, error) {
	if err := ValidateInvocationFlags(request); err != nil {
		return ResolvedRecordPath{}, err
	}
	if strings.TrimSpace(request.RecordPath) != "" {
		return ResolvedRecordPath{ServicePath: request.RecordPath}, nil
	}
	if request.DisableDefaultRecording || strings.TrimSpace(request.ReplayPath) != "" {
		return ResolvedRecordPath{}, nil
	}
	if err := ctx.Err(); err != nil {
		return ResolvedRecordPath{}, err
	}
	if request.RecordingTargetPlanner == nil {
		return ResolvedRecordPath{}, fmt.Errorf("Recordings live recording target planner is required")
	}
	reportedSessionID := strings.TrimSpace(request.ReportedSessionID)
	if reportedSessionID == "" {
		reportedSessionID = DefaultReportedFactorySessionID
	}
	target, err := request.RecordingTargetPlanner.PlanLiveRecordingTarget(recordings.LiveRecordingTargetRequest{
		HomeDir:           request.HomeDir,
		ReportedSessionID: reportedSessionID,
	})
	if err != nil {
		return ResolvedRecordPath{}, fmt.Errorf("resolve default replay record path: %w", err)
	}
	if err := ctx.Err(); err != nil {
		return ResolvedRecordPath{}, err
	}
	return ResolvedRecordPath{
		ServicePath:   target.ServicePath,
		ReportedPath:  target.ReportedPath,
		AutoGenerated: true,
	}, nil
}

func (defaultAdapter) ReportRecordingPathOnShutdown(output io.Writer, resolved ResolvedRecordPath) {
	if output == nil || !resolved.AutoGenerated || strings.TrimSpace(resolved.ReportedPath) == "" {
		return
	}
	fmt.Fprintf(output, "Recording saved: %s\n", resolved.ReportedPath)
}

func (defaultAdapter) RecordingDiagnosticsLabel(resolved ResolvedRecordPath, replayPath string) string {
	switch {
	case strings.TrimSpace(replayPath) != "":
		return "replay"
	case strings.TrimSpace(resolved.ServicePath) == "":
		return "disabled"
	case resolved.AutoGenerated:
		return "default"
	default:
		return "explicit"
	}
}

// ValidateInvocationFlags rejects incompatible Recordings CLI flag combinations
// before runtime opening begins.
func ValidateInvocationFlags(request InvocationRequest) error {
	if request.DisableDefaultRecording && strings.TrimSpace(request.RecordPath) != "" {
		return fmt.Errorf("--no-record cannot be used with --record")
	}
	if strings.TrimSpace(request.RecordPath) != "" && strings.TrimSpace(request.ReplayPath) != "" {
		return fmt.Errorf("--record and --replay cannot be used together")
	}
	return nil
}
