package cli_rest_journeys_test

import "testing"

// TestFactoryEventCLIJourneys owns its immutable fixture until all customer scenarios finish.
func TestFactoryEventCLIJourneys(t *testing.T) {
	t.Parallel()
	reseteventsfactoryevents5State()
	initializeEventsfactoryeventsFixture(t)
	t.Run("TestFSCP01CanonicalReconnectAndArtifactReadsIndependentOfResponseEvents", testEventsfactoryeventsFSCP01CanonicalReconnectAndArtifactReadsIndependentOfResponseEvents)
	t.Run("TestFSCP01ResponseTeardownThenCanonicalReconnectAndArtifactReads", testEventsfactoryeventsFSCP01ResponseTeardownThenCanonicalReconnectAndArtifactReads)
	t.Run("TestAPIGetFactoryEventsReturnsOrderedDurableHistory", testEventsfactoryeventsAPIGetFactoryEventsReturnsOrderedDurableHistory)
	t.Run("TestAPIEventCursorReturnsOnlyNewerEvents", testEventsfactoryeventsAPIEventCursorReturnsOnlyNewerEvents)
	t.Run("TestAPIInvalidEventCursorReturnsTypedError", testEventsfactoryeventsAPIInvalidEventCursorReturnsTypedError)
	t.Run("TestAPISubmitWorkEmitsCanonicalTraceAwareBatchEvent", testEventsfactoryeventsAPISubmitWorkEmitsCanonicalTraceAwareBatchEvent)
	t.Run("TestFactoryEventStreamIsOrderedAndClosesAtSessionTermination", testEventsfactoryeventsFactoryEventStreamIsOrderedAndClosesAtSessionTermination)
	t.Run("TestFactoryEventStreamReconnectHasNoGapOrDuplicate", testEventsfactoryeventsFactoryEventStreamReconnectHasNoGapOrDuplicate)
	t.Run("TestCanonicalTopologySnapshotsPreservePublicIdentityAndResourceEvidence", testEventsfactoryeventsCanonicalTopologySnapshotsPreservePublicIdentityAndResourceEvidence)
	t.Run("TestFactoryWebhooksInitialRecordedSessions", testEventsfactoryeventsFactoryWebhooksInitialRecordedSessions)
	t.Run("TestFactoryWebhooksRecordedFaultsAndPeerContinuation", testEventsfactoryeventsFactoryWebhooksRecordedFaultsAndPeerContinuation)
	t.Run("TestFactoryWebhooksInitialRecordedDispatchFailure", testEventsfactoryeventsFactoryWebhooksInitialRecordedDispatchFailure)
	t.Run("TestFactoryWebhooksRunThroughRootProcess", testEventsfactoryeventsFactoryWebhooksRunThroughRootProcess)

}
