package cli_rest_journeys_test

import "testing"

// runFactoryValidationPersistenceJourneys owns its immutable fixture until all customer scenarios finish.
func runFactoryValidationPersistenceJourneys(t *testing.T) {
	t.Parallel()
	t.Run("TestFactoryValidateRejectsUnsupportedJoinArity", testFactorydefinitionstransportsclivalidatepersistFactoryValidateRejectsUnsupportedJoinArity)
	t.Run("TestFactoryValidateAcceptsSupportedTwoInputJoinArity", testFactorydefinitionstransportsclivalidatepersistFactoryValidateAcceptsSupportedTwoInputJoinArity)
	t.Run("TestFactoryValidateRejectsReservedInvocationFlag", testFactorydefinitionstransportsclivalidatepersistFactoryValidateRejectsReservedInvocationFlag)
	t.Run("TestCLIFactoryValidateRejectsInvalidDefinitionActionably", testFactorydefinitionstransportsclivalidatepersistCLIFactoryValidateRejectsInvalidDefinitionActionably)
	t.Run("TestCLIFactoryValidateDoesNotMutateOnFailure", testFactorydefinitionstransportsclivalidatepersistCLIFactoryValidateDoesNotMutateOnFailure)
	t.Run("TestCLIFactoryPersistFromFileThenRunSucceeds", testFactorydefinitionstransportsclivalidatepersistCLIFactoryPersistFromFileThenRunSucceeds)
}
