package cli_rest_journeys_test

import "testing"

// Named Factory journeys retain separate customer profiles on the shared process.
func runNamedFactoryCLIJourneys(t *testing.T) {
	t.Parallel()
	t.Run("TestFactoryListAndInitKeepConcurrentProfilesSeparate", testFactorydefinitionstransportsclinamedlifecycleFactoryListAndInitKeepConcurrentProfilesSeparate)
	t.Run("TestMissingHomeRejectsFactoryEffectsButKeepsHelpAvailable", testFactorydefinitionstransportsclinamedlifecycleMissingHomeRejectsFactoryEffectsButKeepsHelpAvailable)
	t.Run("TestCLIFactoryNamedCreateListUpdateDelete", testFactorydefinitionstransportsclinamedlifecycleCLIFactoryNamedCreateListUpdateDelete)
	t.Run("TestCLIFactoryListReflectsCreateAndDelete", testFactorydefinitionstransportsclinamedlifecycleCLIFactoryListReflectsCreateAndDelete)
	t.Run("TestCLIFactoryDeleteMissingReturnsActionableFailure", testFactorydefinitionstransportsclinamedlifecycleCLIFactoryDeleteMissingReturnsActionableFailure)
	t.Run("TestPackagedFactoryInstallFormatsValidateAndPreserveCustomerFiles", testFactorydefinitionstransportsclinamedlifecyclePackagedFactoryInstallFormatsValidateAndPreserveCustomerFiles)
}
