package cli_rest_journeys_test

import (
	"testing"

	"github.com/portpowered/infinite-you/tests/internal/functionalevidence"
)

// TestRESTServerJourneys owns its immutable fixture until all customer scenarios finish.
func TestRESTServerJourneys(t *testing.T) {
	t.Parallel()
	resettransporthttpserver3State()
	resettransporthttpserver7State()
	initializeTransporthttpserverFixture(t)
	t.Run("TestAPIConcurrentSessionRequestsRemainIsolated", testTransporthttpserverAPIConcurrentSessionRequestsRemainIsolated)
	t.Run("TestAPICancelledRequestDoesNotCancelUnrelatedSession", testTransporthttpserverAPICancelledRequestDoesNotCancelUnrelatedSession)
	t.Run("TestAPIJSONRequestsAndResponsesUseDocumentedContentType", testTransporthttpserverAPIJSONRequestsAndResponsesUseDocumentedContentType)
	t.Run("TestAPIUnsupportedContentTypeReturns415", testTransporthttpserverAPIUnsupportedContentTypeReturns415)
	t.Run("TestAPIMalformedJSONReturnsStructured400", testTransporthttpserverAPIMalformedJSONReturnsStructured400)
	t.Run("TestGeneratedClientStatusAndSessionRoundTrip", testTransporthttpserverGeneratedClientStatusAndSessionRoundTrip)
	t.Run("TestGeneratedClientDecodesRepresentativeStructuredError", testTransporthttpserverGeneratedClientDecodesRepresentativeStructuredError)
	t.Run("TestGeneratedClientAndServerSchemaStayAligned", testTransporthttpserverGeneratedClientAndServerSchemaStayAligned)
	t.Run("TestAPIServerDiagnosticsUseProductionLoopbackStarter", testTransporthttpserverAPIServerDiagnosticsUseProductionLoopbackStarter)
	t.Run("TestAPIServerGracefulShutdownThroughProductionLoopbackLifecycle", testTransporthttpserverAPIServerGracefulShutdownThroughProductionLoopbackLifecycle)
	t.Run("TestAPIUnknownRouteReturnsStructuredNotFound", testTransporthttpserverAPIUnknownRouteReturnsStructuredNotFound)
	t.Run("TestAPIDashboardRoutesServeEmbeddedShellAssetAndFallback", testTransporthttpserverAPIDashboardRoutesServeEmbeddedShellAssetAndFallback)
	t.Run("TestAPIWrongMethodReturnsDocumentedMethodError", testTransporthttpserverAPIWrongMethodReturnsDocumentedMethodError)
	t.Run("TestAPIServerPprofIsOptInThroughThePublicRunPath", testTransporthttpserverAPIServerPprofIsOptInThroughThePublicRunPath)
	t.Run("TestAPIServerStartsOnConfiguredListenerAndServesStatus", testTransporthttpserverAPIServerStartsOnConfiguredListenerAndServesStatus)
	t.Run("TestAPIServerUsesPlatformStarterThroughRootProcess", testTransporthttpserverAPIServerUsesPlatformStarterThroughRootProcess)
	t.Run("TestAPIServerShutdownClosesListenerAndActiveStreams", testTransporthttpserverAPIServerShutdownClosesListenerAndActiveStreams)
	t.Run("TestAPIServerBindFailureUnwindsStartedLifecycleRoles", testTransporthttpserverAPIServerBindFailureUnwindsStartedLifecycleRoles)
	t.Run("TestAPIStatusReportsReadyAfterStartup", testTransporthttpserverAPIStatusReportsReadyAfterStartup)
	t.Run("TestAPIStatusDoesNotLeakInternalConfiguration", testTransporthttpserverAPIStatusDoesNotLeakInternalConfiguration)
	t.Run("TestWorkTerminalResponsePreservesOrderedTypedContentThroughPublicBoundary", testTransporthttpserverWorkTerminalResponsePreservesOrderedTypedContentThroughPublicBoundary)
	functionalevidence.Covers(t, "rest/getEventsBySessionId", "rest/getStatusBySessionId", "rest/listWorkBySessionId", "rest/submitWorkBySessionId")
}
