package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunRejectsProductionDirectConstruction(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "pkg/runtimehost/runtime_sessions.go", `package runtimehost
func build() any { return factorysessionexecution.NewJavaScriptRuntimeService(config) }
`)

	stderr := &bytes.Buffer{}
	err := run(config{root: root}, &bytes.Buffer{}, stderr)
	if err == nil {
		t.Fatal("run() error = nil, want prohibited production construction error")
	}
	for _, want := range []string{"pkg/runtimehost/runtime_sessions.go:2", constructorName} {
		if !strings.Contains(stderr.String(), want) {
			t.Fatalf("stderr = %q, want %q", stderr.String(), want)
		}
	}
}

func TestRunAcceptsApprovedOwnersAndTestFixtures(t *testing.T) {
	root := t.TempDir()
	for path := range approvedProductionFiles {
		writeFixture(t, root, path, "package fixture\nfunc build() any { return NewJavaScriptRuntimeService(config) }\n")
	}
	writeFixture(t, root, "pkg/runtimehost/runtime_sessions_test.go", "package runtimehost\nfunc buildFixture() any { return NewJavaScriptRuntimeService(config) }\n")
	writeFixture(t, root, "pkg/runtimehost/testdata/deterministic_fixture.go", "package fixture\nfunc build() any { return NewJavaScriptRuntimeService(config) }\n")
	writeFixture(t, root, "vendor/example/generated.go", "package example\nfunc build() any { return NewJavaScriptRuntimeService(config) }\n")
	writeFixture(t, root, "pkg/generated/example.go", "// Code generated by fixturegen. DO NOT EDIT.\npackage generated\nfunc build() any { return NewJavaScriptRuntimeService(config) }\n")

	stdout := &bytes.Buffer{}
	if err := run(config{root: root}, stdout, &bytes.Buffer{}); err != nil {
		t.Fatalf("run() error = %v, want nil", err)
	}
	if !strings.Contains(stdout.String(), "limited to approved composition owners") {
		t.Fatalf("stdout = %q, want success message", stdout.String())
	}
}

func writeFixture(t *testing.T, root, relativePath, source string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relativePath))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("create fixture directory: %v", err)
	}
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
}
