// Package automations is the public Automations service boundary.
package automations

import (
	"context"
	"sync"

	"github.com/portpowered/infinite-you/pkg/services/automations/timework"
	factorydefinitions "github.com/portpowered/infinite-you/pkg/services/factory_definitions"
	"github.com/portpowered/infinite-you/pkg/services/work"
)

// WorkRequestSubmitter admits one Work Request generated by an automation.
type WorkRequestSubmitter func(context.Context, work.WorkRequest) error

// HostedWorkSubmitter admits one normalized Work Request produced by a hosted
// poller.
type HostedWorkSubmitter func(context.Context, work.WorkRequest) error

// HostedPollers is the provider-specific polling capability supervised by the
// Automations service.
type HostedPollers interface {
	StartLinearPoller(
		context.Context,
		*sync.WaitGroup,
		factorydefinitions.RuntimeConfigLookup,
		factorydefinitions.FactoryWorkstationConfig,
		*factorydefinitions.FactoryWorkerConfig,
		HostedWorkSubmitter,
	) error
	ValidateLinearPoller(
		factorydefinitions.RuntimeConfigLookup,
		factorydefinitions.FactoryWorkstationConfig,
		*factorydefinitions.FactoryWorkerConfig,
		HostedWorkSubmitter,
	) error
}

// Service supervises runtime-scoped cron, watcher, listener, and poller
// automations.
type Service interface {
	StartSchedulerSidecarsForRuntime(
		context.Context,
		*sync.WaitGroup,
		string,
		*factorydefinitions.FactoryConfig,
		factorydefinitions.RuntimeConfigLookup,
		WorkRequestSubmitter,
	) error
}

var (
	ValidateCronSchedule  = timework.ValidateCronSchedule
	ParseCronJitter       = timework.ParseCronJitter
	ParseCronExpiryWindow = timework.ParseCronExpiryWindow
)
