// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package compose

import (
	"context"
	"github.com/portpowered/infinite-you/pkg/service"
)

// Injectors from wire.go:

// InjectFactoryService is the wireinject entry for the factory composition root.
func InjectFactoryService(ctx context.Context, cfg *service.FactoryServiceConfig) (*service.FactoryService, error) {
	factoryServiceRoot, err := provideFactoryServiceRoot(cfg)
	if err != nil {
		return nil, err
	}
	registry := provideFactorySessionsRegistry()
	v := provideLocalModelDomain(cfg)
	factoryConfigLoadResult, err := provideFactoryConfigLoad(cfg, factoryServiceRoot)
	if err != nil {
		return nil, err
	}
	clock := provideServiceClock(cfg, factoryConfigLoadResult)
	logger := provideBaseLogger(factoryServiceRoot)
	runtimebuildService := provideRuntimeBuildService(cfg, clock, logger, v)
	factoryServiceCollaborators := provideFactoryServiceCollaborators(registry, v, runtimebuildService)
	config := provideHostedWorkersConfig(cfg, logger, clock)
	factoryService, err := provideFactoryService(ctx, cfg, factoryServiceRoot, factoryServiceCollaborators, factoryConfigLoadResult, clock, config)
	if err != nil {
		return nil, err
	}
	return factoryService, nil
}
