package backendvisualizations

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/portpowered/infinite-you/internal/backenddependencygraph"
)

// Config names the source tree, optional completed coverage measurements, and
// the directory containing the generated architecture pages.
type Config struct {
	Root              string
	OutputDir         string
	GoBinary          string
	SourceCommit      string
	UnitSummary       string
	FunctionalSummary string
	RequireCoverage   bool
}

type coverageSummary struct {
	Complete bool `json:"complete"`
	Packages []struct {
		Package              string `json:"package"`
		CoveredStatements    int    `json:"coveredStatements"`
		MeasurableStatements int    `json:"measurableStatements"`
	} `json:"packages"`
}

type counts struct{ covered, measurable int }

type packageInfo struct {
	path  string
	owner string
	loc   int
	files int
}

type model struct {
	module     string
	packages   []backenddependencygraph.Package
	info       map[string]packageInfo
	owners     []string
	unit       map[string]counts
	functional map[string]counts
	commit     string
}

// Generate writes deterministic Markdown from the Go package inventory and
// existing coverage summaries. It never runs tests or changes coverage floors.
func Generate(ctx context.Context, cfg Config) error {
	if cfg.Root == "" {
		cfg.Root = "."
	}
	if cfg.GoBinary == "" {
		cfg.GoBinary = "go"
	}
	if cfg.OutputDir == "" {
		cfg.OutputDir = "docs/architecture/visualizations"
	}
	packages, module, err := backenddependencygraph.Load(ctx, cfg.Root, cfg.GoBinary)
	if err != nil {
		return err
	}
	unit, err := readCoverage(cfg.Root, cfg.UnitSummary, cfg.RequireCoverage)
	if err != nil {
		return fmt.Errorf("unit coverage: %w", err)
	}
	functional, err := readCoverage(cfg.Root, cfg.FunctionalSummary, cfg.RequireCoverage)
	if err != nil {
		return fmt.Errorf("functional coverage: %w", err)
	}
	m, err := buildModel(cfg.Root, module, packages, unit, functional, cfg.SourceCommit)
	if err != nil {
		return err
	}
	outputDir := resolve(cfg.Root, cfg.OutputDir)
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}
	for _, page := range []struct{ name, body string }{
		{"high-level-backend.md", renderBackend(m)},
		{"high-level-test-coverage.md", renderCoverage(m)},
	} {
		if err := os.WriteFile(filepath.Join(outputDir, page.name), []byte(page.body), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", page.name, err)
		}
	}
	serviceDir := filepath.Join(outputDir, "services")
	if err := os.MkdirAll(serviceDir, 0o755); err != nil {
		return err
	}
	wanted := make(map[string]bool, len(m.owners))
	for _, owner := range m.owners {
		name := strings.TrimPrefix(owner, "services/") + ".md"
		wanted[name] = true
		if err := os.WriteFile(filepath.Join(serviceDir, name), []byte(renderOwner(m, owner)), 0o644); err != nil {
			return fmt.Errorf("write service page %s: %w", name, err)
		}
	}
	entries, err := os.ReadDir(serviceDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") || wanted[entry.Name()] {
			continue
		}
		path := filepath.Join(serviceDir, entry.Name())
		body, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !strings.Contains(string(body), "<!-- Generated by make architecture. -->") {
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove stale service page %s: %w", entry.Name(), err)
		}
	}
	return nil
}

func resolve(root, path string) string {
	if filepath.IsAbs(path) {
		return path
	}
	return filepath.Join(root, path)
}

func readCoverage(root, path string, required bool) (map[string]counts, error) {
	if path == "" {
		if required {
			return nil, fmt.Errorf("coverage summary path is required")
		}
		return nil, nil
	}
	data, err := os.ReadFile(resolve(root, path))
	if err != nil {
		if os.IsNotExist(err) && !required {
			return nil, nil
		}
		return nil, err
	}
	var summary coverageSummary
	if err := json.Unmarshal(data, &summary); err != nil {
		return nil, err
	}
	if !summary.Complete {
		return nil, fmt.Errorf("coverage measurement is incomplete")
	}
	result := make(map[string]counts, len(summary.Packages))
	for _, p := range summary.Packages {
		result[p.Package] = counts{p.CoveredStatements, p.MeasurableStatements}
	}
	return result, nil
}

func buildModel(root, module string, packages []backenddependencygraph.Package, unit, functional map[string]counts, commit string) (model, error) {
	m := model{module: module, packages: packages, info: make(map[string]packageInfo), unit: unit, functional: functional, commit: commit}
	owners := make(map[string]bool)
	for _, pkg := range packages {
		path := strings.TrimPrefix(pkg.ImportPath, module+"/")
		if !strings.HasPrefix(path, "pkg/") {
			continue
		}
		owner := ownerOf(path)
		loc, files, err := sourceSize(root, pkg)
		if err != nil {
			return model{}, fmt.Errorf("measure %s: %w", path, err)
		}
		m.info[pkg.ImportPath] = packageInfo{path: path, owner: owner, loc: loc, files: files}
		if strings.HasPrefix(owner, "services/") {
			owners[owner] = true
		}
	}
	for owner := range owners {
		m.owners = append(m.owners, owner)
	}
	slices.Sort(m.owners)
	return m, nil
}

func ownerOf(path string) string {
	parts := strings.Split(path, "/")
	if len(parts) >= 3 && parts[0] == "pkg" && parts[1] == "services" {
		return "services/" + parts[2]
	}
	if len(parts) >= 2 && parts[0] == "pkg" {
		return parts[1]
	}
	return ""
}

func sourceSize(root string, pkg backenddependencygraph.Package) (int, int, error) {
	loc, files := 0, 0
	for _, name := range append(slices.Clone(pkg.GoFiles), pkg.CgoFiles...) {
		path := filepath.Join(pkg.Dir, name)
		if pkg.Dir == "" {
			path = filepath.Join(root, name)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return 0, 0, err
		}
		header := firstLines(string(data), 12)
		if strings.Contains(header, "Code generated") && strings.Contains(header, "DO NOT EDIT.") {
			continue
		}
		files++
		for _, line := range strings.Split(string(data), "\n") {
			if strings.TrimSpace(line) != "" {
				loc++
			}
		}
	}
	return loc, files, nil
}

func firstLines(value string, count int) string {
	lines := strings.SplitN(value, "\n", count+1)
	if len(lines) > count {
		lines = lines[:count]
	}
	return strings.Join(lines, "\n")
}
