package backendvisualizations

import (
	"fmt"
	"slices"
	"strings"
)

func renderBackend(m model) string {
	var b strings.Builder
	b.WriteString("# Backend service graph\n\n")
	renderArchitectureDiagram(&b, m, false)
	renderAreaLegend(&b, false)
	b.WriteString("## Test presentation\n\n[View test coverage](high-level-test-coverage.md).\n\n")
	b.WriteString("## Service presentations\n\n| Service | Subservices |\n| --- | --- |\n")
	for _, owner := range m.owners {
		name := strings.TrimPrefix(owner, "services/")
		fmt.Fprintf(&b, "| [`%s`](services/%s.md) | %s |\n", name, name, subserviceSummary(m, owner))
	}
	return b.String()
}

func renderOwner(m model, owner string) string {
	var b strings.Builder
	name := strings.TrimPrefix(owner, "services/")
	loc, files, _ := ownerSize(m, owner)
	fmt.Fprintf(&b, "# %s service architecture\n\n<!-- Generated by make architecture. -->\n\n", strings.ReplaceAll(name, "_", " "))
	writeSource(&b, m.commit)
	fmt.Fprintf(&b, "[High-level backend](../high-level-backend.md) · [Test coverage](../high-level-test-coverage.md)\n\n%d LOC across %d files. Arrows show imports between package groups within this service. They are static dependencies, not runtime calls. `XX%%` means coverage was unmeasured.\n\n```mermaid\nflowchart LR\n", loc, files)
	paths := ownerPaths(m, owner)
	groups := ownerGroups(m, owner)
	names := make([]string, 0, len(groups))
	for group := range groups {
		names = append(names, group)
	}
	slices.Sort(names)
	ids := make(map[string]string, len(names))
	for i, group := range names {
		id := fmt.Sprintf("p%d", i)
		ids[group] = id
		packageLabel := fmt.Sprintf("%d packages", groups[group].packages)
		if groups[group].packages == 1 {
			packageLabel = "1 package"
		}
		fmt.Fprintf(&b, "  %s[\"%s<br/>%d LOC · %s\"]\n", id, mermaidLabel(groupLabel(group)), groups[group].loc, packageLabel)
	}
	edges := make(map[string]int)
	for _, pkg := range m.packages {
		info, ok := m.info[pkg.ImportPath]
		if !ok || info.owner != owner {
			continue
		}
		from := internalGroup(info.path, owner)
		for _, imported := range pkg.Imports {
			other, ok := m.info[imported]
			if !ok || other.owner != owner {
				continue
			}
			to := internalGroup(other.path, owner)
			if from != to {
				edges[from+"\x00"+to]++
			}
		}
	}
	keys := make([]string, 0, len(edges))
	for key := range edges {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	for _, key := range keys {
		from, to, _ := strings.Cut(key, "\x00")
		fmt.Fprintf(&b, "  %s --> %s\n", ids[from], ids[to])
	}
	area := areaFor(owner)
	for _, group := range names {
		fmt.Fprintf(&b, "  style %s fill:%s,stroke:%s,stroke-width:2px,color:#111827\n", ids[group], area.fill, area.stroke)
	}
	if len(keys) > 0 {
		fmt.Fprintf(&b, "  linkStyle default stroke:%s,stroke-width:2px\n", area.stroke)
	}
	b.WriteString("```\n\n## Package groups\n\n`(subservice)` identifies a private service under `internal/services/`. `internal/service` is the core service implementation.\n\n| Group | LOC | Files | Packages | Unit | Functional |\n| --- | ---: | ---: | ---: | ---: | ---: |\n")
	for _, group := range names {
		info := groups[group]
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %s | %s |\n", groupLabel(group), info.loc, info.files, info.packages, percent(groupCoverage(m, owner, group, m.unit)), percent(groupCoverage(m, owner, group, m.functional)))
	}
	b.WriteString("\n## Packages\n\n| Package | LOC | Files | Unit | Functional |\n| --- | ---: | ---: | ---: | ---: |\n")
	for _, path := range paths {
		info := m.info[path]
		fmt.Fprintf(&b, "| [`%s`](../../../../%s) | %d | %d | %s | %s |\n", info.path, info.path, info.loc, info.files, percent(m.unit[path]), percent(m.functional[path]))
	}
	return b.String()
}

type groupSize struct{ loc, files, packages int }

func ownerGroups(m model, owner string) map[string]groupSize {
	groups := make(map[string]groupSize)
	for _, path := range ownerPaths(m, owner) {
		group := internalGroup(m.info[path].path, owner)
		current := groups[group]
		current.loc += m.info[path].loc
		current.files += m.info[path].files
		current.packages++
		groups[group] = current
	}
	return groups
}

func subserviceSummary(m model, owner string) string {
	groups := ownerGroups(m, owner)
	parts := make([]string, 0)
	for group, size := range groups {
		if strings.HasPrefix(group, "internal/services/") {
			parts = append(parts, fmt.Sprintf("%s (%d LOC)", groupLabel(group), size.loc))
		}
	}
	slices.Sort(parts)
	if len(parts) == 0 {
		return "—"
	}
	return strings.Join(parts, "<br/>")
}

func subserviceCount(m model, owner string) int {
	count := 0
	for group := range ownerGroups(m, owner) {
		if strings.HasPrefix(group, "internal/services/") {
			count++
		}
	}
	return count
}

func groupCoverage(m model, owner, group string, values map[string]counts) counts {
	var total counts
	for path, info := range m.info {
		if info.owner != owner || internalGroup(info.path, owner) != group {
			continue
		}
		item := values[path]
		total.covered += item.covered
		total.measurable += item.measurable
	}
	return total
}

func groupLabel(group string) string {
	if strings.HasPrefix(group, "internal/services/") {
		return "(subservice) " + strings.ReplaceAll(strings.TrimPrefix(group, "internal/services/"), "_", " ")
	}
	if group == "internal" {
		return "core implementation"
	}
	if group == "internal/service" {
		return group
	}
	if strings.HasPrefix(group, "internal/") {
		return strings.ReplaceAll(strings.TrimPrefix(group, "internal/"), "_", " ")
	}
	return strings.ReplaceAll(group, "_", " ")
}

func internalGroup(path, owner string) string {
	relative := strings.TrimPrefix(path, "pkg/"+owner)
	relative = strings.TrimPrefix(relative, "/")
	if relative == "" {
		return "root"
	}
	parts := strings.Split(relative, "/")
	if len(parts) >= 3 && parts[0] == "internal" && parts[1] == "services" {
		return strings.Join(parts[:3], "/")
	}
	if len(parts) >= 2 && parts[0] == "internal" {
		return strings.Join(parts[:2], "/")
	}
	return parts[0]
}

func renderCoverage(m model) string {
	var b strings.Builder
	b.WriteString("# High-level test coverage\n\n<!-- Generated by make architecture. -->\n\n")
	writeSource(&b, m.commit)
	b.WriteString("[Backend service graph](high-level-backend.md). Unit and functional percentages use measured statement coverage. `XX%` means unmeasured.\n\n")
	if m.unit == nil && m.functional == nil {
		b.WriteString("Coverage values await the first successful `main` CI publication.\n\n")
	}
	b.WriteString("## Service coverage\n\n")
	renderArchitectureDiagram(&b, m, true)
	renderAreaLegend(&b, true)
	b.WriteString("| Service owner | Subservices | Unit | Functional |\n| --- | ---: | ---: | ---: |\n")
	for _, owner := range m.owners {
		unit := ownerCoverage(m, owner, m.unit)
		functional := ownerCoverage(m, owner, m.functional)
		name := strings.TrimPrefix(owner, "services/")
		fmt.Fprintf(&b, "| [`%s`](services/%s.md) | %d | %s | %s |\n", name, name, subserviceCount(m, owner), percent(unit), percent(functional))
	}
	b.WriteString("## Other backend package coverage\n\n| Package | Unit | Functional |\n| --- | ---: | ---: |\n")
	paths := make([]string, 0)
	for path, info := range m.info {
		if !strings.HasPrefix(info.owner, "services/") {
			paths = append(paths, path)
		}
	}
	slices.Sort(paths)
	for _, path := range paths {
		info := m.info[path]
		fmt.Fprintf(&b, "| [`%s`](../../../%s) | %s | %s |\n", info.path, info.path, percent(m.unit[path]), percent(m.functional[path]))
	}
	return b.String()
}

func writeSource(b *strings.Builder, commit string) {
	if commit != "" {
		fmt.Fprintf(b, "Source commit: `%s`.\n\n", commit)
	}
}

func mermaidLabel(value string) string {
	return strings.NewReplacer("\"", "'", "<", "&lt;", ">", "&gt;", "\n", " ").Replace(value)
}

func nodeID(owner string) string { return "s_" + strings.ReplaceAll(owner, "/", "_") }

type serviceArea struct {
	id, label, fill, background, stroke, swatch string
}

var serviceAreas = []serviceArea{
	{"input", "Inputs", "#dbeafe", "#eff6ff", "#1d4ed8", "🟦 Blue"},
	{"configuration", "Configuration", "#ede9fe", "#f5f3ff", "#6d28d9", "🟪 Purple"},
	{"coordination", "Factory coordination", "#ccfbf1", "#f0fdfa", "#0f766e", "🔹 Teal"},
	{"execution", "Execution", "#ffedd5", "#fff7ed", "#c2410c", "🟧 Orange"},
	{"recordings", "Recordings and events", "#dcfce7", "#f0fdf4", "#15803d", "🟩 Green"},
	{"metrics", "Metrics", "#fce7f3", "#fdf2f8", "#be185d", "🩷 Pink"},
	{"support", "Support", "#e2e8f0", "#f8fafc", "#475569", "⬛ Slate"},
}

func areaFor(owner string) serviceArea {
	group := serviceGroup(owner)
	for _, area := range serviceAreas {
		if area.id == group {
			return area
		}
	}
	return serviceAreas[len(serviceAreas)-1]
}

func renderAreaLegend(b *strings.Builder, coverage bool) {
	b.WriteString("## Legend\n\nEach arrow shows a service's most frequent direct import. Its color identifies the importing service.\n\n")
	b.WriteString("| Color | Service area |\n| --- | --- |\n")
	for _, area := range serviceAreas {
		fmt.Fprintf(b, "| %s (`%s`) | %s |\n", area.swatch, area.stroke, area.label)
	}
	if coverage {
		b.WriteString("\nNode borders use the area colors above. Node fill shows unit coverage: 🟩 80% or higher, 🟨 50–79.9%, 🟥 below 50%, ⬜ `XX%` (unmeasured). Functional coverage appears in each node label.\n\n")
		return
	}
	b.WriteString("\n")
}

func renderArchitectureDiagram(b *strings.Builder, m model, withCoverage bool) {
	selected := overviewEdges(m)
	b.WriteString("```mermaid\nflowchart TB\n")
	for _, group := range serviceAreas {
		fmt.Fprintf(b, "  subgraph %s[\"%s\"]\n", group.id, group.label)
		for _, owner := range m.owners {
			if serviceGroup(owner) != group.id {
				continue
			}
			renderServiceNode(b, m, owner, withCoverage, "    ")
		}
		b.WriteString("  end\n")
	}
	for _, item := range selected {
		fmt.Fprintf(b, "  %s --> %s\n", nodeID(item.from), nodeID(item.to))
	}
	for _, owner := range m.owners {
		area := areaFor(owner)
		fill := area.fill
		if withCoverage {
			fill = coverageColor(ownerCoverage(m, owner, m.unit))
		}
		fmt.Fprintf(b, "  style %s fill:%s,stroke:%s,stroke-width:2px,color:#111827\n", nodeID(owner), fill, area.stroke)
	}
	for _, group := range serviceAreas {
		fmt.Fprintf(b, "  style %s fill:%s,stroke:%s,stroke-width:2px,color:#111827\n", group.id, group.background, group.stroke)
	}
	for i, item := range selected {
		fmt.Fprintf(b, "  linkStyle %d stroke:%s,stroke-width:2px\n", i, areaFor(item.from).stroke)
	}
	b.WriteString("```\n\n")
}

func renderServiceNode(b *strings.Builder, m model, owner string, withCoverage bool, indent string) {
	name := strings.ReplaceAll(strings.TrimPrefix(owner, "services/"), "_", " ")
	subservices := subserviceCount(m, owner)
	subserviceLabel := fmt.Sprintf("%d subservices", subservices)
	if subservices == 1 {
		subserviceLabel = "1 subservice"
	}
	if withCoverage {
		fmt.Fprintf(b, "%s%s[\"%s<br/>%s unit<br/>%s func<br/>%s\"]\n", indent, nodeID(owner), name, percent(ownerCoverage(m, owner, m.unit)), percent(ownerCoverage(m, owner, m.functional)), subserviceLabel)
		return
	}
	loc, _, _ := ownerSize(m, owner)
	fmt.Fprintf(b, "%s%s[\"%s<br/>%d LOC · %s\"]\n", indent, nodeID(owner), name, loc, subserviceLabel)
}

func serviceGroup(owner string) string {
	switch strings.TrimPrefix(owner, "services/") {
	case "automations", "chat_sessions", "webhooks", "work":
		return "input"
	case "factory_definitions", "operator_settings":
		return "configuration"
	case "factory_runtime", "factory_sessions":
		return "coordination"
	case "models", "provider_sessions", "providers", "worker_sessions", "workers":
		return "execution"
	case "events", "recordings":
		return "recordings"
	case "costs", "factory_visualization":
		return "metrics"
	default:
		return "support"
	}
}

func overviewEdges(m model) []edge {
	all := ownerEdges(m)
	result := make([]edge, 0, len(m.owners))
	for _, owner := range m.owners {
		outgoing := make([]edge, 0)
		for _, item := range all {
			if item.from == owner {
				outgoing = append(outgoing, item)
			}
		}
		slices.SortFunc(outgoing, func(a, c edge) int {
			if a.count != c.count {
				return c.count - a.count
			}
			return strings.Compare(a.to, c.to)
		})
		for _, item := range outgoing[:min(1, len(outgoing))] {
			result = append(result, item)
		}
	}
	return result
}

func ownerPaths(m model, owner string) []string {
	paths := make([]string, 0)
	for path, info := range m.info {
		if info.owner == owner {
			paths = append(paths, path)
		}
	}
	slices.Sort(paths)
	return paths
}

func ownerSize(m model, owner string) (loc, files, packages int) {
	for _, info := range m.info {
		if info.owner == owner {
			loc += info.loc
			files += info.files
			packages++
		}
	}
	return
}

type edge struct {
	from, to string
	count    int
}

func ownerEdges(m model) []edge {
	counts := make(map[string]int)
	for _, pkg := range m.packages {
		from := m.info[pkg.ImportPath].owner
		if !strings.HasPrefix(from, "services/") {
			continue
		}
		for _, imported := range pkg.Imports {
			to := m.info[imported].owner
			if strings.HasPrefix(to, "services/") && to != from {
				counts[from+"\x00"+to]++
			}
		}
	}
	result := make([]edge, 0, len(counts))
	for key, count := range counts {
		from, to, _ := strings.Cut(key, "\x00")
		result = append(result, edge{from, to, count})
	}
	slices.SortFunc(result, func(a, b edge) int {
		if a.from != b.from {
			return strings.Compare(a.from, b.from)
		}
		return strings.Compare(a.to, b.to)
	})
	return result
}

func ownerCoverage(m model, owner string, values map[string]counts) counts {
	var result counts
	for path, info := range m.info {
		if info.owner == owner {
			c := values[path]
			result.covered += c.covered
			result.measurable += c.measurable
		}
	}
	return result
}

func percent(c counts) string {
	if c.measurable == 0 {
		return "XX%"
	}
	return fmt.Sprintf("%.1f%%", 100*float64(c.covered)/float64(c.measurable))
}

func coverageColor(c counts) string {
	if c.measurable == 0 {
		return "#e5e7eb"
	}
	value := 100 * float64(c.covered) / float64(c.measurable)
	if value >= 80 {
		return "#bbf7d0"
	}
	if value >= 50 {
		return "#fde68a"
	}
	return "#fecaca"
}
