package analyzers

import (
	"fmt"
	"strings"
	"testing"

	"golang.org/x/tools/go/analysis/analysistest"
)

func TestProcessEdgesCompilerImports(t *testing.T) {
	useFixtures(t)
	dir, cleanup, err := analysistest.WriteFiles(map[string]string{
		"m/pkg/services/models/wire/wire.go": "package wire\nconst Value = 1\n",
		"m/pkg/services/edges/definition.go": `package edges
type Edges struct{}
`,
		"m/pkg/services/edges/models_effects.go": `package edges
import alias "m/pkg/services/models/wire" // want "process-edge-models-wire-import"
var _ = alias.Value
type AssetReadFile func() // reviewed exact contract
type Other struct{} // want "process-edge-contract-ownership"
`,
		"m/pkg/services/edges/generated.go": `// Code generated by fixture. DO NOT EDIT.
package edges
type Extra struct{} // want "process-edge-contract-ownership"
`,
		"m/pkg/services/edges/import_test.go": `package edges
import _ "m/pkg/services/models/wire" // want "process-edge-models-wire-import"
type TestHelper struct{}
`,
		"m/pkg/services/edges/external_test.go": `package edges_test
import . "m/pkg/services/models/wire" // want "process-edge-models-wire-import"
var _ = Value
type ExternalHelper struct{}
`,
		"m/pkg/services/edges/sub/sub.go": `package sub
import _ "m/pkg/services/models/wire" // want "process-edge-models-wire-import"
type SubHelper struct{}
`,
		"m/pkg/services/edgeslookalike/other.go": `package other
import _ "m/pkg/services/models/wire"
type Other struct{}
`,
		"m/pkg/services/models/service_contract.go": "package models\ntype Service interface{}\n",
	})
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, ProcessEdges, "m/pkg/services/edges", "m/pkg/services/edges/sub", "m/pkg/services/edgeslookalike", "m/pkg/services/models")
}

func TestProcessEdgesExactEffectAllowances(t *testing.T) {
	useFixtures(t)
	for name := range allowedProcessEdgeModelEffectTypes {
		t.Run(name, func(t *testing.T) {
			if !allowedProcessEdgeType("models_effects.go", name) || allowedProcessEdgeType("other.go", name) {
				t.Fatalf("%s must be allowed only in models_effects.go", name)
			}
		})
	}
	pass, diagnostics := shapePass(t, "pkg/services/edges", map[string]string{
		"models_effects.go": "package edges\ntype AssetReadFile func()\ntype Extra struct{}\n",
		"other.go":          "package edges\ntype AssetReadFileElsewhere func()\ntype Edges struct{}\n",
		"helper_test.go":    "package edges\ntype TestOnly struct{}\n",
	})
	pass.Analyzer = ProcessEdges
	if _, err := ProcessEdges.Run(pass); err != nil {
		t.Fatal(err)
	}
	if len(*diagnostics) != 2 {
		t.Fatalf("want two forbidden declarations, got %v", *diagnostics)
	}
	for _, diagnostic := range *diagnostics {
		if !strings.Contains(diagnostic.Message, "process-edge-contract-ownership") || pass.Fset.Position(diagnostic.Pos).Line != 3 && pass.Fset.Position(diagnostic.Pos).Line != 2 {
			t.Fatalf("missing rule/site: %+v", diagnostic)
		}
	}
}

func TestProcessEdgesModelsInterfaceIdentity(t *testing.T) {
	useFixtures(t)
	for _, tc := range []struct {
		name, filename, source string
		want                   bool
	}{
		{"exact", "service_contract.go", "type Service interface{}", false},
		{"missing", "service_contract.go", "type Service struct{}", true},
		{"wrong-name", "service_contract.go", "type Other interface{}", true},
		{"wrong-file", "other.go", "type Service interface{}", true},
		{"extra", "service_contract.go", "type Service interface{}; type Other interface{}", true},
		// The legacy rule counts literal interface declarations, not aliases or
		// interfaces nested in another type. Preserve that exact policy.
		{"alias", "service_contract.go", "type Service = interface{}", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			pass, diagnostics := shapePass(t, "pkg/services/models", map[string]string{
				tc.filename:      "package models\n" + tc.source,
				"helper_test.go": "package models\ntype TestOnly interface{}",
			})
			pass.Analyzer = ProcessEdges
			if _, err := ProcessEdges.Run(pass); err != nil {
				t.Fatal(err)
			}
			if (len(*diagnostics) != 0) != tc.want {
				t.Fatalf("want violation=%v, got %v", tc.want, *diagnostics)
			}
			if tc.want && !strings.Contains((*diagnostics)[0].Message, "models-root-service-interface") {
				t.Fatal(fmt.Sprint(*diagnostics))
			}
		})
	}
}
