package analyzers

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"reflect"
	"sort"
	"strings"
	"testing"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/analysistest"
)

// These tests serialize because useFixtures temporarily replaces the existing
// analyzer module prefix and ledger. The passes and ledgers are test-owned.
func TestServiceShapeCompilerUnits(t *testing.T) {
	useFixtures(t)
	analysistest.Run(t, analysistest.TestData(), ServiceShape,
		"m/pkg/services/shapevalid", "m/pkg/services/shapeinvalid",
		"m/pkg/services/shapevalid/internal/implementation",
		"m/pkg/services/shapevalid/internal/services/nested",
		"m/pkg/services/shapevalid/internal/services/nested/internal/services/deep",
		"m/pkg/services/shapevalid/extra/descendant",
		"m/pkg/services/shapevalid/services/legacy",
		"m/pkg/services/shapevalid/internal/services",
	)
}

func TestServiceShapeBaseline(t *testing.T) {
	const unit = "pkg/services/shape"
	const export = "service-root-exported-function|" + unit + "|" + unit + "/service.go#Start"
	const deleted = "service-root-exported-function|" + unit + "|" + unit + "/deleted.go#Gone"
	useFixtures(t, export, deleted)
	pass, diagnostics := shapePass(t, unit, map[string]string{
		"service.go": "package shape\ntype Service interface{}\nfunc Start() {}\nfunc New() {}\n",
	})
	if _, err := ServiceShape.Run(pass); err != nil {
		t.Fatal(err)
	}
	if len(*diagnostics) != 2 {
		t.Fatalf("want new and stale diagnostics, got %v", *diagnostics)
	}
	if got := (*diagnostics)[0]; !strings.Contains(got.Message, unit+"/service.go#New") || pass.Fset.Position(got.Pos).Line != 4 {
		t.Fatalf("new finding must identify exact export and declaration: %+v", got)
	}
	if got := (*diagnostics)[1]; !strings.Contains(got.Message, "stale baseline entry `"+deleted+"`") {
		t.Fatalf("deleted source in analyzed unit must be stale: %+v", got)
	}
}

func TestServiceShapeIgnoredDeclarations(t *testing.T) {
	const unit = "pkg/services/shape"
	const count = "service-root-interface-count|" + unit + "|" + unit + "/base.go:Service," + unit + "/tagged.go:Other"
	const export = "service-root-exported-function|" + unit + "|" + unit + "/tagged.go#New"
	useFixtures(t, count, export)
	pass, diagnostics := shapePass(t, unit, map[string]string{
		"base.go": "package shape\ntype Service interface{}\n",
	})
	pass.IgnoredFiles = []string{"/fixture/" + unit + "/tagged.go"}
	if _, err := ServiceShape.Run(pass); err != nil {
		t.Fatal(err)
	}
	if len(*diagnostics) != 0 {
		t.Fatalf("excluded declaration debt must not be falsely stale: %v", *diagnostics)
	}
	selected, selectedDiagnostics := shapePass(t, unit, map[string]string{
		"base.go":   "package shape\ntype Service interface{}\n",
		"tagged.go": "package shape\ntype Other interface{}\nfunc New() {}\n",
	})
	ServiceShape.Run(selected)
	if len(*selectedDiagnostics) != 0 {
		t.Fatalf("selected exact debt must be accepted: %v", *selectedDiagnostics)
	}
	selected.Files[1].Decls = selected.Files[1].Decls[:1]
	ServiceShape.Run(selected)
	if len(*selectedDiagnostics) != 1 || !strings.Contains((*selectedDiagnostics)[0].Message, "stale baseline entry `"+export+"`") {
		t.Fatalf("selected repaired export must be stale: %v", *selectedDiagnostics)
	}
}

func TestServiceShapeEmptyContracts(t *testing.T) {
	useFixtures(t)
	for _, source := range []string{
		"package shape\ntype Value struct{}\n",
		"// Code generated by fixture. DO NOT EDIT.\npackage shape\ntype Service interface{}\nfunc Generated() {}\n",
	} {
		pass, diagnostics := shapePass(t, "pkg/services/shape", map[string]string{"service.go": source})
		ServiceShape.Run(pass)
		if len(*diagnostics) != 1 || !strings.Contains((*diagnostics)[0].Message, "service-root-interface-count: pkg/services/shape -> <none>") {
			t.Fatalf("zero handwritten interfaces must fail: %v", *diagnostics)
		}
	}
}

func TestServiceShapeContainerFiles(t *testing.T) {
	useFixtures(t)
	for _, unit := range []string{
		"pkg/services/shape/internal/services", "pkg/services/shape/services",
	} {
		pass, diagnostics := shapePass(t, unit, map[string]string{
			"container.go":      "package services\n",
			"generated.go":      "// Code generated by fixture. DO NOT EDIT.\npackage services\n",
			"container_test.go": "package services\n",
		})
		ServiceShape.Run(pass)
		var targets []string
		for _, diagnostic := range *diagnostics {
			if strings.Contains(diagnostic.Message, "service-container-go-file:") {
				targets = append(targets, pass.Fset.Position(diagnostic.Pos).Filename)
			}
		}
		if len(targets) != 3 {
			t.Fatalf("every compiled container source must fail, including generated/tests: %v", *diagnostics)
		}
	}
}

func TestServiceShapeStaleInterfaceCount(t *testing.T) {
	const unit = "pkg/services/shape"
	const key = "service-root-interface-count|" + unit + "|<none>"
	useFixtures(t, key)
	pass, diagnostics := shapePass(t, unit, map[string]string{
		"service.go": "package shape\ntype Service interface{}\n",
	})
	ServiceShape.Run(pass)
	if len(*diagnostics) != 1 || !strings.Contains((*diagnostics)[0].Message, "stale baseline entry `"+key+"`") {
		t.Fatalf("a repaired contract must fail until its debt key is deleted: %v", *diagnostics)
	}
}

func TestServiceShapeBuildConfigurations(t *testing.T) {
	const unit = "pkg/services/shapetagged"
	useFixtures(t, "service-root-exported-function|"+unit+"|"+unit+"/tagged.go#New")
	t.Run("default", func(t *testing.T) {
		t.Setenv("GOFLAGS", "")
		analysistest.Run(t, analysistest.TestData(), ServiceShape, "m/"+unit)
	})
	t.Run("repository-tags", func(t *testing.T) {
		t.Setenv("GOFLAGS", "-tags=functionallong,backendconformance,factoryartifact,managed_process_integration")
		analysistest.Run(t, analysistest.TestData(), ServiceShape, "m/"+unit)
	})
}

func TestServiceShapeOSDeclarations(t *testing.T) {
	const unit = "pkg/services/shapeos"
	var keys []string
	for _, platform := range []string{"windows", "linux"} {
		file := unit + "/service_" + platform + ".go"
		keys = append(keys,
			"service-root-interface-count|"+unit+"|"+unit+"/service.go:Service,"+file+":Platform",
			"service-root-exported-function|"+unit+"|"+file+"#Existing")
	}
	useFixtures(t, keys...)
	for _, platform := range []string{"windows", "linux"} {
		t.Run(platform, func(t *testing.T) {
			// Only package loading crosses GOOS; no foreign executable is run.
			// Serialize because the compiler environment and fixture ledger are global.
			t.Setenv("GOOS", platform)
			t.Setenv("GOARCH", "amd64")
			t.Setenv("CGO_ENABLED", "0")
			t.Setenv("GOFLAGS", "")
			analysistest.Run(t, analysistest.TestData(), ServiceShape, "m/"+unit)
		})
	}
}

func TestServiceShapeRecursiveLocations(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		unit, root string
		container  bool
		unexpected []string
	}{
		{"pkg/services/a", "pkg/services/a", false, nil},
		{"pkg/services/a/internal/services/b/internal/services/c", "pkg/services/a/internal/services/b/internal/services/c", false, nil},
		{"pkg/services/a/internal/services", "pkg/services/a", true, nil},
		{"pkg/services/a/internal/implementation", "", false, nil},
		{"pkg/services/a/wire", "", false, nil},
		{"pkg/services/a/transports/http", "", false, nil},
		{"pkg/services/a/extra/sub", "", false, []string{"pkg/services/a/extra"}},
		{"pkg/services/a/services/b/services", "pkg/services/a/services/b", true, []string{"pkg/services/a/services", "pkg/services/a/services/b/services"}},
		{"pkg/services", "", false, nil},
		{"pkg/platform/a", "", false, nil},
	} {
		root, container, unexpected := serviceLocation(tc.unit)
		if root != tc.root || container != tc.container || !reflect.DeepEqual(unexpected, tc.unexpected) {
			t.Errorf("%s: got (%q, %v, %v)", tc.unit, root, container, unexpected)
		}
	}
}

func shapePass(t *testing.T, unit string, sources map[string]string) (*analysis.Pass, *[]analysis.Diagnostic) {
	t.Helper()
	fset := token.NewFileSet()
	var files []*ast.File
	// Stable filenames make declaration and diagnostic ordering reproducible.
	names := make([]string, 0, len(sources))
	for name := range sources {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		source := sources[name]
		file, err := parser.ParseFile(fset, "/fixture/"+unit+"/"+name, source, parser.ParseComments)
		if err != nil {
			t.Fatal(err)
		}
		files = append(files, file)
	}
	var diagnostics []analysis.Diagnostic
	return &analysis.Pass{
		Analyzer: ServiceShape, Fset: fset, Files: files, Pkg: types.NewPackage("m/"+unit, "shape"),
		Report: func(d analysis.Diagnostic) { diagnostics = append(diagnostics, d) },
	}, &diagnostics
}
