package analyzers

import (
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"golang.org/x/tools/go/analysis"
	"strings"
	"testing"

	"golang.org/x/tools/go/analysis/analysistest"
)

func TestTestBoundaryWorkNormalization(t *testing.T) {
	useFixtures(t)
	files := map[string]string{
		"m/pkg/services/work/work.go": `package work
func NormalizeWorkRequest() {}
type Lookalike struct{}
func (Lookalike) NormalizeWorkRequest() {}
`,
		"m/pkg/services/work/work_test.go": `package work
func owner() { NormalizeWorkRequest() }
`,
		"m/pkg/services/work/external_test.go": `package work_test
import "m/pkg/services/work"
func owner() { work.NormalizeWorkRequest() }
`,
		"m/pkg/services/work/child/child_test.go": `package child
import "m/pkg/services/work"
func owner() { work.NormalizeWorkRequest() }
`,
		"m/pkg/services/workers/consumer.go": `package workers
import "m/pkg/services/work"
func production() { work.NormalizeWorkRequest() }
`,
		"m/pkg/services/workers/consumer_test.go": `package workers
import renamed "m/pkg/services/work"
func consumer() {
 renamed.NormalizeWorkRequest() // want "test-work-normalization.*pkg/services/workers.*NormalizeWorkRequest"
 f := renamed.NormalizeWorkRequest // want "test-work-normalization"
 f()
 renamed.Lookalike{}.NormalizeWorkRequest()
 renamed := struct { NormalizeWorkRequest func() }{func(){}}
 renamed.NormalizeWorkRequest()
}

`,
		"m/pkg/services/workers/external_test.go": `package workers_test
import . "m/pkg/services/work"
func consumer() {
 NormalizeWorkRequest() // want "test-work-normalization.*pkg/services/workers_test"
 NormalizeWorkRequest := func() {}
 NormalizeWorkRequest()
}
`,
		"m/internal/testutil/child/support.go": `package child
import . "m/pkg/services/work"
var normalize = NormalizeWorkRequest // want "test-work-normalization"
`,
		"m/tests/functional/internal/support/support.go": `package support
import "m/pkg/services/work"
func helper() { work.NormalizeWorkRequest() } // want "test-work-normalization"
`,
		"m/pkg/services/workers/generated_test.go": `// Code generated by fixture. DO NOT EDIT.
package workers
import "m/pkg/services/work"
func generated() { work.NormalizeWorkRequest() }
`,
		"m/internal/testutility/support.go": `package testutility
import "m/pkg/services/work"
func production() { work.NormalizeWorkRequest() }
`,
		"m/tests/functional/scenario/scenario_test.go": `package scenario
import "m/pkg/services/work"
func scenario() { work.NormalizeWorkRequest() } // want "test-work-normalization"
`,
	}
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/pkg/services/work", "m/pkg/services/work/child", "m/pkg/services/workers", "m/internal/testutil/child", "m/internal/testutility", "m/tests/functional/internal/support", "m/tests/functional/scenario")
}

func TestTestBoundaryFunctionalTransportComposition(t *testing.T) {
	useFixtures(t)
	files := functionalTransportFixtures()
	files["m/tests/functional/scenario/scenario_test.go"] = `package scenario
import (
 renamed "m/pkg/transports/cli/clihttp"
 . "m/pkg/transports/mapping/factoryconfig"
 submit "m/pkg/services/work/transports/cli/submit"
 child "m/pkg/transports/http/client/child"
)
func scenario() {
 renamed.NewProtocol() // want "test-functional-transport-composition.*pkg/transports/cli/clihttp.NewProtocol"
 f := renamed.NewProtocol // want "test-functional-transport-composition"
 f()
 NewFactoryConfigMapper() // want "test-functional-transport-composition.*NewFactoryConfigMapper"
 BuildMapper() // want "test-functional-transport-composition.*BuildMapper"
 CreateMapper() // want "test-functional-transport-composition.*CreateMapper"
 submit.NewSubmit() // want "test-functional-transport-composition.*pkg/services/work/transports/cli/submit.NewSubmit"
 child.NewClient() // want "test-functional-transport-composition.*pkg/transports/http/client/child.NewClient"
 _ = renamed.NewValue(0) // want "test-functional-transport-composition.*NewValue"
 renamed.BuildVariable() // want "test-functional-transport-composition.*BuildVariable"
 variable := renamed.BuildVariable // want "test-functional-transport-composition.*BuildVariable"
 variable()
 renamed.Lookalike{}.NewProtocol()
 renamed := struct { NewProtocol func() }{func(){}}
 renamed.NewProtocol()
 NewFactoryConfigMapper := func() {}
 NewFactoryConfigMapper()
}
`
	files["m/tests/functional/internal/support/helper.go"] = `package support
import "m/pkg/transports/cli/clihttp"
var helper = clihttp.NewProtocol // want "test-functional-transport-composition.*tests/functional/internal/support"
`
	files["m/tests/functional/scenario/external_test.go"] = `package scenario_test
import "m/pkg/transports/cli/clihttp"
func external() { clihttp.NewProtocol() } // want "test-functional-transport-composition.*scenario_test"
`
	files["m/tests/functional/scenario/production.go"] = `package scenario
import "m/pkg/transports/cli/clihttp"
func production() { clihttp.NewProtocol() }
`
	files["m/tests/functional/scenario/generated_test.go"] = `// Code generated by fixture. DO NOT EDIT.
package scenario
import "m/pkg/transports/cli/clihttp"
func generated() { clihttp.NewProtocol() }
`
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/tests/functional/scenario", "m/tests/functional/internal/support")
}

func TestTestBoundaryFunctionalTransportAllowances(t *testing.T) {
	useFixtures(t)
	files := functionalTransportFixtures()
	allowed := `import (
 "m/pkg/transports/cli/clihttp"
 "m/pkg/services/work/transports/cli/submit"
)
func allowed() { clihttp.NewProtocol(); submit.NewSubmit() }
`
	for path, pkg := range map[string]string{
		"m/pkg/services/work/transports/cli/submit/protocol_test.go": "submit_test",
		"m/pkg/transports/cli/clihttp/protocol_test.go":              "clihttp_test",
		"m/internal/testutil/support.go":                             "testutil",
		"m/tests/functionality/scenario_test.go":                     "functionality",
	} {
		files[path] = "package " + pkg + "\n" + allowed
	}
	files["m/tests/functional/scenario/scenario_test.go"] = `package scenario
import (
 "m/pkg/root"
 "m/pkg/transports/http/generated"
 "m/pkg/transports/http/client"
 "m/pkg/transports/cli/clihttp"
 "m/pkg/services/work/transports/cli/submit"
 "m/other/transports"
)
func allowed() {
 root.BuildProcess(); generated.NewPublicValue(); client.NewClient()
 clihttp.Observe(); submit.NewOther(); transports.NewProtocol()
 var detached clihttp.NewValue
 _ = detached; _ = clihttp.NewVersion; _ = clihttp.NewSetting
}
`
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/tests/functional/scenario", "m/pkg/services/work/transports/cli/submit", "m/pkg/transports/cli/clihttp", "m/internal/testutil", "m/tests/functionality")
}

func TestTestBoundaryWorkInvocationCallback(t *testing.T) {
	useFixtures(t)
	source := `package callbacks
type fake struct { prepare func(int) int }
func (f fake) PrepareInvocationInput(request int) int { return f.prepare(request) }
type pointer struct { prepare func(int) int }
func (f *pointer) PrepareInvocationInput(request int) int { return f.prepare(request) }
type policy struct{}
func (policy) PrepareInvocationInput(request int) int { return request + 1 } // want "test-work-invocation-policy.*PrepareInvocationInput"
type branching struct { prepare func(int) int }
func (f branching) PrepareInvocationInput(request int) int { // want "test-work-invocation-policy"
 if request == 0 { return 1 }; return f.prepare(request)
}
type transformed struct { prepare func(int) int }
func (f transformed) PrepareInvocationInput(request int) int { return f.prepare(request + 1) } // want "test-work-invocation-policy"
type detached struct { prepare func(int) int }
var other = fake{}
func (f detached) PrepareInvocationInput(request int) int { return other.prepare(request) } // want "test-work-invocation-policy"
type indirect struct { prepare func(int) int }
func (f indirect) PrepareInvocationInput(request int) int { // want "test-work-invocation-policy"
 callback := f.prepare; return callback(request)
}
func PrepareInvocationInput(request int) int { return request } // want "test-work-invocation-policy"
`
	files := map[string]string{
		"m/pkg/transports/http/callbacks_test.go": source,
		"m/pkg/transports/cli/external_test.go":   strings.Replace(source, "package callbacks", "package cli_test", 1),
		"m/internal/testutil/callbacks.go":        strings.ReplaceAll(source, ` // want "test-work-invocation-policy`, ` // unrelated "test-work-invocation-policy`),
	}
	clean := strings.ReplaceAll(source, ` // want "test-work-invocation-policy`, ` // unrelated "test-work-invocation-policy`)
	files["m/pkg/transports/http/production/production.go"] = clean
	files["m/pkg/transports/http/generated/generated_test.go"] = "// Code generated by fixture. DO NOT EDIT.\n" + clean
	files["m/pkg/services/work/callbacks_test.go"] = clean
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/pkg/transports/http", "m/pkg/transports/cli", "m/pkg/transports/http/generated", "m/pkg/transports/http/production", "m/pkg/services/work", "m/internal/testutil")
}

func TestTestBoundaryHTTPEngineLiterals(t *testing.T) {
	useFixtures(t)
	files := map[string]string{
		"m/pkg/services/factory_runtime/runtime.go": `package runtime
type EngineStateSnapshot struct{}
type Net struct{}
type PetriMarkingSnapshot map[string]int
type RuntimeToken struct{}
type RuntimeTokenColor struct{}
type WorkflowPreview struct{}
type TokenAlias = RuntimeToken
`,
		"m/other/runtime/runtime.go": "package runtime\ntype RuntimeToken struct{}\n",
		"m/pkg/transports/http/servertests/server_test.go": `package servertests
import (
 renamed "m/pkg/services/factory_runtime"
 other "m/other/runtime"
)
type Alias = renamed.RuntimeToken
type RuntimeToken struct{}
func fixtures() {
 _ = renamed.EngineStateSnapshot{} // want "test-http-engine-literal.*EngineStateSnapshot"
 _ = renamed.Net{} // want "test-http-engine-literal.*Net"
 _ = renamed.PetriMarkingSnapshot{} // want "test-http-engine-literal.*PetriMarkingSnapshot"
 _ = renamed.RuntimeToken{} // want "test-http-engine-literal.*RuntimeToken"
 _ = renamed.RuntimeToken{} // want "test-http-engine-literal.*RuntimeToken"
 _ = renamed.RuntimeTokenColor{} // want "test-http-engine-literal.*RuntimeTokenColor"
 _ = renamed.TokenAlias{} // want "test-http-engine-literal.*RuntimeToken"
 _ = Alias{} // want "test-http-engine-literal.*RuntimeToken"
 _ = []renamed.RuntimeToken{{}} // want "test-http-engine-literal.*RuntimeToken"
 _ = &renamed.RuntimeToken{} // want "test-http-engine-literal.*RuntimeToken"
 _ = renamed.WorkflowPreview{}
 _ = other.RuntimeToken{}
 _ = RuntimeToken{}
 var detached renamed.RuntimeToken
 _ = detached
}
`,
		"m/pkg/transports/http/servertests/external_test.go": `package servertests_test
import . "m/pkg/services/factory_runtime"
func external() { _ = RuntimeToken{} } // want "test-http-engine-literal.*servertests_test.*RuntimeToken"
`,
	}
	clean := `package clean
import runtime "m/pkg/services/factory_runtime"
func allowed() { _ = runtime.RuntimeToken{} }
`
	files["m/pkg/transports/http/production/production.go"] = clean
	files["m/pkg/transports/http/generated/generated_test.go"] = "// Code generated by fixture. DO NOT EDIT.\n" + clean
	files["m/pkg/transports/cli/cli_test.go"] = clean
	files["m/pkg/transports/httpother/other_test.go"] = clean
	files["m/pkg/services/factory_runtime/runtime_test.go"] = strings.ReplaceAll(clean, "package clean", "package runtime_test")
	files["m/tests/functional/scenario/scenario_test.go"] = clean
	files["m/internal/testutil/helper.go"] = clean
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/pkg/transports/http/servertests", "m/pkg/transports/http/production", "m/pkg/transports/http/generated", "m/pkg/transports/cli", "m/pkg/transports/httpother", "m/pkg/services/factory_runtime", "m/tests/functional/scenario", "m/internal/testutil")
}

func functionalTransportFixtures() map[string]string {
	return map[string]string{
		"m/pkg/transports/cli/clihttp/protocol.go": `package clihttp
func NewProtocol() {}
func Observe() {}
type NewValue int
const NewVersion = 1
var NewSetting = 1
var BuildVariable = func() {}
type Lookalike struct{}
func (Lookalike) NewProtocol() {}
`,
		"m/pkg/transports/mapping/factoryconfig/mapper.go": `package factoryconfig
func NewFactoryConfigMapper() {}
func BuildMapper() {}
func CreateMapper() {}
`,
		"m/pkg/services/work/transports/cli/submit/submit.go": `package submit
func NewSubmit() {}
func NewOther() {}
`,
		"m/pkg/transports/http/generated/client.go":    "package generated\nfunc NewPublicValue() {}\n",
		"m/pkg/transports/http/client/client.go":       "package client\nfunc NewClient() {}\n",
		"m/pkg/transports/http/client/child/client.go": "package child\nfunc NewClient() {}\n",
		"m/pkg/root/process.go":                        "package root\nfunc BuildProcess() {}\n",
		"m/other/transports/protocol.go":               "package transports\nfunc NewProtocol() {}\n",
	}
}

func TestTestBoundaryProcessComposition(t *testing.T) {
	useFixtures(t)
	files := testProcessCompositionFixtures()
	allowed := `import (
 "m/pkg/root"
 "m/internal/builtcliacceptance"
)
func allowed() { root.BuildProcess(); builtcliacceptance.NewHarness() }
`
	for path, pkg := range map[string]string{
		"m/tests/functional/internal/support/support.go": "support",
		"m/internal/testutil/support.go":                 "testutil",
		"m/tests/functional/scenario/scenario_test.go":   "scenario",
		"m/pkg/wire/process_test.go":                     "wire",
		"m/pkg/services/example/production.go":           "example",
	} {
		// Wire may construct the root process, but not the built CLI harness.
		source := allowed
		if pkg == "wire" {
			source = `import "m/pkg/root"
func allowed() { root.BuildProcess() }
`
		}
		files[path] = "package " + pkg + "\n" + source
	}
	files["m/pkg/services/example/generated_test.go"] = "// Code generated by fixture. DO NOT EDIT.\npackage example\n" + strings.Replace(allowed, "func allowed", "func generated", 1)
	for i, path := range []string{
		"pkg/transports/cli/baseline/goal_failure_process_test.go",
		"pkg/transports/cli/baseline/root_process_external_test.go",
		"pkg/transports/cli/baseline/root_process_test.go",
		"pkg/transports/cli/clicontract/root_process_test.go",
		"pkg/transports/cli/cliinputs/root_process_test.go",
		"pkg/transports/cli/commandidentity/root_process_test.go",
	} {
		pkg := strings.Split(path, "/")[3]
		files["m/"+path] = fmt.Sprintf(`package %s_test
import "m/pkg/root"
func inventory%d() { root.BuildProcess(); f := root.BuildProcess; f() }
`, pkg, i)
	}
	files["m/pkg/transports/cli/baseline/neighbor_test.go"] = `package baseline_test
import "m/pkg/root"
func scenario() { root.BuildProcess() } // want "test-customer-process-under-transport"
`
	files["m/pkg/transports/cli/baseline/child/root_process_test.go"] = `package child
import "m/pkg/root"
func scenario() { root.BuildProcess() } // want "test-customer-process-under-transport"
`
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/pkg/...", "m/internal/testutil", "m/tests/functional/...")
}

func testProcessCompositionFixtures() map[string]string {
	return map[string]string{
		"m/pkg/root/root.go": `package root
func BuildProcess() {}
type Lookalike struct{}
func (Lookalike) BuildProcess() {}
`,
		"m/internal/builtcliacceptance/harness.go": `package builtcliacceptance
func NewHarness() {}
`,
		"m/pkg/services/example/process_test.go": `package example
import (
 renamed "m/pkg/root"
 cli "m/internal/builtcliacceptance"
)
func scenario() {
 renamed.BuildProcess() // want "test-alternate-customer-composition.*pkg/services/example.*pkg/root.BuildProcess"
 f := renamed.BuildProcess // want "test-alternate-customer-composition"
 f()
 cli.NewHarness() // want "test-alternate-customer-composition.*NewHarness"
 renamed.Lookalike{}.BuildProcess()
 renamed := struct { BuildProcess func() }{func(){}}
 renamed.BuildProcess()
}
`,
		"m/pkg/transports/cli/session/process_test.go": `package session_test
import . "m/pkg/root"
func scenario() {
 (BuildProcess)() // want "test-customer-process-under-transport.*pkg/transports/cli/session_test"
 f := BuildProcess // want "test-customer-process-under-transport"
 f()
 BuildProcess := func() {}
 BuildProcess()
}
`,
		"m/pkg/platform/example/process_test.go": `package example
import "m/internal/builtcliacceptance"
var harness = builtcliacceptance.NewHarness // want "test-alternate-customer-composition"
`,
	}
}

func TestTestBoundaryCrossOwnerPolicyTable(t *testing.T) {
	useFixtures(t)
	for path, symbols := range crossOwnerTestPolicy {
		for symbol := range symbols {
			t.Run(path+"/"+symbol, func(t *testing.T) {
				pkg := types.NewPackage(modulePrefix+path, "policy")
				fn := types.NewFunc(token.Pos(1), pkg, symbol, types.NewSignatureType(nil, nil, nil, nil, nil, false))
				id := &ast.Ident{Name: symbol, NamePos: token.Pos(1)}
				var diagnostics []violation
				fset := token.NewFileSet()
				fset.AddFile("policy_test.go", 1, 100)
				pass := &analysis.Pass{Fset: fset}
				owner := strings.Split(path, "/")[2]
				for _, unit := range []string{"pkg/services/" + owner, "pkg/services/" + owner + "_test", "pkg/services/" + owner + "/child", "pkg/wire", "pkg/wire/child_test"} {
					if v := crossOwnerTestPolicyViolation(pass, id, fn, unit, false); v != nil {
						diagnostics = append(diagnostics, *v)
					}
				}
				if len(diagnostics) != 0 {
					t.Fatalf("owner/composition diagnostics: %v", diagnostics)
				}
				for _, unit := range []string{"pkg/services/" + owner + "other", "pkg/wireother", "internal/testutil", "tests/functional/internal/support", "pkg/transports/http_test"} {
					if v := crossOwnerTestPolicyViolation(pass, id, fn, unit, false); v != nil {
						diagnostics = append(diagnostics, *v)
					}
				}
				if len(diagnostics) != 5 {
					t.Fatalf("diagnostics = %v, want five rejected consumers", diagnostics)
				}
				for _, d := range diagnostics {
					if d.pos != id.Pos() || !strings.Contains(d.importee, path+"."+symbol) {
						t.Fatalf("wrong diagnostic: %v", d)
					}
				}
			})
		}
	}
}

func TestTestBoundaryCrossOwnerPolicy(t *testing.T) {
	useFixtures(t)
	files := map[string]string{
		"m/pkg/services/factory_definitions/definitions.go": `package factory_definitions
func MapDir() {}
func NamedFactoriesRoot() {}
func ResolveCurrentDir() {}
func WriteCurrentPointer() {}
type Lookalike struct{}
func (Lookalike) MapDir() {}
`,
		"m/pkg/services/operator_settings/settings.go": `package operator
func DefaultConfigPath() {}
func ResolveFromHomeWithEnvironment() {}
`,
		"m/pkg/services/workers/workers.go": `package workers
func LoadMockWorkersConfig() {}
`,
	}
	consumer := `import (
 renamed "m/pkg/services/factory_definitions"
 . "m/pkg/services/operator_settings"
 "m/pkg/services/workers"
)
func policy() {
 renamed.MapDir() // want "test-cross-owner-policy.*factory_definitions.MapDir"
 renamed.NamedFactoriesRoot() // want "test-cross-owner-policy.*NamedFactoriesRoot"
 renamed.ResolveCurrentDir() // want "test-cross-owner-policy.*ResolveCurrentDir"
 renamed.WriteCurrentPointer() // want "test-cross-owner-policy.*WriteCurrentPointer"
 DefaultConfigPath() // want "test-cross-owner-policy.*operator_settings.DefaultConfigPath"
 ResolveFromHomeWithEnvironment() // want "test-cross-owner-policy.*ResolveFromHomeWithEnvironment"
 workers.LoadMockWorkersConfig() // want "test-cross-owner-policy.*workers.LoadMockWorkersConfig"
 f := renamed.MapDir
 f()
 renamed.Lookalike{}.MapDir()
 renamed := struct { MapDir func() }{func(){}}
 renamed.MapDir()
 DefaultConfigPath := func() {}
 DefaultConfigPath()
}
`
	files["m/pkg/transports/http/policy_test.go"] = "package http\n" + consumer
	files["m/pkg/transports/http/external_test.go"] = "package http_test\n" + consumer
	files["m/internal/testutil/support.go"] = "package testutil\n" + consumer
	files["m/tests/functional/internal/support/support.go"] = "package support\n" + consumer
	clean := strings.ReplaceAll(consumer, " // want", " // clean")
	files["m/pkg/wire/policy_test.go"] = "package wire_test\n" + clean
	files["m/pkg/transports/http/generated_test.go"] = "// Code generated by fixture. DO NOT EDIT.\npackage http\n" + strings.ReplaceAll(clean, "func policy()", "func generated()")
	files["m/pkg/transports/http/production.go"] = "package http\n" + strings.ReplaceAll(clean, "func policy()", "func production()")
	for path, symbols := range crossOwnerTestPolicy {
		owner := strings.Split(path, "/")[2]
		if strings.Contains(path, "/internal/") {
			source := "package namedpaths\n"
			for symbol := range symbols {
				source += "func " + symbol + "() {}\n"
			}
			files["m/"+path+"/paths.go"] = source
		}
		source := "package policy_test\nimport p \"m/" + path + "\"\nfunc allowed_" + strings.ReplaceAll(path, "/", "_") + "() {\n"
		for symbol := range symbols {
			source += "p." + symbol + "()\n"
		}
		source += "}\n"
		files["m/pkg/services/"+owner+"/policy/"+strings.ReplaceAll(path, "/", "_")+"_test.go"] = source
	}
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/pkg/transports/http", "m/internal/testutil", "m/tests/functional/internal/support", "m/pkg/wire", "m/pkg/services/.../policy")
}

func TestTestBoundaryCrossOwnerPolicyDebt(t *testing.T) {
	useFixtures(t)
	baseline = func() map[string]struct{} {
		keys := map[string]struct{}{}
		for _, pkg := range []string{"debt", "growth", "stale"} {
			keys["test-cross-owner-policy|pkg/transports/"+pkg+"|pkg/transports/"+pkg+"/policy_test.go#pkg/services/workers.LoadMockWorkersConfig::count=2"] = struct{}{}
		}
		return keys
	}
	files := map[string]string{
		"m/pkg/services/workers/workers.go": "package workers\nfunc LoadMockWorkersConfig() {}\n",
		"m/pkg/transports/debt/policy_test.go": `package debt
import "m/pkg/services/workers"
func policy() {workers.LoadMockWorkersConfig(); workers.LoadMockWorkersConfig()}
`,
		"m/pkg/transports/growth/policy_test.go": `package growth // want "stale baseline entry"
import "m/pkg/services/workers"
func policy() {
 workers.LoadMockWorkersConfig() // want "test-cross-owner-policy.*count=3"
 workers.LoadMockWorkersConfig()
 workers.LoadMockWorkersConfig()
}
`,
		"m/pkg/transports/stale/policy_test.go": `package stale // want "stale baseline entry"
`,
	}
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/pkg/transports/...")
}
