package analyzers

import (
	"strings"
	"testing"

	"golang.org/x/tools/go/analysis/analysistest"
)

func TestTestBoundaryWorkNormalization(t *testing.T) {
	useFixtures(t)
	files := map[string]string{
		"m/pkg/services/work/work.go": `package work
func NormalizeWorkRequest() {}
type Lookalike struct{}
func (Lookalike) NormalizeWorkRequest() {}
`,
		"m/pkg/services/work/work_test.go": `package work
func owner() { NormalizeWorkRequest() }
`,
		"m/pkg/services/work/external_test.go": `package work_test
import "m/pkg/services/work"
func owner() { work.NormalizeWorkRequest() }
`,
		"m/pkg/services/work/child/child_test.go": `package child
import "m/pkg/services/work"
func owner() { work.NormalizeWorkRequest() }
`,
		"m/pkg/services/workers/consumer.go": `package workers
import "m/pkg/services/work"
func production() { work.NormalizeWorkRequest() }
`,
		"m/pkg/services/workers/consumer_test.go": `package workers
import renamed "m/pkg/services/work"
func consumer() {
 renamed.NormalizeWorkRequest() // want "test-work-normalization.*pkg/services/workers.*NormalizeWorkRequest"
 f := renamed.NormalizeWorkRequest // want "test-work-normalization"
 f()
 renamed.Lookalike{}.NormalizeWorkRequest()
 renamed := struct { NormalizeWorkRequest func() }{func(){}}
 renamed.NormalizeWorkRequest()
}

`,
		"m/pkg/services/workers/external_test.go": `package workers_test
import . "m/pkg/services/work"
func consumer() {
 NormalizeWorkRequest() // want "test-work-normalization.*pkg/services/workers_test"
 NormalizeWorkRequest := func() {}
 NormalizeWorkRequest()
}
`,
		"m/internal/testutil/child/support.go": `package child
import . "m/pkg/services/work"
var normalize = NormalizeWorkRequest // want "test-work-normalization"
`,
		"m/tests/functional/internal/support/support.go": `package support
import "m/pkg/services/work"
func helper() { work.NormalizeWorkRequest() } // want "test-work-normalization"
`,
		"m/pkg/services/workers/generated_test.go": `// Code generated by fixture. DO NOT EDIT.
package workers
import "m/pkg/services/work"
func generated() { work.NormalizeWorkRequest() }
`,
		"m/internal/testutility/support.go": `package testutility
import "m/pkg/services/work"
func production() { work.NormalizeWorkRequest() }
`,
		"m/tests/functional/scenario/scenario_test.go": `package scenario
import "m/pkg/services/work"
func scenario() { work.NormalizeWorkRequest() } // want "test-work-normalization"
`,
	}
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/pkg/services/work", "m/pkg/services/work/child", "m/pkg/services/workers", "m/internal/testutil/child", "m/internal/testutility", "m/tests/functional/internal/support", "m/tests/functional/scenario")
}

func TestTestBoundaryFunctionalTransportComposition(t *testing.T) {
	useFixtures(t)
	files := functionalTransportFixtures()
	files["m/tests/functional/scenario/scenario_test.go"] = `package scenario
import (
 renamed "m/pkg/transports/cli/clihttp"
 . "m/pkg/transports/mapping/factoryconfig"
 submit "m/pkg/services/work/transports/cli/submit"
 child "m/pkg/transports/http/client/child"
)
func scenario() {
 renamed.NewProtocol() // want "test-functional-transport-composition.*pkg/transports/cli/clihttp.NewProtocol"
 f := renamed.NewProtocol // want "test-functional-transport-composition"
 f()
 NewFactoryConfigMapper() // want "test-functional-transport-composition.*NewFactoryConfigMapper"
 BuildMapper() // want "test-functional-transport-composition.*BuildMapper"
 CreateMapper() // want "test-functional-transport-composition.*CreateMapper"
 submit.NewSubmit() // want "test-functional-transport-composition.*pkg/services/work/transports/cli/submit.NewSubmit"
 child.NewClient() // want "test-functional-transport-composition.*pkg/transports/http/client/child.NewClient"
 _ = renamed.NewValue(0) // want "test-functional-transport-composition.*NewValue"
 renamed.BuildVariable() // want "test-functional-transport-composition.*BuildVariable"
 variable := renamed.BuildVariable // want "test-functional-transport-composition.*BuildVariable"
 variable()
 renamed.Lookalike{}.NewProtocol()
 renamed := struct { NewProtocol func() }{func(){}}
 renamed.NewProtocol()
 NewFactoryConfigMapper := func() {}
 NewFactoryConfigMapper()
}
`
	files["m/tests/functional/internal/support/helper.go"] = `package support
import "m/pkg/transports/cli/clihttp"
var helper = clihttp.NewProtocol // want "test-functional-transport-composition.*tests/functional/internal/support"
`
	files["m/tests/functional/scenario/external_test.go"] = `package scenario_test
import "m/pkg/transports/cli/clihttp"
func external() { clihttp.NewProtocol() } // want "test-functional-transport-composition.*scenario_test"
`
	files["m/tests/functional/scenario/production.go"] = `package scenario
import "m/pkg/transports/cli/clihttp"
func production() { clihttp.NewProtocol() }
`
	files["m/tests/functional/scenario/generated_test.go"] = `// Code generated by fixture. DO NOT EDIT.
package scenario
import "m/pkg/transports/cli/clihttp"
func generated() { clihttp.NewProtocol() }
`
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/tests/functional/scenario", "m/tests/functional/internal/support")
}

func TestTestBoundaryFunctionalTransportAllowances(t *testing.T) {
	useFixtures(t)
	files := functionalTransportFixtures()
	allowed := `import (
 "m/pkg/transports/cli/clihttp"
 "m/pkg/services/work/transports/cli/submit"
)
func allowed() { clihttp.NewProtocol(); submit.NewSubmit() }
`
	for path, pkg := range map[string]string{
		"m/pkg/services/work/transports/cli/submit/protocol_test.go": "submit_test",
		"m/pkg/transports/cli/clihttp/protocol_test.go":              "clihttp_test",
		"m/internal/testutil/support.go":                             "testutil",
		"m/tests/functionality/scenario_test.go":                     "functionality",
	} {
		files[path] = "package " + pkg + "\n" + allowed
	}
	files["m/tests/functional/scenario/scenario_test.go"] = `package scenario
import (
 "m/pkg/root"
 "m/pkg/transports/http/generated"
 "m/pkg/transports/http/client"
 "m/pkg/transports/cli/clihttp"
 "m/pkg/services/work/transports/cli/submit"
 "m/other/transports"
)
func allowed() {
 root.BuildProcess(); generated.NewPublicValue(); client.NewClient()
 clihttp.Observe(); submit.NewOther(); transports.NewProtocol()
 var detached clihttp.NewValue
 _ = detached; _ = clihttp.NewVersion; _ = clihttp.NewSetting
}
`
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/tests/functional/scenario", "m/pkg/services/work/transports/cli/submit", "m/pkg/transports/cli/clihttp", "m/internal/testutil", "m/tests/functionality")
}

func TestTestBoundaryWorkInvocationCallback(t *testing.T) {
	useFixtures(t)
	source := `package callbacks
type fake struct { prepare func(int) int }
func (f fake) PrepareInvocationInput(request int) int { return f.prepare(request) }
type pointer struct { prepare func(int) int }
func (f *pointer) PrepareInvocationInput(request int) int { return f.prepare(request) }
type policy struct{}
func (policy) PrepareInvocationInput(request int) int { return request + 1 } // want "test-work-invocation-policy.*PrepareInvocationInput"
type branching struct { prepare func(int) int }
func (f branching) PrepareInvocationInput(request int) int { // want "test-work-invocation-policy"
 if request == 0 { return 1 }; return f.prepare(request)
}
type transformed struct { prepare func(int) int }
func (f transformed) PrepareInvocationInput(request int) int { return f.prepare(request + 1) } // want "test-work-invocation-policy"
type detached struct { prepare func(int) int }
var other = fake{}
func (f detached) PrepareInvocationInput(request int) int { return other.prepare(request) } // want "test-work-invocation-policy"
type indirect struct { prepare func(int) int }
func (f indirect) PrepareInvocationInput(request int) int { // want "test-work-invocation-policy"
 callback := f.prepare; return callback(request)
}
func PrepareInvocationInput(request int) int { return request } // want "test-work-invocation-policy"
`
	files := map[string]string{
		"m/pkg/transports/http/callbacks_test.go": source,
		"m/pkg/transports/cli/external_test.go":   strings.Replace(source, "package callbacks", "package cli_test", 1),
		"m/internal/testutil/callbacks.go":        strings.ReplaceAll(source, ` // want "test-work-invocation-policy`, ` // unrelated "test-work-invocation-policy`),
	}
	clean := strings.ReplaceAll(source, ` // want "test-work-invocation-policy`, ` // unrelated "test-work-invocation-policy`)
	files["m/pkg/transports/http/production/production.go"] = clean
	files["m/pkg/transports/http/generated/generated_test.go"] = "// Code generated by fixture. DO NOT EDIT.\n" + clean
	files["m/pkg/services/work/callbacks_test.go"] = clean
	dir, cleanup, err := analysistest.WriteFiles(files)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanup()
	analysistest.Run(t, dir, TestBoundary, "m/pkg/transports/http", "m/pkg/transports/cli", "m/pkg/transports/http/generated", "m/pkg/transports/http/production", "m/pkg/services/work", "m/internal/testutil")
}

func functionalTransportFixtures() map[string]string {
	return map[string]string{
		"m/pkg/transports/cli/clihttp/protocol.go": `package clihttp
func NewProtocol() {}
func Observe() {}
type NewValue int
const NewVersion = 1
var NewSetting = 1
var BuildVariable = func() {}
type Lookalike struct{}
func (Lookalike) NewProtocol() {}
`,
		"m/pkg/transports/mapping/factoryconfig/mapper.go": `package factoryconfig
func NewFactoryConfigMapper() {}
func BuildMapper() {}
func CreateMapper() {}
`,
		"m/pkg/services/work/transports/cli/submit/submit.go": `package submit
func NewSubmit() {}
func NewOther() {}
`,
		"m/pkg/transports/http/generated/client.go":    "package generated\nfunc NewPublicValue() {}\n",
		"m/pkg/transports/http/client/client.go":       "package client\nfunc NewClient() {}\n",
		"m/pkg/transports/http/client/child/client.go": "package child\nfunc NewClient() {}\n",
		"m/pkg/root/process.go":                        "package root\nfunc BuildProcess() {}\n",
		"m/other/transports/protocol.go":               "package transports\nfunc NewProtocol() {}\n",
	}
}
