package discoverygen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/portpowered/infinite-you/internal/contractjoiner"
)

const (
	// DiscoveryJSONPath is the generated MCP discovery metadata artifact.
	DiscoveryJSONPath = "pkg/transports/mcp/generated/discovery.json"
	// DiscoveryGoPath is the generated runtime MCP discovery metadata surface.
	DiscoveryGoPath = "pkg/transports/mcp/generated/discovery.gen.go"
)

// DiscoveryArtifact returns deterministic generated MCP discovery metadata bytes.
func DiscoveryArtifact(repositoryRoot string) ([]byte, error) {
	metadata, err := discoveryMetadata(repositoryRoot)
	if err != nil {
		return nil, err
	}
	return contractjoiner.MarshalCanonicalJSON(metadata)
}

// DiscoveryGoArtifact returns deterministic generated Go discovery metadata.
func DiscoveryGoArtifact(repositoryRoot string) ([]byte, error) {
	metadata, err := discoveryMetadata(repositoryRoot)
	if err != nil {
		return nil, err
	}

	ids := make([]string, 0, len(metadata.Tools))
	for id := range metadata.Tools {
		ids = append(ids, id)
	}
	slices.Sort(ids)

	var source strings.Builder
	source.WriteString("// Code generated by mcpdiscoverygen. DO NOT EDIT.\n\n")
	source.WriteString("package generated\n\n")
	source.WriteString("import \"encoding/json\"\n\n")
	source.WriteString("// DiscoveryTool is one canonical generated MCP tools/list descriptor.\n")
	source.WriteString("type DiscoveryTool struct {\n\tID string\n\tName string\n\tDescription string\n\tInputSchema json.RawMessage\n}\n\n")
	source.WriteString("// PrimaryDiscovery returns canonical generated discovery in stable tool-ID order.\n")
	source.WriteString("func PrimaryDiscovery() []DiscoveryTool {\n\treturn []DiscoveryTool{\n")
	for _, id := range ids {
		tool := metadata.Tools[id]
		schema, marshalErr := contractjoiner.MarshalCanonicalJSON(tool.InputSchema)
		if marshalErr != nil {
			return nil, fmt.Errorf("marshal input schema for %s: %w", id, marshalErr)
		}
		fmt.Fprintf(&source, "\t\t{ID: %s, Name: %s, Description: %s, InputSchema: json.RawMessage(%s)},\n",
			strconv.Quote(tool.ID), strconv.Quote(tool.Name), strconv.Quote(tool.Description), strconv.Quote(string(schema)))
	}
	source.WriteString("\t}\n}\n")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated Go discovery metadata: %w", err)
	}
	return formatted, nil
}

func discoveryMetadata(repositoryRoot string) (DiscoveryMetadata, error) {
	resolved, err := LoadResolvedCatalog(repositoryRoot)
	if err != nil {
		return DiscoveryMetadata{}, err
	}
	metadata, err := ProjectDiscoveryFromCatalogDocument(resolved)
	if err != nil {
		return DiscoveryMetadata{}, err
	}
	if err := VerifyDiscoveryByteStability(metadata); err != nil {
		return DiscoveryMetadata{}, err
	}
	return metadata, nil
}

// Generate writes MCP discovery metadata artifacts for review and drift checks.
func Generate(repositoryRoot string) error {
	artifacts := []struct {
		path     string
		producer func(string) ([]byte, error)
	}{
		{path: DiscoveryJSONPath, producer: DiscoveryArtifact},
		{path: DiscoveryGoPath, producer: DiscoveryGoArtifact},
	}
	for _, artifact := range artifacts {
		if err := writeArtifact(repositoryRoot, artifact.path, artifact.producer); err != nil {
			return err
		}
	}
	return nil
}

// Drift describes byte-level differences between generated artifacts and the
// current generator output.
type Drift struct {
	Stale      []string
	Missing    []string
	Unexpected []string
}

// Empty reports whether generated artifacts match the generator output.
func (drift Drift) Empty() bool {
	return len(drift.Stale) == 0 && len(drift.Missing) == 0 && len(drift.Unexpected) == 0
}

// Check compares committed MCP discovery artifacts with freshly generated output.
func Check(repositoryRoot string) (Drift, error) {
	artifacts := []struct {
		path     string
		producer func(string) ([]byte, error)
	}{
		{path: DiscoveryJSONPath, producer: DiscoveryArtifact},
		{path: DiscoveryGoPath, producer: DiscoveryGoArtifact},
	}
	drift := Drift{}
	for _, artifact := range artifacts {
		payload, err := artifact.producer(repositoryRoot)
		if err != nil {
			return Drift{}, err
		}
		target := filepath.Join(repositoryRoot, filepath.FromSlash(artifact.path))
		got, err := os.ReadFile(target)
		if err != nil {
			if os.IsNotExist(err) {
				drift.Missing = append(drift.Missing, artifact.path)
				continue
			}
			return Drift{}, fmt.Errorf("read %s: %w", artifact.path, err)
		}
		if !bytes.Equal(normalizeGeneratedArtifactBytes(got), normalizeGeneratedArtifactBytes(payload)) {
			drift.Stale = append(drift.Stale, artifact.path)
		}
	}
	return drift, nil
}

func writeArtifact(repositoryRoot, path string, producer func(string) ([]byte, error)) error {
	payload, err := producer(repositoryRoot)
	if err != nil {
		return err
	}
	target := filepath.Join(repositoryRoot, filepath.FromSlash(path))
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	if err := os.WriteFile(target, payload, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func normalizeGeneratedArtifactBytes(payload []byte) []byte {
	return bytes.ReplaceAll(payload, []byte("\r\n"), []byte("\n"))
}
