package apiserver_test

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/portpowered/infinite-you/internal/testutil"
	"github.com/portpowered/infinite-you/internal/testutil/factoryfixtures"
	"github.com/portpowered/infinite-you/internal/testutil/validationassert"
	factoryconfig "github.com/portpowered/infinite-you/pkg/config"
	interfaces "github.com/portpowered/infinite-you/pkg/factory/contracts"
	factoryvalidation "github.com/portpowered/infinite-you/pkg/factory/validation"
	factoryapi "github.com/portpowered/infinite-you/pkg/transports/http/generated"
	apisurface "github.com/portpowered/infinite-you/pkg/transports/mapping"
	workerconfig "github.com/portpowered/infinite-you/pkg/workers/config"
)

func TestFactoryLayoutBoundary_ReturnsFieldSpecificHTTPValidationTargets(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		method   string
		path     string
		factory  string
		wantCode string
		wantPath string
	}{
		{
			name:     "save rejects non-strict base64 before generated byte decoding",
			method:   http.MethodPut,
			path:     "/factory-sessions/~default/factory",
			factory:  portableImageAnnotationFactoryJSON("AQI=\n", 120),
			wantCode: factoryvalidation.CodeLayoutInvalidValue,
			wantPath: "factory.layout.annotations[0].image.source.data",
		},
		{
			name:     "validation identifies empty alternative text",
			method:   http.MethodPost,
			path:     "/factory-validations",
			factory:  strings.Replace(portableImageAnnotationFactoryJSON("AQID", 120), `"alternativeText":"diagram"`, `"alternativeText":""`, 1),
			wantCode: factoryvalidation.CodeLayoutInvalidValue,
			wantPath: "factory.layout.annotations[0].image.alternativeText",
		},
		{
			name:     "validation identifies whitespace-only alternative text",
			method:   http.MethodPost,
			path:     "/factory-validations",
			factory:  strings.Replace(portableImageAnnotationFactoryJSON("AQID", 120), `"alternativeText":"diagram"`, `"alternativeText":"   "`, 1),
			wantCode: factoryvalidation.CodeLayoutInvalidValue,
			wantPath: "factory.layout.annotations[0].image.alternativeText",
		},
		{
			name:     "validation identifies whitespace-only note body",
			method:   http.MethodPost,
			path:     "/factory-validations",
			factory:  portableNoteAnnotationFactoryJSON("note-1", " \n\t "),
			wantCode: factoryvalidation.CodeLayoutInvalidValue,
			wantPath: "factory.layout.annotations[0].note.body",
		},
		{
			name:     "validation identifies whitespace-only empty-state text",
			method:   http.MethodPost,
			path:     "/factory-validations",
			factory:  portableNodeEmptyStateFactoryJSON("workstation:review", " \n\t "),
			wantCode: factoryvalidation.CodeLayoutInvalidValue,
			wantPath: "factory.layout.nodes[0].emptyState.text",
		},
		{
			name:     "validation identifies blank annotation id",
			method:   http.MethodPost,
			path:     "/factory-validations",
			factory:  strings.Replace(portableImageAnnotationFactoryJSON("AQID", 120), `"id":"image-1"`, `"id":""`, 1),
			wantCode: factoryvalidation.CodeLayoutInvalidValue,
			wantPath: "factory.layout.annotations[0].id",
		},
		{
			name:     "save identifies whitespace-only canonical node id",
			method:   http.MethodPut,
			path:     "/factory-sessions/~default/factory",
			factory:  portableNodeEmptyStateFactoryJSON("   ", "Nothing here"),
			wantCode: factoryvalidation.CodeLayoutInvalidValue,
			wantPath: "factory.layout.nodes[0].id",
		},
		{
			name:     "validation identifies zero width",
			method:   http.MethodPost,
			path:     "/factory-validations",
			factory:  portableImageAnnotationFactoryJSON("AQID", 0),
			wantCode: factoryvalidation.CodeLayoutInvalidGeometry,
			wantPath: "factory.layout.annotations[0].size.width",
		},
	}

	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			body := test.factory
			if test.method == http.MethodPut {
				body = saveFactoryForSessionRequestBody(test.factory)
			}
			assertLayoutBoundaryHTTPRejection(t, test.method, test.path, body, test.wantCode, test.wantPath)
		})
	}
}

func TestFactoryLayoutBoundary_RejectsOppositeVariantNullFields(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name, factory, wantPath string
	}{
		{
			name:     "note rejects null image field",
			factory:  strings.Replace(portableNoteAnnotationFactoryJSON("note-1", "safe"), `"note":`, `"image":null,"note":`, 1),
			wantPath: "factory.layout.annotations[0].image",
		},
		{
			name:     "image rejects null note field",
			factory:  strings.Replace(portableImageAnnotationFactoryJSON("AQID", 120), `"image":`, `"note":null,"image":`, 1),
			wantPath: "factory.layout.annotations[0].note",
		},
	}

	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			assertLayoutBoundaryHTTPRejection(
				t, http.MethodPost, "/factory-validations", test.factory,
				factoryvalidation.CodeLayoutInvalidValue, test.wantPath,
			)
		})
	}
}

func TestFactoryLayoutBoundary_AcceptsValidAnnotationVariants(t *testing.T) {
	t.Parallel()

	for _, factory := range []string{
		portableNoteAnnotationFactoryJSON("note-1", "safe"),
		portableImageAnnotationFactoryJSON("AQID", 120),
	} {
		req := httptest.NewRequest(http.MethodPost, "/factory-validations", bytes.NewBufferString(factory))
		req.Header.Set("Content-Type", "application/json")
		rec := httptest.NewRecorder()
		newAPITestServer(&testutil.MockFactory{}).Handler().ServeHTTP(rec, req)

		if rec.Code != http.StatusOK {
			t.Fatalf("status = %d, want 200: %s", rec.Code, rec.Body.String())
		}
		result := decodeJSONResponse[factoryapi.FactoryValidationResult](t, rec)
		if len(result.Targets) != 0 {
			t.Fatalf("targets = %#v, want valid annotation", result.Targets)
		}
	}
}

func TestValidateFactory_ReturnsFieldSpecificTotalImageBudgetTarget(t *testing.T) {
	t.Parallel()

	decoded := make([]byte, 2*1024*1024)
	encoded := base64.StdEncoding.EncodeToString(decoded)
	annotations := make([]string, 5)
	for index := range annotations {
		annotations[index] = fmt.Sprintf(`{
			"id":"image-%d","kind":"IMAGE","position":{"x":%d,"y":0},"size":{"width":120,"height":80},
			"image":{"alternativeText":"diagram","source":{"kind":"EMBEDDED","mediaType":"image/png","data":%q}}
		}`, index, index*140, encoded)
	}
	factory := fmt.Sprintf(`{"name":"layout-factory","layout":{"schemaVersion":1,"annotations":[%s]}}`, strings.Join(annotations, ","))
	assertLayoutBoundaryHTTPRejection(
		t,
		http.MethodPost,
		"/factory-validations",
		factory,
		factoryvalidation.CodeLayoutImageBudgetExceeded,
		"factory.layout.annotations[4].image.source.data",
	)
}

func assertLayoutBoundaryHTTPRejection(t *testing.T, method, path, body, wantCode, wantPath string) {
	t.Helper()
	srv := newAPITestServer(&testutil.MockFactory{})
	req := httptest.NewRequest(method, path, bytes.NewBufferString(body))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	response := decodeJSONResponse[factoryapi.ErrorResponse](t, rec)
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400: %s", rec.Code, rec.Body.String())
	}
	if response.Targets == nil || len(*response.Targets) != 1 {
		t.Fatalf("targets = %#v, want one field-specific layout target", response.Targets)
	}
	target := (*response.Targets)[0]
	if target.Code != wantCode || target.Path == nil || *target.Path != wantPath {
		t.Fatalf("target = %#v, want code %q path %q", target, wantCode, wantPath)
	}
}

func portableImageAnnotationFactoryJSON(data string, width int) string {
	return fmt.Sprintf(`{
		"name":"layout-factory",
		"layout":{"schemaVersion":1,"annotations":[{
			"id":"image-1","kind":"IMAGE","position":{"x":0,"y":0},"size":{"width":%d,"height":80},
			"image":{"alternativeText":"diagram","source":{"kind":"EMBEDDED","mediaType":"image/png","data":%q}}
		}],"viewport":{"x":0,"y":0,"zoom":1},"preferences":{"direction":"RIGHT"}}
	}`, width, data)
}

func portableNoteAnnotationFactoryJSON(id, body string) string {
	return fmt.Sprintf(`{
		"name":"layout-factory",
		"layout":{"schemaVersion":1,"annotations":[{
			"id":%q,"kind":"NOTE","position":{"x":0,"y":0},
			"note":{"body":%q,"tone":"NEUTRAL"}
		}],"viewport":{"x":0,"y":0,"zoom":1},"preferences":{"direction":"RIGHT"}}
	}`, id, body)
}

func portableNodeEmptyStateFactoryJSON(id, text string) string {
	return fmt.Sprintf(`{
		"name":"layout-factory",
		"layout":{"schemaVersion":1,"nodes":[{
			"id":%q,"position":{"x":0,"y":0},"emptyState":{"text":%q}
		}]}
	}`, id, text)
}

func TestFactoryValidation_EquivalentCanonicalTargetsAcrossPackageConfigAndAPIPaths(t *testing.T) {
	t.Parallel()

	factory, err := factoryfixtures.DecodeCrossPathInvalidFactory()
	if err != nil {
		t.Fatalf("DecodeCrossPathInvalidFactory: %v", err)
	}
	cfg, err := factoryconfig.FactoryConfigFromOpenAPI(factory)
	if err != nil {
		t.Fatalf("FactoryConfigFromOpenAPI: %v", err)
	}

	explicit := factoryvalidation.Validate(&cfg)
	packageSignatures := factoryvalidation.CanonicalTargetSignatures(explicit.Targets)

	configFindings := factoryconfig.CanonicalStructuralFindings(&cfg)
	if len(configFindings) != len(explicit.Targets) {
		t.Fatalf("config findings = %d, package targets = %d, want equivalent coverage",
			len(configFindings), len(explicit.Targets))
	}
	for index, target := range explicit.Targets {
		if configFindings[index].Rule != target.Code {
			t.Fatalf("config finding[%d].Rule = %q, want package target code %q",
				index, configFindings[index].Rule, target.Code)
		}
	}

	srv := newAPITestServer(&testutil.MockFactory{})
	req := httptest.NewRequest(
		http.MethodPost,
		"/factory-validations",
		bytes.NewBufferString(factoryfixtures.CrossPathInvalidFactoryJSON),
	)
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("POST /factory-validations status = %d, want 200: %s", rec.Code, rec.Body.String())
	}

	result := decodeJSONResponse[factoryapi.FactoryValidationResult](t, rec)
	apiSignatures := validationassert.CanonicalAPITargetSignatures(result.Targets)
	if !factoryvalidation.EquivalentCanonicalTargetSignatures(packageSignatures, apiSignatures) {
		t.Fatalf("package signatures = %#v, api signatures = %#v, want equivalent canonical targets",
			packageSignatures, apiSignatures)
	}
}

func TestValidateFactory_OperationalCronRulesRemainConfigScoped(t *testing.T) {
	srv := newAPITestServer(&testutil.MockFactory{})

	body := `{
		"name":"alpha",
		"workTypes":[{"name":"task","states":[{"name":"init","type":"INITIAL"},{"name":"done","type":"TERMINAL"}]}],
		"workers":[{"name":"w1"}],
		"workstations":[{
			"name":"daily-refresh",
			"behavior":"CRON",
			"worker":"w1",
			"outputs":[{"workType":"task","state":"init"}]
		}]
	}`

	req := httptest.NewRequest(http.MethodPost, "/factory-validations", bytes.NewBufferString(body))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rec.Code, rec.Body.String())
	}

	result := decodeJSONResponse[factoryapi.FactoryValidationResult](t, rec)
	for _, target := range result.Targets {
		if target.Code == "cron-config" || target.Code == "cron-schedule" {
			t.Fatalf("validation-only API targets = %#v, want operational cron rules to stay config-scoped", result.Targets)
		}
	}

	cfg := &interfaces.FactoryConfig{
		WorkTypes: []interfaces.WorkTypeConfig{{
			Name: "task",
			States: []interfaces.StateConfig{
				{Name: "init", Type: interfaces.StateTypeInitial},
				{Name: "done", Type: interfaces.StateTypeTerminal},
			},
		}},
		Workers: []workerconfig.Config{{Name: "w1"}},
		Workstations: []interfaces.FactoryWorkstationConfig{{
			Name:           "daily-refresh",
			Kind:           interfaces.WorkstationKindCron,
			WorkerTypeName: "w1",
			Outputs:        []interfaces.IOConfig{{WorkTypeName: "task", StateName: "init"}},
		}},
	}
	configFindings := factoryconfig.NewConfigValidator().Validate(cfg).Findings
	assertConfigFindingRule(t, configFindings, "cron-config")
}

func TestValidateFactory_RejectsDuplicateDefaultHandlingWorkTypes(t *testing.T) {
	t.Parallel()

	srv := newAPITestServer(&testutil.MockFactory{})
	body := `{
		"name":"alpha",
		"workTypes":[
			{"name":"story","handlingBehavior":["DEFAULT"],"states":[
				{"name":"queued","type":"INITIAL"},
				{"name":"done","type":"TERMINAL"}
			]},
			{"name":"task","handlingBehavior":["DEFAULT"],"states":[
				{"name":"queued","type":"INITIAL"},
				{"name":"done","type":"TERMINAL"}
			]}
		],
		"workers":[{"name":"worker-a"}],
		"workstations":[{
			"name":"process",
			"worker":"worker-a",
			"inputs":[{"workType":"story","state":"queued"}],
			"outputs":[{"workType":"story","state":"done"}]
		}]
	}`

	req := httptest.NewRequest(http.MethodPost, "/factory-validations", bytes.NewBufferString(body))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rec.Code, rec.Body.String())
	}

	result := decodeJSONResponse[factoryapi.FactoryValidationResult](t, rec)
	assertHasValidationTargetCode(t, result.Targets, factoryvalidation.CodeWorkTypeHandlingBehaviorUniqueDefault)
	for _, target := range result.Targets {
		if target.Code == factoryvalidation.CodeWorkTypeHandlingBehaviorUniqueDefault &&
			!strings.Contains(target.Message, "handlingBehavior DEFAULT") {
			t.Fatalf("target message = %q, want duplicate default handling explanation", target.Message)
		}
	}
}

func TestValidateFactory_RejectsResourceSlotAuthoredAsWorkstationRoute(t *testing.T) {
	t.Parallel()

	srv := newAPITestServer(&testutil.MockFactory{})
	body := `{
		"name":"alpha",
		"resources":[{"name":"executor-slot","capacity":10}],
		"workTypes":[{"name":"task","states":[
			{"name":"init","type":"INITIAL"},
			{"name":"done","type":"TERMINAL"}
		]}],
		"workers":[{"name":"processor"}],
		"workstations":[{
			"name":"process",
			"worker":"processor",
			"inputs":[
				{"workType":"task","state":"init"},
				{"workType":"executor-slot","state":"available"}
			],
			"outputs":[{"workType":"task","state":"done"}]
		}]
	}`

	req := httptest.NewRequest(http.MethodPost, "/factory-validations", bytes.NewBufferString(body))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rec.Code, rec.Body.String())
	}

	result := decodeJSONResponse[factoryapi.FactoryValidationResult](t, rec)
	assertHasValidationTargetCode(t, result.Targets, factoryvalidation.CodeDanglingPlaceReference)
	assertHasValidationTarget(
		t,
		result.Targets,
		factoryvalidation.CodeDanglingPlaceReference,
		factoryapi.FactoryValidationSubjectTypeRoute,
		"process->executor-slot:available",
		factoryapi.FactoryValidationSubjectLocationInputs,
		`resource slot route target`,
	)
}

func TestValidateFactory_PreservesCanonicalStructuralCodesFromCrossPathFixture(t *testing.T) {
	srv := newAPITestServer(&testutil.MockFactory{})

	req := httptest.NewRequest(
		http.MethodPost,
		"/factory-validations",
		bytes.NewBufferString(factoryfixtures.CrossPathInvalidFactoryJSON),
	)
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rec.Code, rec.Body.String())
	}

	result := decodeJSONResponse[factoryapi.FactoryValidationResult](t, rec)
	wantCodes := []string{
		factoryvalidation.CodeDuplicateIdentifier,
		factoryvalidation.CodeDanglingWorkerReference,
		factoryvalidation.CodeDanglingPlaceReference,
		factoryvalidation.CodeWorkstationMissingFailureRoute,
		factoryvalidation.CodeWorkTypeMissingCompletionState,
		factoryvalidation.CodeWorkTypeMissingFailureState,
		factoryvalidation.CodeWorkStateMissingTerminalPath,
	}
	for _, code := range wantCodes {
		assertHasValidationTargetCode(t, result.Targets, code)
	}
}

func TestValidateFactory_RejectsInvalidInvocationSignature(t *testing.T) {
	t.Parallel()

	srv := newAPITestServer(&testutil.MockFactory{})
	body := `{
		"name":"signature-invalid",
		"invocationSignature":{
			"unknownNamedArgumentPolicy":"COLLECT",
			"parameters":[
				{
					"name":"items",
					"externalName":"items",
					"valueMode":"REPEATED",
					"bindings":[{"kind":"NAMED"}]
				}
			],
			"outputContract":{
				"mode":"FILE",
				"pathParameter":"missing-output"
			}
		},
		"workTypes":[{"name":"task","states":[
			{"name":"queued","type":"INITIAL"},
			{"name":"done","type":"TERMINAL"},
			{"name":"failed","type":"FAILED"}
		]}],
		"workers":[{"name":"worker-a","type":"INFERENCE_WORKER","model":"${missing}"}],
		"workstations":[{
			"name":"process",
			"worker":"worker-a",
			"inputs":[{"workType":"task","state":"queued"}],
			"outputs":[{"workType":"task","state":"done"}],
			"onFailure":[{"workType":"task","state":"failed"}],
			"body":"Use ${items}"
		}]
	}`

	req := httptest.NewRequest(http.MethodPost, "/factory-validations", bytes.NewBufferString(body))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rec.Code, rec.Body.String())
	}

	result := decodeJSONResponse[factoryapi.FactoryValidationResult](t, rec)
	assertHasValidationTargetCode(t, result.Targets, factoryvalidation.CodeInvocationSignatureUnknownOutputPathParameter)
	assertHasValidationTargetCode(t, result.Targets, factoryvalidation.CodeInvocationSignatureInvalidInterpolationReference)
	assertHasValidationTargetCode(t, result.Targets, factoryvalidation.CodeInvocationSignatureIncompatibleInterpolationReference)
}

func assertConfigFindingRule(t *testing.T, findings []factoryconfig.Finding, rule string) {
	t.Helper()
	for _, finding := range findings {
		if finding.Rule == rule {
			return
		}
	}
	t.Fatalf("expected config finding rule %q, got %#v", rule, findings)
}

func TestSaveCurrentFactory_ReturnsMultipleTopologyValidationTargets(t *testing.T) {
	targets := []factoryapi.FactoryValidationTarget{
		{
			Code:     factoryvalidation.CodeDuplicateIdentifier,
			Severity: factoryapi.FactoryValidationSeverityError,
			Message:  `duplicate worker identifier "worker-a".`,
			Subject: factoryapi.FactoryValidationSubject{
				Type:     factoryapi.FactoryValidationSubjectTypeWorker,
				Id:       "worker-a",
				Location: factoryapi.FactoryValidationSubjectLocationDefinition,
			},
		},
		{
			Code:     factoryvalidation.CodeDanglingWorkerReference,
			Severity: factoryapi.FactoryValidationSeverityError,
			Message:  `workstation "process" references unknown worker "missing-worker".`,
			Subject: factoryapi.FactoryValidationSubject{
				Type:     factoryapi.FactoryValidationSubjectTypeWorkstation,
				Id:       "process",
				Location: factoryapi.FactoryValidationSubjectLocationDefinition,
			},
		},
		{
			Code:     factoryvalidation.CodeDanglingPlaceReference,
			Severity: factoryapi.FactoryValidationSeverityError,
			Message:  `workstation "process" routes to unknown place.`,
			Subject: factoryapi.FactoryValidationSubject{
				Type:     factoryapi.FactoryValidationSubjectTypeWorkstation,
				Id:       "process",
				Location: factoryapi.FactoryValidationSubjectLocationOutputs,
			},
		},
	}
	srv := newAPITestServer(&testutil.MockFactory{
		SaveFactoryForSessionErr: apisurface.NewTopologyValidationError(
			"Factory topology contains invalid graph references.",
			targets,
		),
	})

	req := httptest.NewRequest(http.MethodPut, "/factory-sessions/~default/factory", bytes.NewBufferString(saveFactoryForSessionRequestBody(`{"name":"beta"}`)))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	response := decodeJSONResponse[factoryapi.ErrorResponse](t, rec)
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", rec.Code)
	}
	assertErrorResponsePreservesLegacyFields(
		t,
		response,
		factoryapi.ErrorResponseCodeINVALIDFACTORY,
		factoryapi.ErrorFamilyBadRequest,
		"Factory payload is not a valid Agent Factory definition.",
	)
	if response.Targets == nil || len(*response.Targets) < 3 {
		t.Fatalf("targets = %#v, want multiple blocking validation targets", response.Targets)
	}
	assertHasValidationTargetCode(t, *response.Targets, factoryvalidation.CodeDuplicateIdentifier)
	assertHasValidationTargetCode(t, *response.Targets, factoryvalidation.CodeDanglingWorkerReference)
	assertHasValidationTargetCode(t, *response.Targets, factoryvalidation.CodeDanglingPlaceReference)
	assertBlockingValidationTarget(t, (*response.Targets)[0])
}

func TestUpsertNamedFactory_ReturnsTopologyValidationTargets(t *testing.T) {
	target := factoryapi.FactoryValidationTarget{
		Code:     factoryvalidation.CodeDanglingPlaceReference,
		Severity: factoryapi.FactoryValidationSeverityError,
		Message:  "workstation process routes to unknown place.",
		Subject: factoryapi.FactoryValidationSubject{
			Type:     factoryapi.FactoryValidationSubjectTypeWorkstation,
			Id:       "process",
			Location: factoryapi.FactoryValidationSubjectLocationOutputs,
		},
	}
	srv := newAPITestServer(&testutil.MockFactory{
		SaveFactoryForSessionErr: apisurface.NewTopologyValidationError(
			"Factory topology contains invalid graph references.",
			[]factoryapi.FactoryValidationTarget{target},
		),
	})

	req := httptest.NewRequest(http.MethodPut, "/factory-sessions/~default/factory", bytes.NewBufferString(upsertNamedFactoryRequestBody(validNamedFactoryBody("beta", "beta-task"))))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	response := decodeJSONResponse[factoryapi.ErrorResponse](t, rec)
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", rec.Code)
	}
	assertErrorResponsePreservesLegacyFields(
		t,
		response,
		factoryapi.ErrorResponseCodeINVALIDFACTORY,
		factoryapi.ErrorFamilyBadRequest,
		"Factory payload is not a valid Agent Factory definition.",
	)
	if response.Targets == nil || len(*response.Targets) != 1 {
		t.Fatalf("targets = %#v, want one canonical target", response.Targets)
	}
	gotTarget := (*response.Targets)[0]
	assertBlockingValidationTarget(t, gotTarget)
	if gotTarget.Code != factoryvalidation.CodeDanglingPlaceReference ||
		gotTarget.Subject.Type != factoryapi.FactoryValidationSubjectTypeWorkstation ||
		gotTarget.Subject.Id != "process" ||
		gotTarget.Subject.Location != factoryapi.FactoryValidationSubjectLocationOutputs {
		t.Fatalf("error target = %#v, want dangling output workstation target", gotTarget)
	}
}

func TestUpsertNamedFactory_RejectsInvalidFactoryPayloadWithTargets(t *testing.T) {
	srv := newAPITestServer(&testutil.MockFactory{SaveFactoryForSessionErr: apisurface.ErrInvalidNamedFactory})
	body := `{"name":"beta","workTypes":[{"name":"beta-task","states":[{"name":"init","type":"INITIAL"},{"name":"done","type":"TERMINAL"}]}],"workers":[{"name":"planner","type":"MODEL_WORKER","modelProvider":"CLAUDE","executorProvider":"SCRIPT_WRAP","model":"claude-sonnet-4-20250514"}],"workstations":[{"name":"plan-task","behavior":"STANDARD","type":"MODEL_WORKSTATION","worker":"missing-worker","inputs":[{"workType":"beta-task","state":"init"}],"outputs":[{"workType":"beta-task","state":"done"}]}]}`
	req := httptest.NewRequest(http.MethodPut, "/factory-sessions/~default/factory", bytes.NewBufferString(upsertNamedFactoryRequestBody(body)))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	response := decodeJSONResponse[factoryapi.ErrorResponse](t, rec)
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", rec.Code)
	}
	assertErrorResponsePreservesLegacyFields(
		t,
		response,
		factoryapi.ErrorResponseCodeINVALIDFACTORY,
		factoryapi.ErrorFamilyBadRequest,
		"Factory payload is not a valid Agent Factory definition.",
	)
	if response.Targets == nil || len(*response.Targets) != 1 || (*response.Targets)[0].Code != factoryvalidation.CodeFactoryPayloadInvalid {
		t.Fatalf("error targets = %#v, want canonical invalid factory payload target", response.Targets)
	}
	assertBlockingValidationTarget(t, (*response.Targets)[0])
}

func TestSaveCurrentFactory_ReturnsBobWorkstationOnFailureTarget(t *testing.T) {
	target := factoryapi.FactoryValidationTarget{
		Code:     factoryvalidation.CodeWorkstationMissingFailureRoute,
		Severity: factoryapi.FactoryValidationSeverityError,
		Message:  `workstation "bob" must define a failure route.`,
		Subject: factoryapi.FactoryValidationSubject{
			Type:     factoryapi.FactoryValidationSubjectTypeWorkstation,
			Id:       "bob",
			Location: factoryapi.FactoryValidationSubjectLocationOnFailure,
		},
	}
	srv := newAPITestServer(&testutil.MockFactory{
		SaveFactoryForSessionErr: apisurface.NewTopologyValidationError(
			"Factory topology contains invalid graph references.",
			[]factoryapi.FactoryValidationTarget{target},
		),
	})

	req := httptest.NewRequest(http.MethodPut, "/factory-sessions/~default/factory", bytes.NewBufferString(saveFactoryForSessionRequestBody(`{"name":"beta"}`)))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	response := decodeJSONResponse[factoryapi.ErrorResponse](t, rec)
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("response = %#v status=%d", response, rec.Code)
	}
	assertErrorResponsePreservesLegacyFields(
		t,
		response,
		factoryapi.ErrorResponseCodeINVALIDFACTORY,
		factoryapi.ErrorFamilyBadRequest,
		"Factory payload is not a valid Agent Factory definition.",
	)
	if response.Targets == nil || len(*response.Targets) != 1 {
		t.Fatalf("targets = %#v, want one canonical target", response.Targets)
	}
	got := (*response.Targets)[0]
	assertBlockingValidationTarget(t, got)
	assertHasValidationTarget(
		t,
		[]factoryapi.FactoryValidationTarget{got},
		factoryvalidation.CodeWorkstationMissingFailureRoute,
		factoryapi.FactoryValidationSubjectTypeWorkstation,
		"bob",
		factoryapi.FactoryValidationSubjectLocationOnFailure,
		"bob ON_FAILURE target",
	)
}

func TestUpsertNamedFactory_ReturnsBobWorkstationOnFailureTarget(t *testing.T) {
	target := factoryapi.FactoryValidationTarget{
		Code:     factoryvalidation.CodeWorkstationMissingFailureRoute,
		Severity: factoryapi.FactoryValidationSeverityError,
		Message:  `workstation "bob" must define a failure route.`,
		Subject: factoryapi.FactoryValidationSubject{
			Type:     factoryapi.FactoryValidationSubjectTypeWorkstation,
			Id:       "bob",
			Location: factoryapi.FactoryValidationSubjectLocationOnFailure,
		},
	}
	srv := newAPITestServer(&testutil.MockFactory{
		SaveFactoryForSessionErr: apisurface.NewTopologyValidationError(
			"Factory topology contains invalid graph references.",
			[]factoryapi.FactoryValidationTarget{target},
		),
	})

	req := httptest.NewRequest(http.MethodPut, "/factory-sessions/~default/factory", bytes.NewBufferString(upsertNamedFactoryRequestBody(validNamedFactoryBody("beta", "beta-task"))))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)

	response := decodeJSONResponse[factoryapi.ErrorResponse](t, rec)
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("response = %#v status=%d", response, rec.Code)
	}
	assertErrorResponsePreservesLegacyFields(
		t,
		response,
		factoryapi.ErrorResponseCodeINVALIDFACTORY,
		factoryapi.ErrorFamilyBadRequest,
		"Factory payload is not a valid Agent Factory definition.",
	)
	if response.Targets == nil || len(*response.Targets) != 1 {
		t.Fatalf("targets = %#v, want one canonical target", response.Targets)
	}
	got := (*response.Targets)[0]
	assertBlockingValidationTarget(t, got)
	assertHasValidationTarget(
		t,
		[]factoryapi.FactoryValidationTarget{got},
		factoryvalidation.CodeWorkstationMissingFailureRoute,
		factoryapi.FactoryValidationSubjectTypeWorkstation,
		"bob",
		factoryapi.FactoryValidationSubjectLocationOnFailure,
		"bob ON_FAILURE target",
	)
}

func assertErrorResponsePreservesLegacyFields(
	t *testing.T,
	response factoryapi.ErrorResponse,
	wantCode factoryapi.ErrorResponseCode,
	wantFamily factoryapi.ErrorFamily,
	wantMessage string,
) {
	t.Helper()
	if response.Code != wantCode {
		t.Fatalf("error code = %q, want %q", response.Code, wantCode)
	}
	if response.Family != wantFamily {
		t.Fatalf("error family = %q, want %q", response.Family, wantFamily)
	}
	if response.Message != wantMessage {
		t.Fatalf("error message = %q, want %q", response.Message, wantMessage)
	}
}

func assertBlockingValidationTarget(t *testing.T, target factoryapi.FactoryValidationTarget) {
	t.Helper()
	if target.Severity != factoryapi.FactoryValidationSeverityError {
		t.Fatalf("target severity = %q, want error", target.Severity)
	}
	if target.Code == "" {
		t.Fatal("target code is empty, want stable validation code")
	}
	if target.Message == "" {
		t.Fatal("target message is empty, want human-readable validation message")
	}
	if target.Subject.Type == "" || target.Subject.Location == "" {
		t.Fatalf("target subject = %#v, want structured type and location", target.Subject)
	}
	if target.Subject.Type != factoryapi.FactoryValidationSubjectTypeFactory && target.Subject.Id == "" {
		t.Fatalf("target subject = %#v, want non-empty id for component-scoped targets", target.Subject)
	}
}

func decodeJSONResponse[T any](t *testing.T, rec *httptest.ResponseRecorder) T {
	t.Helper()

	var out T
	if err := json.NewDecoder(rec.Body).Decode(&out); err != nil {
		t.Fatalf("decode JSON response: %v", err)
	}
	return out
}

func assertHasValidationTarget(
	t *testing.T,
	targets []factoryapi.FactoryValidationTarget,
	code string,
	subjectType factoryapi.FactoryValidationSubjectType,
	subjectID string,
	location factoryapi.FactoryValidationSubjectLocation,
	want string,
) {
	t.Helper()
	for _, target := range targets {
		if target.Code != code {
			continue
		}
		if target.Subject.Type != subjectType || target.Subject.Id != subjectID || target.Subject.Location != location {
			continue
		}
		return
	}
	t.Fatalf("validation targets = %#v, want %s", targets, want)
}

func assertHasValidationTargetCode(t *testing.T, targets []factoryapi.FactoryValidationTarget, code string) {
	t.Helper()
	for _, target := range targets {
		if target.Code == code {
			return
		}
	}
	t.Fatalf("targets = %#v, want code %q", targets, code)
}

func validNamedFactoryBody(name, workType string) string {
	return fmt.Sprintf(`{"name":%q,%s`, name, strings.TrimPrefix(namedFactoryPayloadJSON(name, workType), "{"))
}

func saveFactoryForSessionRequestBody(factoryJSON string) string {
	return fmt.Sprintf(`{"factory":%s}`, factoryJSON)
}

func upsertNamedFactoryRequestBody(factoryJSON string) string {
	return fmt.Sprintf(`{"mode":"UPSERT_NAMED_AND_ACTIVATE","factory":%s}`, factoryJSON)
}

func namedFactoryPayloadJSON(project, workType string) string {
	return fmt.Sprintf(`{
		"name": %q,
		"id": %q,
		"workTypes": [{
			"name": %q,
			"states": [
				{"name":"init","type":"INITIAL"},
				{"name":"done","type":"TERMINAL"},
				{"name":"failed","type":"FAILED"}
			]
		}],
		"workers": [{
			"name":"planner",
			"type":"MODEL_WORKER",
			"modelProvider":"CLAUDE",
			"executorProvider":"SCRIPT_WRAP",
			"model":"claude-sonnet-4-20250514"
		}],
		"workstations": [{
			"name":"plan-task",
			"behavior":"STANDARD",
			"type":"MODEL_WORKSTATION",
			"worker":"planner",
			"inputs":[{"workType":%q,"state":"init"}],
			"outputs":[{"workType":%q,"state":"done"}]
		}]
	}`, project, project, workType, workType, workType)
}
