// Package run implements the agent-factory run command behavior.
package run

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"strconv"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/portpowered/infinite-you/pkg/api"
	"github.com/portpowered/infinite-you/pkg/apisurface"
	"github.com/portpowered/infinite-you/pkg/cli/batchload"
	"github.com/portpowered/infinite-you/pkg/cli/clidiag"
	"github.com/portpowered/infinite-you/pkg/cli/dashboard"
	initcmd "github.com/portpowered/infinite-you/pkg/cli/init"
	"github.com/portpowered/infinite-you/pkg/cli/timedisplay"
	factoryconfig "github.com/portpowered/infinite-you/pkg/config"
	"github.com/portpowered/infinite-you/pkg/interfaces"
	"github.com/portpowered/infinite-you/pkg/logging"
	"github.com/portpowered/infinite-you/pkg/petri"
	"github.com/portpowered/infinite-you/pkg/service"
	"go.uber.org/zap"
)

// RunConfig holds parameters for the run command.
type RunConfig struct {
	Workflow     string
	Continuously bool
	WorkFile     string
	Dir          string
	// FactoryConfigPath is the factory.json file path from you run --factory.
	// The service uses Dir as the resolved factory root directory.
	FactoryConfigPath string
	RunnerID     string
	// ExecutionBaseDir overrides the base directory used to resolve relative
	// runtime execution paths. Empty defaults to the caller's current working
	// directory for CLI-style runs.
	ExecutionBaseDir string
	Bootstrap        bool
	// BindHost is the hostname from --server used in dashboard URLs (for example localhost or 127.0.0.1).
	BindHost string
	Port     int
	// AutoPort resolves Port to the next available local TCP port when the
	// preferred port is unavailable. Explicit port selections should leave this
	// false so operator intent is preserved.
	AutoPort   bool
	RecordPath string
	ReplayPath string
	// DisableDefaultRecording disables the default live-run replay artifact
	// generation for a single invocation.
	DisableDefaultRecording bool
	// RuntimeLogDir overrides the service-owned structured runtime log root.
	// Empty uses the service default under the user's home directory.
	RuntimeLogDir string
	// RuntimeLogConfig controls service-owned structured runtime log rotation.
	RuntimeLogConfig logging.RuntimeLogConfig
	// MockWorkersEnabled enables deterministic mock-worker execution. When
	// true and MockWorkersConfigPath is empty, the runtime uses the default
	// accept behavior for all worker dispatches.
	MockWorkersEnabled    bool
	MockWorkersConfigPath string
	Verbose               bool
	// SuppressDashboardRendering disables the simple stdout dashboard while
	// preserving the normal service-layer run path.
	SuppressDashboardRendering bool
	// OpenDashboard attempts to open the embedded dashboard URL in a browser.
	OpenDashboard bool
	// StartupOutput receives human-facing startup messages. Nil suppresses
	// startup output for programmatic callers and tests.
	StartupOutput io.Writer
	// Diagnostics receives metadata-only verbose command diagnostics. Nil
	// suppresses diagnostics for programmatic callers and tests.
	Diagnostics io.Writer
	Logger      *zap.Logger
}

type factoryServiceRunner interface {
	Run(ctx context.Context) error
}

type runtimeLogDiagnosticsProvider interface {
	RuntimeLogDiagnostics() service.RuntimeLogDiagnostics
}

var buildFactoryService = func(
	ctx context.Context,
	cfg *service.FactoryServiceConfig,
) (factoryServiceRunner, error) {
	return service.BuildFactoryService(ctx, cfg)
}

const (
	completedPlaceIDSuffix        = "completed"
	failedPlaceIDSuffix           = "failed"
	defaultRecordingsDir          = ".you-agent-factory/recordings"
	defaultFactorySessionID       = "~default"
	defaultRecordPathSessionToken = "__factory_session_id__"
)

var bootstrapFactory = func(dir string) error {
	resolvedDir, err := factoryconfig.ResolveCurrentFactoryDir(dir)
	if err != nil {
		if errors.Is(err, factoryconfig.ErrFactoryLayoutNotFound) {
			return initcmd.Init(initcmd.InitConfig{Dir: dir})
		}
		return err
	}

	defaultInputDir := filepath.Join(resolvedDir, interfaces.InputsDir, initcmd.DefaultFactoryInputType, interfaces.DefaultChannelName)
	return os.MkdirAll(defaultInputDir, 0o755)
}

var dashboardOpener = openURLInBrowser

var interactiveOutput = isInteractiveOutput
var defaultLiveRunRecordPath = generateDefaultLiveRunRecordPath
var defaultLiveRunRecordTime = time.Now
var defaultLiveRunRecordUUID = uuid.NewString

const dashboardReadyTimeout = 5 * time.Second
const maxAutoPortAttempts = 100

type reservedAPIServerListener struct {
	listener net.Listener
	port     int
	taken    bool
	mu       sync.Mutex
}

type resolvedRunRecordPath struct {
	servicePath   string
	reportedPath  string
	autoGenerated bool
}

var startAPIServer = func(
	ctx context.Context,
	runtime apisurface.APISurface,
	port int,
	logger *zap.Logger,
	markReady func(),
) error {
	addr := fmt.Sprintf(":%d", port)
	listener, err := net.Listen("tcp", addr)
	if err != nil {
		return err
	}
	return serveAPIServer(ctx, runtime, port, logger, markReady, listener)
}

func serveAPIServer(
	ctx context.Context,
	runtime apisurface.APISurface,
	port int,
	logger *zap.Logger,
	markReady func(),
	listener net.Listener,
) error {
	markReady()
	srv := api.NewServer(runtime, port, logger)
	return srv.Serve(ctx, listener)
}

func reserveAPIServerListener(port int, autoPort bool) (*reservedAPIServerListener, error) {
	if port <= 0 || !autoPort {
		return nil, nil
	}

	var firstErr error
	for candidate := port; candidate <= 65535 && candidate < port+maxAutoPortAttempts; candidate++ {
		listener, err := net.Listen("tcp", fmt.Sprintf(":%d", candidate))
		if err == nil {
			return &reservedAPIServerListener{
				listener: listener,
				port:     candidate,
			}, nil
		}
		if firstErr == nil {
			firstErr = err
		}
	}

	if firstErr == nil {
		firstErr = fmt.Errorf("invalid preferred port %d", port)
	}
	return nil, fmt.Errorf("resolve open API server port from %d: %w", port, firstErr)
}

func (r *reservedAPIServerListener) Port() int {
	if r == nil {
		return 0
	}
	return r.port
}

func (r *reservedAPIServerListener) Take() net.Listener {
	if r == nil {
		return nil
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.taken {
		return nil
	}
	r.taken = true
	return r.listener
}

func (r *reservedAPIServerListener) CloseIfUnused() error {
	if r == nil {
		return nil
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.taken {
		return nil
	}
	r.taken = true
	return r.listener.Close()
}

// Run loads a workflow from factory.json and starts the factory via
// FactoryService. The CLI is a thin wrapper — all orchestration logic
// (file watcher, dashboard, API server, engine) lives in the service layer.
func Run(ctx context.Context, cfg RunConfig) error {
	logger := cfg.Logger
	if logger == nil {
		logger = zap.NewNop()
	}
	if cfg.ExecutionBaseDir == "" {
		if workingDirectory, err := os.Getwd(); err == nil && workingDirectory != "" {
			cfg.ExecutionBaseDir = workingDirectory
		}
	}

	if cfg.Bootstrap {
		if err := bootstrapFactory(cfg.Dir); err != nil {
			return err
		}
	}

	recordPath, err := resolveRecordPathForRun(cfg)
	if err != nil {
		return err
	}
	cfg.RecordPath = recordPath.servicePath

	var mockWorkersConfig *factoryconfig.MockWorkersConfig
	if cfg.MockWorkersEnabled {
		loadedMockWorkersConfig, err := factoryconfig.LoadMockWorkersConfig(cfg.MockWorkersConfigPath)
		if err != nil {
			return err
		}
		mockWorkersConfig = loadedMockWorkersConfig
	}

	reservedAPIServer, err := reserveAPIServerListener(cfg.Port, cfg.AutoPort)
	if err != nil {
		return err
	}
	requestedPort := cfg.Port
	if reservedAPIServer != nil {
		defer func() {
			if err := reservedAPIServer.CloseIfUnused(); err != nil {
				logger.Warn("release reserved API server listener failed", zap.Error(err))
			}
		}()
		cfg.Port = reservedAPIServer.Port()
	}
	emitVerboseStartupDiagnostics(cfg, recordPath, requestedPort)

	dashboardReady := make(chan struct{})
	var dashboardReadyOnce sync.Once
	svcCfg := buildRunServiceConfig(cfg, logger, mockWorkersConfig, reservedAPIServer, dashboardReady, &dashboardReadyOnce)

	factorySvc, err := buildFactoryService(ctx, svcCfg)
	if err != nil {
		return err
	}

	shouldOpenDashboard := emitStartupMessages(cfg, runtimeLogDiagnosticsForRunner(factorySvc))
	waitForDashboardOpen := func() {}
	if shouldOpenDashboard {
		waitForDashboardOpen = openDashboardWhenServerReady(ctx, cfg, dashboardReady)
	}
	defer waitForDashboardOpen()

	err = factorySvc.Run(ctx)
	reportRecordingPathOnShutdown(cfg.StartupOutput, recordPath)
	return err
}

func resolveRecordPathForRun(cfg RunConfig) (resolvedRunRecordPath, error) {
	if cfg.DisableDefaultRecording && strings.TrimSpace(cfg.RecordPath) != "" {
		return resolvedRunRecordPath{}, fmt.Errorf("--no-record cannot be used with --record")
	}
	if strings.TrimSpace(cfg.RecordPath) != "" {
		return resolvedRunRecordPath{servicePath: cfg.RecordPath}, nil
	}
	if cfg.DisableDefaultRecording || strings.TrimSpace(cfg.ReplayPath) != "" {
		return resolvedRunRecordPath{}, nil
	}
	recordPath, err := defaultLiveRunRecordPath()
	if err != nil {
		return resolvedRunRecordPath{}, fmt.Errorf("resolve default replay record path: %w", err)
	}
	return resolvedRunRecordPath{
		servicePath:   recordPath,
		reportedPath:  resolveDefaultSessionRecordPath(recordPath),
		autoGenerated: true,
	}, nil
}

func generateDefaultLiveRunRecordPath() (string, error) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve user home: %w", err)
	}
	now := defaultLiveRunRecordTime()
	recordingID := fmt.Sprintf(
		"factory-session-%s-%s-%s.json",
		defaultRecordPathSessionToken,
		now.Format("150405"),
		defaultLiveRunRecordUUID(),
	)
	return filepath.Join(
		homeDir,
		defaultRecordingsDir,
		now.Format("2006-01"),
		now.Format("2006-01-02"),
		recordingID,
	), nil
}

func resolveDefaultSessionRecordPath(path string) string {
	if strings.TrimSpace(path) == "" {
		return ""
	}
	return strings.ReplaceAll(path, defaultRecordPathSessionToken, defaultFactorySessionID)
}

func runtimeModeForRun(cfg RunConfig) interfaces.RuntimeMode {
	if cfg.Continuously {
		return interfaces.RuntimeModeService
	}
	return interfaces.RuntimeModeBatch
}

func buildRunServiceConfig(
	cfg RunConfig,
	logger *zap.Logger,
	mockWorkersConfig *factoryconfig.MockWorkersConfig,
	reservedAPIServer *reservedAPIServerListener,
	dashboardReady chan struct{},
	dashboardReadyOnce *sync.Once,
) *service.FactoryServiceConfig {
	var apiServerReady chan struct{}
	if cfg.Port > 0 {
		apiServerReady = dashboardReady
	}
	svcCfg := &service.FactoryServiceConfig{
		Dir:               cfg.Dir,
		RunnerID:          cfg.RunnerID,
		ExecutionBaseDir:  cfg.ExecutionBaseDir,
		RuntimeMode:       runtimeModeForRun(cfg),
		Port:              cfg.Port,
		Logger:            logger,
		Verbose:           cfg.Verbose,
		WorkFile:          cfg.WorkFile,
		RecordPath:        cfg.RecordPath,
		ReplayPath:        cfg.ReplayPath,
		RuntimeLogDir:     cfg.RuntimeLogDir,
		RuntimeLogConfig:  cfg.RuntimeLogConfig,
		WorkflowID:        cfg.Workflow,
		MockWorkersConfig: mockWorkersConfig,
		APIServerStarter:  runAPIServerStarter(reservedAPIServer, dashboardReady, dashboardReadyOnce),
		APIServerReady:    apiServerReady,
	}
	if !cfg.SuppressDashboardRendering {
		svcCfg.SimpleDashboardRenderer = renderSimpleDashboard
	}
	return svcCfg
}

func emitVerboseStartupDiagnostics(cfg RunConfig, recordPath resolvedRunRecordPath, requestedPort int) {
	resolvedFactoryDir := resolveFactoryDirForDiagnostics(cfg.Dir)
	clidiag.Printf(
		cfg.Diagnostics,
		cfg.Verbose,
		"run startup factoryDir=%q configuredDir=%q runtimeMode=%s workflow=%q runnerOverride=%t mockWorkers=%t mockWorkersConfigPath=%q recording=%s runtimeLogDir=%q dashboardPort=%d requestedDashboardPort=%d autoPort=%s",
		resolvedFactoryDir,
		cfg.Dir,
		runtimeModeForRun(cfg),
		workflowLabel(cfg.Workflow),
		strings.TrimSpace(cfg.RunnerID) != "",
		cfg.MockWorkersEnabled,
		cfg.MockWorkersConfigPath,
		recordingDiagnostics(recordPath, cfg.ReplayPath),
		runtimeLogDirLabel(cfg.RuntimeLogDir),
		cfg.Port,
		requestedPort,
		autoPortDiagnostics(cfg.AutoPort, requestedPort, cfg.Port),
	)
}

func resolveFactoryDirForDiagnostics(dir string) string {
	resolved, err := factoryconfig.ResolveCurrentFactoryDir(dir)
	if err != nil {
		return "unresolved"
	}
	return resolved
}

func workflowLabel(workflow string) string {
	if strings.TrimSpace(workflow) == "" {
		return "all"
	}
	return workflow
}

func runtimeLogDirLabel(dir string) string {
	if strings.TrimSpace(dir) == "" {
		return "default"
	}
	return dir
}

func recordingDiagnostics(recordPath resolvedRunRecordPath, replayPath string) string {
	switch {
	case strings.TrimSpace(replayPath) != "":
		return "replay"
	case strings.TrimSpace(recordPath.servicePath) == "":
		return "disabled"
	case recordPath.autoGenerated:
		return "default"
	default:
		return "explicit"
	}
}

func autoPortDiagnostics(autoPort bool, requestedPort, resolvedPort int) string {
	switch {
	case requestedPort <= 0:
		return "dashboard-disabled"
	case !autoPort:
		return "disabled"
	case requestedPort == resolvedPort:
		return "preferred-available"
	default:
		return "fallback"
	}
}

func runAPIServerStarter(
	reservedAPIServer *reservedAPIServerListener,
	dashboardReady chan struct{},
	dashboardReadyOnce *sync.Once,
) service.APIServerStarter {
	markReady := func() {
		dashboardReadyOnce.Do(func() {
			close(dashboardReady)
		})
	}
	return func(ctx context.Context, runtime apisurface.APISurface, port int, l *zap.Logger) error {
		if reservedAPIServer != nil {
			listener := reservedAPIServer.Take()
			if listener == nil {
				return fmt.Errorf("reserved API server listener for port %d was already used", port)
			}
			return serveAPIServer(ctx, runtime, port, l, markReady, listener)
		}
		return startAPIServer(ctx, runtime, port, l, markReady)
	}
}

func renderSimpleDashboard(input service.SimpleDashboardRenderInput) {
	fmt.Print(dashboard.FormatSimpleDashboardWithRenderData(
		input.EngineState,
		input.RenderData,
		input.Now,
	))
}

func bindDashboardHost(cfg RunConfig) string {
	if strings.TrimSpace(cfg.BindHost) != "" {
		return cfg.BindHost
	}
	return "localhost"
}

// DashboardURL returns the embedded browser dashboard URL for the configured
// local factory server host and port.
func DashboardURL(host string, port int) string {
	if port <= 0 {
		return ""
	}
	if strings.TrimSpace(host) == "" {
		host = "localhost"
	}
	authority := net.JoinHostPort(host, strconv.Itoa(port))
	return "http://" + authority + "/dashboard/ui"
}

func runtimeLogDiagnosticsForRunner(runner factoryServiceRunner) service.RuntimeLogDiagnostics {
	provider, ok := runner.(runtimeLogDiagnosticsProvider)
	if !ok {
		return service.RuntimeLogDiagnostics{}
	}
	return provider.RuntimeLogDiagnostics()
}

func emitStartupMessages(cfg RunConfig, runtimeLog service.RuntimeLogDiagnostics) bool {
	if cfg.StartupOutput == nil {
		return false
	}

	fmt.Fprintf(cfg.StartupOutput, "Factory initiated: %s\n", cfg.Dir)
	if cfg.Bootstrap {
		fmt.Fprintf(cfg.StartupOutput, "Factory directory ready: %s\n", cfg.Dir)
	}
	if cfg.Continuously {
		fmt.Fprintln(cfg.StartupOutput, "Runtime mode: continuous")
	}
	if strings.TrimSpace(runtimeLog.Path) != "" {
		fmt.Fprintf(cfg.StartupOutput, "Runtime log: %s\n", runtimeLog.Path)
		fmt.Fprintf(cfg.StartupOutput, "Runtime log start (UTC): %s\n", timedisplay.Timestamp(runtimeLog.StartTimeUTC))
	}
	if cfg.Port <= 0 {
		fmt.Fprintln(cfg.StartupOutput, "Dashboard server disabled")
		return false
	}

	url := DashboardURL(bindDashboardHost(cfg), cfg.Port)
	fmt.Fprintf(cfg.StartupOutput, "Dashboard URL: %s\n", url)
	if !cfg.OpenDashboard || !interactiveOutput(cfg.StartupOutput) {
		fmt.Fprintf(cfg.StartupOutput, "Dashboard auto-open disabled; open %s\n", url)
		return false
	}
	return true
}

func reportRecordingPathOnShutdown(output io.Writer, recordPath resolvedRunRecordPath) {
	if output == nil || !recordPath.autoGenerated || strings.TrimSpace(recordPath.reportedPath) == "" {
		return
	}
	fmt.Fprintf(output, "Recording saved: %s\n", recordPath.reportedPath)
}

func openDashboardWhenServerReady(ctx context.Context, cfg RunConfig, dashboardReady <-chan struct{}) func() {
	ctx, cancel := context.WithCancel(ctx)
	done := make(chan struct{})
	go func() {
		defer close(done)
		timer := time.NewTimer(dashboardReadyTimeout)
		defer timer.Stop()

		url := DashboardURL(bindDashboardHost(cfg), cfg.Port)
		select {
		case <-dashboardReady:
			if err := dashboardOpener(ctx, url); err != nil {
				fmt.Fprintf(cfg.StartupOutput, "Dashboard auto-open unavailable: %v\n", err)
				fmt.Fprintf(cfg.StartupOutput, "Open the dashboard at %s\n", url)
				return
			}
			fmt.Fprintf(cfg.StartupOutput, "Opening dashboard: %s\n", url)
		case <-timer.C:
			fmt.Fprintln(cfg.StartupOutput, "Dashboard auto-open unavailable: dashboard server did not become ready")
			fmt.Fprintf(cfg.StartupOutput, "Open the dashboard at %s\n", url)
		case <-ctx.Done():
		}
	}()

	return func() {
		cancel()
		<-done
	}
}

func openURLInBrowser(ctx context.Context, url string) error {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "windows":
		cmd = exec.CommandContext(ctx, "rundll32", "url.dll,FileProtocolHandler", url)
	case "darwin":
		cmd = exec.CommandContext(ctx, "open", url)
	default:
		cmd = exec.CommandContext(ctx, "xdg-open", url)
	}
	if err := cmd.Start(); err != nil {
		return err
	}
	return cmd.Process.Release()
}

func isInteractiveOutput(output io.Writer) bool {
	file, ok := output.(*os.File)
	if !ok {
		return false
	}
	info, err := file.Stat()
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeCharDevice != 0
}

// LoadWorkFile reads a canonical FACTORY_REQUEST_BATCH from a JSON file.
func LoadWorkFile(path string) (interfaces.WorkRequest, error) {
	return batchload.LoadFromFile(path)
}

// CountTokenStates counts tokens by their state category based on place ID conventions.
// Place IDs follow the pattern '{work_type_id}:{state_value}'.
// Terminal states contain "completed", failed states contain "failed".
func CountTokenStates(snap *petri.MarkingSnapshot) (wip, completed, failed int) {
	for _, t := range snap.Tokens {
		placeID := t.PlaceID
		// Extract state from place ID (after the last ':').
		state := placeID
		if idx := strings.LastIndexByte(placeID, ':'); idx >= 0 {
			state = placeID[idx+1:]
		}

		switch {
		case isFailedState(state):
			failed++
		case isTerminalState(state):
			completed++
		default:
			wip++
		}
	}
	return
}

func isTerminalState(state string) bool {
	return state == completedPlaceIDSuffix
}

func isFailedState(state string) bool {
	return state == failedPlaceIDSuffix
}

// FormatDuration formats a duration as "Xm" or "Xh Ym".
func FormatDuration(d time.Duration) string {
	return dashboard.FormatDuration(d)
}
