package cobracompletion

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

const powerShellNoFileCompletionBlock = `    if (($Directive -band $ShellCompDirectiveNoFileComp) -ne 0 ) {`

const powerShellFilesystemDelegationBlock = `    if (($Directive -eq 0) -and ($Values.Length -eq 0)) {
        # Cobra's PowerShell generator does not delegate an empty default result
        # to the shell. Complete the entered path here while keeping discovery
        # outside the executable and the detached completion projection.
        $EnteredParent = Split-Path -Parent $WordToComplete
        $EnteredLeaf = Split-Path -Leaf $WordToComplete
        $SearchParent = $EnteredParent
        if ([string]::IsNullOrEmpty($SearchParent)) {
            $SearchParent = "."
        }
        $EscapedLeaf = [System.Management.Automation.WildcardPattern]::Escape($EnteredLeaf)
        Get-ChildItem -LiteralPath $SearchParent -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like "$EscapedLeaf*" } |
            ForEach-Object {
                $CompletionText = $_.Name
                if (-Not [string]::IsNullOrEmpty($EnteredParent)) {
                    $CompletionText = Join-Path $EnteredParent $_.Name
                }
                if ($_.PSIsContainer) {
                    $CompletionText += [System.IO.Path]::DirectorySeparatorChar
                }
                if ($IsEqualFlag) {
                    $CompletionText = $Flag + "=" + $CompletionText
                }
                $CompletionText = $CompletionText | __you_escapeStringWithSpecialChars
                [System.Management.Automation.CompletionResult]::new(
                    $CompletionText,
                    $CompletionText,
                    'ProviderItem',
                    $_.FullName
                )
            }
        return
    }

`

// ExecuteWithPowerShellFilesystemDelegation installs the generated-script
// compatibility wrapper before executing the canonical command tree.
func ExecuteWithPowerShellFilesystemDelegation(root *cobra.Command) error {
	if err := RegisterPowerShellFilesystemDelegation(root); err != nil {
		return err
	}
	return root.Execute()
}

// RegisterPowerShellFilesystemDelegation replaces Cobra's generated
// PowerShell writer with a compatibility wrapper for default file completion.
func RegisterPowerShellFilesystemDelegation(root *cobra.Command) error {
	if root == nil {
		return fmt.Errorf("register PowerShell filesystem completion: root command is required")
	}
	root.InitDefaultCompletionCmd()
	command, _, err := root.Find([]string{"completion", "powershell"})
	if err != nil || command == nil || command.Name() != "powershell" {
		return fmt.Errorf("register PowerShell filesystem completion: generated command is unavailable")
	}
	command.RunE = func(cmd *cobra.Command, _ []string) error {
		var generated bytes.Buffer
		noDescriptions := root.CompletionOptions.DisableDescriptions
		if flag := cmd.Flags().Lookup("no-descriptions"); flag != nil {
			noDescriptions, err = cmd.Flags().GetBool(flag.Name)
			if err != nil {
				return fmt.Errorf("read PowerShell completion options: %w", err)
			}
		}
		if noDescriptions {
			err = root.GenPowerShellCompletion(&generated)
		} else {
			err = root.GenPowerShellCompletionWithDesc(&generated)
		}
		if err != nil {
			return fmt.Errorf("generate PowerShell completion: %w", err)
		}
		patched, err := patchPowerShellFilesystemDelegation(generated.String())
		if err != nil {
			return err
		}
		if _, err := cmd.OutOrStdout().Write([]byte(patched)); err != nil {
			return fmt.Errorf("write PowerShell completion: %w", err)
		}
		return nil
	}
	return nil
}

func patchPowerShellFilesystemDelegation(script string) (string, error) {
	if strings.Count(script, powerShellNoFileCompletionBlock) != 1 {
		return "", fmt.Errorf(
			"generate PowerShell completion: unsupported Cobra completion template",
		)
	}
	return strings.Replace(
		script,
		powerShellNoFileCompletionBlock,
		powerShellFilesystemDelegationBlock+powerShellNoFileCompletionBlock,
		1,
	), nil
}
