// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	wire10 "github.com/google/wire"
	"github.com/portpowered/infinite-you/pkg/initializer/application"
	"github.com/portpowered/infinite-you/pkg/initializer/process"
	"github.com/portpowered/infinite-you/pkg/services/automations"
	wire7 "github.com/portpowered/infinite-you/pkg/services/automations/wire"
	"github.com/portpowered/infinite-you/pkg/services/edges"
	"github.com/portpowered/infinite-you/pkg/services/factory_definitions"
	wire5 "github.com/portpowered/infinite-you/pkg/services/factory_definitions/wire"
	"github.com/portpowered/infinite-you/pkg/services/factory_runtime"
	wire4 "github.com/portpowered/infinite-you/pkg/services/factory_runtime/wire"
	wire2 "github.com/portpowered/infinite-you/pkg/services/factory_sessions/wire"
	wire9 "github.com/portpowered/infinite-you/pkg/services/factory_visualization/wire"
	wire6 "github.com/portpowered/infinite-you/pkg/services/models/wire"
	"github.com/portpowered/infinite-you/pkg/services/operator_settings/wire"
	"github.com/portpowered/infinite-you/pkg/services/provider_sessions/transports/http"
	wire3 "github.com/portpowered/infinite-you/pkg/services/recordings/wire"
	wire8 "github.com/portpowered/infinite-you/pkg/services/webhooks/wire"
	"github.com/portpowered/infinite-you/pkg/services/work"
	"github.com/portpowered/infinite-you/pkg/services/worker_sessions/transports/cli/worker_sessions"
	"github.com/portpowered/infinite-you/pkg/transports/acp"
	"github.com/portpowered/infinite-you/pkg/transports/cli"
	"github.com/portpowered/infinite-you/pkg/transports/cli/run"
	"github.com/portpowered/infinite-you/pkg/transports/mcp/stdio"
)

// Injectors from wire.go:

// InjectBundle is the single application-process injector. Callers provide
// production defaults or functional overrides through the same typed inputs.
func InjectBundle(ctx context.Context, edges2 edges.Edges) (*application.Process, error) {
	cliObserver := provideCLIObserver(edges2)
	namedPathFileSystem := provideFactoryDefinitionNamedPathFileSystem(edges2)
	namedPathResolver, err := provideFactoryDefinitionNamedPathResolver(namedPathFileSystem)
	if err != nil {
		return nil, err
	}
	namedFactoryCatalogFileSystem := provideFactoryDefinitionNamedFactoryCatalogFileSystem(edges2)
	v, err := provideNamedFactoryCatalog(namedPathResolver, namedFactoryCatalogFileSystem)
	if err != nil {
		return nil, err
	}
	authoredLayoutReaderFileSystem := provideFactoryDefinitionAuthoredReaderFileSystem(edges2)
	v2, err := providePackagedFactoryDefinitions()
	if err != nil {
		return nil, err
	}
	effectiveFactoryCatalogDiscovery, err := provideEffectiveFactoryCatalogDiscovery(v, authoredLayoutReaderFileSystem, v2)
	if err != nil {
		return nil, err
	}
	effectiveFactoryDefinitionNormalizer := provideEffectiveFactoryDefinitionNormalizer()
	effectiveFactoryCatalogOperation, err := provideEffectiveFactoryCatalogOperation(effectiveFactoryCatalogDiscovery, effectiveFactoryDefinitionNormalizer)
	if err != nil {
		return nil, err
	}
	v3, err := provideEffectiveFactoryDefinitionsService(effectiveFactoryCatalogOperation)
	if err != nil {
		return nil, err
	}
	factoryNamesOperation := provideFactoryNameCompletionOperation(v3)
	packagedFactoryCatalogOperations, err := providePackagedFactoryCatalog(v2)
	if err != nil {
		return nil, err
	}
	packagedFactoryNamesOperation := providePackagedFactoryNameCompletionOperation(packagedFactoryCatalogOperations)
	selectedFactorySignatureOperation, err := provideSelectedFactorySignatureCompletionOperation(v3)
	if err != nil {
		return nil, err
	}
	namedFactoryRootsResolver := provideNamedFactoryRootsResolver()
	namedFactoryCandidatePathsResolver := provideNamedFactoryCandidatePathsResolver(namedPathResolver)
	v4 := provideCurrentFactoryDirectoryResolver(namedPathResolver)
	factoryConfigRootResolver := provideFactoryConfigRootResolver(authoredLayoutReaderFileSystem)
	authoredFactorySourceLoader := provideAuthoredFactorySourceLoader(authoredLayoutReaderFileSystem)
	factoryConfigFileLoader := provideFactoryConfigFileLoader(authoredFactorySourceLoader)
	requestFileLoader := provideWorkRequestFileLoader()
	singleWorkTargetPreparation := work.NewSingleWorkTargetPreparation()
	submittedFileReader := provideWorkSubmittedFileReader(edges2)
	submittedFilePathInspector := provideWorkSubmittedFilePathInspector(edges2)
	invocationInputPreparation := work.NewInvocationInputPreparation(submittedFileReader, submittedFilePathInspector)
	loggerBuilder := provideTerminalLoggerBuilder()
	reserver, err := provideRuntimeArtifactPathReserver()
	if err != nil {
		return nil, err
	}
	v5 := provideLiveRecordingTargetPlanner(reserver)
	adapter := provideRecordingsCLIAdapter()
	v6 := provideCLIRunDefaults(v5, adapter)
	batchInputFileSystem := provideBatchInputFileSystem()
	pathInspector := provideRunInputPathInspector()
	directoryCreator := provideRunDirectoryCreator()
	opener := provideBrowserOpener(edges2)
	fileSystem := provideOperatorSettingsFileSystem(edges2)
	createTemporaryFile := provideOperatorSettingsCreateTemporaryFile(edges2)
	configDecoder := provideOperatorConfigDecoder()
	configEncoder := provideOperatorConfigEncoder()
	service, err := provideProvidersService(edges2)
	if err != nil {
		return nil, err
	}
	providerCatalog := provideOperatorSettingsProviderCatalog(service)
	configDocumentPreserver := provideOperatorSettingsDocumentPreserver()
	configDiagnosticsDecoder := provideOperatorConfigDiagnosticsDecoder()
	v7 := wire.NewDocumentService(fileSystem, createTemporaryFile, configDecoder, configEncoder, providerCatalog, configDocumentPreserver, configDiagnosticsDecoder)
	v8, err := wire.NewResolutionService(service)
	if err != nil {
		return nil, err
	}
	idGenerator := provideOperatorSettingsIDGenerator(edges2)
	logger, err := provideProcessLogger(edges2)
	if err != nil {
		return nil, err
	}
	loggingLogger := provideOperatorSettingsLogger(logger)
	operatorsettingsService, err := wire.NewService(v7, v8, fileSystem, createTemporaryFile, configDecoder, configEncoder, idGenerator, loggingLogger, configDiagnosticsDecoder)
	if err != nil {
		return nil, err
	}
	defaultsResolver := provideOperatorDefaultsResolver(operatorsettingsService)
	configLoader := provideOperatorConfigLoader(operatorsettingsService)
	v9 := wire2.NewSessionRegistry()
	responseEventIDGenerator := provideFactorySessionResponseEventIDGenerator(edges2)
	responseEventRetentionLimits := provideFactorySessionResponseEventRetentionLimits(edges2)
	eventsService, err := provideEventsService(loggingLogger)
	if err != nil {
		return nil, err
	}
	v10, err := wire2.NewResponseStreams(responseEventIDGenerator, responseEventRetentionLimits, eventsService, loggingLogger)
	if err != nil {
		return nil, err
	}
	clock := provideFactoryRuntimeClock(edges2)
	v11, err := wire2.NewResponseStreamRegistry(v10, clock)
	if err != nil {
		return nil, err
	}
	v12 := provideFactorySessionIDGenerator(edges2)
	v13 := wire2.NewSessionState(v9, v11, clock, responseEventIDGenerator, v12, v10)
	v14 := wire2.NewStreamObserver()
	v15 := wire2.NewStreamManager(v13, v14, v11, v10)
	timerSource := provideFactoryRuntimeMetricsClock(edges2)
	v16 := wire3.NewProjectionService()
	worldStateProjector := provideInvocationWorldStateProjector(v16)
	v17 := wire2.NewInvocationAuthority(v13, timerSource, worldStateProjector)
	v18, err := wire4.NewLifecycle(clock, timerSource)
	if err != nil {
		return nil, err
	}
	v19, err := wire4.NewInstanceHost(clock, timerSource, v18)
	if err != nil {
		return nil, err
	}
	runtimeStopOperation := wire4.NewRuntimeStopOperation(v19)
	v20 := wire2.NewScopeControl(v13, runtimeStopOperation)
	sessionResultProjectionOperation := factory.NewSessionResultProjectionOperation()
	invocationPolicyPorts, err := provideFactoryInvocationPolicyPorts()
	if err != nil {
		return nil, err
	}
	invocationInterpolationService := provideInvocationInterpolationService(invocationPolicyPorts)
	invocationWorkTypeService := provideInvocationWorkTypeService(invocationPolicyPorts)
	ttsObservabilityService := provideTTSObservabilityService(invocationPolicyPorts)
	homeDirectoryResolver := provideFactorySessionResolveHomeDirectory(edges2)
	v21 := provideFactorySessionDirectoryInspection(edges2)
	v22 := provideFactorySessionInvocationInputReader(edges2)
	v23 := provideFactorySessionInitialWorkReader(edges2)
	logicalTargetResolveSymlinks := provideFactorySessionResolveLogicalTargetSymlinks(edges2)
	v24, err := wire2.NewIdentity(logicalTargetResolveSymlinks, homeDirectoryResolver)
	if err != nil {
		return nil, err
	}
	v25 := wire2.NewLiveChangeCoordinator()
	storage := provideReplayArtifactStorage()
	v26 := provideReplayArtifactLoader(storage)
	v27 := provideFactorySessionReplayRecordingReader(edges2)
	v28 := provideRecordingOpenFile(edges2)
	replayInputLoader := provideFactorySessionReplayInputs(v26, v27, v28, loggingLogger)
	recordedSessionInventory := provideRecordedSessionInventory(edges2, replayInputLoader, loggingLogger)
	v29, err := provideFactorySessionsAssembly(v9, v13, v15, v17, v20, sessionResultProjectionOperation, invocationInterpolationService, invocationWorkTypeService, ttsObservabilityService, responseEventIDGenerator, v12, homeDirectoryResolver, v21, namedPathResolver, v22, v23, v24, v10, clock, v25, recordedSessionInventory)
	if err != nil {
		return nil, err
	}
	providersessionsService, err := provideProviderSessions(edges2)
	if err != nil {
		return nil, err
	}
	v30 := &wire2.ProviderSessionsPorts{
		Service: providersessionsService,
	}
	workflowSourceFileSystem := provideFactoryRuntimeWorkflowSources(edges2)
	workflowHomeResolver := provideFactoryRuntimeWorkflowHome(edges2)
	workflowSourceResolveSymlinks := provideFactoryRuntimeWorkflowSourceResolveSymlinks(edges2)
	javaScriptWorkflows := provideJavaScriptWorkflows(workflowSourceFileSystem, workflowHomeResolver, workflowSourceResolveSymlinks)
	javaScriptWorkflowDefinitions := provideJavaScriptWorkflowDefinitions(javaScriptWorkflows)
	workflowPreviewOperation := provideWorkflowPreviewOperation(javaScriptWorkflows)
	workersMockCommandRunnerFactory := provideWorkersMockCommandRunnerFactory()
	quorumPolicyService := provideQuorumPolicyService(invocationPolicyPorts)
	invocationOutputShapingService := provideInvocationOutputShapingService(invocationPolicyPorts)
	workPropagationPolicyService := provideWorkPropagationPolicyService(invocationPolicyPorts)
	contentStagingService, err := provideWorkContentStagingService(edges2)
	if err != nil {
		return nil, err
	}
	contentHostPlatform := provideWorkContentHostPlatform(edges2)
	contentMaterializer, err := provideContentMaterializer(contentHostPlatform, edges2)
	if err != nil {
		return nil, err
	}
	v31, err := provideRecordingClock(clock)
	if err != nil {
		return nil, err
	}
	v32 := wire3.NewRuntimeLedgerRouter(v31)
	v33 := wire3.RuntimeLedger(v32)
	v34 := provideRecordingReadFile(edges2)
	v35 := provideRecordingSnapshotWriter(edges2, storage, v34)
	v36 := wire3.NewRecordingFlushTickerFactory()
	v37 := wire3.NewRecordingLifecycleOwner(v5, v35, v36, v31)
	portableArtifactPublication, err := provideRecordingPublication(edges2)
	if err != nil {
		return nil, err
	}
	v38 := wire3.NewArtifactsExportOwner(v37, portableArtifactPublication)
	factorySnapshotJSONDecoder := wire5.FactorySnapshotJSONDecoder()
	v39 := wire3.NewReplayOwner(v37, v16, v34, factorySnapshotJSONDecoder)
	v40 := wire3.NewCanonicalLedgerOwner(v33)
	v41 := wire3.NewHistoricalQueryOwner(v34, v16)
	v42 := provideLoadedFactorySnapshotCapturer()
	replayRuntimeConfigDecoder := provideReplayRuntimeConfigDecoder()
	recordingsService := provideRecordingsRoot(edges2, v33, v16, v37, v38, v39, v40, v41, v31, loggingLogger, v32, v42, factorySnapshotJSONDecoder, replayRuntimeConfigDecoder, replayInputLoader)
	v43 := provideWorkDurabilityReader(recordingsService)
	workService := provideWorkService(v29, submittedFileReader, submittedFilePathInspector, contentStagingService, contentMaterializer, v43)
	decisionEnvelopeService := provideDecisionEnvelopeService(invocationPolicyPorts)
	runtimeLoggerFactory := provideRuntimeLoggerFactory()
	wireRuntimeArtifactClock := provideRuntimeArtifactClock()
	wireRuntimeArtifactIDGenerator := provideRuntimeArtifactIDGenerator()
	factoryRuntimeLogOwner, err := provideRuntimeLogOwner(logger, wireRuntimeArtifactClock, wireRuntimeArtifactIDGenerator, reserver)
	if err != nil {
		return nil, err
	}
	runtimeMetricsRetentionFileSystem := provideRuntimeMetricsRetentionFileSystem()
	runtimeMetricsCoordination, err := provideRuntimeMetricsCoordination()
	if err != nil {
		return nil, err
	}
	factoryRuntimeMetricsOwner, err := provideRuntimeMetricsOwner(logger, wireRuntimeArtifactClock, wireRuntimeArtifactIDGenerator, reserver, runtimeMetricsRetentionFileSystem, runtimeMetricsCoordination)
	if err != nil {
		return nil, err
	}
	factoryIDGenerator := provideFactoryRuntimeIDGenerator(edges2)
	requestIDGenerator := provideWorkRequestIDGenerator(edges2)
	runtimeDirectoryFileSystem := provideFactoryRuntimeDirectories(edges2)
	inputFileSystem := provideFactoryRuntimeInputs(edges2)
	inputDirectoryWalker := provideFactoryRuntimeInputDirectoryWalker(edges2)
	v44 := provideRuntimeOrchestration(factoryIDGenerator, javaScriptWorkflows)
	orchestrationCompilation := provideOrchestrationCompilation(v44)
	v45 := wire4.NewRuntimeFactory(quorumPolicyService, invocationOutputShapingService, workPropagationPolicyService, workService, decisionEnvelopeService, invocationInterpolationService, logger, runtimeLoggerFactory, factoryRuntimeLogOwner, factoryRuntimeMetricsOwner, factoryIDGenerator, requestIDGenerator, runtimeDirectoryFileSystem, inputFileSystem, inputDirectoryWalker, orchestrationCompilation, providersessionsService)
	v46, err := provideWorkerRecordingWriter(edges2)
	if err != nil {
		return nil, err
	}
	v47, err := provideWorkerSessionRecorder(eventsService, v46, loggingLogger)
	if err != nil {
		return nil, err
	}
	workerSessionsFactory := provideWorkerSessionsFactoryWithRecorder(eventsService, providersessionsService, loggingLogger, v47)
	v48, err := provideModelRuntimeScopes()
	if err != nil {
		return nil, err
	}
	assetHostPlatform := provideModelAssetHostPlatform(edges2)
	v49 := provideModelAssetHTTP(edges2)
	runtimeAssetEndpoints := provideModelAssetEndpoints(edges2)
	v50 := provideModelAssetMakeDirectories(edges2)
	v51 := provideModelAssetInspectPath(edges2)
	v52 := provideModelAssetResolveHomeDirectory(edges2)
	v53 := provideModelAssetWriteFile(edges2)
	v54 := provideModelAssetRenamePath(edges2)
	v55 := provideModelAssetRemovePath(edges2)
	v56 := provideModelAssetReadFile(edges2)
	v57 := provideModelAssetReadDirectory(edges2)
	v58 := provideModelAssetCreateFile(edges2)
	v59 := provideModelAssetOpenFile(edges2)
	v60 := provideModelAssetResolveEnvironment(edges2)
	wireModelAssetRevisionResolver := provideModelAssetRevision(edges2)
	v61, err := provideModelAssetCoordination(edges2)
	if err != nil {
		return nil, err
	}
	v62, err := provideModelAssets(v48, assetHostPlatform, v49, runtimeAssetEndpoints, v50, v51, v52, v53, v54, v55, v56, v57, v58, v59, v60, wireModelAssetRevisionResolver, v61)
	if err != nil {
		return nil, err
	}
	v63 := wire6.NewCatalogReadinessQuery(v62)
	v64, err := wire6.NewCatalog(v48, v63)
	if err != nil {
		return nil, err
	}
	v65 := provideModelHostClock(edges2)
	v66 := wire6.NewSlotState()
	v67 := provideModelSlotFacts(v66, v48, v62)
	v68 := provideModelHostLogger(logger)
	v69 := provideModelHostMetrics(edges2)
	v70 := provideModelSlotCoordinator(v66, v48, v65, v68, v69)
	v71, err := wire6.NewHostLeases(v65, v67, v70)
	if err != nil {
		return nil, err
	}
	wireModelRuntimeEvidenceSource, err := provideModelRuntimeEvidenceSource()
	if err != nil {
		return nil, err
	}
	v72 := provideModelHostLauncher(edges2, wireModelRuntimeEvidenceSource)
	v73 := provideModelHostHTTP(edges2)
	v74 := provideModelHostSymlinks()
	v75 := provideModelHostProtocol(edges2, v74)
	v76, err := provideModelHostCompatibility(edges2)
	if err != nil {
		return nil, err
	}
	v77 := provideModelOrderedRuntimeEvidence(wireModelRuntimeEvidenceSource)
	v78, err := provideModelRuntimeHost(v48, v62, v71, v66, v72, v73, v65, v68, v69, assetHostPlatform, v75, v76, v74, v77)
	if err != nil {
		return nil, err
	}
	wireModelRuntimeRunner, err := provideModelRuntimeRunner(edges2)
	if err != nil {
		return nil, err
	}
	v79 := provideModelRuntimeTempDirectory(edges2)
	v80 := provideModelRuntimeTempFile(edges2)
	v81 := provideModelRuntimeInspectFile(edges2)
	v82, err := provideModelInvocationRuntime(edges2, wireModelRuntimeRunner, v79, v80, v53, v81, v56, v55)
	if err != nil {
		return nil, err
	}
	wireModelNow := provideModelNow(edges2)
	v83, err := provideModelInference(v48, v62, v64, v78, v82, wireModelNow)
	if err != nil {
		return nil, err
	}
	v84 := provideModelRuntimeHTTP(edges2)
	v85, err := provideModelBackendArtifactResolver(edges2, wireModelRuntimeRunner, v49)
	if err != nil {
		return nil, err
	}
	modelsService, err := provideModelsService(edges2, v48, v62, v64, v78, v83, v72, v73, v65, wireModelRuntimeRunner, v84, v81, v79, v80, wireModelNow, v68, v69, v77, v85, assetHostPlatform, logger)
	if err != nil {
		return nil, err
	}
	readOpener := provideWorkersInferenceMediaFileReader(edges2)
	v86, err := provideFactoryRuntimeScriptCommandRunner(edges2)
	if err != nil {
		return nil, err
	}
	readFileTree := provideWorkersFactoryDocsFileSystem(edges2)
	factoryWorktreePreparer, err := provideWorkersWorktree(edges2)
	if err != nil {
		return nil, err
	}
	v87 := provideWorkersWorktreeRelease(factoryWorktreePreparer)
	temporaryFileSystem := provideWorkersProviderTemporaryFileSystem(edges2)
	v88 := provideFactoryRuntimeProviderOverride(edges2)
	agentToolFileSystem := provideWorkersAgentToolFileSystem(edges2)
	workersService, err := provideStatelessWorkersService(service, modelsService, contentMaterializer, readOpener, v86, readFileTree, clock, logger, factoryWorktreePreparer, v87, temporaryFileSystem, v88, agentToolFileSystem, decisionEnvelopeService)
	if err != nil {
		return nil, err
	}
	v89, err := wire4.NewAssembly(v45, workerSessionsFactory, workersService, timerSource, v19)
	if err != nil {
		return nil, err
	}
	v90 := provideRuntimeDispatchPlanning()
	factoryRuntimeRoot, err := provideFactoryRuntimeRoot(v44, v19, v90)
	if err != nil {
		return nil, err
	}
	clockResolver := provideFactoryRuntimeClockResolver()
	sessionLoggerFactory := provideFactoryRuntimeSessionLoggerFactory()
	v91 := provideFactoryRuntimeSubmissionRecorder(edges2)
	v92 := provideFactoryRuntimeDispatchRecorder(edges2)
	v93 := &wire2.FactoryRuntimePorts{
		Logger:                          logger,
		FactoryWorkflows:                javaScriptWorkflowDefinitions,
		WorkflowPreview:                 workflowPreviewOperation,
		WorkersMockCommandRunnerFactory: workersMockCommandRunnerFactory,
		FactoryRuntimeAssembler:         v89,
		RuntimeRoot:                     factoryRuntimeRoot,
		ResolveClock:                    clockResolver,
		NewSessionLogger:                sessionLoggerFactory,
		Clock:                           clock,
		ProviderOverride:                v88,
		SubmissionRecorder:              v91,
		DispatchRecorder:                v92,
	}
	portablefilesFileSystem := provideFactoryDefinitionPortableFileSystem(edges2)
	v94, err := providePortableBundledFilesApplier(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	v95, err := provideFactoryStarterWorkApplier(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	v96 := providePortableBundledFilesMaterializer(portablefilesFileSystem)
	loadingFileSystem := provideFactoryDefinitionLoadingFileSystem(edges2)
	v97, err := providePortableBundledFileSourceResolver(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	portableBundledFileInspection := provideFactoryDefinitionPortableBundledFileInspection(edges2)
	requiredToolPathLookup := provideFactoryDefinitionRequiredToolPathLookup(edges2)
	requiredToolVersionProbe := provideFactoryDefinitionRequiredToolVersionProbe(edges2)
	v98, err := provideFactoryDefinitionRequiredToolChecker(requiredToolPathLookup, requiredToolVersionProbe)
	if err != nil {
		return nil, err
	}
	v99 := provideFactoryDefinitionLoader(v94, v95, v96, loadingFileSystem, namedPathResolver, authoredLayoutReaderFileSystem, v97, portableBundledFileInspection, v98)
	v100 := provideFactoryDefinitionCompilation(v99)
	v101 := provideOrchestratorDefinitionValidator(javaScriptWorkflows)
	validationOperations := provideFactoryDefinitionValidationService(javaScriptWorkflows, v100, v101)
	v102 := provideFactoryDefinitionValidator(validationOperations)
	definitionRuntimeRouter := provideFactoryDefinitionsRuntimeRouter()
	v103, err := providePortableBundledDocsPruner(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	v104 := providePortableBundledFileWritesValidator(portablefilesFileSystem)
	v105 := providePortableBundledFilesCopier(portablefilesFileSystem)
	authoredLayoutWriterFileSystem := provideFactoryDefinitionAuthoredWriterFileSystem(edges2)
	inputInboxSentinelEnsurer := provideFactoryDefinitionInputInboxSentinelEnsurer(authoredLayoutWriterFileSystem)
	persistenceFileSystem := provideFactoryDefinitionPersistenceFileSystem(edges2)
	directoryReplacementStore := provideFactoryDefinitionDirectoryReplacementStore(edges2)
	v106, err := provideFactoryDefinitionPersistence(v102, v99, v103, v96, v104, v105, authoredLayoutWriterFileSystem, inputInboxSentinelEnsurer, persistenceFileSystem, namedPathResolver, directoryReplacementStore)
	if err != nil {
		return nil, err
	}
	v107 := provideFactoryDefinitionValidationOwner(validationOperations, v100, v98, v101)
	v108 := provideFactoryDefinitionRuntimeSnapshot(v99, definitionRuntimeRouter)
	v109 := wire5.NewCatalogService(namedPathResolver, namedFactoryCatalogFileSystem)
	factorydefinitionsClock := provideFactoryDefinitionClock(edges2)
	versionFileSystem := provideFactoryDefinitionVersionFileSystem(edges2)
	packagedInstallationFileSystem := provideFactoryDefinitionPackagedInstallationFileSystem(edges2)
	packagedInstallationDirectoryCreator := provideFactoryDefinitionPackagedInstallationDirectoryCreator(edges2)
	packagedFactoryInstallationOperations := providePackagedFactoryInstallation(v106, packagedInstallationFileSystem, packagedInstallationDirectoryCreator, loggingLogger)
	factorydefinitionsService, err := provideFactoryDefinitionsRoot(definitionRuntimeRouter, v102, v106, v99, v100, v107, v108, v94, v95, namedPathResolver, v109, factorydefinitionsClock, versionFileSystem, effectiveFactoryCatalogOperation, packagedFactoryCatalogOperations, packagedFactoryInstallationOperations, v98, v101, portablefilesFileSystem, directoryReplacementStore)
	if err != nil {
		return nil, err
	}
	initialFactorySnapshotFactory := provideInitialFactorySnapshotFactory(v94, v95)
	v110 := provideLoadedFactoryLoader(v99)
	v111 := provideLoadedFactorySourceFactory()
	v112 := &wire2.FactoryDefinitionsPorts{
		Validator:                     v102,
		NamedPaths:                    namedPathResolver,
		Service:                       factorydefinitionsService,
		RuntimeRouter:                 definitionRuntimeRouter,
		InitialFactorySnapshotFactory: initialFactorySnapshotFactory,
		LoadFactory:                   v110,
		NewLoadedFactory:              v111,
		DecodeReplayConfig:            replayRuntimeConfigDecoder,
		CaptureLoadedFactorySnapshot:  v42,
	}
	durableExecutionFactory := provideDurableExecutionFactory(configLoader)
	orchestrationJavaScriptExecution := provideOrchestrationJavaScriptExecution(v44)
	v113, err := providePortableRecordingWriter(edges2)
	if err != nil {
		return nil, err
	}
	v114 := provideFactorySessionRuntimePersistenceFileSystem(edges2)
	v115 := provideFactorySessionRuntimePersistenceStoreFactory(v114)
	v116 := provideFactorySessionSyncWaitScheduler()
	v117, err := provideAgyPTYAllocator(edges2)
	if err != nil {
		return nil, err
	}
	v118 := provideWorkerCommandRunnerAdapter()
	v119 := provideFactorySessionExecutionFactory(javaScriptWorkflows, orchestrationJavaScriptExecution, v113, v115, v116, v12, responseEventIDGenerator, v10, v117, v118, v88, v25)
	scaffoldFileSystem := provideFactoryDefinitionScaffoldFileSystem(edges2)
	scaffoldOutput := provideFactoryDefinitionScaffoldOutput(edges2)
	v120, err := provideFactoryScaffoldCommandInitializer(scaffoldFileSystem, scaffoldOutput)
	if err != nil {
		return nil, err
	}
	factoryScaffoldInitializer := provideFactoryScaffoldInitializer(v120)
	v121 := provideDefinitionValidationOperation(validationOperations)
	editableFactoryValidator := provideEditableFactoryValidator(v121)
	commandLineReader := providePprofCommandLineReader()
	starter, err := provideAPIServerStarter(edges2, commandLineReader)
	if err != nil {
		return nil, err
	}
	v122 := provideRuntimeHostOperation(starter)
	processRuntimeFactory, err := provideProcessRuntimeFactory(v122)
	if err != nil {
		return nil, err
	}
	runtimeInstanceIDGenerator := provideFactorySessionRuntimeInstanceIDGenerator(edges2)
	providerIdentityResolver := provideFactorySessionProviderIdentityResolver(service)
	v123 := provideFactorySessionInvocationMetricsRecorder(edges2)
	v124 := &wire2.FactorySessionsPorts{
		RuntimeAssembly:                v29,
		DurableExecutionFactory:        durableExecutionFactory,
		FactorySessionExecutionFactory: v119,
		FactoryScaffoldInitializer:     factoryScaffoldInitializer,
		EditableFactoryValidator:       editableFactoryValidator,
		ProcessRuntimeFactory:          processRuntimeFactory,
		GenerateSessionID:              v12,
		GenerateRuntimeInstanceID:      runtimeInstanceIDGenerator,
		ResolveHome:                    homeDirectoryResolver,
		ProviderIdentities:             providerIdentityResolver,
		InvocationMetricsRecorder:      v123,
	}
	v125 := &wire2.WorkPorts{
		Service: workService,
	}
	v126 := provideAutomationsClock(clock)
	commandRunner, err := provideAutomationsCommandRunner(edges2)
	if err != nil {
		return nil, err
	}
	workstationExecutionPolicyService := provideWorkstationExecutionPolicyService(invocationPolicyPorts)
	v127 := provideAutomationsCursorFileSystem(edges2)
	v128 := wire7.NewCursorScopes(v127)
	v129 := provideAutomationsScriptPollers(logger, v126, commandRunner, workstationExecutionPolicyService, v128)
	v130 := wire7.NewCron()
	v131 := wire7.NewFilesystemWatchers()
	v132 := provideAutomationHostedClock(edges2)
	v133 := provideAutomationHostedHTTPClient(edges2)
	v134 := provideAutomationHostedSecretResolver(edges2)
	v135, err := provideAutomationHostedCheckpointStore(edges2)
	if err != nil {
		return nil, err
	}
	v136 := provideAutomationsHostedPollers(logger, v132, v133, v134, v135, edges2)
	v137 := wire7.NewSourceLifecycle(logger, v126, v129, v130, v131, v136, v128, workstationExecutionPolicyService)
	v138 := wire7.NewReconciliation(v137)
	v139 := provideAutomationsOwner(logger, v126, v137, v138, v129, v130, v131, v136, workstationExecutionPolicyService, v128)
	root := provideAutomationsRoot(v139)
	v140 := &wire2.AutomationsPorts{
		Service: root,
	}
	v141 := &wire2.ModelsPorts{
		Service: modelsService,
	}
	v142, err := provideRecordingsRuntimeScopeService(recordingsService)
	if err != nil {
		return nil, err
	}
	v143 := &wire2.RecordingsPorts{
		Service: recordingsService,
		Runtime: v142,
	}
	httpClient := provideFactoryWebhookHTTPClient(edges2)
	secretResolver := provideFactoryWebhookSecretResolver(edges2)
	wireClock := provideFactoryWebhookClock(edges2)
	deadLetterAppender := provideFactoryWebhookDeadLetterAppender(edges2)
	webhooksService := wire8.NewService(recordingsService, httpClient, secretResolver, wireClock, deadLetterAppender, loggingLogger)
	v144 := &wire2.WebhooksPorts{
		Service: webhooksService,
	}
	providerFromCommandRunnerFactory := provideProviderFromCommandRunnerFactory(service, edges2)
	providerCommandRunner, err := provideFactoryRuntimeProviderCommandRunner(edges2)
	if err != nil {
		return nil, err
	}
	v145 := &wire2.WorkersPorts{
		Service:                          workersService,
		ProviderFromCommandRunnerFactory: providerFromCommandRunnerFactory,
		ProviderCommandRunner:            providerCommandRunner,
		ScriptCommandRunner:              v86,
	}
	backendScopeEnsurer := provideOperatorBackendScopeEnsurer(operatorsettingsService)
	v146 := &wire2.OperatorSettingsPorts{
		EnsureBackendScope: backendScopeEnsurer,
	}
	v147, err := wire2.NewRoot(v30, v93, v112, v124, v125, v140, v141, v143, v144, v145, v146)
	if err != nil {
		return nil, err
	}
	factorysessionsService, err := provideFactorySessionsService(v29, v147, v25)
	if err != nil {
		return nil, err
	}
	wireStandardCLIHTTPProtocol, err := provideStandardCLIHTTPProtocol()
	if err != nil {
		return nil, err
	}
	wireModelsPullCLIHTTPProtocol, err := provideModelsPullCLIHTTPProtocol()
	if err != nil {
		return nil, err
	}
	workingDirectory := provideFactorySessionsWorkingDirectory(edges2)
	v148, err := provideModelInvocationArtifactExporter(edges2)
	if err != nil {
		return nil, err
	}
	modelInvocationTimeout := provideModelInvocationTimeout()
	runtimeArtifactRootResolver := provideRuntimeArtifactRootResolver()
	openingPresentationOwner := wire2.NewOpeningPresentationOwner()
	v149, err := provideInvocationOperation(factorysessionsService, modelsService, workingDirectory, v4, v148, modelInvocationTimeout, runtimeArtifactRootResolver, v12, logger, openingPresentationOwner)
	if err != nil {
		return nil, err
	}
	invocationOperation := provideModelsCLIInvocationOperation(v149)
	compositionScopeProvider, err := provideModelsCLIComposition(modelsService, v149, configLoader)
	if err != nil {
		return nil, err
	}
	outputFileSystem := provideModelsCLIOutputFileSystem(edges2)
	inputFileReader := provideModelsCLIInputFileReader(edges2)
	cliService := provideModelsCLIService(wireStandardCLIHTTPProtocol, wireModelsPullCLIHTTPProtocol, invocationOperation, compositionScopeProvider, outputFileSystem, inputFileReader, wireRuntimeArtifactClock)
	service2 := provideProvidersCLIService(service)
	v150 := wire2.NewRequestPreparation()
	sessionService := provideSessionsCLIService(wireStandardCLIHTTPProtocol, v150)
	localSessionsCLIService := provideLocalSessionsCLIService(factorysessionsService)
	payloadFileReader := provideSubmitPayloadReader()
	wireExtendedCLIHTTPProtocol, err := provideExtendedCLIHTTPProtocol()
	if err != nil {
		return nil, err
	}
	submitWorkOperation := provideSubmitWorkOperation(payloadFileReader, wireExtendedCLIHTTPProtocol)
	factoryRequestBatchPreparation := work.NewFactoryRequestBatchPreparation()
	submitBatchOperation := provideSubmitBatchOperation(wireExtendedCLIHTTPProtocol, factoryRequestBatchPreparation)
	flattenFactoryConfigOperation := provideFlattenFactoryConfigOperation(v106)
	expandFactoryConfigOperation := provideExpandFactoryConfigOperation(v106)
	service3 := wire.NewCLIService(operatorsettingsService)
	configureInitOperation, err := provideConfigureInitOperation(operatorsettingsService, service3)
	if err != nil {
		return nil, err
	}
	installPackagedFactoryOperation := provideInstallPackagedFactoryOperation(packagedFactoryCatalogOperations, packagedFactoryInstallationOperations)
	cliInstallPackagedFactoryOperation := provideInstallPackagedFactoryCLI(installPackagedFactoryOperation)
	queryFactoryOperation := provideQueryFactoryOperation(wireStandardCLIHTTPProtocol)
	v151 := provideCurrentFactoryPointerReader(namedPathResolver)
	listFactoriesOperation := provideListFactoriesOperation(v3, v151)
	v152 := provideSubmittedDefinitionValidationOperation(validationOperations)
	validateFactoryOperation, err := provideValidateFactoryOperation(v152, authoredFactorySourceLoader)
	if err != nil {
		return nil, err
	}
	v153 := provideNamedFactoryPersistenceOperation(v106)
	createFactoryFromFileOperation := provideCreateFactoryFromFileOperation(v153, authoredFactorySourceLoader)
	replaceFactoryCurrentOperation := provideReplaceFactoryCurrentOperation(wireStandardCLIHTTPProtocol)
	updateFactoryFromFileOperation := provideUpdateFactoryFromFileOperation(v153, authoredFactorySourceLoader)
	deleteFactoryOperation := provideDeleteFactoryOperation(v)
	listRequestPreparation := work.NewListRequestPreparation()
	listWorkOperation := provideListWorkOperation(wireStandardCLIHTTPProtocol, listRequestPreparation)
	listHumanApprovalsOperation := provideListHumanApprovalsOperation(wireStandardCLIHTTPProtocol)
	showHumanApprovalOperation := provideShowHumanApprovalOperation(wireStandardCLIHTTPProtocol)
	wireWatchCLIHTTPProtocol, err := provideWatchCLIHTTPProtocol()
	if err != nil {
		return nil, err
	}
	v154 := provideWatchReconnectWait()
	watchWorkOperation := provideWatchWorkOperation(wireWatchCLIHTTPProtocol, v154)
	showWorkOperation := provideShowWorkOperation(wireStandardCLIHTTPProtocol)
	moveWorkOperation := provideMoveWorkOperation(wireExtendedCLIHTTPProtocol)
	v155 := provideWorkVisualizationOperation()
	visualizeWorkOperation := provideVisualizeWorkOperation(v155)
	v156 := provideListWorkerSessionsOperation(wireStandardCLIHTTPProtocol)
	v157 := provideShowWorkerSessionOperation(wireStandardCLIHTTPProtocol)
	v158 := provideReadWorkerSessionOperation(wireStandardCLIHTTPProtocol)
	wireStreamingCLIHTTPProtocol, err := provideStreamingCLIHTTPProtocol()
	if err != nil {
		return nil, err
	}
	v159 := provideStreamWorkerSessionOperation(wireStreamingCLIHTTPProtocol)
	wireLocalWorkerSessionsBoundary, err := provideLocalWorkerSessionsBoundary(eventsService, providersessionsService, loggingLogger, workersService, v47)
	if err != nil {
		return nil, err
	}
	cliIDGenerator := provideWorkerSessionsCLIIdentityGenerator()
	executionFileReader := provideWorkerSessionsCLIExecutionFileReader()
	v160 := provideInvokeWorkerSessionOperation(wireStreamingCLIHTTPProtocol, wireLocalWorkerSessionsBoundary, cliIDGenerator, executionFileReader)
	v161 := provideContinueWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary, cliIDGenerator)
	v162 := provideInterruptWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary, cliIDGenerator)
	pauseWorkerSessionOperation := providePauseWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	resumeWorkerSessionOperation := provideResumeWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	cancelWorkerSessionOperation := provideCancelWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	terminateWorkerSessionOperation := provideTerminateWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	runtimeFactory := provideFactoryVisualizationFactory()
	v163 := wire9.NewRuntimeSinkOwner()
	factoryStatusProjector := factory.NewFactoryStatusProjector()
	httpAdapter := http.NewAdapter(providersessionsService)
	handler := http.NewHandler(httpAdapter, logger)
	contentPreparation := work.NewContentPreparation()
	requestPreparation := provideFactorySessionHTTPRequestPreparation(v150)
	runtimeMetricsQuery, err := provideFactoryVisualizationMetricsQuery(loggingLogger)
	if err != nil {
		return nil, err
	}
	priceTableReader, err := provideProviderPriceTableReader()
	if err != nil {
		return nil, err
	}
	costsQuery, err := provideCostsQuery(priceTableReader, operatorsettingsService, runtimeMetricsQuery, loggingLogger)
	if err != nil {
		return nil, err
	}
	wireHttpRuntimeBinding, err := provideHTTPRuntimeBindingWithMetrics(factoryStatusProjector, handler, contentPreparation, v152, invocationWorkTypeService, requestPreparation, runtimeMetricsQuery, costsQuery)
	if err != nil {
		return nil, err
	}
	runnerFactory := provideLifecycleRunnerFactory()
	v164 := wire2.NewLifecyclePlanOperation()
	runtimeRunnerBuilder, err := provideRunRuntimeRunnerBuilder(v147, edges2, runtimeFactory, v163, wireHttpRuntimeBinding, runnerFactory, v164)
	if err != nil {
		return nil, err
	}
	v165 := provideResponsePresentation()
	directJavaScriptHost, err := provideDirectJavaScriptHostAdapter(v152, invocationWorkTypeService, requestPreparation, starter, runnerFactory, logger)
	if err != nil {
		return nil, err
	}
	managedRunnerFactory := provideManagedRunnerFactory()
	lifecycleRunnerBuilder, err := application.NewLifecycleRunnerBuilder(managedRunnerFactory)
	if err != nil {
		return nil, err
	}
	directJavaScriptRunOperation, err := run.NewDirectJavaScriptRunOperation(factorysessionsService, v12, directJavaScriptHost, openingPresentationOwner, lifecycleRunnerBuilder)
	if err != nil {
		return nil, err
	}
	mockWorkersConfigFileSystem := provideWorkersMockWorkersConfigFileSystem(edges2)
	mockWorkersConfigDiagnosticsLoader, err := provideWorkersMockWorkersConfigDiagnosticsLoader(mockWorkersConfigFileSystem)
	if err != nil {
		return nil, err
	}
	sessionStartRequestFactory := provideSessionStartRequestFactory()
	selectionFactory, err := provideRunSelectionFactory(runtimeRunnerBuilder, v149, v165, directJavaScriptRunOperation, singleWorkTargetPreparation, mockWorkersConfigDiagnosticsLoader, sessionStartRequestFactory, openingPresentationOwner, v163)
	if err != nil {
		return nil, err
	}
	remoteInvocationOperation := provideRemoteInvocationOperation(wireStandardCLIHTTPProtocol)
	operations := provideACPCLIService(operatorsettingsService, service, idGenerator)
	chatsessionsService, err := provideChatSessionsService(eventsService, loggingLogger)
	if err != nil {
		return nil, err
	}
	catalogPathsService, err := wire5.NewCatalogPathsService(effectiveFactoryCatalogOperation, v, v4, loggingLogger)
	if err != nil {
		return nil, err
	}
	factoryTargetCatalogService, err := provideChatSessionsFactoryTargetCatalogService(operatorsettingsService, catalogPathsService, loggingLogger)
	if err != nil {
		return nil, err
	}
	wireAcpServerResolveHomeDir := provideACPServerResolveHomeDir(edges2)
	v166 := provideChatSessionsResponseBridge(chatsessionsService, factorysessionsService, eventsService, loggingLogger)
	responseBridge := provideACPServerResponseBridge(v166)
	v167, err := provideACPWireRecorder(edges2, reserver, wireRuntimeArtifactClock, wireAcpServerResolveHomeDir)
	if err != nil {
		return nil, err
	}
	factorySessionStartResolver := provideACPServerFactorySessionStartResolver(wireAcpServerResolveHomeDir, v, defaultsResolver, runtimeArtifactRootResolver)
	server := provideACPServer(loggingLogger, chatsessionsService, factoryTargetCatalogService, factorysessionsService, eventsService, wireAcpServerResolveHomeDir, responseBridge, v167, factorySessionStartResolver)
	operation := provideMetricsCLI()
	costReportOperation := provideCostsReportCLI()
	cliOperation := provideCostsCLI()
	serverstopOperation := provideServerStopCLI()
	commandOperations := cli.CommandOperations{
		ObserveCLI:                        cliObserver,
		NamedFactoryCatalog:               v,
		CompleteFactoryNames:              factoryNamesOperation,
		CompletePackagedFactoryNames:      packagedFactoryNamesOperation,
		CompleteSelectedFactorySignature:  selectedFactorySignatureOperation,
		ResolveNamedFactoryRoots:          namedFactoryRootsResolver,
		ResolveNamedFactoryCandidatePaths: namedFactoryCandidatePathsResolver,
		ResolveCurrentFactoryDir:          v4,
		ResolveFactoryConfigRoot:          factoryConfigRootResolver,
		LoadFactoryConfigFile:             factoryConfigFileLoader,
		WorkRequestFileLoader:             requestFileLoader,
		PrepareSingleWorkTarget:           singleWorkTargetPreparation,
		PrepareInvocationInput:            invocationInputPreparation,
		BuildTerminalLogger:               loggerBuilder,
		RunDefaults:                       v6,
		BatchInputFileSystem:              batchInputFileSystem,
		RunInputPathInspector:             pathInspector,
		RunDirectoryCreator:               directoryCreator,
		BrowserOpener:                     opener,
		ResolveOperatorDefaults:           defaultsResolver,
		LoadOperatorConfig:                configLoader,
		FactorySessions:                   factorysessionsService,
		ModelsCLI:                         cliService,
		ProvidersCLI:                      service2,
		SessionsCLI:                       sessionService,
		LocalSessionsCLI:                  localSessionsCLIService,
		SubmitWork:                        submitWorkOperation,
		SubmitBatch:                       submitBatchOperation,
		FlattenFactoryConfig:              flattenFactoryConfigOperation,
		ExpandFactoryConfig:               expandFactoryConfigOperation,
		InitFactory:                       v120,
		ConfigureInit:                     configureInitOperation,
		InstallPackagedFactory:            cliInstallPackagedFactoryOperation,
		QueryFactory:                      queryFactoryOperation,
		ListFactories:                     listFactoriesOperation,
		ValidateFactory:                   validateFactoryOperation,
		CreateFactoryFromFile:             createFactoryFromFileOperation,
		ReplaceFactoryCurrent:             replaceFactoryCurrentOperation,
		UpdateFactoryFromFile:             updateFactoryFromFileOperation,
		DeleteFactory:                     deleteFactoryOperation,
		ListWork:                          listWorkOperation,
		ListHumanApprovals:                listHumanApprovalsOperation,
		ShowHumanApproval:                 showHumanApprovalOperation,
		WatchWork:                         watchWorkOperation,
		ShowWork:                          showWorkOperation,
		MoveWork:                          moveWorkOperation,
		VisualizeWork:                     visualizeWorkOperation,
		ListWorkerSessions:                v156,
		ShowWorkerSession:                 v157,
		ReadWorkerSession:                 v158,
		StreamWorkerSession:               v159,
		InvokeWorkerSession:               v160,
		ContinueWorkerSession:             v161,
		InterruptWorkerSession:            v162,
		PauseWorkerSession:                pauseWorkerSessionOperation,
		ResumeWorkerSession:               resumeWorkerSessionOperation,
		CancelWorkerSession:               cancelWorkerSessionOperation,
		TerminateWorkerSession:            terminateWorkerSessionOperation,
		LocalWorkerSessions:               wireLocalWorkerSessionsBoundary,
		LocalWorkerSessionControls:        wireLocalWorkerSessionsBoundary,
		OpenRunSelection:                  selectionFactory,
		RemoteInvocation:                  remoteInvocationOperation,
		ResponsePresentation:              v165,
		ACP:                               operations,
		ACPServer:                         server,
		RuntimeMetricsQuery:               runtimeMetricsQuery,
		MetricsCLI:                        operation,
		MetricsCostReportCLI:              costReportOperation,
		CostsCLI:                          cliOperation,
		ServerStopCLI:                     serverstopOperation,
	}
	v168 := provideSessionListPreparation(factorysessionsService)
	v169 := provideCommandDiagnostics()
	sessionResolvedHandlers := provideSessionResolvedHandlers(localSessionsCLIService, sessionService, v168, v169)
	factoryConfigInitHandler := provideFactoryConfigInitHandler(queryFactoryOperation, listFactoriesOperation, createFactoryFromFileOperation, updateFactoryFromFileOperation, deleteFactoryOperation, replaceFactoryCurrentOperation, validateFactoryOperation, flattenFactoryConfigOperation, expandFactoryConfigOperation, configureInitOperation, cliInstallPackagedFactoryOperation, namedFactoryRootsResolver, v169)
	commandFactory := provideCLICommandFactory(commandOperations, sessionResolvedHandlers, factoryConfigInitHandler)
	stdioOpener := stdio.NewOpener()
	wireMcpServerBuilder := provideMCPServerBuilder(workingDirectory, operatorsettingsService, service, fileSystem, homeDirectoryResolver)
	stdioHandler, err := provideStdioHandler(factorysessionsService, recordingsService, lifecycleRunnerBuilder, runnerFactory, stdioOpener, wireMcpServerBuilder, v150, workflowPreviewOperation)
	if err != nil {
		return nil, err
	}
	v170 := provideSystemInitializationInspectPath(edges2)
	systeminitializationService, err := provideSystemInitializationService(v106, packagedInstallationFileSystem, packagedInstallationDirectoryCreator, packagedFactoryCatalogOperations, operatorsettingsService, v170, loggingLogger)
	if err != nil {
		return nil, err
	}
	systemInitializationOperation := provideSystemInitializationOperation(systeminitializationService)
	initializer, err := application.NewInitializer(stdioHandler, systemInitializationOperation)
	if err != nil {
		return nil, err
	}
	providerRegistry, err := provideProviderRegistry(edges2, service)
	if err != nil {
		return nil, err
	}
	processLifecycle, err := provideApplicationProcessLifecycle(service, modelsService, eventsService, factorysessionsService, wireLocalWorkerSessionsBoundary, factoryRuntimeMetricsOwner)
	if err != nil {
		return nil, err
	}
	workerRecordingReader, err := provideWorkerRecordingReader(v46)
	if err != nil {
		return nil, err
	}
	processFactorySessionsCapability, err := provideFactorySessionsCapability(factorysessionsService)
	if err != nil {
		return nil, err
	}
	processRuntimeMetricsQueryCapability, err := provideRuntimeMetricsQueryCapability(runtimeMetricsQuery)
	if err != nil {
		return nil, err
	}
	processRuntimeCostsQueryCapability, err := provideCostsQueryCapability(costsQuery)
	if err != nil {
		return nil, err
	}
	process, err := application.NewProcessWithRuntimeCosts(commandFactory, initializer, providerRegistry, processLifecycle, server, workerRecordingReader, processFactorySessionsCapability, processRuntimeMetricsQueryCapability, processRuntimeCostsQueryCapability)
	if err != nil {
		return nil, err
	}
	return process, nil
}

// wire.go:

var platformSet = wire10.NewSet(
	provideProcessLogger,
)

var apiSet = wire10.NewSet(http.NewAdapter, http.NewHandler, stdio.NewOpener, provideHTTPRuntimeBindingWithMetrics)

var servicesSet = wire10.NewSet(
	provideProvidersService,
	provideEventsService,
	provideWorkerRecordingWriter,
	provideWorkerSessionRecorder,
	provideWorkerRecordingReader,
	provideWorkerSessionsFactoryWithRecorder,
	provideApplicationProcessLifecycle,
	provideProviderRegistry,
	provideFactorySessionProviderIdentityResolver, wire2.NewRequestPreparation, wire2.NewLiveChangeCoordinator, wire2.NewIdentity, wire2.NewResponseStreams, wire2.NewSessionRegistry, wire2.NewResponseStreamRegistry, wire2.NewSessionState, wire2.NewInvocationAuthority, wire2.NewScopeControl, provideInvocationWorldStateProjector, wire2.NewStreamObserver, wire2.NewStreamManager, provideFactorySessionHTTPRequestPreparation, factory.NewFactoryStatusProjector, factory.NewSessionResultProjectionOperation, provideOperatorSettingsFileSystem,
	provideOperatorSettingsCreateTemporaryFile,
	provideOperatorSettingsProviderCatalog,
	provideOperatorSettingsLogger,
	provideChatSessionsService, wire.NewDocumentService, wire.NewResolutionService, wire.NewService, wire.NewCLIService, provideOperatorSettingsDocumentPreserver,
	provideOperatorSettingsIDGenerator,
	provideChatSessionsFactoryTargetCatalogService,
	provideACPServerFactorySessionStartResolver,
	provideACPServerResolveHomeDir,
	provideChatSessionsResponseBridge,
	provideACPServerResponseBridge,
	provideACPServer,
	provideACPWireRecorder,
	provideOperatorConfigDecoder,
	provideOperatorConfigDiagnosticsDecoder,
	provideOperatorConfigEncoder,
	provideSystemInitializationInspectPath,
	provideOperatorConfigLoader,
	provideOperatorBackendScopeEnsurer,
	provideDurableExecutionFactory,
	provideAPIServerStarter,
	provideRuntimeHostOperation,
	provideProcessRuntimeFactory, wire2.NewLifecyclePlanOperation, provideFactoryVisualizationFactory,
	provideResponsePresentation, wire9.NewRuntimeSinkOwner, wire2.NewOpeningPresentationOwner, provideWorkContentStagingService, work.NewContentPreparation, work.NewRequestPreparationService, work.NewSingleWorkTargetPreparation, work.NewListRequestPreparation, work.NewFactoryRequestBatchPreparation, work.NewInvocationInputPreparation, provideWorkersMockWorkersConfigFileSystem,
	provideWorkersMockWorkersConfigDiagnosticsLoader,
	provideRuntimeArtifactClock,
	provideRuntimeArtifactIDGenerator,
	provideRuntimeArtifactPathReserver,
	provideRuntimeMetricsCoordination,
	provideRuntimeMetricsRetentionFileSystem,
	provideRuntimeArtifactRootResolver,
	provideRuntimeLoggerFactory,
	provideRuntimeLogOwner,
	provideRuntimeMetricsOwner,
	provideManagedRunnerFactory,
	provideModelAssetHTTP,
	provideModelAssetMakeDirectories,
	provideModelAssetInspectPath,
	provideModelAssetResolveHomeDirectory,
	provideModelAssetWriteFile,
	provideModelAssetRenamePath,
	provideModelAssetRemovePath,
	provideModelAssetReadFile,
	provideModelAssetReadDirectory,
	provideModelAssetCreateFile,
	provideModelAssetOpenFile,
	provideModelAssetResolveEnvironment,
	provideModelHostHTTP,
	provideModelRuntimeHTTP,
	provideModelRuntimeInspectFile,
	provideModelRuntimeTempDirectory,
	provideModelAssetEndpoints,
	provideModelAssetCoordination,
	provideModelHostClock,
	provideModelNow,
	provideModelRuntimeRunner,
	provideModelRuntimeTempFile,
	provideModelHostLauncher,
	provideModelOrderedRuntimeEvidence,
	provideModelRuntimeEvidenceSource,
	provideModelHostSymlinks,
	provideModelHostProtocol,
	provideModelHostCompatibility,
	provideModelBackendArtifactResolver,
	provideModelAssetRevision,
	provideModelRuntimeScopes,
	provideModelAssets,
	provideModelSlotFacts,
	provideModelHostLogger,
	provideModelHostMetrics,
	provideModelSlotCoordinator,
	provideModelRuntimeHost,
	provideModelInvocationRuntime,
	provideModelInference,
	provideModelsService, wire6.NewCatalogReadinessQuery, wire6.NewCatalog, wire6.NewSlotState, wire6.NewHostLeases, provideModelAssetHostPlatform,
	provideFactorySessionsWorkingDirectory,
	provideFactorySessionDirectoryInspection,
	provideFactorySessionResolveLogicalTargetSymlinks,
	provideFactorySessionContractFixtureReader,
	provideFactorySessionInvocationInputReader,
	provideFactorySessionReplayRecordingReader,
	provideRecordingOpenFile,
	provideRecordedSessionInventory,
	provideFactorySessionInitialWorkReader,
	provideFactorySessionResolveHomeDirectory,
	provideFactorySessionIDGenerator,
	provideFactorySessionRuntimeInstanceIDGenerator,
	provideFactorySessionResponseEventIDGenerator,
	provideFactorySessionResponseEventRetentionLimits,
	provideFactorySessionCursorPersistenceFileSystem,
	provideFactorySessionCursorCreateTemporaryFile,
	provideFactorySessionCursorStoreFactory,
	provideFactorySessionRuntimePersistenceFileSystem,
	provideFactorySessionRuntimePersistenceStoreFactory,
	provideFactorySessionSyncWaitScheduler,
	provideModelInvocationArtifactExporter,
	provideModelInvocationTimeout,
	provideModelInvocationOperation,
	provideModelsCLIComposition,
	provideModelsCLIInputFileReader,
	provideModelsCLIOutputFileSystem,
	provideWorkService,
	provideWorkDurabilityReader,
	provideWorkRequestIDGenerator,
	provideWorkSubmittedFileReader,
	provideWorkSubmittedFilePathInspector,
	provideWorkContentHostPlatform,
	provideContentMaterializer,
	provideFactoryInvocationPolicyPorts,
	provideWorkersInferenceMediaFileReader,
	provideDecisionEnvelopeService,
	provideInvocationInterpolationService,
	provideInvocationOutputShapingService,
	provideInvocationWorkTypeService,
	provideQuorumPolicyService,
	provideWorkPropagationPolicyService,
	provideWorkstationExecutionPolicyService,
	provideTTSObservabilityService,
	provideAutomationHostedClock,
	provideAutomationHostedHTTPClient,
	provideAutomationHostedSecretResolver,
	provideAutomationHostedCheckpointStore,
	provideAutomationsCursorFileSystem,
	provideAutomationsHostedPollers,
	provideAutomationsClock,
	provideAutomationsScriptPollers,
	provideAutomationsOwner, wire7.NewCursorScopes, wire7.NewSourceLifecycle, wire7.NewReconciliation, wire7.NewCron, wire7.NewFilesystemWatchers, provideAutomationsCommandRunner,
	provideAutomationsRoot, wire10.Bind(new(automations.Service), new(automations.Root)), provideFactorySessionsAssembly,
	provideFactorySessionsCapability,
	provideFactoryVisualizationMetricsQuery,
	provideRuntimeMetricsQueryCapability,
	provideProviderPriceTableReader,
	provideCostsQuery,
	provideCostsQueryCapability,
	provideFactoryWebhookHTTPClient,
	provideFactoryWebhookSecretResolver,
	provideFactoryWebhookClock,
	provideFactoryWebhookDeadLetterAppender, wire8.NewService, providePortableRecordingWriter,
	provideOrchestrationJavaScriptExecution,
	provideOrchestrationCompilation,
	provideFactorySessionExecutionFactory,
	provideConductorInvocationWithProgressFactory,
	provideFactorySessionReplayInputs,
	provideRecordingClock,
	provideRecordingSnapshotWriter,
	provideRecordingPublication,
	provideRecordingReadFile, wire3.NewRuntimeLedgerRouter, wire3.RuntimeLedger, wire3.NewProjectionService, wire3.NewRecordingLifecycleOwner, wire3.NewCanonicalLedgerOwner, wire3.NewArtifactsExportOwner, wire3.NewReplayOwner, wire3.NewHistoricalQueryOwner, wire3.NewRecordingFlushTickerFactory, wire5.FactorySnapshotJSONDecoder, provideRecordingsRoot,
	provideRecordingsRuntimeScopeService,
	provideReplayArtifactStorage,
	provideFactoryRuntimeIDGenerator,
	provideFactoryRuntimeDirectories,
	provideFactoryRuntimeInputs,
	provideFactoryRuntimeInputDirectoryWalker,
	provideFactoryRuntimeWorkflowSources,
	provideFactoryRuntimeWorkflowSourceResolveSymlinks,
	provideFactoryRuntimeWorkflowHome,
	provideFactoryDefinitionPortableFileSystem,
	provideFactoryDefinitionLoadingFileSystem,
	provideFactoryDefinitionClock,
	provideFactoryDefinitionVersionFileSystem,
	provideFactoryDefinitionPackagedGoalPromptFileSystem,
	provideFactoryDefinitionPortableBundledFileInspection,
	provideFactoryDefinitionRequiredToolPathLookup,
	provideFactoryDefinitionRequiredToolVersionProbe,
	provideFactoryDefinitionRequiredToolChecker,
	provideFactoryDefinitionPersistenceFileSystem,
	provideFactoryDefinitionDirectoryReplacementStore,
	provideFactoryDefinitionNamedPathFileSystem,
	provideFactoryDefinitionNamedPathResolver,
	provideFactoryDefinitionNamedFactoryCatalogFileSystem,
	provideFactoryDefinitionPackagedInstallationFileSystem,
	provideFactoryDefinitionPackagedInstallationDirectoryCreator,
	providePackagedFactoryInstallation,
	provideFactoryDefinitionAuthoredReaderFileSystem,
	provideFactoryDefinitionAuthoredWriterFileSystem,
	provideFactoryDefinitionScaffoldFileSystem,
	provideFactoryDefinitionScaffoldOutput,
	provideFactoryDefinitionInputInboxSentinelEnsurer,
	providePortableBundledFilesMaterializer,
	providePortableBundledFileWritesValidator,
	providePortableBundledFilesCopier,
	providePortableBundledFileSourceResolver,
	providePortableBundledFilesApplier,
	provideFactoryStarterWorkApplier,
	providePortableBundledDocsPruner,
	provideFactoryDefinitionLoader,
	provideFactoryRuntimeClockResolver,
	provideFactoryRuntimeClock,
	provideFactoryRuntimeMetricsClock,
	providePprofCommandLineReader,
	provideFactoryRuntimeProviderOverride,
	provideFactoryRuntimeSubmissionRecorder,
	provideFactoryRuntimeDispatchRecorder,
	provideFactorySessionInvocationMetricsRecorder,
	provideFactoryRuntimeProviderCommandRunner,
	provideFactoryRuntimeScriptCommandRunner,
	provideFactoryRuntimeSessionLoggerFactory,
	provideWorkersRetryRandomSource,
	provideWorkersWorkstationFileSystem,
	provideWorkersProviderTemporaryFileSystem,
	provideAgyPTYAllocator,
	provideWorkersMockCommandRunnerFactory,
	provideWorkerCommandRunnerAdapter,
	provideFactoryDefinitionsRuntimeRouter,
	provideFactoryDefinitionsRoot,
	provideFactoryScaffoldInitializer,
	provideEditableFactoryValidator,
	provideInitialFactorySnapshotFactory, wire4.NewRuntimeFactory, wire4.NewAssembly, provideFactoryRuntimeRoot,
	provideRuntimeOrchestration,
	provideRuntimeDispatchPlanning, wire4.NewLifecycle, wire4.NewInstanceHost, wire4.NewRuntimeStopOperation, wire10.Bind(new(wire2.FactoryRuntimeAssembler), new(*wire4.Assembly)), wire10.Struct(new(wire2.ProviderSessionsPorts), "*"), wire10.Struct(new(wire2.FactoryRuntimePorts), "*"), wire10.Struct(new(wire2.FactoryDefinitionsPorts), "*"), wire10.Struct(new(wire2.FactorySessionsPorts), "*"), wire10.Struct(new(wire2.WorkPorts), "*"), wire10.Struct(new(wire2.AutomationsPorts), "*"), wire10.Struct(new(wire2.ModelsPorts), "*"), wire10.Struct(new(wire2.RecordingsPorts), "*"), wire10.Struct(new(wire2.WebhooksPorts), "*"), wire10.Struct(new(wire2.WorkersPorts), "*"), wire10.Struct(new(wire2.OperatorSettingsPorts), "*"), provideLoadedFactorySourceFactory,
	provideLoadedFactoryLoader,
	provideReplayArtifactLoader,
	provideReplayRuntimeConfigDecoder, wire2.NewRoot, provideFactorySessionsService,
)

var providerSessionServiceSet = wire10.NewSet(
	provideProviderSessions,
)

var factorySessionsServicesSet = wire10.NewSet(
	provideJavaScriptWorkflows,
)

var factoryDefinitionsServicesSet = wire10.NewSet(
	provideFactoryDefinitionCompilation,
	provideFactoryDefinitionRuntimeSnapshot,
	provideFactoryDefinitionValidationOwner,
	provideOrchestratorDefinitionValidator,
	provideFactoryDefinitionValidationService,
	provideFactoryDefinitionValidator,
	provideDefinitionValidationOperation,
	provideSubmittedDefinitionValidationOperation,
	provideAuthoredFactorySourceLoader,
	provideJavaScriptWorkflowDefinitions,
	provideWorkflowPreviewOperation,
	provideNamedFactoryCatalog,
	provideLoadedFactorySnapshotCapturer,
	provideFactoryScaffoldCommandInitializer,
	provideFactoryDefinitionPersistence,
	provideNamedFactoryPersistenceOperation,
	provideEffectiveFactoryCatalogDiscovery,
	provideEffectiveFactoryDefinitionNormalizer,
	provideEffectiveFactoryCatalogOperation,
	provideEffectiveFactoryDefinitionsService, wire5.NewCatalogPathsService, wire5.NewCatalogService,
)

var workerServiceSet = wire10.NewSet(
	provideStatelessWorkersService,
	provideWorkersAgentToolFileSystem,
	provideWorkersWorktree,
	provideWorkersWorktreeRelease,
	provideWorkersFactoryDocsFileSystem,
	provideProviderFromCommandRunnerFactory,
	provideWorkerProcessEnvironment,
	provideWorkerCurrentWorkingDirectory,
)

var cliCommandOperationsSet = wire10.NewSet(
	provideCLIObserver,
	provideNamedFactoryRootsResolver,
	provideNamedFactoryCandidatePathsResolver,
	provideBatchInputFileSystem,
	provideRunInputPathInspector,
	provideRunDirectoryCreator,
	provideBrowserOpener,
	provideCurrentFactoryDirectoryResolver,
	provideFactoryConfigRootResolver,
	provideFactoryConfigFileLoader,
	provideWorkRequestFileLoader,
	provideTerminalLoggerBuilder,
	provideLiveRecordingTargetPlanner,
	provideRecordingsCLIAdapter,
	provideCLIRunDefaults,
	provideSubmitPayloadReader,
	provideOperatorDefaultsResolver,
	provideStandardCLIHTTPProtocol,
	provideModelsPullCLIHTTPProtocol,
	provideMetricsCLI,
	provideCostsCLI,
	provideCostsReportCLI,
	provideServerStopCLI,
	provideRemoteInvocationOperation,
	provideExtendedCLIHTTPProtocol,
	provideWatchCLIHTTPProtocol,
	provideStreamingCLIHTTPProtocol,
	provideSubmitWorkOperation,
	provideSubmitBatchOperation,
	provideListWorkerSessionsOperation,
	provideShowWorkerSessionOperation,
	provideReadWorkerSessionOperation,
	provideStreamWorkerSessionOperation,
	provideWorkerSessionsCLIIdentityGenerator,
	provideWorkerSessionsCLIExecutionFileReader,
	provideContinueWorkerSessionOperation,
	provideInterruptWorkerSessionOperation,
	providePauseWorkerSessionOperation,
	provideResumeWorkerSessionOperation,
	provideCancelWorkerSessionOperation,
	provideTerminateWorkerSessionOperation,
	provideLocalWorkerSessionsBoundary, wire10.Bind(new(workersessions.LocalInvokeBoundary), new(*localWorkerSessionsBoundary)), wire10.Bind(new(workersessions.LocalControlBoundary), new(*localWorkerSessionsBoundary)), provideInvokeWorkerSessionOperation,
	provideSessionsCLIService,
	provideSessionListPreparation,
	provideCommandDiagnostics,
	provideSessionResolvedHandlers,
	provideFactoryConfigInitHandler,
	provideLocalSessionsCLIService,
	provideModelsCLIService,
	provideProvidersCLIService,
	provideFlattenFactoryConfigOperation,
	provideExpandFactoryConfigOperation,
	provideConfigureInitOperation,
	provideACPCLIService,
	provideInstallPackagedFactoryOperation,
	provideInstallPackagedFactoryCLI,
	provideQueryFactoryOperation,
	provideCurrentFactoryPointerReader,
	provideListFactoriesOperation,
	provideFactoryNameCompletionOperation,
	providePackagedFactoryNameCompletionOperation,
	provideSelectedFactorySignatureCompletionOperation,
	provideValidateFactoryOperation,
	provideCreateFactoryFromFileOperation,
	provideReplaceFactoryCurrentOperation,
	provideUpdateFactoryFromFileOperation,
	provideDeleteFactoryOperation,
	provideListWorkOperation,
	provideListHumanApprovalsOperation,
	provideShowHumanApprovalOperation,
	provideWatchReconnectWait,
	provideWatchWorkOperation,
	provideShowWorkOperation,
	provideMoveWorkOperation,
	provideWorkVisualizationOperation,
	provideVisualizeWorkOperation, wire10.Struct(new(cli.CommandOperations), "*"),
)

// BundleSet is the one canonical provider set used by the single public bundle
// injector. It constructs only inert command and service initializers.
var BundleSet = wire10.NewSet(
	platformSet,
	apiSet,
	servicesSet,
	providerSessionServiceSet,
	factorySessionsServicesSet,
	factoryDefinitionsServicesSet,
	workerServiceSet,
	cliCommandOperationsSet,
	providePackagedFactoryDefinitions,
	providePackagedFactoryCatalog,
	provideSystemInitializationService,
	provideSystemInitializationOperation, wire10.Bind(new(factorydefinitions.Persistence), new(factorydefinitions.PackagedFactoryPersistence)), wire10.Bind(new(process.ACPServer), new(acp.Server)), provideLifecycleRunnerFactory,
	provideWorkStopSummaryProjector,
	provideSessionStartRequestFactory, application.NewLifecycleRunnerBuilder, provideRunRuntimeRunnerBuilder,
	provideRunSelectionFactory,
	provideInvocationOperation,
	provideMCPServerBuilder,
	provideStdioHandler,
	provideDirectJavaScriptHostAdapter, run.NewDirectJavaScriptRunOperation, application.NewInitializer, provideRunInvocationOperation,
	provideModelsCLIInvocationOperation,
	provideCLICommandFactory, application.NewProcessWithRuntimeCosts, wire10.Bind(new(process.Initializer), new(*application.Initializer)), wire10.Bind(new(process.CommandFactory), new(cli.CommandFactory)),
)
