// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	wire10 "github.com/google/wire"
	"github.com/portpowered/infinite-you/pkg/initializer/application"
	"github.com/portpowered/infinite-you/pkg/initializer/process"
	"github.com/portpowered/infinite-you/pkg/services/automations"
	wire7 "github.com/portpowered/infinite-you/pkg/services/automations/wire"
	"github.com/portpowered/infinite-you/pkg/services/edges"
	"github.com/portpowered/infinite-you/pkg/services/factory_definitions"
	wire4 "github.com/portpowered/infinite-you/pkg/services/factory_definitions/wire"
	"github.com/portpowered/infinite-you/pkg/services/factory_runtime"
	wire5 "github.com/portpowered/infinite-you/pkg/services/factory_runtime/wire"
	wire2 "github.com/portpowered/infinite-you/pkg/services/factory_sessions/wire"
	wire9 "github.com/portpowered/infinite-you/pkg/services/factory_visualization/wire"
	wire6 "github.com/portpowered/infinite-you/pkg/services/models/wire"
	"github.com/portpowered/infinite-you/pkg/services/operator_settings/wire"
	"github.com/portpowered/infinite-you/pkg/services/provider_sessions/transports/http"
	wire3 "github.com/portpowered/infinite-you/pkg/services/recordings/wire"
	wire8 "github.com/portpowered/infinite-you/pkg/services/webhooks/wire"
	"github.com/portpowered/infinite-you/pkg/services/work"
	"github.com/portpowered/infinite-you/pkg/services/worker_sessions/transports/cli/worker_sessions"
	"github.com/portpowered/infinite-you/pkg/transports/acp"
	"github.com/portpowered/infinite-you/pkg/transports/cli"
	"github.com/portpowered/infinite-you/pkg/transports/cli/run"
	"github.com/portpowered/infinite-you/pkg/transports/mcp/stdio"
)

// Injectors from wire.go:

// InjectBundle is the single application-process injector. Callers provide
// production defaults or functional overrides through the same typed inputs.
func InjectBundle(ctx context.Context, edges2 edges.Edges) (*application.Process, error) {
	cliObserver := provideCLIObserver(edges2)
	namedPathFileSystem := provideFactoryDefinitionNamedPathFileSystem(edges2)
	namedPathResolver, err := provideFactoryDefinitionNamedPathResolver(namedPathFileSystem)
	if err != nil {
		return nil, err
	}
	namedFactoryCatalogFileSystem := provideFactoryDefinitionNamedFactoryCatalogFileSystem(edges2)
	v, err := provideNamedFactoryCatalog(namedPathResolver, namedFactoryCatalogFileSystem)
	if err != nil {
		return nil, err
	}
	authoredLayoutReaderFileSystem := provideFactoryDefinitionAuthoredReaderFileSystem(edges2)
	v2, err := providePackagedFactoryDefinitions()
	if err != nil {
		return nil, err
	}
	effectiveFactoryCatalogDiscovery, err := provideEffectiveFactoryCatalogDiscovery(v, authoredLayoutReaderFileSystem, v2)
	if err != nil {
		return nil, err
	}
	effectiveFactoryDefinitionNormalizer := provideEffectiveFactoryDefinitionNormalizer()
	effectiveFactoryCatalogOperation, err := provideEffectiveFactoryCatalogOperation(effectiveFactoryCatalogDiscovery, effectiveFactoryDefinitionNormalizer)
	if err != nil {
		return nil, err
	}
	v3, err := provideEffectiveFactoryDefinitionsService(effectiveFactoryCatalogOperation)
	if err != nil {
		return nil, err
	}
	factoryNamesOperation := provideFactoryNameCompletionOperation(v3)
	packagedFactoryCatalogOperations, err := providePackagedFactoryCatalog(v2)
	if err != nil {
		return nil, err
	}
	packagedFactoryNamesOperation := providePackagedFactoryNameCompletionOperation(packagedFactoryCatalogOperations)
	selectedFactorySignatureOperation, err := provideSelectedFactorySignatureCompletionOperation(v3)
	if err != nil {
		return nil, err
	}
	namedFactoryRootsResolver := provideNamedFactoryRootsResolver()
	namedFactoryCandidatePathsResolver := provideNamedFactoryCandidatePathsResolver(namedPathResolver)
	v4 := provideCurrentFactoryDirectoryResolver(namedPathResolver)
	factoryConfigRootResolver := provideFactoryConfigRootResolver(authoredLayoutReaderFileSystem)
	authoredFactorySourceLoader := provideAuthoredFactorySourceLoader(authoredLayoutReaderFileSystem)
	factoryConfigFileLoader := provideFactoryConfigFileLoader(authoredFactorySourceLoader)
	requestFileLoader := provideWorkRequestFileLoader()
	singleWorkTargetPreparation := work.NewSingleWorkTargetPreparation()
	submittedFileReader := provideWorkSubmittedFileReader(edges2)
	submittedFilePathInspector := provideWorkSubmittedFilePathInspector(edges2)
	invocationInputPreparation := work.NewInvocationInputPreparation(submittedFileReader, submittedFilePathInspector)
	loggerBuilder := provideTerminalLoggerBuilder()
	reserver, err := provideRuntimeArtifactPathReserver()
	if err != nil {
		return nil, err
	}
	v5 := provideLiveRecordingTargetPlanner(reserver)
	adapter := provideRecordingsCLIAdapter()
	v6 := provideCLIRunDefaults(v5, adapter)
	batchInputFileSystem := provideBatchInputFileSystem()
	pathInspector := provideRunInputPathInspector()
	directoryCreator := provideRunDirectoryCreator()
	opener := provideBrowserOpener(edges2)
	fileSystem := provideOperatorSettingsFileSystem(edges2)
	createTemporaryFile := provideOperatorSettingsCreateTemporaryFile(edges2)
	configDecoder := provideOperatorConfigDecoder()
	configEncoder := provideOperatorConfigEncoder()
	service, err := provideProvidersService(edges2)
	if err != nil {
		return nil, err
	}
	providerCatalog := provideOperatorSettingsProviderCatalog(service)
	configDocumentPreserver := provideOperatorSettingsDocumentPreserver()
	configDiagnosticsDecoder := provideOperatorConfigDiagnosticsDecoder()
	v7 := wire.NewDocumentService(fileSystem, createTemporaryFile, configDecoder, configEncoder, providerCatalog, configDocumentPreserver, configDiagnosticsDecoder)
	v8, err := wire.NewResolutionService(service)
	if err != nil {
		return nil, err
	}
	idGenerator := provideOperatorSettingsIDGenerator(edges2)
	logger, err := provideProcessLogger(edges2)
	if err != nil {
		return nil, err
	}
	loggingLogger := provideOperatorSettingsLogger(logger)
	operatorsettingsService, err := wire.NewService(v7, v8, fileSystem, createTemporaryFile, configDecoder, configEncoder, idGenerator, loggingLogger, configDiagnosticsDecoder)
	if err != nil {
		return nil, err
	}
	defaultsResolver := provideOperatorDefaultsResolver(operatorsettingsService)
	configLoader := provideOperatorConfigLoader(operatorsettingsService)
	v9 := wire2.NewSessionRegistry()
	responseEventIDGenerator := provideFactorySessionResponseEventIDGenerator(edges2)
	responseEventRetentionLimits := provideFactorySessionResponseEventRetentionLimits(edges2)
	eventsService, err := provideEventsService(loggingLogger)
	if err != nil {
		return nil, err
	}
	v10, err := wire2.NewResponseStreams(responseEventIDGenerator, responseEventRetentionLimits, eventsService, loggingLogger)
	if err != nil {
		return nil, err
	}
	clock := provideFactoryRuntimeClock(edges2)
	v11, err := wire2.NewResponseStreamRegistry(v10, clock)
	if err != nil {
		return nil, err
	}
	v12 := provideFactorySessionIDGenerator(edges2)
	v13 := wire2.NewSessionState(v9, v11, clock, responseEventIDGenerator, v12, v10)
	v14 := wire2.NewStreamObserver()
	v15 := wire2.NewStreamManager(v13, v14, v11, v10)
	sessionResultProjectionOperation := factory.NewSessionResultProjectionOperation()
	invocationPolicyPorts, err := provideFactoryInvocationPolicyPorts()
	if err != nil {
		return nil, err
	}
	invocationInterpolationService := provideInvocationInterpolationService(invocationPolicyPorts)
	invocationWorkTypeService := provideInvocationWorkTypeService(invocationPolicyPorts)
	ttsObservabilityService := provideTTSObservabilityService(invocationPolicyPorts)
	homeDirectoryResolver := provideFactorySessionResolveHomeDirectory(edges2)
	v16 := provideFactorySessionDirectoryInspection(edges2)
	v17 := provideFactorySessionInvocationInputReader(edges2)
	v18 := provideFactorySessionInitialWorkReader(edges2)
	logicalTargetResolveSymlinks := provideFactorySessionResolveLogicalTargetSymlinks(edges2)
	v19, err := wire2.NewIdentity(logicalTargetResolveSymlinks, homeDirectoryResolver)
	if err != nil {
		return nil, err
	}
	v20 := wire2.NewLiveChangeCoordinator()
	storage := provideReplayArtifactStorage()
	v21 := provideReplayArtifactLoader(storage)
	v22 := provideFactorySessionReplayRecordingReader(edges2)
	v23 := provideRecordingOpenFile(edges2)
	replayInputLoader := provideFactorySessionReplayInputs(v21, v22, v23, loggingLogger)
	recordedSessionInventory := provideRecordedSessionInventory(edges2, replayInputLoader, loggingLogger)
	v24, err := provideFactorySessionsAssembly(v9, v13, v15, sessionResultProjectionOperation, invocationInterpolationService, invocationWorkTypeService, ttsObservabilityService, responseEventIDGenerator, v12, homeDirectoryResolver, v16, namedPathResolver, v17, v18, v19, v10, clock, v20, recordedSessionInventory)
	if err != nil {
		return nil, err
	}
	providersessionsService, err := provideProviderSessions(edges2)
	if err != nil {
		return nil, err
	}
	v25 := &wire2.ProviderSessionsPorts{
		Service: providersessionsService,
	}
	workflowSourceFileSystem := provideFactoryRuntimeWorkflowSources(edges2)
	workflowHomeResolver := provideFactoryRuntimeWorkflowHome(edges2)
	workflowSourceResolveSymlinks := provideFactoryRuntimeWorkflowSourceResolveSymlinks(edges2)
	javaScriptWorkflows := provideJavaScriptWorkflows(workflowSourceFileSystem, workflowHomeResolver, workflowSourceResolveSymlinks)
	javaScriptWorkflowDefinitions := provideJavaScriptWorkflowDefinitions(javaScriptWorkflows)
	workflowPreviewOperation := provideWorkflowPreviewOperation(javaScriptWorkflows)
	workersMockCommandRunnerFactory := provideWorkersMockCommandRunnerFactory()
	quorumPolicyService := provideQuorumPolicyService(invocationPolicyPorts)
	invocationOutputShapingService := provideInvocationOutputShapingService(invocationPolicyPorts)
	workPropagationPolicyService := provideWorkPropagationPolicyService(invocationPolicyPorts)
	contentStagingService, err := provideWorkContentStagingService(edges2)
	if err != nil {
		return nil, err
	}
	contentHostPlatform := provideWorkContentHostPlatform(edges2)
	contentMaterializer, err := provideContentMaterializer(contentHostPlatform, edges2)
	if err != nil {
		return nil, err
	}
	v26, err := provideRecordingClock(clock)
	if err != nil {
		return nil, err
	}
	v27 := wire3.NewRuntimeLedgerRouter(v26)
	v28 := wire3.RuntimeLedger(v27)
	v29 := wire3.NewProjectionService()
	v30 := provideRecordingReadFile(edges2)
	v31 := provideRecordingSnapshotWriter(edges2, storage, v30)
	v32 := wire3.NewRecordingFlushTickerFactory()
	v33 := wire3.NewRecordingLifecycleOwner(v5, v31, v32, v26)
	portableArtifactPublication, err := provideRecordingPublication(edges2)
	if err != nil {
		return nil, err
	}
	v34 := wire3.NewArtifactsExportOwner(v33, portableArtifactPublication)
	factorySnapshotJSONDecoder := wire4.FactorySnapshotJSONDecoder()
	v35 := wire3.NewReplayOwner(v33, v29, v30, factorySnapshotJSONDecoder)
	v36 := wire3.NewCanonicalLedgerOwner(v28)
	v37 := wire3.NewHistoricalQueryOwner(v30, v29)
	v38 := provideLoadedFactorySnapshotCapturer()
	replayRuntimeConfigDecoder := provideReplayRuntimeConfigDecoder()
	recordingsService := provideRecordingsRoot(edges2, v28, v29, v33, v34, v35, v36, v37, v26, loggingLogger, v27, v38, factorySnapshotJSONDecoder, replayRuntimeConfigDecoder, replayInputLoader)
	v39 := provideWorkDurabilityReader(recordingsService)
	workService := provideWorkService(v24, submittedFileReader, submittedFilePathInspector, contentStagingService, contentMaterializer, v39)
	decisionEnvelopeService := provideDecisionEnvelopeService(invocationPolicyPorts)
	runtimeLoggerFactory := provideRuntimeLoggerFactory()
	wireRuntimeArtifactClock := provideRuntimeArtifactClock()
	wireRuntimeArtifactIDGenerator := provideRuntimeArtifactIDGenerator()
	factoryRuntimeLogOwner, err := provideRuntimeLogOwner(logger, wireRuntimeArtifactClock, wireRuntimeArtifactIDGenerator, reserver)
	if err != nil {
		return nil, err
	}
	runtimeMetricsRetentionFileSystem := provideRuntimeMetricsRetentionFileSystem()
	runtimeMetricsCoordination, err := provideRuntimeMetricsCoordination()
	if err != nil {
		return nil, err
	}
	factoryRuntimeMetricsOwner, err := provideRuntimeMetricsOwner(logger, wireRuntimeArtifactClock, wireRuntimeArtifactIDGenerator, reserver, runtimeMetricsRetentionFileSystem, runtimeMetricsCoordination)
	if err != nil {
		return nil, err
	}
	factoryIDGenerator := provideFactoryRuntimeIDGenerator(edges2)
	requestIDGenerator := provideWorkRequestIDGenerator(edges2)
	runtimeDirectoryFileSystem := provideFactoryRuntimeDirectories(edges2)
	inputFileSystem := provideFactoryRuntimeInputs(edges2)
	inputDirectoryWalker := provideFactoryRuntimeInputDirectoryWalker(edges2)
	v40 := provideRuntimeOrchestration(factoryIDGenerator, javaScriptWorkflows)
	orchestrationCompilation := provideOrchestrationCompilation(v40)
	v41 := wire5.NewRuntimeFactory(quorumPolicyService, invocationOutputShapingService, workPropagationPolicyService, workService, decisionEnvelopeService, invocationInterpolationService, logger, runtimeLoggerFactory, factoryRuntimeLogOwner, factoryRuntimeMetricsOwner, factoryIDGenerator, requestIDGenerator, runtimeDirectoryFileSystem, inputFileSystem, inputDirectoryWalker, orchestrationCompilation, providersessionsService)
	v42, err := provideWorkerRecordingWriter(edges2)
	if err != nil {
		return nil, err
	}
	v43, err := provideWorkerSessionRecorder(eventsService, v42, loggingLogger)
	if err != nil {
		return nil, err
	}
	workerSessionsFactory := provideWorkerSessionsFactoryWithRecorder(eventsService, providersessionsService, loggingLogger, v43)
	v44, err := provideModelRuntimeScopes()
	if err != nil {
		return nil, err
	}
	assetHostPlatform := provideModelAssetHostPlatform(edges2)
	v45 := provideModelAssetHTTP(edges2)
	runtimeAssetEndpoints := provideModelAssetEndpoints(edges2)
	v46 := provideModelAssetMakeDirectories(edges2)
	v47 := provideModelAssetInspectPath(edges2)
	v48 := provideModelAssetResolveHomeDirectory(edges2)
	v49 := provideModelAssetWriteFile(edges2)
	v50 := provideModelAssetRenamePath(edges2)
	v51 := provideModelAssetRemovePath(edges2)
	v52 := provideModelAssetReadFile(edges2)
	v53 := provideModelAssetReadDirectory(edges2)
	v54 := provideModelAssetCreateFile(edges2)
	v55 := provideModelAssetOpenFile(edges2)
	v56 := provideModelAssetResolveEnvironment(edges2)
	wireModelAssetRevisionResolver := provideModelAssetRevision(edges2)
	v57, err := provideModelAssetCoordination(edges2)
	if err != nil {
		return nil, err
	}
	v58, err := provideModelAssets(v44, assetHostPlatform, v45, runtimeAssetEndpoints, v46, v47, v48, v49, v50, v51, v52, v53, v54, v55, v56, wireModelAssetRevisionResolver, v57)
	if err != nil {
		return nil, err
	}
	v59 := wire6.NewCatalogReadinessQuery(v58)
	v60, err := wire6.NewCatalog(v44, v59)
	if err != nil {
		return nil, err
	}
	v61 := provideModelHostClock(edges2)
	v62 := wire6.NewSlotState()
	v63 := provideModelSlotFacts(v62, v44, v58)
	v64 := provideModelHostLogger(logger)
	v65 := provideModelHostMetrics(edges2)
	v66 := provideModelSlotCoordinator(v62, v44, v61, v64, v65)
	v67, err := wire6.NewHostLeases(v61, v63, v66)
	if err != nil {
		return nil, err
	}
	wireModelRuntimeEvidenceSource, err := provideModelRuntimeEvidenceSource()
	if err != nil {
		return nil, err
	}
	v68 := provideModelHostLauncher(edges2, wireModelRuntimeEvidenceSource)
	v69 := provideModelHostHTTP(edges2)
	v70 := provideModelHostSymlinks()
	v71 := provideModelHostProtocol(edges2, v70)
	v72, err := provideModelHostCompatibility(edges2)
	if err != nil {
		return nil, err
	}
	v73 := provideModelOrderedRuntimeEvidence(wireModelRuntimeEvidenceSource)
	v74, err := provideModelRuntimeHost(v44, v58, v67, v62, v68, v69, v61, v64, v65, assetHostPlatform, v71, v72, v70, v73)
	if err != nil {
		return nil, err
	}
	wireModelRuntimeRunner, err := provideModelRuntimeRunner(edges2)
	if err != nil {
		return nil, err
	}
	v75 := provideModelRuntimeTempDirectory(edges2)
	v76 := provideModelRuntimeTempFile(edges2)
	v77 := provideModelRuntimeInspectFile(edges2)
	v78, err := provideModelInvocationRuntime(edges2, wireModelRuntimeRunner, v75, v76, v49, v77, v52, v51)
	if err != nil {
		return nil, err
	}
	wireModelNow := provideModelNow(edges2)
	v79, err := provideModelInference(v44, v58, v60, v74, v78, wireModelNow)
	if err != nil {
		return nil, err
	}
	v80 := provideModelRuntimeHTTP(edges2)
	v81, err := provideModelBackendArtifactResolver(edges2, wireModelRuntimeRunner, v45)
	if err != nil {
		return nil, err
	}
	modelsService, err := provideModelsService(edges2, v44, v58, v60, v74, v79, v68, v69, v61, wireModelRuntimeRunner, v80, v77, v75, v76, wireModelNow, v64, v65, v73, v81, assetHostPlatform, logger)
	if err != nil {
		return nil, err
	}
	readOpener := provideWorkersInferenceMediaFileReader(edges2)
	v82, err := provideFactoryRuntimeScriptCommandRunner(edges2)
	if err != nil {
		return nil, err
	}
	readFileTree := provideWorkersFactoryDocsFileSystem(edges2)
	factoryWorktreePreparer, err := provideWorkersWorktree(edges2)
	if err != nil {
		return nil, err
	}
	v83 := provideWorkersWorktreeRelease(factoryWorktreePreparer)
	temporaryFileSystem := provideWorkersProviderTemporaryFileSystem(edges2)
	v84 := provideFactoryRuntimeProviderOverride(edges2)
	agentToolFileSystem := provideWorkersAgentToolFileSystem(edges2)
	workersService, err := provideStatelessWorkersService(service, modelsService, contentMaterializer, readOpener, v82, readFileTree, clock, logger, factoryWorktreePreparer, v83, temporaryFileSystem, v84, agentToolFileSystem, decisionEnvelopeService)
	if err != nil {
		return nil, err
	}
	timerSource := provideFactoryRuntimeMetricsClock(edges2)
	v85, err := wire5.NewLifecycle(clock, timerSource)
	if err != nil {
		return nil, err
	}
	v86, err := wire5.NewInstanceHost(clock, timerSource, v85)
	if err != nil {
		return nil, err
	}
	v87 := provideRuntimePreparationWorkstationLoader()
	portablefilesFileSystem := provideFactoryDefinitionPortableFileSystem(edges2)
	v88, err := providePortableBundledFilesApplier(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	v89, err := provideFactoryStarterWorkApplier(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	v90 := providePortableBundledFilesMaterializer(portablefilesFileSystem)
	loadingFileSystem := provideFactoryDefinitionLoadingFileSystem(edges2)
	v91, err := providePortableBundledFileSourceResolver(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	portableBundledFileInspection := provideFactoryDefinitionPortableBundledFileInspection(edges2)
	requiredToolPathLookup := provideFactoryDefinitionRequiredToolPathLookup(edges2)
	requiredToolVersionProbe := provideFactoryDefinitionRequiredToolVersionProbe(edges2)
	v92, err := provideFactoryDefinitionRequiredToolChecker(requiredToolPathLookup, requiredToolVersionProbe)
	if err != nil {
		return nil, err
	}
	v93 := provideFactoryDefinitionLoader(v88, v89, v90, loadingFileSystem, namedPathResolver, authoredLayoutReaderFileSystem, v91, portableBundledFileInspection, v92)
	v94 := provideLoadedFactoryLoader(v93)
	v95 := wire5.NewRuntimePreparation(v87, v94, factoryIDGenerator, logger)
	fileReader := provideRuntimeRequestInvocationFiles(inputFileSystem)
	v96 := provideRuntimeRequestPrompts(workersService)
	v97 := provideRuntimeRequestTemplateFields(workersService)
	progressPublisher := provideRuntimeRequestProgress()
	expectedArtifactFileSystem := provideRuntimeRequestArtifactFiles(inputFileSystem)
	factoryLogger := provideRuntimeRequestLogger(logger, runtimeLoggerFactory)
	v98 := wire5.NewWorkstationRequestExecutor(workersService, invocationInterpolationService, fileReader, factoryIDGenerator, v96, v97, progressPublisher, expectedArtifactFileSystem, factoryLogger)
	v99, err := wire5.NewAssembly(v41, workerSessionsFactory, workersService, timerSource, v86, v95, v98)
	if err != nil {
		return nil, err
	}
	v100 := provideRuntimeDispatchPlanning()
	factoryRuntimeRoot, err := provideFactoryRuntimeRoot(v40, v86, v100)
	if err != nil {
		return nil, err
	}
	clockResolver := provideFactoryRuntimeClockResolver(clock)
	sessionLoggerFactory := provideFactoryRuntimeSessionLoggerFactory()
	v101 := provideFactoryRuntimeSubmissionRecorder(edges2)
	v102 := provideFactoryRuntimeDispatchRecorder(edges2)
	v103 := &wire2.FactoryRuntimePorts{
		Logger:                          logger,
		FactoryWorkflows:                javaScriptWorkflowDefinitions,
		WorkflowPreview:                 workflowPreviewOperation,
		WorkersMockCommandRunnerFactory: workersMockCommandRunnerFactory,
		FactoryRuntimeAssembler:         v99,
		RuntimeRoot:                     factoryRuntimeRoot,
		ResolveClock:                    clockResolver,
		NewSessionLogger:                sessionLoggerFactory,
		Clock:                           clock,
		ProviderOverride:                v84,
		SubmissionRecorder:              v101,
		DispatchRecorder:                v102,
	}
	v104 := provideFactoryDefinitionCompilation(v93)
	v105 := provideOrchestratorDefinitionValidator(javaScriptWorkflows)
	validationOperations := provideFactoryDefinitionValidationService(javaScriptWorkflows, v104, v105)
	v106 := provideFactoryDefinitionValidator(validationOperations)
	definitionRuntimeRouter := provideFactoryDefinitionsRuntimeRouter()
	v107, err := providePortableBundledDocsPruner(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	v108 := providePortableBundledFileWritesValidator(portablefilesFileSystem)
	v109 := providePortableBundledFilesCopier(portablefilesFileSystem)
	authoredLayoutWriterFileSystem := provideFactoryDefinitionAuthoredWriterFileSystem(edges2)
	inputInboxSentinelEnsurer := provideFactoryDefinitionInputInboxSentinelEnsurer(authoredLayoutWriterFileSystem)
	persistenceFileSystem := provideFactoryDefinitionPersistenceFileSystem(edges2)
	directoryReplacementStore := provideFactoryDefinitionDirectoryReplacementStore(edges2)
	v110, err := provideFactoryDefinitionPersistence(v106, v93, v107, v90, v108, v109, authoredLayoutWriterFileSystem, inputInboxSentinelEnsurer, persistenceFileSystem, namedPathResolver, directoryReplacementStore)
	if err != nil {
		return nil, err
	}
	v111 := provideFactoryDefinitionValidationOwner(validationOperations, v104, v92, v105)
	v112 := provideFactoryDefinitionRuntimeSnapshot(v93, definitionRuntimeRouter)
	v113 := wire4.NewCatalogService(namedPathResolver, namedFactoryCatalogFileSystem)
	factorydefinitionsClock := provideFactoryDefinitionClock(edges2)
	versionFileSystem := provideFactoryDefinitionVersionFileSystem(edges2)
	packagedInstallationFileSystem := provideFactoryDefinitionPackagedInstallationFileSystem(edges2)
	packagedInstallationDirectoryCreator := provideFactoryDefinitionPackagedInstallationDirectoryCreator(edges2)
	packagedFactoryInstallationOperations := providePackagedFactoryInstallation(v110, packagedInstallationFileSystem, packagedInstallationDirectoryCreator, loggingLogger)
	factorydefinitionsService, err := provideFactoryDefinitionsRoot(definitionRuntimeRouter, v106, v110, v93, v104, v111, v112, v88, v89, namedPathResolver, v113, factorydefinitionsClock, versionFileSystem, effectiveFactoryCatalogOperation, packagedFactoryCatalogOperations, packagedFactoryInstallationOperations, v92, v105, portablefilesFileSystem, directoryReplacementStore)
	if err != nil {
		return nil, err
	}
	initialFactorySnapshotFactory := provideInitialFactorySnapshotFactory(v88, v89)
	v114 := provideLoadedFactorySourceFactory()
	v115 := &wire2.FactoryDefinitionsPorts{
		Validator:                     v106,
		NamedPaths:                    namedPathResolver,
		Service:                       factorydefinitionsService,
		RuntimeRouter:                 definitionRuntimeRouter,
		InitialFactorySnapshotFactory: initialFactorySnapshotFactory,
		LoadFactory:                   v94,
		NewLoadedFactory:              v114,
		DecodeReplayConfig:            replayRuntimeConfigDecoder,
		CaptureLoadedFactorySnapshot:  v38,
	}
	durableExecutionFactory := provideDurableExecutionFactory(configLoader)
	orchestrationJavaScriptExecution := provideOrchestrationJavaScriptExecution(v40)
	v116, err := providePortableRecordingWriter(edges2)
	if err != nil {
		return nil, err
	}
	v117 := provideFactorySessionRuntimePersistenceFileSystem(edges2)
	v118 := provideFactorySessionRuntimePersistenceStoreFactory(v117)
	v119 := provideFactorySessionSyncWaitScheduler()
	v120, err := provideAgyPTYAllocator(edges2)
	if err != nil {
		return nil, err
	}
	v121 := provideWorkerCommandRunnerAdapter()
	v122 := provideFactorySessionExecutionFactory(javaScriptWorkflows, orchestrationJavaScriptExecution, v116, v118, v119, v12, responseEventIDGenerator, v10, v120, v121, v84, v20)
	scaffoldFileSystem := provideFactoryDefinitionScaffoldFileSystem(edges2)
	scaffoldOutput := provideFactoryDefinitionScaffoldOutput(edges2)
	v123, err := provideFactoryScaffoldCommandInitializer(scaffoldFileSystem, scaffoldOutput)
	if err != nil {
		return nil, err
	}
	factoryScaffoldInitializer := provideFactoryScaffoldInitializer(v123)
	v124 := provideDefinitionValidationOperation(validationOperations)
	editableFactoryValidator := provideEditableFactoryValidator(v124)
	commandLineReader := providePprofCommandLineReader()
	starter, err := provideAPIServerStarter(edges2, commandLineReader)
	if err != nil {
		return nil, err
	}
	v125 := provideRuntimeHostOperation(starter)
	processRuntimeFactory, err := provideProcessRuntimeFactory(v125)
	if err != nil {
		return nil, err
	}
	runtimeInstanceIDGenerator := provideFactorySessionRuntimeInstanceIDGenerator(edges2)
	providerIdentityResolver := provideFactorySessionProviderIdentityResolver(service)
	v126 := provideFactorySessionInvocationMetricsRecorder(edges2)
	v127 := &wire2.FactorySessionsPorts{
		RuntimeAssembly:                v24,
		DurableExecutionFactory:        durableExecutionFactory,
		FactorySessionExecutionFactory: v122,
		FactoryScaffoldInitializer:     factoryScaffoldInitializer,
		EditableFactoryValidator:       editableFactoryValidator,
		ProcessRuntimeFactory:          processRuntimeFactory,
		GenerateSessionID:              v12,
		GenerateRuntimeInstanceID:      runtimeInstanceIDGenerator,
		ResolveHome:                    homeDirectoryResolver,
		ProviderIdentities:             providerIdentityResolver,
		InvocationMetricsRecorder:      v126,
	}
	v128 := &wire2.WorkPorts{
		Service: workService,
	}
	v129 := provideAutomationsClock(clock)
	commandRunner, err := provideAutomationsCommandRunner(edges2)
	if err != nil {
		return nil, err
	}
	workstationExecutionPolicyService := provideWorkstationExecutionPolicyService(invocationPolicyPorts)
	v130 := provideAutomationsCursorFileSystem(edges2)
	v131 := wire7.NewCursorScopes(v130)
	v132 := provideAutomationsScriptPollers(logger, v129, commandRunner, workstationExecutionPolicyService, v131)
	v133 := wire7.NewCron()
	v134 := wire7.NewFilesystemWatchers()
	v135 := provideAutomationHostedClock(edges2)
	v136 := provideAutomationHostedHTTPClient(edges2)
	v137 := provideAutomationHostedSecretResolver(edges2)
	v138, err := provideAutomationHostedCheckpointStore(edges2)
	if err != nil {
		return nil, err
	}
	v139 := provideAutomationsHostedPollers(logger, v135, v136, v137, v138, edges2)
	v140 := wire7.NewSourceLifecycle(logger, v129, v132, v133, v134, v139, v131, workstationExecutionPolicyService)
	v141 := wire7.NewReconciliation(v140)
	v142 := provideAutomationsOwner(logger, v129, v140, v141, v132, v133, v134, v139, workstationExecutionPolicyService, v131)
	root := provideAutomationsRoot(v142)
	v143 := &wire2.AutomationsPorts{
		Service: root,
	}
	v144 := &wire2.ModelsPorts{
		Service: modelsService,
	}
	v145, err := provideRecordingsRuntimeScopeService(recordingsService)
	if err != nil {
		return nil, err
	}
	v146 := &wire2.RecordingsPorts{
		Service: recordingsService,
		Runtime: v145,
	}
	httpClient := provideFactoryWebhookHTTPClient(edges2)
	secretResolver := provideFactoryWebhookSecretResolver(edges2)
	wireClock := provideFactoryWebhookClock(edges2)
	deadLetterAppender := provideFactoryWebhookDeadLetterAppender(edges2)
	webhooksService := wire8.NewService(recordingsService, httpClient, secretResolver, wireClock, deadLetterAppender, loggingLogger)
	v147 := &wire2.WebhooksPorts{
		Service: webhooksService,
	}
	providerFromCommandRunnerFactory := provideProviderFromCommandRunnerFactory(service, edges2)
	providerCommandRunner, err := provideFactoryRuntimeProviderCommandRunner(edges2)
	if err != nil {
		return nil, err
	}
	v148 := &wire2.WorkersPorts{
		Service:                          workersService,
		ProviderFromCommandRunnerFactory: providerFromCommandRunnerFactory,
		ProviderCommandRunner:            providerCommandRunner,
		ScriptCommandRunner:              v82,
	}
	backendScopeEnsurer := provideOperatorBackendScopeEnsurer(operatorsettingsService)
	v149 := &wire2.OperatorSettingsPorts{
		EnsureBackendScope: backendScopeEnsurer,
	}
	v150, err := wire2.NewRoot(v25, v103, v115, v127, v128, v143, v144, v146, v147, v148, v149)
	if err != nil {
		return nil, err
	}
	factorysessionsService, err := provideFactorySessionsService(v24, v150, v20)
	if err != nil {
		return nil, err
	}
	wireStandardCLIHTTPProtocol, err := provideStandardCLIHTTPProtocol()
	if err != nil {
		return nil, err
	}
	wireModelsPullCLIHTTPProtocol, err := provideModelsPullCLIHTTPProtocol()
	if err != nil {
		return nil, err
	}
	workingDirectory := provideFactorySessionsWorkingDirectory(edges2)
	v151, err := provideModelInvocationArtifactExporter(edges2)
	if err != nil {
		return nil, err
	}
	modelInvocationTimeout := provideModelInvocationTimeout()
	runtimeArtifactRootResolver := provideRuntimeArtifactRootResolver()
	openingPresentationOwner := wire2.NewOpeningPresentationOwner()
	v152, err := provideInvocationOperation(factorysessionsService, modelsService, workingDirectory, v4, v151, modelInvocationTimeout, runtimeArtifactRootResolver, v12, logger, openingPresentationOwner)
	if err != nil {
		return nil, err
	}
	invocationOperation := provideModelsCLIInvocationOperation(v152)
	compositionScopeProvider, err := provideModelsCLIComposition(modelsService, v152, configLoader)
	if err != nil {
		return nil, err
	}
	outputFileSystem := provideModelsCLIOutputFileSystem(edges2)
	inputFileReader := provideModelsCLIInputFileReader(edges2)
	cliService := provideModelsCLIService(wireStandardCLIHTTPProtocol, wireModelsPullCLIHTTPProtocol, invocationOperation, compositionScopeProvider, outputFileSystem, inputFileReader, wireRuntimeArtifactClock)
	service2 := provideProvidersCLIService(service)
	v153 := wire2.NewRequestPreparation()
	sessionService := provideSessionsCLIService(wireStandardCLIHTTPProtocol, v153)
	localSessionsCLIService := provideLocalSessionsCLIService(factorysessionsService)
	payloadFileReader := provideSubmitPayloadReader()
	wireExtendedCLIHTTPProtocol, err := provideExtendedCLIHTTPProtocol()
	if err != nil {
		return nil, err
	}
	submitWorkOperation := provideSubmitWorkOperation(payloadFileReader, wireExtendedCLIHTTPProtocol)
	factoryRequestBatchPreparation := work.NewFactoryRequestBatchPreparation()
	submitBatchOperation := provideSubmitBatchOperation(wireExtendedCLIHTTPProtocol, factoryRequestBatchPreparation)
	flattenFactoryConfigOperation := provideFlattenFactoryConfigOperation(v110)
	expandFactoryConfigOperation := provideExpandFactoryConfigOperation(v110)
	service3 := wire.NewCLIService(operatorsettingsService)
	configureInitOperation, err := provideConfigureInitOperation(operatorsettingsService, service3)
	if err != nil {
		return nil, err
	}
	installPackagedFactoryOperation := provideInstallPackagedFactoryOperation(packagedFactoryCatalogOperations, packagedFactoryInstallationOperations)
	cliInstallPackagedFactoryOperation := provideInstallPackagedFactoryCLI(installPackagedFactoryOperation)
	queryFactoryOperation := provideQueryFactoryOperation(wireStandardCLIHTTPProtocol)
	v154 := provideCurrentFactoryPointerReader(namedPathResolver)
	listFactoriesOperation := provideListFactoriesOperation(v3, v154)
	v155 := provideSubmittedDefinitionValidationOperation(validationOperations)
	validateFactoryOperation, err := provideValidateFactoryOperation(v155, authoredFactorySourceLoader)
	if err != nil {
		return nil, err
	}
	v156 := provideNamedFactoryPersistenceOperation(v110)
	createFactoryFromFileOperation := provideCreateFactoryFromFileOperation(v156, authoredFactorySourceLoader)
	replaceFactoryCurrentOperation := provideReplaceFactoryCurrentOperation(wireStandardCLIHTTPProtocol)
	updateFactoryFromFileOperation := provideUpdateFactoryFromFileOperation(v156, authoredFactorySourceLoader)
	deleteFactoryOperation := provideDeleteFactoryOperation(v)
	listRequestPreparation := work.NewListRequestPreparation()
	listWorkOperation := provideListWorkOperation(wireStandardCLIHTTPProtocol, listRequestPreparation)
	listHumanApprovalsOperation := provideListHumanApprovalsOperation(wireStandardCLIHTTPProtocol)
	showHumanApprovalOperation := provideShowHumanApprovalOperation(wireStandardCLIHTTPProtocol)
	wireWatchCLIHTTPProtocol, err := provideWatchCLIHTTPProtocol()
	if err != nil {
		return nil, err
	}
	v157 := provideWatchReconnectWait()
	watchWorkOperation := provideWatchWorkOperation(wireWatchCLIHTTPProtocol, v157)
	showWorkOperation := provideShowWorkOperation(wireStandardCLIHTTPProtocol)
	moveWorkOperation := provideMoveWorkOperation(wireExtendedCLIHTTPProtocol)
	v158 := provideWorkVisualizationOperation()
	visualizeWorkOperation := provideVisualizeWorkOperation(v158)
	v159 := provideListWorkerSessionsOperation(wireStandardCLIHTTPProtocol)
	v160 := provideShowWorkerSessionOperation(wireStandardCLIHTTPProtocol)
	v161 := provideReadWorkerSessionOperation(wireStandardCLIHTTPProtocol)
	wireStreamingCLIHTTPProtocol, err := provideStreamingCLIHTTPProtocol()
	if err != nil {
		return nil, err
	}
	v162 := provideStreamWorkerSessionOperation(wireStreamingCLIHTTPProtocol)
	wireLocalWorkerSessionsBoundary, err := provideLocalWorkerSessionsBoundary(eventsService, providersessionsService, loggingLogger, workersService, v43)
	if err != nil {
		return nil, err
	}
	cliIDGenerator := provideWorkerSessionsCLIIdentityGenerator()
	executionFileReader := provideWorkerSessionsCLIExecutionFileReader()
	v163 := provideInvokeWorkerSessionOperation(wireStreamingCLIHTTPProtocol, wireLocalWorkerSessionsBoundary, cliIDGenerator, executionFileReader)
	v164 := provideContinueWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary, cliIDGenerator)
	v165 := provideInterruptWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary, cliIDGenerator)
	pauseWorkerSessionOperation := providePauseWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	resumeWorkerSessionOperation := provideResumeWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	cancelWorkerSessionOperation := provideCancelWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	terminateWorkerSessionOperation := provideTerminateWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	runtimeFactory := provideFactoryVisualizationFactory()
	v166 := wire9.NewRuntimeSinkOwner()
	factoryStatusProjector := factory.NewFactoryStatusProjector()
	httpAdapter := http.NewAdapter(providersessionsService)
	handler := http.NewHandler(httpAdapter, logger)
	contentPreparation := work.NewContentPreparation()
	requestPreparation := provideFactorySessionHTTPRequestPreparation(v153)
	runtimeMetricsQuery, err := provideFactoryVisualizationMetricsQuery(loggingLogger)
	if err != nil {
		return nil, err
	}
	priceTableReader, err := provideProviderPriceTableReader()
	if err != nil {
		return nil, err
	}
	costsQuery, err := provideCostsQuery(priceTableReader, operatorsettingsService, runtimeMetricsQuery, loggingLogger)
	if err != nil {
		return nil, err
	}
	wireHttpRuntimeBinding, err := provideHTTPRuntimeBindingWithMetrics(factoryStatusProjector, handler, contentPreparation, v155, invocationWorkTypeService, requestPreparation, runtimeMetricsQuery, costsQuery)
	if err != nil {
		return nil, err
	}
	runnerFactory := provideLifecycleRunnerFactory()
	v167 := wire2.NewLifecyclePlanOperation()
	runtimeRunnerBuilder, err := provideRunRuntimeRunnerBuilder(v150, edges2, runtimeFactory, v166, wireHttpRuntimeBinding, runnerFactory, v167)
	if err != nil {
		return nil, err
	}
	v168 := provideResponsePresentation()
	directJavaScriptHost, err := provideDirectJavaScriptHostAdapter(v155, invocationWorkTypeService, requestPreparation, starter, runnerFactory, logger)
	if err != nil {
		return nil, err
	}
	managedRunnerFactory := provideManagedRunnerFactory()
	lifecycleRunnerBuilder, err := application.NewLifecycleRunnerBuilder(managedRunnerFactory)
	if err != nil {
		return nil, err
	}
	directJavaScriptRunOperation, err := run.NewDirectJavaScriptRunOperation(factorysessionsService, v12, directJavaScriptHost, openingPresentationOwner, lifecycleRunnerBuilder)
	if err != nil {
		return nil, err
	}
	mockWorkersConfigFileSystem := provideWorkersMockWorkersConfigFileSystem(edges2)
	mockWorkersConfigDiagnosticsLoader, err := provideWorkersMockWorkersConfigDiagnosticsLoader(mockWorkersConfigFileSystem)
	if err != nil {
		return nil, err
	}
	sessionStartRequestFactory := provideSessionStartRequestFactory()
	selectionFactory, err := provideRunSelectionFactory(runtimeRunnerBuilder, v152, v168, directJavaScriptRunOperation, singleWorkTargetPreparation, mockWorkersConfigDiagnosticsLoader, sessionStartRequestFactory, openingPresentationOwner, v166)
	if err != nil {
		return nil, err
	}
	remoteInvocationOperation := provideRemoteInvocationOperation(wireStandardCLIHTTPProtocol)
	operations := provideACPCLIService(operatorsettingsService, service, idGenerator)
	chatsessionsService, err := provideChatSessionsService(eventsService, loggingLogger)
	if err != nil {
		return nil, err
	}
	catalogPathsService, err := wire4.NewCatalogPathsService(effectiveFactoryCatalogOperation, v, v4, loggingLogger)
	if err != nil {
		return nil, err
	}
	factoryTargetCatalogService, err := provideChatSessionsFactoryTargetCatalogService(operatorsettingsService, catalogPathsService, loggingLogger)
	if err != nil {
		return nil, err
	}
	wireAcpServerResolveHomeDir := provideACPServerResolveHomeDir(edges2)
	v169 := provideChatSessionsResponseBridge(chatsessionsService, factorysessionsService, eventsService, loggingLogger)
	responseBridge := provideACPServerResponseBridge(v169)
	v170, err := provideACPWireRecorder(edges2, reserver, wireRuntimeArtifactClock, wireAcpServerResolveHomeDir)
	if err != nil {
		return nil, err
	}
	factorySessionStartResolver := provideACPServerFactorySessionStartResolver(wireAcpServerResolveHomeDir, v, defaultsResolver, runtimeArtifactRootResolver)
	server := provideACPServer(loggingLogger, chatsessionsService, factoryTargetCatalogService, factorysessionsService, eventsService, wireAcpServerResolveHomeDir, responseBridge, v170, factorySessionStartResolver)
	operation := provideMetricsCLI()
	costReportOperation := provideCostsReportCLI()
	cliOperation := provideCostsCLI()
	serverstopOperation := provideServerStopCLI()
	commandOperations := cli.CommandOperations{
		ObserveCLI:                        cliObserver,
		NamedFactoryCatalog:               v,
		CompleteFactoryNames:              factoryNamesOperation,
		CompletePackagedFactoryNames:      packagedFactoryNamesOperation,
		CompleteSelectedFactorySignature:  selectedFactorySignatureOperation,
		ResolveNamedFactoryRoots:          namedFactoryRootsResolver,
		ResolveNamedFactoryCandidatePaths: namedFactoryCandidatePathsResolver,
		ResolveCurrentFactoryDir:          v4,
		ResolveFactoryConfigRoot:          factoryConfigRootResolver,
		LoadFactoryConfigFile:             factoryConfigFileLoader,
		WorkRequestFileLoader:             requestFileLoader,
		PrepareSingleWorkTarget:           singleWorkTargetPreparation,
		PrepareInvocationInput:            invocationInputPreparation,
		BuildTerminalLogger:               loggerBuilder,
		RunDefaults:                       v6,
		BatchInputFileSystem:              batchInputFileSystem,
		RunInputPathInspector:             pathInspector,
		RunDirectoryCreator:               directoryCreator,
		BrowserOpener:                     opener,
		ResolveOperatorDefaults:           defaultsResolver,
		LoadOperatorConfig:                configLoader,
		FactorySessions:                   factorysessionsService,
		ModelsCLI:                         cliService,
		ProvidersCLI:                      service2,
		SessionsCLI:                       sessionService,
		LocalSessionsCLI:                  localSessionsCLIService,
		SubmitWork:                        submitWorkOperation,
		SubmitBatch:                       submitBatchOperation,
		FlattenFactoryConfig:              flattenFactoryConfigOperation,
		ExpandFactoryConfig:               expandFactoryConfigOperation,
		InitFactory:                       v123,
		ConfigureInit:                     configureInitOperation,
		InstallPackagedFactory:            cliInstallPackagedFactoryOperation,
		QueryFactory:                      queryFactoryOperation,
		ListFactories:                     listFactoriesOperation,
		ValidateFactory:                   validateFactoryOperation,
		CreateFactoryFromFile:             createFactoryFromFileOperation,
		ReplaceFactoryCurrent:             replaceFactoryCurrentOperation,
		UpdateFactoryFromFile:             updateFactoryFromFileOperation,
		DeleteFactory:                     deleteFactoryOperation,
		ListWork:                          listWorkOperation,
		ListHumanApprovals:                listHumanApprovalsOperation,
		ShowHumanApproval:                 showHumanApprovalOperation,
		WatchWork:                         watchWorkOperation,
		ShowWork:                          showWorkOperation,
		MoveWork:                          moveWorkOperation,
		VisualizeWork:                     visualizeWorkOperation,
		ListWorkerSessions:                v159,
		ShowWorkerSession:                 v160,
		ReadWorkerSession:                 v161,
		StreamWorkerSession:               v162,
		InvokeWorkerSession:               v163,
		ContinueWorkerSession:             v164,
		InterruptWorkerSession:            v165,
		PauseWorkerSession:                pauseWorkerSessionOperation,
		ResumeWorkerSession:               resumeWorkerSessionOperation,
		CancelWorkerSession:               cancelWorkerSessionOperation,
		TerminateWorkerSession:            terminateWorkerSessionOperation,
		LocalWorkerSessions:               wireLocalWorkerSessionsBoundary,
		LocalWorkerSessionControls:        wireLocalWorkerSessionsBoundary,
		OpenRunSelection:                  selectionFactory,
		RemoteInvocation:                  remoteInvocationOperation,
		ResponsePresentation:              v168,
		ACP:                               operations,
		ACPServer:                         server,
		RuntimeMetricsQuery:               runtimeMetricsQuery,
		MetricsCLI:                        operation,
		MetricsCostReportCLI:              costReportOperation,
		CostsCLI:                          cliOperation,
		ServerStopCLI:                     serverstopOperation,
	}
	v171 := provideSessionListPreparation(factorysessionsService)
	v172 := provideCommandDiagnostics()
	sessionResolvedHandlers := provideSessionResolvedHandlers(localSessionsCLIService, sessionService, v171, v172)
	factoryConfigInitHandler := provideFactoryConfigInitHandler(queryFactoryOperation, listFactoriesOperation, createFactoryFromFileOperation, updateFactoryFromFileOperation, deleteFactoryOperation, replaceFactoryCurrentOperation, validateFactoryOperation, flattenFactoryConfigOperation, expandFactoryConfigOperation, configureInitOperation, cliInstallPackagedFactoryOperation, namedFactoryRootsResolver, v172)
	commandFactory := provideCLICommandFactory(commandOperations, sessionResolvedHandlers, factoryConfigInitHandler)
	stdioOpener := stdio.NewOpener()
	wireMcpServerBuilder := provideMCPServerBuilder(workingDirectory, operatorsettingsService, service, fileSystem, homeDirectoryResolver)
	stdioHandler, err := provideStdioHandler(factorysessionsService, recordingsService, lifecycleRunnerBuilder, runnerFactory, stdioOpener, wireMcpServerBuilder, v153, workflowPreviewOperation)
	if err != nil {
		return nil, err
	}
	v173 := provideSystemInitializationInspectPath(edges2)
	systeminitializationService, err := provideSystemInitializationService(v110, packagedInstallationFileSystem, packagedInstallationDirectoryCreator, packagedFactoryCatalogOperations, operatorsettingsService, v173, loggingLogger)
	if err != nil {
		return nil, err
	}
	systemInitializationOperation := provideSystemInitializationOperation(systeminitializationService)
	initializer, err := application.NewInitializer(stdioHandler, systemInitializationOperation)
	if err != nil {
		return nil, err
	}
	providerRegistry, err := provideProviderRegistry(edges2, service)
	if err != nil {
		return nil, err
	}
	processLifecycle, err := provideApplicationProcessLifecycle(service, modelsService, eventsService, factorysessionsService, wireLocalWorkerSessionsBoundary, factoryRuntimeMetricsOwner)
	if err != nil {
		return nil, err
	}
	workerRecordingReader, err := provideWorkerRecordingReader(v42)
	if err != nil {
		return nil, err
	}
	processFactorySessionsCapability, err := provideFactorySessionsCapability(factorysessionsService)
	if err != nil {
		return nil, err
	}
	processRuntimeMetricsQueryCapability, err := provideRuntimeMetricsQueryCapability(runtimeMetricsQuery)
	if err != nil {
		return nil, err
	}
	processRuntimeCostsQueryCapability, err := provideCostsQueryCapability(costsQuery)
	if err != nil {
		return nil, err
	}
	process, err := application.NewProcessWithRuntimeCosts(commandFactory, initializer, providerRegistry, processLifecycle, server, workerRecordingReader, processFactorySessionsCapability, processRuntimeMetricsQueryCapability, processRuntimeCostsQueryCapability)
	if err != nil {
		return nil, err
	}
	return process, nil
}

// wire.go:

var platformSet = wire10.NewSet(
	provideProcessLogger,
)

var apiSet = wire10.NewSet(http.NewAdapter, http.NewHandler, stdio.NewOpener, provideHTTPRuntimeBindingWithMetrics)

var servicesSet = wire10.NewSet(
	provideProvidersService,
	provideEventsService,
	provideWorkerRecordingWriter,
	provideWorkerSessionRecorder,
	provideWorkerRecordingReader,
	provideWorkerSessionsFactoryWithRecorder,
	provideApplicationProcessLifecycle,
	provideProviderRegistry,
	provideFactorySessionProviderIdentityResolver, wire2.NewRequestPreparation, wire2.NewLiveChangeCoordinator, wire2.NewIdentity, wire2.NewResponseStreams, wire2.NewSessionRegistry, wire2.NewResponseStreamRegistry, wire2.NewSessionState, wire2.NewStreamObserver, wire2.NewStreamManager, provideFactorySessionHTTPRequestPreparation, factory.NewFactoryStatusProjector, factory.NewSessionResultProjectionOperation, provideOperatorSettingsFileSystem,
	provideOperatorSettingsCreateTemporaryFile,
	provideOperatorSettingsProviderCatalog,
	provideOperatorSettingsLogger,
	provideChatSessionsService, wire.NewDocumentService, wire.NewResolutionService, wire.NewService, wire.NewCLIService, provideOperatorSettingsDocumentPreserver,
	provideOperatorSettingsIDGenerator,
	provideChatSessionsFactoryTargetCatalogService,
	provideACPServerFactorySessionStartResolver,
	provideACPServerResolveHomeDir,
	provideChatSessionsResponseBridge,
	provideACPServerResponseBridge,
	provideACPServer,
	provideACPWireRecorder,
	provideOperatorConfigDecoder,
	provideOperatorConfigDiagnosticsDecoder,
	provideOperatorConfigEncoder,
	provideSystemInitializationInspectPath,
	provideOperatorConfigLoader,
	provideOperatorBackendScopeEnsurer,
	provideDurableExecutionFactory,
	provideAPIServerStarter,
	provideRuntimeHostOperation,
	provideProcessRuntimeFactory, wire2.NewLifecyclePlanOperation, provideFactoryVisualizationFactory,
	provideResponsePresentation, wire9.NewRuntimeSinkOwner, wire2.NewOpeningPresentationOwner, provideWorkContentStagingService, work.NewContentPreparation, work.NewRequestPreparationService, work.NewSingleWorkTargetPreparation, work.NewListRequestPreparation, work.NewFactoryRequestBatchPreparation, work.NewInvocationInputPreparation, provideWorkersMockWorkersConfigFileSystem,
	provideWorkersMockWorkersConfigDiagnosticsLoader,
	provideRuntimeArtifactClock,
	provideRuntimeArtifactIDGenerator,
	provideRuntimeArtifactPathReserver,
	provideRuntimeMetricsCoordination,
	provideRuntimeMetricsRetentionFileSystem,
	provideRuntimeArtifactRootResolver,
	provideRuntimeLoggerFactory,
	provideRuntimeLogOwner,
	provideRuntimeMetricsOwner,
	provideManagedRunnerFactory,
	provideModelAssetHTTP,
	provideModelAssetMakeDirectories,
	provideModelAssetInspectPath,
	provideModelAssetResolveHomeDirectory,
	provideModelAssetWriteFile,
	provideModelAssetRenamePath,
	provideModelAssetRemovePath,
	provideModelAssetReadFile,
	provideModelAssetReadDirectory,
	provideModelAssetCreateFile,
	provideModelAssetOpenFile,
	provideModelAssetResolveEnvironment,
	provideModelHostHTTP,
	provideModelRuntimeHTTP,
	provideModelRuntimeInspectFile,
	provideModelRuntimeTempDirectory,
	provideModelAssetEndpoints,
	provideModelAssetCoordination,
	provideModelHostClock,
	provideModelNow,
	provideModelRuntimeRunner,
	provideModelRuntimeTempFile,
	provideModelHostLauncher,
	provideModelOrderedRuntimeEvidence,
	provideModelRuntimeEvidenceSource,
	provideModelHostSymlinks,
	provideModelHostProtocol,
	provideModelHostCompatibility,
	provideModelBackendArtifactResolver,
	provideModelAssetRevision,
	provideModelRuntimeScopes,
	provideModelAssets,
	provideModelSlotFacts,
	provideModelHostLogger,
	provideModelHostMetrics,
	provideModelSlotCoordinator,
	provideModelRuntimeHost,
	provideModelInvocationRuntime,
	provideModelInference,
	provideModelsService, wire6.NewCatalogReadinessQuery, wire6.NewCatalog, wire6.NewSlotState, wire6.NewHostLeases, provideModelAssetHostPlatform,
	provideFactorySessionsWorkingDirectory,
	provideFactorySessionDirectoryInspection,
	provideFactorySessionResolveLogicalTargetSymlinks,
	provideFactorySessionContractFixtureReader,
	provideFactorySessionInvocationInputReader,
	provideFactorySessionReplayRecordingReader,
	provideRecordingOpenFile,
	provideRecordedSessionInventory,
	provideFactorySessionInitialWorkReader,
	provideFactorySessionResolveHomeDirectory,
	provideFactorySessionIDGenerator,
	provideFactorySessionRuntimeInstanceIDGenerator,
	provideFactorySessionResponseEventIDGenerator,
	provideFactorySessionResponseEventRetentionLimits,
	provideFactorySessionCursorPersistenceFileSystem,
	provideFactorySessionCursorCreateTemporaryFile,
	provideFactorySessionCursorStoreFactory,
	provideFactorySessionRuntimePersistenceFileSystem,
	provideFactorySessionRuntimePersistenceStoreFactory,
	provideFactorySessionSyncWaitScheduler,
	provideModelInvocationArtifactExporter,
	provideModelInvocationTimeout,
	provideModelInvocationOperation,
	provideModelsCLIComposition,
	provideModelsCLIInputFileReader,
	provideModelsCLIOutputFileSystem,
	provideWorkService,
	provideWorkDurabilityReader,
	provideWorkRequestIDGenerator,
	provideWorkSubmittedFileReader,
	provideWorkSubmittedFilePathInspector,
	provideWorkContentHostPlatform,
	provideContentMaterializer,
	provideFactoryInvocationPolicyPorts,
	provideWorkersInferenceMediaFileReader,
	provideDecisionEnvelopeService,
	provideInvocationInterpolationService,
	provideInvocationOutputShapingService,
	provideInvocationWorkTypeService,
	provideQuorumPolicyService,
	provideWorkPropagationPolicyService,
	provideWorkstationExecutionPolicyService,
	provideTTSObservabilityService,
	provideAutomationHostedClock,
	provideAutomationHostedHTTPClient,
	provideAutomationHostedSecretResolver,
	provideAutomationHostedCheckpointStore,
	provideAutomationsCursorFileSystem,
	provideAutomationsHostedPollers,
	provideAutomationsClock,
	provideAutomationsScriptPollers,
	provideAutomationsOwner, wire7.NewCursorScopes, wire7.NewSourceLifecycle, wire7.NewReconciliation, wire7.NewCron, wire7.NewFilesystemWatchers, provideAutomationsCommandRunner,
	provideAutomationsRoot, wire10.Bind(new(automations.Service), new(automations.Root)), provideFactorySessionsAssembly,
	provideFactorySessionsCapability,
	provideFactoryVisualizationMetricsQuery,
	provideRuntimeMetricsQueryCapability,
	provideProviderPriceTableReader,
	provideCostsQuery,
	provideCostsQueryCapability,
	provideFactoryWebhookHTTPClient,
	provideFactoryWebhookSecretResolver,
	provideFactoryWebhookClock,
	provideFactoryWebhookDeadLetterAppender, wire8.NewService, providePortableRecordingWriter,
	provideOrchestrationJavaScriptExecution,
	provideOrchestrationCompilation,
	provideFactorySessionExecutionFactory,
	provideConductorInvocationWithProgressFactory,
	provideFactorySessionReplayInputs,
	provideRecordingClock,
	provideRecordingSnapshotWriter,
	provideRecordingPublication,
	provideRecordingReadFile, wire3.NewRuntimeLedgerRouter, wire3.RuntimeLedger, wire3.NewProjectionService, wire3.NewRecordingLifecycleOwner, wire3.NewCanonicalLedgerOwner, wire3.NewArtifactsExportOwner, wire3.NewReplayOwner, wire3.NewHistoricalQueryOwner, wire3.NewRecordingFlushTickerFactory, wire4.FactorySnapshotJSONDecoder, provideRecordingsRoot,
	provideRecordingsRuntimeScopeService,
	provideReplayArtifactStorage,
	provideFactoryRuntimeIDGenerator,
	provideFactoryRuntimeDirectories,
	provideFactoryRuntimeInputs,
	provideFactoryRuntimeInputDirectoryWalker,
	provideFactoryRuntimeWorkflowSources,
	provideFactoryRuntimeWorkflowSourceResolveSymlinks,
	provideFactoryRuntimeWorkflowHome,
	provideFactoryDefinitionPortableFileSystem,
	provideFactoryDefinitionLoadingFileSystem,
	provideFactoryDefinitionClock,
	provideFactoryDefinitionVersionFileSystem,
	provideFactoryDefinitionPackagedGoalPromptFileSystem,
	provideFactoryDefinitionPortableBundledFileInspection,
	provideFactoryDefinitionRequiredToolPathLookup,
	provideFactoryDefinitionRequiredToolVersionProbe,
	provideFactoryDefinitionRequiredToolChecker,
	provideFactoryDefinitionPersistenceFileSystem,
	provideFactoryDefinitionDirectoryReplacementStore,
	provideFactoryDefinitionNamedPathFileSystem,
	provideFactoryDefinitionNamedPathResolver,
	provideFactoryDefinitionNamedFactoryCatalogFileSystem,
	provideFactoryDefinitionPackagedInstallationFileSystem,
	provideFactoryDefinitionPackagedInstallationDirectoryCreator,
	providePackagedFactoryInstallation,
	provideFactoryDefinitionAuthoredReaderFileSystem,
	provideFactoryDefinitionAuthoredWriterFileSystem,
	provideFactoryDefinitionScaffoldFileSystem,
	provideFactoryDefinitionScaffoldOutput,
	provideFactoryDefinitionInputInboxSentinelEnsurer,
	providePortableBundledFilesMaterializer,
	providePortableBundledFileWritesValidator,
	providePortableBundledFilesCopier,
	providePortableBundledFileSourceResolver,
	providePortableBundledFilesApplier,
	provideFactoryStarterWorkApplier,
	providePortableBundledDocsPruner,
	provideFactoryDefinitionLoader,
	provideFactoryRuntimeClockResolver,
	provideFactoryRuntimeClock,
	provideFactoryRuntimeMetricsClock,
	providePprofCommandLineReader,
	provideFactoryRuntimeProviderOverride,
	provideFactoryRuntimeSubmissionRecorder,
	provideFactoryRuntimeDispatchRecorder,
	provideFactorySessionInvocationMetricsRecorder,
	provideFactoryRuntimeProviderCommandRunner,
	provideFactoryRuntimeScriptCommandRunner,
	provideFactoryRuntimeSessionLoggerFactory,
	provideWorkersRetryRandomSource,
	provideWorkersWorkstationFileSystem,
	provideWorkersProviderTemporaryFileSystem,
	provideAgyPTYAllocator,
	provideWorkersMockCommandRunnerFactory,
	provideWorkerCommandRunnerAdapter,
	provideFactoryDefinitionsRuntimeRouter,
	provideFactoryDefinitionsRoot,
	provideFactoryScaffoldInitializer,
	provideEditableFactoryValidator,
	provideInitialFactorySnapshotFactory, wire5.NewRuntimeFactory, provideRuntimePreparationWorkstationLoader, wire5.NewRuntimePreparation, provideRuntimeRequestInvocationFiles,
	provideRuntimeRequestPrompts,
	provideRuntimeRequestTemplateFields,
	provideRuntimeRequestArtifactFiles,
	provideRuntimeRequestProgress,
	provideRuntimeRequestLogger, wire5.NewWorkstationRequestExecutor, wire5.NewAssembly, provideFactoryRuntimeRoot,
	provideRuntimeOrchestration,
	provideRuntimeDispatchPlanning, wire5.NewLifecycle, wire5.NewInstanceHost, wire10.Bind(new(wire2.FactoryRuntimeAssembler), new(*wire5.Assembly)), wire10.Struct(new(wire2.ProviderSessionsPorts), "*"), wire10.Struct(new(wire2.FactoryRuntimePorts), "*"), wire10.Struct(new(wire2.FactoryDefinitionsPorts), "*"), wire10.Struct(new(wire2.FactorySessionsPorts), "*"), wire10.Struct(new(wire2.WorkPorts), "*"), wire10.Struct(new(wire2.AutomationsPorts), "*"), wire10.Struct(new(wire2.ModelsPorts), "*"), wire10.Struct(new(wire2.RecordingsPorts), "*"), wire10.Struct(new(wire2.WebhooksPorts), "*"), wire10.Struct(new(wire2.WorkersPorts), "*"), wire10.Struct(new(wire2.OperatorSettingsPorts), "*"), provideLoadedFactorySourceFactory,
	provideLoadedFactoryLoader,
	provideReplayArtifactLoader,
	provideReplayRuntimeConfigDecoder, wire2.NewRoot, provideFactorySessionsService,
)

var providerSessionServiceSet = wire10.NewSet(
	provideProviderSessions,
)

var factorySessionsServicesSet = wire10.NewSet(
	provideJavaScriptWorkflows,
)

var factoryDefinitionsServicesSet = wire10.NewSet(
	provideFactoryDefinitionCompilation,
	provideFactoryDefinitionRuntimeSnapshot,
	provideFactoryDefinitionValidationOwner,
	provideOrchestratorDefinitionValidator,
	provideFactoryDefinitionValidationService,
	provideFactoryDefinitionValidator,
	provideDefinitionValidationOperation,
	provideSubmittedDefinitionValidationOperation,
	provideAuthoredFactorySourceLoader,
	provideJavaScriptWorkflowDefinitions,
	provideWorkflowPreviewOperation,
	provideNamedFactoryCatalog,
	provideLoadedFactorySnapshotCapturer,
	provideFactoryScaffoldCommandInitializer,
	provideFactoryDefinitionPersistence,
	provideNamedFactoryPersistenceOperation,
	provideEffectiveFactoryCatalogDiscovery,
	provideEffectiveFactoryDefinitionNormalizer,
	provideEffectiveFactoryCatalogOperation,
	provideEffectiveFactoryDefinitionsService, wire4.NewCatalogPathsService, wire4.NewCatalogService,
)

var workerServiceSet = wire10.NewSet(
	provideStatelessWorkersService,
	provideWorkersAgentToolFileSystem,
	provideWorkersWorktree,
	provideWorkersWorktreeRelease,
	provideWorkersFactoryDocsFileSystem,
	provideProviderFromCommandRunnerFactory,
	provideWorkerProcessEnvironment,
	provideWorkerCurrentWorkingDirectory,
)

var cliCommandOperationsSet = wire10.NewSet(
	provideCLIObserver,
	provideNamedFactoryRootsResolver,
	provideNamedFactoryCandidatePathsResolver,
	provideBatchInputFileSystem,
	provideRunInputPathInspector,
	provideRunDirectoryCreator,
	provideBrowserOpener,
	provideCurrentFactoryDirectoryResolver,
	provideFactoryConfigRootResolver,
	provideFactoryConfigFileLoader,
	provideWorkRequestFileLoader,
	provideTerminalLoggerBuilder,
	provideLiveRecordingTargetPlanner,
	provideRecordingsCLIAdapter,
	provideCLIRunDefaults,
	provideSubmitPayloadReader,
	provideOperatorDefaultsResolver,
	provideStandardCLIHTTPProtocol,
	provideModelsPullCLIHTTPProtocol,
	provideMetricsCLI,
	provideCostsCLI,
	provideCostsReportCLI,
	provideServerStopCLI,
	provideRemoteInvocationOperation,
	provideExtendedCLIHTTPProtocol,
	provideWatchCLIHTTPProtocol,
	provideStreamingCLIHTTPProtocol,
	provideSubmitWorkOperation,
	provideSubmitBatchOperation,
	provideListWorkerSessionsOperation,
	provideShowWorkerSessionOperation,
	provideReadWorkerSessionOperation,
	provideStreamWorkerSessionOperation,
	provideWorkerSessionsCLIIdentityGenerator,
	provideWorkerSessionsCLIExecutionFileReader,
	provideContinueWorkerSessionOperation,
	provideInterruptWorkerSessionOperation,
	providePauseWorkerSessionOperation,
	provideResumeWorkerSessionOperation,
	provideCancelWorkerSessionOperation,
	provideTerminateWorkerSessionOperation,
	provideLocalWorkerSessionsBoundary, wire10.Bind(new(workersessions.LocalInvokeBoundary), new(*localWorkerSessionsBoundary)), wire10.Bind(new(workersessions.LocalControlBoundary), new(*localWorkerSessionsBoundary)), provideInvokeWorkerSessionOperation,
	provideSessionsCLIService,
	provideSessionListPreparation,
	provideCommandDiagnostics,
	provideSessionResolvedHandlers,
	provideFactoryConfigInitHandler,
	provideLocalSessionsCLIService,
	provideModelsCLIService,
	provideProvidersCLIService,
	provideFlattenFactoryConfigOperation,
	provideExpandFactoryConfigOperation,
	provideConfigureInitOperation,
	provideACPCLIService,
	provideInstallPackagedFactoryOperation,
	provideInstallPackagedFactoryCLI,
	provideQueryFactoryOperation,
	provideCurrentFactoryPointerReader,
	provideListFactoriesOperation,
	provideFactoryNameCompletionOperation,
	providePackagedFactoryNameCompletionOperation,
	provideSelectedFactorySignatureCompletionOperation,
	provideValidateFactoryOperation,
	provideCreateFactoryFromFileOperation,
	provideReplaceFactoryCurrentOperation,
	provideUpdateFactoryFromFileOperation,
	provideDeleteFactoryOperation,
	provideListWorkOperation,
	provideListHumanApprovalsOperation,
	provideShowHumanApprovalOperation,
	provideWatchReconnectWait,
	provideWatchWorkOperation,
	provideShowWorkOperation,
	provideMoveWorkOperation,
	provideWorkVisualizationOperation,
	provideVisualizeWorkOperation, wire10.Struct(new(cli.CommandOperations), "*"),
)

// BundleSet is the one canonical provider set used by the single public bundle
// injector. It constructs only inert command and service initializers.
var BundleSet = wire10.NewSet(
	platformSet,
	apiSet,
	servicesSet,
	providerSessionServiceSet,
	factorySessionsServicesSet,
	factoryDefinitionsServicesSet,
	workerServiceSet,
	cliCommandOperationsSet,
	providePackagedFactoryDefinitions,
	providePackagedFactoryCatalog,
	provideSystemInitializationService,
	provideSystemInitializationOperation, wire10.Bind(new(factorydefinitions.Persistence), new(factorydefinitions.PackagedFactoryPersistence)), wire10.Bind(new(process.ACPServer), new(acp.Server)), provideLifecycleRunnerFactory,
	provideWorkStopSummaryProjector,
	provideSessionStartRequestFactory, application.NewLifecycleRunnerBuilder, provideRunRuntimeRunnerBuilder,
	provideRunSelectionFactory,
	provideInvocationOperation,
	provideMCPServerBuilder,
	provideStdioHandler,
	provideDirectJavaScriptHostAdapter, run.NewDirectJavaScriptRunOperation, application.NewInitializer, provideRunInvocationOperation,
	provideModelsCLIInvocationOperation,
	provideCLICommandFactory, application.NewProcessWithRuntimeCosts, wire10.Bind(new(process.Initializer), new(*application.Initializer)), wire10.Bind(new(process.CommandFactory), new(cli.CommandFactory)),
)
