//go:build wireinject

package wire

import (
	"context"

	webhookswire "github.com/portpowered/infinite-you/pkg/services/webhooks/wire"

	"github.com/google/wire"
	initializerapplication "github.com/portpowered/infinite-you/pkg/initializer/application"
	processcontract "github.com/portpowered/infinite-you/pkg/initializer/process"
	automations "github.com/portpowered/infinite-you/pkg/services/automations"
	automationswire "github.com/portpowered/infinite-you/pkg/services/automations/wire"
	edges "github.com/portpowered/infinite-you/pkg/services/edges"
	factorydefinitions "github.com/portpowered/infinite-you/pkg/services/factory_definitions"
	factorydefinitionswire "github.com/portpowered/infinite-you/pkg/services/factory_definitions/wire"
	factoryruntime "github.com/portpowered/infinite-you/pkg/services/factory_runtime"
	factoryruntimewire "github.com/portpowered/infinite-you/pkg/services/factory_runtime/wire"
	factorysessions "github.com/portpowered/infinite-you/pkg/services/factory_sessions"
	factorysessionwire "github.com/portpowered/infinite-you/pkg/services/factory_sessions/wire"
	factoryvisualizationwire "github.com/portpowered/infinite-you/pkg/services/factory_visualization/wire"
	modelswire "github.com/portpowered/infinite-you/pkg/services/models/wire"
	settingswire "github.com/portpowered/infinite-you/pkg/services/operator_settings/wire"
	providersessionshttp "github.com/portpowered/infinite-you/pkg/services/provider_sessions/transports/http"
	recordingswire "github.com/portpowered/infinite-you/pkg/services/recordings/wire"
	"github.com/portpowered/infinite-you/pkg/services/work"
	workwire "github.com/portpowered/infinite-you/pkg/services/work/wire"
	workersessionsrootcli "github.com/portpowered/infinite-you/pkg/services/worker_sessions/transports/cli/worker_sessions"
	acp "github.com/portpowered/infinite-you/pkg/transports/acp"
	"github.com/portpowered/infinite-you/pkg/transports/cli"
	runcli "github.com/portpowered/infinite-you/pkg/transports/cli/run"
	mcpstdio "github.com/portpowered/infinite-you/pkg/transports/mcp/stdio"
)

var platformSet = wire.NewSet(
	provideProcessLogger,
	wire.FieldsOf(new(edges.Edges), "Clock"),
)

var apiSet = wire.NewSet(
	providersessionshttp.NewAdapter,
	providersessionshttp.NewHandler,
	mcpstdio.NewOpener,
	provideHTTPRuntimeBindingWithMetrics,
)

var servicesSet = wire.NewSet(
	provideProvidersService,
	provideEventsService,
	provideWorkerRecordingWriter,
	provideWorkerSessionRecorder,
	recordingswire.NewWorkerControlOperationStore,
	recordingswire.NewWorkerRestartInputStore,
	recordingswire.NewWorkerOwnerRecoveryOperation,
	provideWorkerRecordingReader,
	provideWorkerWorkAttributionReader,
	provideWorkerSessionsService,
	provideWorkerHistorySnapshotBudget,
	provideWorkerAttemptOpener,
	provideApplicationProcessLifecycle,
	provideProviderRegistry,
	provideFactorySessionProviderIdentityResolver,
	factorysessionwire.NewRequestPreparation,
	factorysessionwire.NewLiveChangeCoordinator,
	factorysessionwire.NewIdentity,
	factorysessionwire.NewResponseStreams,
	factorysessionwire.NewSessionRegistry,
	factorysessionwire.NewResponseStreamRegistry,
	factorysessionwire.NewSessionState,
	factorysessionwire.NewInvocationAuthority,
	factorysessionwire.NewInvocationOwner,
	factorysessionwire.NewInvocationTelemetry,
	factorysessionwire.NewInvocationSpecialCase,
	provideInvocationWorkPolicy,
	factorysessionwire.NewScopeControl,
	factorysessionwire.NewRecordedHistory,
	factorysessionwire.NewProcessDurableScope,
	provideProcessDurableExecution,
	factorysessionwire.NewScopeActivation,
	provideInvocationWorldStateProjector,
	factorysessionwire.NewStreamObserver,
	factorysessionwire.NewStreamManager,
	wire.Bind(new(factorysessionwire.StreamManager), new(*factorysessionwire.GatewayStreams)),
	provideFactorySessionHTTPRequestPreparation,
	factoryruntime.NewFactoryStatusProjector,
	factoryruntime.NewSessionResultProjectionOperation,
	provideOperatorSettingsFileSystem,
	provideOperatorSettingsCreateTemporaryFile,
	provideOperatorSettingsProviderCatalog,
	provideOperatorSettingsLogger,
	provideChatSessionsService,
	settingswire.NewDocumentService,
	settingswire.NewResolutionService,
	settingswire.NewService,
	settingswire.NewCLIService,
	provideOperatorSettingsDocumentPreserver,
	provideOperatorSettingsIDGenerator,
	provideChatSessionsFactoryTargetCatalogService,
	provideACPServerFactorySessionStartResolver,
	provideACPServerResolveHomeDir,
	provideChatSessionsResponseBridge,
	provideACPServerResponseBridge,
	provideACPServer,
	provideACPWireRecorder,
	provideOperatorConfigDecoder,
	provideOperatorConfigDiagnosticsDecoder,
	provideOperatorConfigEncoder,
	provideSystemInitializationInspectPath,
	provideOperatorConfigLoader,
	provideOperatorBackendScopeEnsurer,
	provideDurableOpening,
	provideAPIServerStarter,
	provideRuntimeHostOperation,
	provideProcessRuntimeFactory,
	factorysessionwire.NewLifecyclePlanOperation,
	provideFactoryVisualizationFactory,
	provideResponsePresentation,
	factoryvisualizationwire.NewRuntimeSinkOwner,
	factorysessionwire.NewOpeningPresentationOwner,
	provideWorkContentStagingService,
	workwire.NewContentPolicy,
	workwire.NewContentPreparation,
	workwire.NewRequestContentBridge,
	workwire.NewRequestPolicy,
	workwire.NewRequestPreparationService,
	work.NewSingleWorkTargetPreparation,
	work.NewListRequestPreparation,
	work.NewFactoryRequestBatchPreparation,
	workwire.NewInvocationInputPolicy,
	workwire.NewInvocationInputAdapter,
	provideWorkSessionResolver,
	workwire.NewStateAccess,
	provideWorkSnapshotReader,
	provideWorkersMockWorkersConfigFileSystem,
	provideWorkersMockWorkersConfigDiagnosticsLoader,
	provideRuntimeArtifactClock,
	provideRuntimeArtifactIDGenerator,
	provideRuntimeArtifactPathReserver,
	provideRuntimeMetricsCoordination,
	provideRuntimeMetricsRetentionFileSystem,
	provideRuntimeArtifactRootResolver,
	provideRuntimeLoggerFactory,
	provideRuntimeLogOwner,
	provideRuntimeMetricsOwner,
	provideManagedRunnerFactory,
	provideModelAssetHTTP,
	provideModelAssetMakeDirectories,
	provideModelAssetInspectPath,
	provideModelAssetResolveHomeDirectory,
	provideModelAssetWriteFile,
	provideModelAssetRenamePath,
	provideModelAssetRemovePath,
	provideModelAssetReadFile,
	provideModelAssetReadDirectory,
	provideModelAssetCreateFile,
	provideModelAssetOpenFile,
	provideModelAssetResolveEnvironment,
	provideModelHostHTTP,
	provideModelRuntimeInspectFile,
	provideModelRuntimeTempDirectory,
	provideModelAssetEndpoints,
	provideModelAssetCoordination,
	provideModelHostClock,
	provideModelNow,
	provideModelRuntimeRunner,
	provideModelRuntimeTempFile,
	provideModelHostLauncher,
	provideModelOrderedRuntimeEvidence,
	provideModelRuntimeEvidenceSource,
	provideModelHostSymlinks,
	provideModelHostProtocol,
	provideModelHostCompatibility,
	provideModelBackendArtifactResolver,
	provideModelAssetRevision,
	provideModelRuntimeScopes,
	provideModelAssets,
	provideModelSlotFacts,
	provideModelHostLogger,
	provideModelHostMetrics,
	provideModelSlotCoordinator,
	provideModelRuntimeHost,
	provideModelInvocationRuntime,
	provideModelResourceLimiter,
	modelswire.NewInertInvocationArtifactFileSystem,
	modelswire.NewInvocationArtifactRegistrar,
	modelswire.NewExecutionDeadline,
	provideModelInference,
	provideModelsService,
	provideModelScopedLocalExecution,
	modelswire.NewCatalogReadinessQuery,
	modelswire.NewCatalog,
	modelswire.NewSlotState,
	modelswire.NewHostLeases,
	provideModelAssetHostPlatform,
	provideFactorySessionsWorkingDirectory,
	provideFactorySessionDirectoryInspection,
	provideFactorySessionResolveLogicalTargetSymlinks,
	provideFactorySessionContractFixtureReader,
	provideFactorySessionInvocationInputReader,
	provideFactorySessionReplayRecordingReader,
	provideRecordingOpenFile,
	provideRecordedSessionInventory,
	provideFactorySessionInitialWorkReader,
	provideFactorySessionResolveHomeDirectory,
	provideFactorySessionIDGenerator,
	provideFactorySessionRuntimeInstanceIDGenerator,
	provideFactorySessionResponseEventIDGenerator,
	provideFactorySessionResponseEventRetentionLimits,
	provideFactorySessionCursorPersistenceFileSystem,
	provideFactorySessionCursorCreateTemporaryFile,
	provideFactorySessionCursorStoreFactory,
	provideFactorySessionRuntimePersistenceFileSystem,
	provideFactorySessionRuntimePersistenceStoreFactory,
	provideFactorySessionSyncWaitScheduler,
	provideModelInvocationArtifactExporter,
	provideModelInvocationTimeout,
	provideModelInvocationOperation,
	provideModelsCLIComposition,
	provideModelsCLIInputFileReader,
	provideModelsCLIOutputFileSystem,
	provideWorkService,
	provideWorkDurabilityReader,
	provideWorkRequestIDGenerator,
	provideWorkSubmittedFileReader,
	provideWorkSubmittedFilePathInspector,
	provideWorkContentHostPlatform,
	provideContentMaterializer,
	provideFactoryInvocationPolicyPorts,
	provideWorkersInferenceMediaFileReader,
	provideDecisionEnvelopeService,
	provideInvocationInterpolationService,
	provideInvocationOutputShapingService,
	provideInvocationWorkTypeService,
	provideQuorumPolicyService,
	provideWorkPropagationPolicyService,
	provideWorkstationExecutionPolicyService,
	provideTTSObservabilityService,
	provideAutomationHostedClock,
	provideAutomationHostedHTTPClient,
	provideAutomationHostedSecretResolver,
	provideAutomationHostedCheckpointStore,
	provideAutomationsCursorFileSystem,
	provideAutomationsHostedPollers,
	provideAutomationsClock,
	provideAutomationsScriptPollers,
	provideAutomationsOwner,
	automationswire.NewCursorScopes,
	automationswire.NewSourceLifecycle,
	automationswire.NewReconciliation,
	automationswire.NewCron,
	automationswire.NewFilesystemWatchers,
	provideAutomationsCommandRunner,
	provideAutomationsRoot,
	wire.Bind(new(automations.Service), new(automations.Root)),
	factorysessionwire.NewRuntimeAssembly,
	factorysessionwire.NewGateway,
	factorysessionwire.NewRuntimeModelInvocation,
	provideRuntimeModelFactoryConfigReader,
	provideRuntimeModelWorkerExecution,
	provideFactorySessionReconnectValidator,
	factorysessionwire.NewSessionHost,
	factorysessionwire.NewNamedFactoryActivator,
	factorysessionwire.NewKeyedDefinitionActivationGateway,
	provideSessionCheckpointStoreFactory,
	provideFactorySessionsCapability,
	provideFactoryVisualizationMetricsQuery,
	provideRuntimeMetricsQueryCapability,
	provideProviderPriceTableReader,
	provideCostsQuery,
	provideCostsQueryCapability,
	provideFactoryWebhookHTTPClient,
	provideFactoryWebhookSecretResolver,
	provideFactoryWebhookClock,
	provideFactoryWebhookDeadLetterAppender,
	webhookswire.NewService,
	providePortableRecordingWriter,
	provideOrchestrationJavaScriptExecution,
	provideOrchestrationCompilation,
	factoryruntimewire.NewJavaScriptCheckpointSummaries,
	factorysessionwire.NewRuntimeBackedExecution,
	provideFactorySessionReplayInputs,
	provideRecordingClock,
	provideRecordingSnapshotWriter,
	provideRecordingPublication,
	provideRecordingReadFile,
	recordingswire.NewRuntimeLedgerRouter,
	recordingswire.RuntimeLedger,
	recordingswire.NewProjectionService,
	provideRecordingLifecycleOwner,
	recordingswire.NewCanonicalLedgerOwner,
	recordingswire.NewArtifactsExportOwner,
	recordingswire.NewReplayOwner,
	recordingswire.NewHistoricalQueryOwner,
	recordingswire.NewRecordingFlushTickerFactory,
	factorydefinitionswire.FactorySnapshotJSONDecoder,
	provideRecordingsRoot,
	provideRecordingsRuntimeScopeService,
	provideReplayArtifactStorage,
	provideFactoryRuntimeIDGenerator,
	provideFactoryRuntimeDirectories,
	provideFactoryRuntimeInputs,
	provideFactoryRuntimeInputDirectoryWalker,
	provideFactoryRuntimeWorkflowSources,
	provideFactoryRuntimeWorkflowSourceResolveSymlinks,
	provideFactoryRuntimeWorkflowHome,
	provideFactoryDefinitionPortableFileSystem,
	provideFactoryDefinitionLoadingFileSystem,
	provideFactoryDefinitionClock,
	provideFactoryDefinitionVersionFileSystem,
	provideFactoryDefinitionPackagedGoalPromptFileSystem,
	provideFactoryDefinitionPortableBundledFileInspection,
	provideFactoryDefinitionRequiredToolPathLookup,
	provideFactoryDefinitionRequiredToolVersionProbe,
	provideFactoryDefinitionRequiredToolChecker,
	provideFactoryDefinitionPersistenceFileSystem,
	provideFactoryDefinitionDirectoryReplacementStore,
	provideFactoryDefinitionNamedPathFileSystem,
	provideFactoryDefinitionNamedPathResolver,
	provideFactoryDefinitionNamedFactoryCatalogFileSystem,
	provideFactoryDefinitionPackagedInstallationFileSystem,
	provideFactoryDefinitionPackagedInstallationDirectoryCreator,
	providePackagedFactoryInstallation,
	provideFactoryDefinitionAuthoredReaderFileSystem,
	provideFactoryDefinitionAuthoredWriterFileSystem,
	provideFactoryDefinitionScaffoldFileSystem,
	provideFactoryDefinitionScaffoldOutput,
	provideFactoryDefinitionInputInboxSentinelEnsurer,
	providePortableBundledFilesMaterializer,
	providePortableBundledFileWritesValidator,
	providePortableBundledFilesCopier,
	providePortableBundledFileSourceResolver,
	providePortableBundledFilesApplier,
	provideFactoryStarterWorkApplier,
	providePortableBundledDocsPruner,
	provideFactoryDefinitionLoader,
	provideFactoryRuntimeClockResolver,
	provideFactoryRuntimeMetricsClock,
	providePprofCommandLineReader,
	provideFactoryRuntimeProviderOverride,
	provideFactoryRuntimeSubmissionRecorder,
	provideFactoryRuntimeDispatchRecorder,
	provideFactorySessionInvocationMetricsRecorder,
	provideFactoryRuntimeProviderCommandRunner,
	provideFactoryRuntimeScriptCommandRunner,
	provideFactoryRuntimeSessionLoggerFactory,
	provideWorkersRetryRandomSource,
	provideWorkersWorkstationFileSystem,
	provideWorkersProviderTemporaryFileSystem,
	provideAgyPTYAllocator,
	provideWorkersMockCommandRunnerFactory,
	provideWorkerCommandRunnerAdapter,
	provideFactoryDefinitionsRuntimeRouter,
	provideFactoryDefinitionsRoot,
	provideFactoryScaffoldInitializer,
	provideEditableFactoryValidator,
	provideInitialFactorySnapshotFactory,
	factoryruntimewire.NewRuntimeFactory,
	factoryruntimewire.NewOutboxOpening,
	factoryruntimewire.NewDefinitionMapper,
	provideRuntimePreparationWorkstationLoader,
	provideRuntimePreparation,
	provideRuntimeRequestInvocationFiles,
	provideRuntimeRequestPrompts,
	provideRuntimeRequestTemplateFields,
	provideRuntimeRequestArtifactFiles,
	provideRuntimeRequestProgress,
	provideRuntimeRequestLogger,
	factoryruntimewire.NewWorkstationRequestExecutor,
	provideFactoryRuntimeAssembly,
	provideInitialRuntimeActivation,
	factoryruntimewire.NewSidecarOpening,
	provideFactoryRuntimeRoot,
	provideRuntimeOrchestration,
	provideRuntimeDispatchPlanning,
	factoryruntimewire.NewLifecycle,
	factoryruntimewire.NewInstanceHost,
	factoryruntimewire.NewRuntimeStopOperation,
	provideLoadedFactorySourceFactory,
	provideLoadedFactoryLoader,
	provideReplayArtifactLoader,
	provideReplayRuntimeConfigDecoder,
	factorysessionwire.NewRoot,
	factorysessionwire.NewRuntimeResourceAcquisition,
	factorysessionwire.NewRuntimeInputLoading,
	factorysessionwire.NewRuntimePreparation,
	factorysessionwire.NewRuntimeSnapshotSelection,
	factorysessionwire.NewRuntimeInitialEngine,
	factorysessionwire.NewHistoricalReplayBehavior,
	wire.Bind(new(factorysessions.Service), new(*factorysessionwire.Root)),
)

var providerSessionServiceSet = wire.NewSet(
	provideProviderSessions,
)

var factorySessionsServicesSet = wire.NewSet(
	provideJavaScriptWorkflows,
)

var factoryDefinitionsServicesSet = wire.NewSet(
	provideFactoryDefinitionCompilation,
	provideFactoryDefinitionRuntimeSnapshot,
	provideFactoryDefinitionValidationOwner,
	provideOrchestratorDefinitionValidator,
	provideFactoryDefinitionValidationService,
	provideFactoryDefinitionValidator,
	provideDefinitionValidationOperation,
	provideSubmittedDefinitionValidationOperation,
	provideAuthoredFactorySourceLoader,
	provideJavaScriptWorkflowDefinitions,
	provideWorkflowPreviewOperation,
	provideNamedFactoryCatalog,
	provideLoadedFactorySnapshotCapturer,
	provideFactoryScaffoldCommandInitializer,
	provideFactoryDefinitionPersistence,
	provideNamedFactoryPersistenceOperation,
	provideEffectiveFactoryCatalogDiscovery,
	provideEffectiveFactoryDefinitionNormalizer,
	provideEffectiveFactoryCatalogOperation,
	provideEffectiveFactoryDefinitionsService,
	factorydefinitionswire.NewCatalogPathsService,
	factorydefinitionswire.NewCatalogService,
)

var workerServiceSet = wire.NewSet(
	provideStatelessWorkersService,
	provideWorkersAgentToolFileSystem,
	provideWorkersWorktree,
	provideWorkersWorktreeRelease,
	provideWorkersFactoryDocsFileSystem,
	provideWorkerProcessEnvironment,
	provideWorkerCurrentWorkingDirectory,
)

var cliCommandOperationsSet = wire.NewSet(
	provideCLIObserver,
	provideNamedFactoryRootsResolver,
	provideNamedFactoryCandidatePathsResolver,
	provideBatchInputFileSystem,
	provideRunInputPathInspector,
	provideRunDirectoryCreator,
	provideBrowserOpener,
	provideCurrentFactoryDirectoryResolver,
	provideFactoryConfigRootResolver,
	provideFactoryConfigFileLoader,
	provideWorkRequestFileLoader,
	provideTerminalLoggerBuilder,
	provideLiveRecordingTargetPlanner,
	provideRecordingsCLIAdapter,
	provideCLIRunDefaults,
	provideSubmitPayloadReader,
	provideOperatorDefaultsResolver,
	provideStandardCLIHTTPProtocol,
	provideModelsPullCLIHTTPProtocol,
	provideMetricsCLI,
	provideCostsCLI,
	provideCostsReportCLI,
	provideServerStopCLI,
	provideRemoteInvocationOperation,
	provideExtendedCLIHTTPProtocol,
	provideWatchCLIHTTPProtocol,
	provideStreamingCLIHTTPProtocol,
	provideSubmitWorkOperation,
	provideSubmitBatchOperation,
	provideListWorkerSessionsOperation,
	provideShowWorkerSessionOperation,
	provideReadWorkerSessionOperation,
	provideStreamWorkerSessionOperation,
	provideWorkerSessionsCLIIdentityGenerator,
	provideWorkerSessionsCLIExecutionFileReader,
	provideContinueWorkerSessionOperation,
	provideInterruptWorkerSessionOperation,
	providePauseWorkerSessionOperation,
	provideResumeWorkerSessionOperation,
	provideCancelWorkerSessionOperation,
	provideTerminateWorkerSessionOperation,
	provideLocalWorkerSessionsBoundary,
	wire.Bind(new(workersessionsrootcli.LocalInvokeBoundary), new(*localWorkerSessionsBoundary)),
	wire.Bind(new(workersessionsrootcli.LocalControlBoundary), new(*localWorkerSessionsBoundary)),
	provideInvokeWorkerSessionOperation,
	provideSessionsCLIService,
	provideSessionListPreparation,
	provideCommandDiagnostics,
	provideSessionResolvedHandlers,
	provideFactoryConfigInitHandler,
	provideLocalSessionsCLIService,
	provideModelsCLIService,
	provideProvidersCLIService,
	provideFlattenFactoryConfigOperation,
	provideExpandFactoryConfigOperation,
	provideConfigureInitOperation,
	provideACPCLIService,
	provideInstallPackagedFactoryOperation,
	provideInstallPackagedFactoryCLI,
	provideQueryFactoryOperation,
	provideCurrentFactoryPointerReader,
	provideListFactoriesOperation,
	provideFactoryNameCompletionOperation,
	providePackagedFactoryNameCompletionOperation,
	provideSelectedFactorySignatureCompletionOperation,
	provideValidateFactoryOperation,
	provideCreateFactoryFromFileOperation,
	provideReplaceFactoryCurrentOperation,
	provideUpdateFactoryFromFileOperation,
	provideDeleteFactoryOperation,
	provideListWorkOperation,
	provideListHumanApprovalsOperation,
	provideShowHumanApprovalOperation,
	provideWatchReconnectWait,
	provideWatchWorkOperation,
	provideShowWorkOperation,
	provideMoveWorkOperation,
	provideWorkVisualizationOperation,
	provideVisualizeWorkOperation,
	wire.Struct(new(cli.CommandOperations), "*"),
)

// BundleSet is the one canonical provider set used by the single public bundle
// injector. It constructs only inert command and service initializers.
var BundleSet = wire.NewSet(
	platformSet,
	apiSet,
	servicesSet,
	providerSessionServiceSet,
	factorySessionsServicesSet,
	factoryDefinitionsServicesSet,
	workerServiceSet,
	cliCommandOperationsSet,
	providePackagedFactoryDefinitions,
	provideSerializedFactoryConfigReader,
	provideCanonicalFactoryConfigReader,
	providePackagedFactoryCatalog,
	provideSystemInitializationService,
	provideSystemInitializationOperation,
	wire.Bind(new(factorydefinitions.Persistence), new(factorydefinitions.PackagedFactoryPersistence)),
	wire.Bind(new(processcontract.ACPServer), new(acp.Server)),
	provideLifecycleRunnerFactory,
	provideWorkStopSummaryProjector,
	provideSessionStartRequestFactory,
	initializerapplication.NewLifecycleRunnerBuilder,
	provideRunRuntimeRunnerBuilder,
	provideRunSelectionFactory,
	provideInvocationOperation,
	provideMCPServerBuilder,
	provideStdioHandler,
	provideDirectJavaScriptHostAdapter,
	runcli.NewDirectJavaScriptRunOperation,
	initializerapplication.NewInitializer,
	provideRunInvocationOperation,
	provideModelsCLIInvocationOperation,
	provideCLICommandFactory,
	initializerapplication.NewProcessWithRuntimeCosts,
	wire.Bind(new(processcontract.Initializer), new(*initializerapplication.Initializer)),
	wire.Bind(new(processcontract.CommandFactory), new(cli.CommandFactory)),
)

// InjectBundle is the single application-process injector. Callers provide
// production defaults or functional overrides through the same typed inputs.
func InjectBundle(
	ctx context.Context,
	edges edges.Edges,
	acpWireLogSettings ACPWireLogSettings,
) (*initializerapplication.Process, error) {
	wire.Build(
		BundleSet,
	)
	return nil, nil
}
