//go:build wireinject

package wire

import (
	"context"

	"github.com/google/wire"
	initializerapplication "github.com/portpowered/infinite-you/pkg/initializer/application"
	processcontract "github.com/portpowered/infinite-you/pkg/initializer/process"
	"github.com/portpowered/infinite-you/pkg/platform/logging"
	automations "github.com/portpowered/infinite-you/pkg/services/automations"
	edges "github.com/portpowered/infinite-you/pkg/services/edges"
	factorydefinitions "github.com/portpowered/infinite-you/pkg/services/factory_definitions"
	factorydefinitionswire "github.com/portpowered/infinite-you/pkg/services/factory_definitions/wire"
	factoryruntime "github.com/portpowered/infinite-you/pkg/services/factory_runtime"
	factoryruntimewire "github.com/portpowered/infinite-you/pkg/services/factory_runtime/wire"
	factorysessionwire "github.com/portpowered/infinite-you/pkg/services/factory_sessions/wire"
	factoryvisualizationwire "github.com/portpowered/infinite-you/pkg/services/factory_visualization/wire"
	providersessionshttp "github.com/portpowered/infinite-you/pkg/services/provider_sessions/transports/http"
	"github.com/portpowered/infinite-you/pkg/services/work"
	workersessionsrootcli "github.com/portpowered/infinite-you/pkg/services/worker_sessions/transports/cli/worker_sessions"
	"github.com/portpowered/infinite-you/pkg/services/workers"
	acp "github.com/portpowered/infinite-you/pkg/transports/acp"
	"github.com/portpowered/infinite-you/pkg/transports/cli"
	mcpstdio "github.com/portpowered/infinite-you/pkg/transports/mcp/stdio"
)

var platformSet = wire.NewSet(
	// TODO: remove this when we figure out how to appropriately inject the logging.
	logging.NewDefaultLogger,
)

var apiSet = wire.NewSet(
	providersessionshttp.NewAdapter,
	providersessionshttp.NewHandler,
	mcpstdio.NewOpener,
	provideHTTPRuntimeBindingWithMetrics,
)

var servicesSet = wire.NewSet(
	provideProvidersService,
	provideEventsService,
	provideWorkerRecordingWriter,
	provideWorkerSessionRecorder,
	provideWorkerRecordingReader,
	provideWorkerSessionsFactoryWithRecorder,
	provideApplicationProcessLifecycle,
	provideProviderRegistry,
	provideFactorySessionProviderIdentityResolver,
	factorysessionwire.NewRequestPreparation,
	factorysessionwire.NewLiveChangeCoordinator,
	provideFactorySessionHTTPRequestPreparation,
	factoryruntime.NewFactoryStatusProjector,
	factoryruntime.NewSessionResultProjectionOperation,
	provideOperatorSettingsFileSystem,
	provideOperatorSettingsCreateTemporaryFile,
	provideOperatorSettingsProviderCatalog,
	provideOperatorSettingsLogger,
	provideChatSessionsService,
	provideOperatorSettingsService,
	provideOperatorSettingsIDGenerator,
	provideChatSessionsFactoryTargetCatalogService,
	provideACPServerFactoryTargetRuntimeResolver,
	provideACPServerFactoryTarget,
	provideACPServerFactoryTargetService,
	provideACPServerResolveHomeDir,
	provideChatSessionsResponseBridge,
	provideACPServerResponseBridge,
	provideACPServer,
	provideACPWireRecorder,
	provideOperatorConfigDecoder,
	provideOperatorConfigDiagnosticsDecoder,
	provideOperatorConfigEncoder,
	provideSystemInitializationInspectPath,
	provideOperatorConfigLoader,
	provideOperatorBackendScopeEnsurer,
	provideDurableExecutionFactory,
	provideAPIServerStarter,
	provideRuntimeHostOperation,
	provideProcessRuntimeFactory,
	factorysessionwire.NewLifecyclePlanOperation,
	provideFactoryVisualizationFactory,
	provideResponsePresentation,
	factoryvisualizationwire.NewRuntimeSinkOwner,
	factorysessionwire.NewOpeningPresentationOwner,
	provideWorkContentStagingService,
	work.NewContentPreparation,
	work.NewRequestPreparationService,
	work.NewSingleWorkTargetPreparation,
	work.NewListRequestPreparation,
	work.NewFactoryRequestBatchPreparation,
	work.NewInvocationInputPreparation,
	provideWorkersMockWorkersConfigFileSystem,
	provideWorkersMockWorkersConfigDiagnosticsLoader,
	provideRuntimeArtifactClock,
	provideRuntimeArtifactIDGenerator,
	provideRuntimeArtifactPathReserver,
	provideRuntimeMetricsCoordination,
	provideRuntimeMetricsRetentionFileSystem,
	provideRuntimeArtifactRootResolver,
	provideRuntimeLoggerFactory,
	provideRuntimeLogOwner,
	provideRuntimeMetricsOwner,
	provideManagedRunnerFactory,
	provideModelsService,
	provideFactorySessionsWorkingDirectory,
	provideFactorySessionExecutionOpeningFileSystem,
	provideFactorySessionDirectoryInspection,
	provideFactorySessionResolveLogicalTargetSymlinks,
	provideFactorySessionContractFixtureReader,
	provideFactorySessionInvocationInputReader,
	provideFactorySessionReplayRecordingReader,
	provideRecordingOpenFile,
	provideRecordedSessionInventory,
	provideFactorySessionInitialWorkReader,
	provideFactorySessionResolveHomeDirectory,
	provideFactorySessionIDGenerator,
	provideFactorySessionRuntimeInstanceIDGenerator,
	provideFactorySessionResponseEventIDGenerator,
	provideFactorySessionResponseEventRetentionLimits,
	provideFactorySessionCursorPersistenceFileSystem,
	provideFactorySessionCursorCreateTemporaryFile,
	provideFactorySessionCursorStoreFactory,
	provideFactorySessionRuntimePersistenceFileSystem,
	provideFactorySessionRuntimePersistenceStoreFactory,
	provideFactorySessionSyncWaitScheduler,
	provideModelInvocationArtifactExporter,
	provideModelInvocationTimeout,
	provideModelInvocationOperation,
	provideModelsCLIComposition,
	provideModelsCLIInputFileReader,
	provideModelsCLIOutputFileSystem,
	provideWorkService,
	provideWorkDurabilityReader,
	provideWorkRequestIDGenerator,
	provideWorkSubmittedFileReader,
	provideWorkSubmittedFilePathInspector,
	provideWorkContentHostPlatform,
	provideContentMaterializer,
	provideFactoryInvocationPolicyPorts,
	provideDecisionEnvelopeService,
	provideInvocationInterpolationService,
	provideInvocationOutputShapingService,
	provideInvocationWorkTypeService,
	provideQuorumPolicyService,
	provideWorkPropagationPolicyService,
	provideWorkstationExecutionPolicyService,
	provideTTSObservabilityService,
	provideAutomationHostedSourceInputs,
	provideAutomationsCommandRunner,
	provideAutomationsRoot,
	wire.Bind(new(automations.Service), new(automations.Root)),
	provideFactorySessionsAssembly,
	provideFactorySessionDetachedOperations,
	provideFactoryVisualizationMetricsQuery,
	provideRuntimeMetricsQueryCapability,
	provideFactorySessionExecutionRuntimeOpening,
	provideProviderPriceTableReader,
	provideCostsQuery,
	provideCostsQueryCapability,
	provideFactoryWebhooksService,
	providePortableRecordingWriter,
	provideOrchestrationJavaScriptExecution,
	provideOrchestrationCompilation,
	provideFactorySessionExecutionFactory,
	provideConductorInvocationWithProgressFactory,
	provideFactorySessionReplayInputs,
	provideRecordingsRoot,
	provideRecordingsRuntimeOpening,
	provideReplayArtifactStorage,
	provideFactoryRuntimeIDGenerator,
	provideFactoryRuntimeDirectories,
	provideFactoryRuntimeInputs,
	provideFactoryRuntimeInputDirectoryWalker,
	provideFactoryRuntimeWorkflowSources,
	provideFactoryRuntimeWorkflowSourceResolveSymlinks,
	provideFactoryRuntimeWorkflowHome,
	provideFactoryDefinitionPortableFileSystem,
	provideFactoryDefinitionLoadingFileSystem,
	provideFactoryDefinitionClock,
	provideFactoryDefinitionVersionFileSystem,
	provideFactoryDefinitionPackagedGoalPromptFileSystem,
	provideFactoryDefinitionPortableBundledFileInspection,
	provideFactoryDefinitionRequiredToolPathLookup,
	provideFactoryDefinitionRequiredToolVersionProbe,
	provideFactoryDefinitionRequiredToolChecker,
	provideFactoryDefinitionPersistenceFileSystem,
	provideFactoryDefinitionDirectoryReplacementStore,
	provideFactoryDefinitionNamedPathFileSystem,
	provideFactoryDefinitionNamedPathResolver,
	provideFactoryDefinitionNamedFactoryCatalogFileSystem,
	provideFactoryDefinitionPackagedInstallationFileSystem,
	provideFactoryDefinitionPackagedInstallationDirectoryCreator,
	providePackagedFactoryInstallation,
	provideFactoryDefinitionAuthoredReaderFileSystem,
	provideFactoryDefinitionAuthoredWriterFileSystem,
	provideFactoryDefinitionScaffoldFileSystem,
	provideFactoryDefinitionScaffoldOutput,
	provideFactoryDefinitionInputInboxSentinelEnsurer,
	providePortableBundledFilesMaterializer,
	providePortableBundledFileWritesValidator,
	providePortableBundledFilesCopier,
	providePortableBundledFileSourceResolver,
	providePortableBundledFilesApplier,
	provideFactoryStarterWorkApplier,
	providePortableBundledDocsPruner,
	provideFactoryDefinitionLoader,
	provideFactoryRuntimeClockResolver,
	provideFactoryRuntimeClock,
	provideFactoryRuntimeMetricsClock,
	providePprofCommandLineReader,
	provideFactoryRuntimeProviderOverride,
	provideFactoryRuntimeSubmissionRecorder,
	provideFactoryRuntimeDispatchRecorder,
	provideFactorySessionInvocationMetricsRecorder,
	provideFactoryRuntimeProviderCommandRunner,
	provideFactoryRuntimeScriptCommandRunner,
	provideFactoryRuntimeSessionLoggerFactory,
	provideWorkersRetryRandomSource,
	provideWorkersWorkstationFileSystem,
	provideWorkersProviderTemporaryFileSystem,
	provideAgyPTYAllocator,
	provideWorkersMockCommandRunnerFactory,
	provideWorkerCommandRunnerAdapter,
	provideFactoryDefinitionsRuntimeRouter,
	provideFactoryDefinitionsRoot,
	provideFactoryScaffoldInitializer,
	provideEditableFactoryValidator,
	provideInitialFactorySnapshotFactory,
	factoryruntimewire.NewRuntimeFactory,
	factoryruntimewire.NewAssembly,
	provideFactoryRuntimeRootFactory,
	wire.Bind(new(factorysessionwire.FactoryRuntimeAssembler), new(*factoryruntimewire.Assembly)),
	wire.Struct(new(factorysessionwire.ProviderSessionsRuntimeOpeningPorts), "*"),
	wire.Struct(new(factorysessionwire.FactoryRuntimeOpeningPorts), "*"),
	wire.Struct(new(factorysessionwire.FactoryDefinitionsRuntimeOpeningPorts), "*"),
	wire.Struct(new(factorysessionwire.FactorySessionsRuntimeOpeningPorts), "*"),
	wire.Struct(new(factorysessionwire.WorkRuntimeOpeningPorts), "*"),
	wire.Struct(new(factorysessionwire.AutomationsRuntimeOpeningPorts), "*"),
	wire.Struct(new(factorysessionwire.ModelsRuntimeOpeningPorts), "*"),
	wire.Struct(new(factorysessionwire.RecordingsRuntimeOpeningPorts), "*"),
	wire.Struct(new(factorysessionwire.WebhooksRuntimeOpeningPorts), "*"),
	wire.Struct(new(factorysessionwire.WorkersRuntimeOpeningPorts), "*"),
	wire.Struct(new(factorysessionwire.OperatorSettingsRuntimeOpeningPorts), "*"),
	provideLoadedFactorySourceFactory,
	provideLoadedFactoryLoader,
	provideReplayArtifactLoader,
	provideReplayRuntimeConfigDecoder,
	factorysessionwire.NewRuntimeOpening,
	provideFactorySessionsService,
)

var providerSessionServiceSet = wire.NewSet(
	provideProviderSessions,
)

var factorySessionsServicesSet = wire.NewSet(
	provideStandaloneSessionExecutionFactory,
	provideJavaScriptWorkflows,
)

var factoryDefinitionsServicesSet = wire.NewSet(
	provideOrchestratorDefinitionValidator,
	provideFactoryDefinitionValidationService,
	provideFactoryDefinitionValidator,
	provideDefinitionValidationOperation,
	provideSubmittedDefinitionValidationOperation,
	provideAuthoredFactorySourceLoader,
	provideJavaScriptWorkflowDefinitions,
	provideWorkflowPreviewOperation,
	provideNamedFactoryCatalog,
	provideLoadedFactorySnapshotCapturer,
	provideFactoryScaffoldCommandInitializer,
	provideFactoryDefinitionPersistence,
	provideNamedFactoryPersistenceOperation,
	provideEffectiveFactoryCatalogDiscovery,
	provideEffectiveFactoryDefinitionNormalizer,
	provideEffectiveFactoryCatalogOperation,
	provideEffectiveFactoryDefinitionsService,
	factorydefinitionswire.NewCatalogPathsService,
)

var workerServiceSet = wire.NewSet(
	provideStatelessWorkersService,
	provideWorkersAgentToolFileSystem,
	provideWorkersWorktree,
	provideWorkersWorktreeRelease,
	provideWorkersFactoryDocsFileSystem,
	provideProviderFromCommandRunnerFactory,
	provideWorkerProcessEnvironment,
	provideWorkerCurrentWorkingDirectory,
)

var statelessWorkersSet = wire.NewSet(
	platformSet,
	provideProvidersService,
	provideModelsService,
	provideFactoryRuntimeScriptCommandRunner,
	provideWorkersFactoryDocsFileSystem,
	provideFactoryRuntimeClock,
	provideWorkersProviderTemporaryFileSystem,
	provideWorkersWorktree,
	provideWorkersWorktreeRelease,
	provideFactoryRuntimeProviderOverride,
	provideWorkersAgentToolFileSystem,
	provideFactoryInvocationPolicyPorts,
	provideDecisionEnvelopeService,
	provideStatelessWorkersService,
)

var mockStatelessWorkersSet = wire.NewSet(
	platformSet,
	provideProvidersService,
	provideModelsService,
	provideFactoryRuntimeScriptCommandRunner,
	provideWorkersFactoryDocsFileSystem,
	provideFactoryRuntimeClock,
	provideWorkersProviderTemporaryFileSystem,
	provideWorkersWorktree,
	provideWorkersWorktreeRelease,
	provideFactoryRuntimeProviderOverride,
	provideWorkersAgentToolFileSystem,
	provideFactoryInvocationPolicyPorts,
	provideDecisionEnvelopeService,
	provideMockStatelessWorkersService,
)

var cliCommandOperationsSet = wire.NewSet(
	provideCLIObserver,
	provideNamedFactoryRootsResolver,
	provideNamedFactoryCandidatePathsResolver,
	provideBatchInputFileSystem,
	provideRunInputPathInspector,
	provideRunDirectoryCreator,
	provideBrowserOpener,
	provideCurrentFactoryDirectoryResolver,
	provideFactoryConfigRootResolver,
	provideFactoryConfigFileLoader,
	provideWorkRequestFileLoader,
	provideTerminalLoggerBuilder,
	provideLiveRecordingTargetPlanner,
	provideRecordingsCLIAdapter,
	provideCLIRunDefaults,
	provideSubmitPayloadReader,
	provideOperatorDefaultsResolver,
	provideStandardCLIHTTPProtocol,
	provideModelsPullCLIHTTPProtocol,
	provideMetricsCLI,
	provideCostsCLI,
	provideServerStopCLI,
	provideRemoteInvocationOperation,
	provideExtendedCLIHTTPProtocol,
	provideWatchCLIHTTPProtocol,
	provideStreamingCLIHTTPProtocol,
	provideSubmitWorkOperation,
	provideSubmitBatchOperation,
	provideListWorkerSessionsOperation,
	provideShowWorkerSessionOperation,
	provideReadWorkerSessionOperation,
	provideStreamWorkerSessionOperation,
	provideWorkerSessionsCLIIdentityGenerator,
	provideWorkerSessionsCLIExecutionFileReader,
	provideContinueWorkerSessionOperation,
	provideInterruptWorkerSessionOperation,
	providePauseWorkerSessionOperation,
	provideResumeWorkerSessionOperation,
	provideCancelWorkerSessionOperation,
	provideTerminateWorkerSessionOperation,
	provideLocalWorkerSessionsBoundary,
	wire.Bind(new(workersessionsrootcli.LocalInvokeBoundary), new(*localWorkerSessionsBoundary)),
	wire.Bind(new(workersessionsrootcli.LocalControlBoundary), new(*localWorkerSessionsBoundary)),
	provideInvokeWorkerSessionOperation,
	provideSessionsCLIService,
	provideLocalSessionsCLIService,
	provideModelsCLIService,
	provideProvidersCLIService,
	provideFlattenFactoryConfigOperation,
	provideExpandFactoryConfigOperation,
	provideConfigureInitOperation,
	provideACPCLIService,
	provideInstallPackagedFactoryOperation,
	provideInstallPackagedFactoryCLI,
	provideQueryFactoryOperation,
	provideCurrentFactoryPointerReader,
	provideListFactoriesOperation,
	provideFactoryNameCompletionOperation,
	providePackagedFactoryNameCompletionOperation,
	provideSelectedFactorySignatureCompletionOperation,
	provideValidateFactoryOperation,
	provideCreateFactoryFromFileOperation,
	provideReplaceFactoryCurrentOperation,
	provideUpdateFactoryFromFileOperation,
	provideDeleteFactoryOperation,
	provideListWorkOperation,
	provideListHumanApprovalsOperation,
	provideShowHumanApprovalOperation,
	provideWatchWorkOperation,
	provideShowWorkOperation,
	provideMoveWorkOperation,
	provideWorkVisualizationOperation,
	provideVisualizeWorkOperation,
	wire.Struct(new(cli.CommandOperations), "*"),
)

// BundleSet is the one canonical provider set used by both public bundle
// injectors. It constructs only inert command and service initializers.
var BundleSet = wire.NewSet(
	platformSet,
	apiSet,
	servicesSet,
	providerSessionServiceSet,
	factorySessionsServicesSet,
	factoryDefinitionsServicesSet,
	workerServiceSet,
	cliCommandOperationsSet,
	providePackagedFactoryDefinitions,
	providePackagedFactoryCatalog,
	provideSystemInitializationService,
	provideSystemInitializationOperation,
	wire.Bind(new(factorydefinitions.Persistence), new(factorydefinitions.PackagedFactoryPersistence)),
	wire.Bind(new(processcontract.ACPServer), new(acp.Server)),
	wire.Bind(new(factorysessionwire.ApplicationRuntimeOpening), new(*factorysessionwire.RuntimeOpening)),
	wire.Bind(new(factorysessionwire.InvocationRuntimeOpening), new(*factorysessionwire.RuntimeOpening)),
	wire.Bind(new(factorysessionwire.ExecutionRuntimeOpening), new(*factorysessionwire.RuntimeOpening)),
	wire.Bind(new(factorysessionwire.WorkerExecution), new(workers.Service)),
	provideApplicationRuntimeAdapter,
	provideLifecycleRunnerFactory,
	provideWorkStopSummaryProjector,
	provideRuntimeOpeningRequestFactory,
	provideRunOpener,
	provideRuntimeInputResolver,
	factorysessionwire.NewApplicationService,
	initializerapplication.NewRuntimeRunnerBuilder,
	provideRunRuntimeRunnerBuilder,
	provideRunSelectionFactory,
	provideInvocationOperation,
	initializerapplication.NewStdioRunnerBuilder,
	initializerapplication.NewOpenedStdioRunnerBuilder,
	provideFixtureStdioApplicationBuilder,
	provideRuntimeStdioApplicationBuilder,
	provideMCPServerBuilder,
	provideSessionExecutionOpeningFactory,
	wire.Bind(new(factorysessionwire.StdioExecutionOpening), new(*factorysessionwire.ExecutionOpeningFactory)),
	factorysessionwire.NewStdioOpeningService,
	wire.Bind(new(factorysessionwire.StdioOpeningOperation), new(*factorysessionwire.StdioOpeningService)),
	provideStdioApplicationOpener,
	provideDirectJavaScriptSyncRunner,
	provideDirectJavaScriptHostAdapter,
	factorysessionwire.NewDirectJavaScriptRunOperation,
	initializerapplication.NewInitializer,
	factorysessionwire.NewExecutionServiceBuilder,
	provideCLIExecutionServiceBuilder,
	provideRunInvocationOperation,
	provideModelsCLIInvocationOperation,
	provideCLICommandFactory,
	initializerapplication.NewProcessWithRuntimeCostsAndExecution,
	wire.Bind(new(processcontract.Initializer), new(*initializerapplication.Initializer)),
	wire.Bind(new(processcontract.CommandFactory), new(cli.CommandFactory)),
)

// InjectBundle is the single application-process injector. Callers provide
// production defaults or functional overrides through the same typed inputs.
func InjectBundle(
	ctx context.Context,
	edges edges.Edges,
) (*initializerapplication.Process, error) {
	wire.Build(
		BundleSet,
	)
	return nil, nil
}

// BuildStatelessWorkers composes the standalone Workers Execute root without
// opening the application command graph, Factory Runtime, or Factory Session.
// It is a narrow service-root construction boundary used by direct callers
// that need one detached attempt.
func BuildStatelessWorkers(
	ctx context.Context,
	edges edges.Edges,
) (workers.Service, error) {
	wire.Build(
		statelessWorkersSet,
	)
	return nil, nil
}

// BuildMockStatelessWorkers composes the explicit mock-feature Workers root.
// It shares the detached production construction ports while opting into the
// mock registration only when the caller supplies mock configuration.
func BuildMockStatelessWorkers(
	ctx context.Context,
	edges edges.Edges,
	mockWorkers *workers.MockWorkersConfig,
) (workers.Service, error) {
	wire.Build(
		mockStatelessWorkersSet,
	)
	return nil, nil
}
