// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	wire11 "github.com/google/wire"
	"github.com/portpowered/infinite-you/pkg/initializer/application"
	"github.com/portpowered/infinite-you/pkg/initializer/process"
	"github.com/portpowered/infinite-you/pkg/services/automations"
	wire8 "github.com/portpowered/infinite-you/pkg/services/automations/wire"
	"github.com/portpowered/infinite-you/pkg/services/edges"
	"github.com/portpowered/infinite-you/pkg/services/factory_definitions"
	wire4 "github.com/portpowered/infinite-you/pkg/services/factory_definitions/wire"
	"github.com/portpowered/infinite-you/pkg/services/factory_runtime"
	wire3 "github.com/portpowered/infinite-you/pkg/services/factory_runtime/wire"
	"github.com/portpowered/infinite-you/pkg/services/factory_sessions"
	wire6 "github.com/portpowered/infinite-you/pkg/services/factory_sessions/wire"
	wire10 "github.com/portpowered/infinite-you/pkg/services/factory_visualization/wire"
	wire7 "github.com/portpowered/infinite-you/pkg/services/models/wire"
	wire2 "github.com/portpowered/infinite-you/pkg/services/operator_settings/wire"
	"github.com/portpowered/infinite-you/pkg/services/provider_sessions/transports/http"
	wire5 "github.com/portpowered/infinite-you/pkg/services/recordings/wire"
	wire9 "github.com/portpowered/infinite-you/pkg/services/webhooks/wire"
	"github.com/portpowered/infinite-you/pkg/services/work"
	"github.com/portpowered/infinite-you/pkg/services/work/wire"
	"github.com/portpowered/infinite-you/pkg/services/worker_sessions/transports/cli/worker_sessions"
	"github.com/portpowered/infinite-you/pkg/transports/acp"
	"github.com/portpowered/infinite-you/pkg/transports/cli"
	"github.com/portpowered/infinite-you/pkg/transports/cli/run"
	"github.com/portpowered/infinite-you/pkg/transports/mcp/stdio"
)

// Injectors from wire.go:

// InjectBundle is the single application-process injector. Callers provide
// production defaults or functional overrides through the same typed inputs.
func InjectBundle(ctx context.Context, edges2 edges.Edges, acpWireLogSettings ACPWireLogSettings) (*application.Process, error) {
	cliObserver := provideCLIObserver(edges2)
	namedPathFileSystem := provideFactoryDefinitionNamedPathFileSystem(edges2)
	namedPathResolver, err := provideFactoryDefinitionNamedPathResolver(namedPathFileSystem)
	if err != nil {
		return nil, err
	}
	namedFactoryCatalogFileSystem := provideFactoryDefinitionNamedFactoryCatalogFileSystem(edges2)
	v, err := provideNamedFactoryCatalog(namedPathResolver, namedFactoryCatalogFileSystem)
	if err != nil {
		return nil, err
	}
	authoredLayoutReaderFileSystem := provideFactoryDefinitionAuthoredReaderFileSystem(edges2)
	v2, err := providePackagedFactoryDefinitions()
	if err != nil {
		return nil, err
	}
	effectiveFactoryCatalogDiscovery, err := provideEffectiveFactoryCatalogDiscovery(v, authoredLayoutReaderFileSystem, v2)
	if err != nil {
		return nil, err
	}
	effectiveFactoryDefinitionNormalizer := provideEffectiveFactoryDefinitionNormalizer()
	effectiveFactoryCatalogOperation, err := provideEffectiveFactoryCatalogOperation(effectiveFactoryCatalogDiscovery, effectiveFactoryDefinitionNormalizer)
	if err != nil {
		return nil, err
	}
	v3, err := provideEffectiveFactoryDefinitionsService(effectiveFactoryCatalogOperation)
	if err != nil {
		return nil, err
	}
	factoryNamesOperation := provideFactoryNameCompletionOperation(v3)
	packagedFactoryCatalogOperations, err := providePackagedFactoryCatalog(v2)
	if err != nil {
		return nil, err
	}
	packagedFactoryNamesOperation := providePackagedFactoryNameCompletionOperation(packagedFactoryCatalogOperations)
	selectedFactorySignatureOperation, err := provideSelectedFactorySignatureCompletionOperation(v3)
	if err != nil {
		return nil, err
	}
	namedFactoryRootsResolver := provideNamedFactoryRootsResolver()
	namedFactoryCandidatePathsResolver := provideNamedFactoryCandidatePathsResolver(namedPathResolver)
	v4 := provideCurrentFactoryDirectoryResolver(namedPathResolver)
	factoryConfigRootResolver := provideFactoryConfigRootResolver(authoredLayoutReaderFileSystem)
	authoredFactorySourceLoader := provideAuthoredFactorySourceLoader(authoredLayoutReaderFileSystem)
	factoryConfigFileLoader := provideFactoryConfigFileLoader(authoredFactorySourceLoader)
	requestFileLoader := provideWorkRequestFileLoader()
	singleWorkTargetPreparation := work.NewSingleWorkTargetPreparation()
	submittedFileReader := provideWorkSubmittedFileReader(edges2)
	submittedFilePathInspector := provideWorkSubmittedFilePathInspector(edges2)
	v5 := wire.NewInvocationInputPolicy(submittedFileReader, submittedFilePathInspector)
	invocationInputPreparation := wire.NewInvocationInputAdapter(v5)
	loggerBuilder := provideTerminalLoggerBuilder()
	reserver, err := provideRuntimeArtifactPathReserver()
	if err != nil {
		return nil, err
	}
	source := edges2.Clock
	v6 := provideLiveRecordingTargetPlanner(reserver, source)
	adapter := provideRecordingsCLIAdapter()
	v7 := provideCLIRunDefaults(v6, adapter, source)
	batchInputFileSystem := provideBatchInputFileSystem()
	pathInspector := provideRunInputPathInspector()
	directoryCreator := provideRunDirectoryCreator()
	opener := provideBrowserOpener(edges2)
	fileSystem := provideOperatorSettingsFileSystem(edges2)
	createTemporaryFile := provideOperatorSettingsCreateTemporaryFile(edges2)
	configDecoder := provideOperatorConfigDecoder()
	configEncoder := provideOperatorConfigEncoder()
	service, err := provideProvidersService(edges2)
	if err != nil {
		return nil, err
	}
	providerCatalog := provideOperatorSettingsProviderCatalog(service)
	configDocumentPreserver := provideOperatorSettingsDocumentPreserver()
	configDiagnosticsDecoder := provideOperatorConfigDiagnosticsDecoder()
	v8 := wire2.NewDocumentService(fileSystem, createTemporaryFile, configDecoder, configEncoder, providerCatalog, configDocumentPreserver, configDiagnosticsDecoder)
	v9, err := wire2.NewResolutionService(service)
	if err != nil {
		return nil, err
	}
	idGenerator := provideOperatorSettingsIDGenerator(edges2)
	logger, err := provideProcessLogger(edges2)
	if err != nil {
		return nil, err
	}
	loggingLogger := provideOperatorSettingsLogger(logger)
	operatorsettingsService, err := wire2.NewService(v8, v9, fileSystem, createTemporaryFile, configDecoder, configEncoder, idGenerator, loggingLogger, configDiagnosticsDecoder)
	if err != nil {
		return nil, err
	}
	defaultsResolver := provideOperatorDefaultsResolver(operatorsettingsService)
	configLoader := provideOperatorConfigLoader(operatorsettingsService)
	v10, err := provideWorkerRecordingWriter(edges2)
	if err != nil {
		return nil, err
	}
	providersessionsService, err := provideProviderSessions(v10)
	if err != nil {
		return nil, err
	}
	workflowSourceFileSystem := provideFactoryRuntimeWorkflowSources(edges2)
	workflowHomeResolver := provideFactoryRuntimeWorkflowHome(edges2)
	workflowSourceResolveSymlinks := provideFactoryRuntimeWorkflowSourceResolveSymlinks(edges2)
	javaScriptWorkflows := provideJavaScriptWorkflows(workflowSourceFileSystem, workflowHomeResolver, workflowSourceResolveSymlinks)
	javaScriptWorkflowDefinitions := provideJavaScriptWorkflowDefinitions(javaScriptWorkflows)
	workflowPreviewOperation := provideWorkflowPreviewOperation(javaScriptWorkflows)
	factoryIDGenerator := provideFactoryRuntimeIDGenerator(edges2)
	v11, err := wire3.NewDefinitionMapper(factoryIDGenerator)
	if err != nil {
		return nil, err
	}
	v12 := provideRuntimeOrchestration(v11, javaScriptWorkflows)
	timerSource := provideFactoryRuntimeMetricsClock(edges2)
	v13, err := wire3.NewLifecycle(source, timerSource)
	if err != nil {
		return nil, err
	}
	v14, err := wire3.NewInstanceHost(source, timerSource, v13)
	if err != nil {
		return nil, err
	}
	v15 := provideRuntimeDispatchPlanning()
	v16, err := provideFactoryRuntimeRoot(v12, v14, v15)
	if err != nil {
		return nil, err
	}
	clockResolver := provideFactoryRuntimeClockResolver(source)
	v17 := provideFactoryRuntimeProviderOverride(edges2)
	v18 := provideFactoryRuntimeSubmissionRecorder(edges2)
	v19 := provideFactoryRuntimeDispatchRecorder(edges2)
	portablefilesFileSystem := provideFactoryDefinitionPortableFileSystem(edges2)
	v20, err := providePortableBundledFilesApplier(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	v21, err := provideFactoryStarterWorkApplier(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	v22 := providePortableBundledFilesMaterializer(portablefilesFileSystem)
	loadingFileSystem := provideFactoryDefinitionLoadingFileSystem(edges2)
	v23, err := providePortableBundledFileSourceResolver(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	portableBundledFileInspection := provideFactoryDefinitionPortableBundledFileInspection(edges2)
	requiredToolPathLookup := provideFactoryDefinitionRequiredToolPathLookup(edges2)
	requiredToolVersionProbe := provideFactoryDefinitionRequiredToolVersionProbe(edges2)
	v24, err := provideFactoryDefinitionRequiredToolChecker(requiredToolPathLookup, requiredToolVersionProbe)
	if err != nil {
		return nil, err
	}
	serializedFactoryConfigReader, err := provideSerializedFactoryConfigReader()
	if err != nil {
		return nil, err
	}
	v25 := provideFactoryDefinitionLoader(v20, v21, v22, loadingFileSystem, namedPathResolver, authoredLayoutReaderFileSystem, v23, portableBundledFileInspection, v24, serializedFactoryConfigReader)
	v26 := provideFactoryDefinitionCompilation(v25)
	v27 := provideOrchestratorDefinitionValidator(javaScriptWorkflows)
	validationOperations := provideFactoryDefinitionValidationService(javaScriptWorkflows, v26, v27)
	v28 := provideFactoryDefinitionValidator(validationOperations)
	definitionRuntimeRouter := provideFactoryDefinitionsRuntimeRouter()
	v29, err := providePortableBundledDocsPruner(portablefilesFileSystem)
	if err != nil {
		return nil, err
	}
	v30 := providePortableBundledFileWritesValidator(portablefilesFileSystem)
	v31 := providePortableBundledFilesCopier(portablefilesFileSystem)
	authoredLayoutWriterFileSystem := provideFactoryDefinitionAuthoredWriterFileSystem(edges2)
	inputInboxSentinelEnsurer := provideFactoryDefinitionInputInboxSentinelEnsurer(authoredLayoutWriterFileSystem)
	persistenceFileSystem := provideFactoryDefinitionPersistenceFileSystem(edges2)
	directoryReplacementStore := provideFactoryDefinitionDirectoryReplacementStore(edges2)
	canonicalFactoryConfigReader, err := provideCanonicalFactoryConfigReader()
	if err != nil {
		return nil, err
	}
	v32, err := provideFactoryDefinitionPersistence(v28, v25, v29, v22, v30, v31, authoredLayoutWriterFileSystem, inputInboxSentinelEnsurer, persistenceFileSystem, namedPathResolver, directoryReplacementStore, serializedFactoryConfigReader, canonicalFactoryConfigReader)
	if err != nil {
		return nil, err
	}
	v33 := provideFactoryDefinitionValidationOwner(validationOperations, v26, v24, v27)
	v34 := provideFactoryDefinitionRuntimeSnapshot(v25, definitionRuntimeRouter)
	v35 := wire4.NewCatalogService(namedPathResolver, namedFactoryCatalogFileSystem)
	clock := provideFactoryDefinitionClock(edges2)
	versionFileSystem := provideFactoryDefinitionVersionFileSystem(edges2)
	packagedInstallationFileSystem := provideFactoryDefinitionPackagedInstallationFileSystem(edges2)
	packagedInstallationDirectoryCreator := provideFactoryDefinitionPackagedInstallationDirectoryCreator(edges2)
	packagedFactoryInstallationOperations := providePackagedFactoryInstallation(v32, packagedInstallationFileSystem, packagedInstallationDirectoryCreator, loggingLogger)
	factorydefinitionsService, err := provideFactoryDefinitionsRoot(definitionRuntimeRouter, v28, v32, v25, v26, v33, v34, v20, v21, namedPathResolver, v35, clock, versionFileSystem, effectiveFactoryCatalogOperation, packagedFactoryCatalogOperations, packagedFactoryInstallationOperations, v24, v27, portablefilesFileSystem, directoryReplacementStore)
	if err != nil {
		return nil, err
	}
	v36 := provideLoadedFactoryLoader(v25)
	v37 := provideLoadedFactorySourceFactory()
	replayRuntimeConfigDecoder := provideReplayRuntimeConfigDecoder()
	v38, err := provideRecordingClock(source)
	if err != nil {
		return nil, err
	}
	v39 := wire5.NewRuntimeLedgerRouter(v38)
	v40 := wire5.RuntimeLedger(v39)
	v41 := wire5.NewProjectionService()
	storage := provideReplayArtifactStorage()
	v42 := provideRecordingReadFile(edges2)
	v43 := provideRecordingSnapshotWriter(edges2, storage, v42)
	v44 := wire5.NewRecordingFlushTickerFactory()
	v45 := wire5.NewRecordingLifecycleOwner(v6, v43, v44, v38)
	portableArtifactPublication, err := provideRecordingPublication(edges2)
	if err != nil {
		return nil, err
	}
	v46 := wire5.NewArtifactsExportOwner(v45, portableArtifactPublication)
	factorySnapshotJSONDecoder := wire4.FactorySnapshotJSONDecoder()
	v47 := wire5.NewReplayOwner(v45, v41, v42, factorySnapshotJSONDecoder)
	v48 := wire5.NewCanonicalLedgerOwner(v40)
	v49 := wire5.NewHistoricalQueryOwner(v42, v41)
	v50 := provideLoadedFactorySnapshotCapturer()
	v51 := provideReplayArtifactLoader(storage)
	v52 := provideFactorySessionReplayRecordingReader(edges2)
	v53 := provideRecordingOpenFile(edges2)
	replayInputLoader := provideFactorySessionReplayInputs(v51, v52, v53, loggingLogger)
	recordingsService := provideRecordingsRoot(edges2, v40, v41, v45, v46, v47, v48, v49, v38, loggingLogger, v39, v50, factorySnapshotJSONDecoder, replayRuntimeConfigDecoder, replayInputLoader)
	v54, err := provideRecordingsRuntimeScopeService(recordingsService)
	if err != nil {
		return nil, err
	}
	sessionLoggerFactory := provideFactoryRuntimeSessionLoggerFactory()
	v55 := wire6.NewRuntimeInputLoading(v36, v37, replayRuntimeConfigDecoder, v54, v50, sessionLoggerFactory, logger)
	v56 := wire6.NewSessionRegistry()
	responseEventIDGenerator := provideFactorySessionResponseEventIDGenerator(edges2)
	responseEventRetentionLimits := provideFactorySessionResponseEventRetentionLimits(edges2)
	eventsService, err := provideEventsService(loggingLogger)
	if err != nil {
		return nil, err
	}
	v57, err := wire6.NewResponseStreams(responseEventIDGenerator, responseEventRetentionLimits, eventsService, loggingLogger)
	if err != nil {
		return nil, err
	}
	v58, err := wire6.NewResponseStreamRegistry(v57, source)
	if err != nil {
		return nil, err
	}
	v59 := provideFactorySessionIDGenerator(edges2)
	v60 := wire6.NewSessionState(v56, v58, source, responseEventIDGenerator, v59, v57)
	runtimeStopOperation := wire3.NewRuntimeStopOperation(v14)
	v61 := wire6.NewScopeControl(v60, runtimeStopOperation, logger)
	logicalTargetResolveSymlinks := provideFactorySessionResolveLogicalTargetSymlinks(edges2)
	homeDirectoryResolver := provideFactorySessionResolveHomeDirectory(edges2)
	v62, err := wire6.NewIdentity(logicalTargetResolveSymlinks, homeDirectoryResolver)
	if err != nil {
		return nil, err
	}
	worldStateProjector := provideInvocationWorldStateProjector(v41)
	javaScriptCheckpointStoreFactory := provideSessionCheckpointStoreFactory()
	host := wire6.NewSessionHost(v60, v61, v62, source, worldStateProjector, javaScriptCheckpointStoreFactory, logger)
	v63 := wire6.NewStreamObserver()
	v64 := wire6.NewStreamManager(v60, v63, v58, v57)
	reconnectCursorValidator := provideFactorySessionReconnectValidator(v41)
	sessionResultProjectionOperation := factory.NewSessionResultProjectionOperation()
	liveChangeCoordinator := wire6.NewLiveChangeCoordinator()
	v65 := provideFactorySessionRuntimePersistenceFileSystem(edges2)
	v66 := provideFactorySessionRuntimePersistenceStoreFactory(v65)
	v67 := provideFactorySessionSyncWaitScheduler()
	javaScriptCheckpointSummaries := wire3.NewJavaScriptCheckpointSummaries()
	orchestrationJavaScriptExecution := provideOrchestrationJavaScriptExecution(v12)
	v68, err := providePortableRecordingWriter(edges2)
	if err != nil {
		return nil, err
	}
	v69 := wire6.NewProcessDurableScope(v60)
	v70, err := provideModelRuntimeScopes()
	if err != nil {
		return nil, err
	}
	assetHostPlatform := provideModelAssetHostPlatform(edges2)
	v71 := provideModelAssetHTTP(edges2)
	runtimeAssetEndpoints := provideModelAssetEndpoints(edges2)
	v72 := provideModelAssetMakeDirectories(edges2)
	v73 := provideModelAssetInspectPath(edges2)
	v74 := provideModelAssetResolveHomeDirectory(edges2)
	v75 := provideModelAssetWriteFile(edges2)
	v76 := provideModelAssetRenamePath(edges2)
	v77 := provideModelAssetRemovePath(edges2)
	v78 := provideModelAssetReadFile(edges2)
	v79 := provideModelAssetReadDirectory(edges2)
	v80 := provideModelAssetCreateFile(edges2)
	v81 := provideModelAssetOpenFile(edges2)
	v82 := provideModelAssetResolveEnvironment(edges2)
	wireModelAssetRevisionResolver := provideModelAssetRevision(edges2)
	v83, err := provideModelAssetCoordination(edges2)
	if err != nil {
		return nil, err
	}
	v84, err := provideModelAssets(v70, assetHostPlatform, v71, runtimeAssetEndpoints, v72, v73, v74, v75, v76, v77, v78, v79, v80, v81, v82, wireModelAssetRevisionResolver, v83)
	if err != nil {
		return nil, err
	}
	v85 := wire7.NewCatalogReadinessQuery(v84)
	v86, err := wire7.NewCatalog(v70, v85)
	if err != nil {
		return nil, err
	}
	v87 := provideModelHostClock(edges2)
	v88 := wire7.NewSlotState()
	v89 := provideModelSlotFacts(v88, v70, v84)
	v90 := provideModelHostLogger(logger)
	v91 := provideModelHostMetrics(edges2)
	v92 := provideModelSlotCoordinator(v88, v70, v87, v90, v91)
	v93, err := wire7.NewHostLeases(v87, v89, v92)
	if err != nil {
		return nil, err
	}
	wireModelRuntimeEvidenceSource, err := provideModelRuntimeEvidenceSource()
	if err != nil {
		return nil, err
	}
	v94 := provideModelHostLauncher(edges2, wireModelRuntimeEvidenceSource)
	v95 := provideModelHostHTTP(edges2)
	v96 := provideModelHostSymlinks()
	v97 := provideModelHostProtocol(edges2, v96)
	v98, err := provideModelHostCompatibility(edges2)
	if err != nil {
		return nil, err
	}
	v99 := provideModelOrderedRuntimeEvidence(wireModelRuntimeEvidenceSource)
	v100, err := provideModelRuntimeHost(v70, v84, v93, v88, v94, v95, v87, v90, v91, assetHostPlatform, v97, v98, v96, v99)
	if err != nil {
		return nil, err
	}
	wireModelRuntimeRunner, err := provideModelRuntimeRunner(edges2)
	if err != nil {
		return nil, err
	}
	v101 := provideModelRuntimeTempDirectory(edges2)
	v102 := provideModelRuntimeTempFile(edges2)
	v103 := provideModelRuntimeInspectFile(edges2)
	v104, err := provideModelInvocationRuntime(edges2, wireModelRuntimeRunner, v101, v102, v75, v103, v78, v77)
	if err != nil {
		return nil, err
	}
	v105 := wire7.NewInertInvocationArtifactFileSystem()
	v106, err := wire7.NewInvocationArtifactRegistrar(v105)
	if err != nil {
		return nil, err
	}
	wireModelNow := provideModelNow(edges2)
	v107 := wire7.NewExecutionDeadline()
	v108, err := provideModelInference(v70, v84, v86, v100, v104, v106, wireModelNow, v107)
	if err != nil {
		return nil, err
	}
	v109, err := provideModelResourceLimiter(wireModelNow)
	if err != nil {
		return nil, err
	}
	v110, err := provideModelScopedLocalExecution(v70, v84)
	if err != nil {
		return nil, err
	}
	v111, err := provideModelBackendArtifactResolver(edges2, wireModelRuntimeRunner, v71)
	if err != nil {
		return nil, err
	}
	modelsService, err := provideModelsService(edges2, v70, v84, v86, v100, v108, v109, wireModelNow, v110, v99, v111, wireModelAssetRevisionResolver, assetHostPlatform, logger)
	if err != nil {
		return nil, err
	}
	contentHostPlatform := provideWorkContentHostPlatform(edges2)
	contentMaterializer, err := provideContentMaterializer(contentHostPlatform, edges2)
	if err != nil {
		return nil, err
	}
	readOpener := provideWorkersInferenceMediaFileReader(edges2)
	v112, err := provideFactoryRuntimeScriptCommandRunner(edges2)
	if err != nil {
		return nil, err
	}
	readFileTree := provideWorkersFactoryDocsFileSystem(edges2)
	factoryWorktreePreparer, err := provideWorkersWorktree(edges2)
	if err != nil {
		return nil, err
	}
	v113 := provideWorkersWorktreeRelease(factoryWorktreePreparer)
	temporaryFileSystem := provideWorkersProviderTemporaryFileSystem(edges2)
	agentToolFileSystem := provideWorkersAgentToolFileSystem(edges2)
	invocationPolicyPorts, err := provideFactoryInvocationPolicyPorts()
	if err != nil {
		return nil, err
	}
	decisionEnvelopeService := provideDecisionEnvelopeService(invocationPolicyPorts)
	workersService, err := provideStatelessWorkersService(service, modelsService, contentMaterializer, readOpener, v112, readFileTree, source, logger, factoryWorktreePreparer, v113, temporaryFileSystem, v17, agentToolFileSystem, decisionEnvelopeService)
	if err != nil {
		return nil, err
	}
	v114, err := provideAgyPTYAllocator(edges2)
	if err != nil {
		return nil, err
	}
	v115 := provideWorkerCommandRunnerAdapter()
	v116, err := provideProcessDurableExecution(homeDirectoryResolver, v66, source, v67, javaScriptCheckpointSummaries, javaScriptWorkflows, orchestrationJavaScriptExecution, v68, v59, responseEventIDGenerator, v57, liveChangeCoordinator, v69, workersService, v17, v114, v115, logger)
	if err != nil {
		return nil, err
	}
	recordedSessionInventory := provideRecordedSessionInventory(edges2, replayInputLoader, loggingLogger)
	v117 := wire6.NewRecordedHistory(homeDirectoryResolver, recordedSessionInventory)
	v118 := wire6.NewInvocationAuthority(v60, timerSource, worldStateProjector)
	ttsObservabilityService := provideTTSObservabilityService(invocationPolicyPorts)
	v119 := provideFactorySessionInvocationMetricsRecorder(edges2)
	v120 := wire6.NewInvocationTelemetry(v60, ttsObservabilityService, v119, logger)
	v121 := wire6.NewInvocationSpecialCase(ttsObservabilityService)
	invocationInterpolationService := provideInvocationInterpolationService(invocationPolicyPorts)
	invocationWorkTypeService := provideInvocationWorkTypeService(invocationPolicyPorts)
	invocationInputReader := provideFactorySessionInvocationInputReader(edges2)
	invocationWorkPolicy := provideInvocationWorkPolicy()
	v122, err := wire6.NewInvocationOwner(v118, v61, v120, v121, invocationInterpolationService, invocationWorkTypeService, invocationInputReader, invocationWorkPolicy)
	if err != nil {
		return nil, err
	}
	namedFactoryActivator := wire6.NewNamedFactoryActivator(v60)
	definitionActivationGateway := wire6.NewKeyedDefinitionActivationGateway(v60, source)
	sessionGateway := wire6.NewGateway(host, v64, reconnectCursorValidator, sessionResultProjectionOperation, v57, liveChangeCoordinator, v116, v117, v122, namedFactoryActivator, definitionActivationGateway)
	v123 := wire6.NewScopeActivation(v60)
	v124 := provideFactorySessionDirectoryInspection(edges2)
	initialWorkReader := provideFactorySessionInitialWorkReader(edges2)
	scaffoldFileSystem := provideFactoryDefinitionScaffoldFileSystem(edges2)
	scaffoldOutput := provideFactoryDefinitionScaffoldOutput(edges2)
	v125, err := provideFactoryScaffoldCommandInitializer(scaffoldFileSystem, scaffoldOutput)
	if err != nil {
		return nil, err
	}
	factoryScaffoldInitializer := provideFactoryScaffoldInitializer(v125)
	v126 := provideDefinitionValidationOperation(validationOperations)
	editableFactoryValidator := provideEditableFactoryValidator(v126)
	v127, err := wire6.NewRuntimeAssembly(sessionGateway, v56, v60, v64, v122, v61, v123, javaScriptCheckpointStoreFactory, sessionResultProjectionOperation, responseEventIDGenerator, v59, homeDirectoryResolver, v124, namedPathResolver, initialWorkReader, v62, v57, source, liveChangeCoordinator, v117, host, namedFactoryActivator, definitionActivationGateway, factoryScaffoldInitializer, editableFactoryValidator, v119, factorydefinitionsService, reconnectCursorValidator, worldStateProjector)
	if err != nil {
		return nil, err
	}
	v128, err := wire6.NewRuntimeBackedExecution(v66, source, v67, javaScriptCheckpointSummaries, javaScriptWorkflows, orchestrationJavaScriptExecution, v68, v59, responseEventIDGenerator, v57, liveChangeCoordinator, workersService, logger)
	if err != nil {
		return nil, err
	}
	providerIdentityResolver := provideFactorySessionProviderIdentityResolver(service)
	v129 := provideDurableOpening(configLoader, v128, v114, v115, v17, providerIdentityResolver)
	commandLineReader := providePprofCommandLineReader()
	starter, err := provideAPIServerStarter(edges2, commandLineReader)
	if err != nil {
		return nil, err
	}
	v130 := provideRuntimeHostOperation(starter)
	v131, err := provideProcessRuntimeFactory(v130)
	if err != nil {
		return nil, err
	}
	runtimeInstanceIDGenerator := provideFactorySessionRuntimeInstanceIDGenerator(edges2)
	contentStagingService, err := provideWorkContentStagingService(edges2, source)
	if err != nil {
		return nil, err
	}
	v132 := provideWorkSessionResolver(v127)
	v133 := provideWorkSnapshotReader()
	v134, err := provideWorkDurabilityReader(recordingsService)
	if err != nil {
		return nil, err
	}
	v135 := wire.NewStateAccess(v132, v133, v134)
	v136 := wire.NewContentPolicy()
	contentPreparation := wire.NewContentPreparation(v136)
	requestContentBridge := wire.NewRequestContentBridge(contentPreparation)
	v137 := wire.NewRequestPolicy(requestContentBridge)
	requestPreparationService := wire.NewRequestPreparationService(v137)
	workService := provideWorkService(v127, submittedFileReader, submittedFilePathInspector, contentStagingService, contentMaterializer, v135, requestPreparationService, invocationInputPreparation)
	v138 := provideAutomationsClock(source, timerSource)
	commandRunner, err := provideAutomationsCommandRunner(edges2)
	if err != nil {
		return nil, err
	}
	workstationExecutionPolicyService := provideWorkstationExecutionPolicyService(invocationPolicyPorts)
	v139 := provideAutomationsCursorFileSystem(edges2)
	v140 := wire8.NewCursorScopes(v139)
	v141 := provideAutomationsScriptPollers(logger, v138, commandRunner, workstationExecutionPolicyService, v140)
	v142 := wire8.NewCron()
	v143 := wire8.NewFilesystemWatchers()
	v144 := provideAutomationHostedClock(edges2)
	v145 := provideAutomationHostedHTTPClient(edges2)
	v146 := provideAutomationHostedSecretResolver(edges2)
	v147, err := provideAutomationHostedCheckpointStore(edges2)
	if err != nil {
		return nil, err
	}
	v148 := provideAutomationsHostedPollers(logger, v144, v145, v146, v147, edges2)
	v149 := wire8.NewSourceLifecycle(logger, v138, v141, v142, v143, v148, v140, workstationExecutionPolicyService)
	v150 := wire8.NewReconciliation(v149)
	v151 := provideAutomationsOwner(logger, v138, v149, v150, v141, v142, v143, v148, workstationExecutionPolicyService, v140)
	root := provideAutomationsRoot(v151)
	httpClient := provideFactoryWebhookHTTPClient(edges2)
	secretResolver := provideFactoryWebhookSecretResolver(edges2)
	wireClock := provideFactoryWebhookClock(edges2)
	deadLetterAppender := provideFactoryWebhookDeadLetterAppender(edges2)
	webhooksService := wire9.NewService(recordingsService, httpClient, secretResolver, wireClock, deadLetterAppender, loggingLogger)
	v152, err := provideFactoryRuntimeProviderCommandRunner(edges2)
	if err != nil {
		return nil, err
	}
	backendScopeEnsurer := provideOperatorBackendScopeEnsurer(operatorsettingsService)
	runtimeLoggerFactory := provideRuntimeLoggerFactory()
	wireRuntimeArtifactClock := provideRuntimeArtifactClock(source)
	wireRuntimeArtifactIDGenerator := provideRuntimeArtifactIDGenerator()
	factoryRuntimeLogOwner, err := provideRuntimeLogOwner(wireRuntimeArtifactClock, wireRuntimeArtifactIDGenerator, reserver)
	if err != nil {
		return nil, err
	}
	runtimeMetricsRetentionFileSystem := provideRuntimeMetricsRetentionFileSystem()
	runtimeMetricsCoordination, err := provideRuntimeMetricsCoordination()
	if err != nil {
		return nil, err
	}
	factoryRuntimeMetricsOwner, err := provideRuntimeMetricsOwner(logger, wireRuntimeArtifactClock, wireRuntimeArtifactIDGenerator, reserver, runtimeMetricsRetentionFileSystem, runtimeMetricsCoordination)
	if err != nil {
		return nil, err
	}
	requestIDGenerator := provideWorkRequestIDGenerator(edges2)
	runtimeDirectoryFileSystem := provideFactoryRuntimeDirectories(edges2)
	inputFileSystem := provideFactoryRuntimeInputs(edges2)
	inputDirectoryWalker := provideFactoryRuntimeInputDirectoryWalker(edges2)
	orchestrationCompilation := provideOrchestrationCompilation(v12)
	quorumPolicyService := provideQuorumPolicyService(invocationPolicyPorts)
	invocationOutputShapingService := provideInvocationOutputShapingService(invocationPolicyPorts)
	workPropagationPolicyService := provideWorkPropagationPolicyService(invocationPolicyPorts)
	v153 := wire3.NewOutboxOpening()
	v154 := wire3.NewRuntimeFactory(runtimeLoggerFactory, factoryRuntimeLogOwner, factoryRuntimeMetricsOwner, factoryIDGenerator, requestIDGenerator, runtimeDirectoryFileSystem, inputFileSystem, inputDirectoryWalker, orchestrationCompilation, timerSource, v11, invocationInterpolationService, providersessionsService, quorumPolicyService, invocationOutputShapingService, workPropagationPolicyService, workService, decisionEnvelopeService, v153, v18, v19, worldStateProjector, v54)
	v155, err := provideWorkerSessionRecorder(eventsService, v10, loggingLogger)
	if err != nil {
		return nil, err
	}
	v156, err := wire5.NewWorkerControlOperationStore(v10)
	if err != nil {
		return nil, err
	}
	v157, err := wire5.NewWorkerRestartInputStore(v10)
	if err != nil {
		return nil, err
	}
	v158 := provideWorkerHistorySnapshotBudget()
	workersessionsService, err := provideWorkerSessionsService(workersService, eventsService, loggingLogger, source, timerSource, v155, v10, v156, v157, v158, service)
	if err != nil {
		return nil, err
	}
	workerAttemptOpener, err := provideWorkerAttemptOpener(workersessionsService)
	if err != nil {
		return nil, err
	}
	fileReader := provideRuntimeRequestInvocationFiles(inputFileSystem)
	v159 := provideRuntimeRequestPrompts(workersService)
	v160 := provideRuntimeRequestTemplateFields(workersService)
	progressPublisher := provideRuntimeRequestProgress()
	expectedArtifactFileSystem := provideRuntimeRequestArtifactFiles(inputFileSystem)
	factoryLogger := provideRuntimeRequestLogger(logger, runtimeLoggerFactory)
	v161 := wire3.NewWorkstationRequestExecutor(workersService, invocationInterpolationService, fileReader, factoryIDGenerator, v159, v160, progressPublisher, expectedArtifactFileSystem, factoryLogger)
	initialFactorySnapshotFactory := provideInitialFactorySnapshotFactory(v20, v21)
	v162 := wire3.NewSidecarOpening(root, timerSource)
	v163 := provideRuntimePreparationWorkstationLoader()
	workersMockCommandRunnerFactory := provideWorkersMockCommandRunnerFactory()
	v164 := provideRuntimePreparation(v163, v36, factoryIDGenerator, logger, v17, v152, v112, workersMockCommandRunnerFactory)
	v165, err := provideFactoryRuntimeAssembly(v154, timerSource, workersService, workersessionsService, workerAttemptOpener, v161, initialFactorySnapshotFactory, v162, v14, v164, v54, root, v127)
	if err != nil {
		return nil, err
	}
	initialRuntimeActivationOperation := provideInitialRuntimeActivation(v165, source, logger, v37)
	v166 := provideRuntimeModelFactoryConfigReader(v127)
	v167 := provideRuntimeModelWorkerExecution(workersService)
	v168 := wire6.NewRuntimeModelInvocation(modelsService, v166, v167)
	v169 := wire6.NewHistoricalReplayBehavior()
	v170, err := wire6.NewRoot(providersessionsService, logger, javaScriptWorkflowDefinitions, workflowPreviewOperation, v16, clockResolver, source, v17, v18, v19, v28, namedPathResolver, factorydefinitionsService, definitionRuntimeRouter, v55, replayRuntimeConfigDecoder, v127, v129, factoryScaffoldInitializer, editableFactoryValidator, v131, v59, runtimeInstanceIDGenerator, homeDirectoryResolver, providerIdentityResolver, workService, root, webhooksService, modelsService, recordingsService, v54, workersService, v152, v112, backendScopeEnsurer, initialRuntimeActivationOperation, v168, v169, liveChangeCoordinator, v41)
	if err != nil {
		return nil, err
	}
	wireStandardCLIHTTPProtocol, err := provideStandardCLIHTTPProtocol(source)
	if err != nil {
		return nil, err
	}
	wireModelsPullCLIHTTPProtocol, err := provideModelsPullCLIHTTPProtocol(source)
	if err != nil {
		return nil, err
	}
	workingDirectory := provideFactorySessionsWorkingDirectory(edges2)
	v171, err := provideModelInvocationArtifactExporter(edges2)
	if err != nil {
		return nil, err
	}
	modelInvocationTimeout := provideModelInvocationTimeout()
	runtimeArtifactRootResolver := provideRuntimeArtifactRootResolver()
	openingPresentationOwner := wire6.NewOpeningPresentationOwner()
	v172, err := provideInvocationOperation(v170, modelsService, workingDirectory, v4, v171, modelInvocationTimeout, runtimeArtifactRootResolver, v59, logger, openingPresentationOwner)
	if err != nil {
		return nil, err
	}
	invocationOperation := provideModelsCLIInvocationOperation(v172)
	compositionScopeProvider, err := provideModelsCLIComposition(modelsService, v172, configLoader)
	if err != nil {
		return nil, err
	}
	outputFileSystem := provideModelsCLIOutputFileSystem(edges2)
	inputFileReader := provideModelsCLIInputFileReader(edges2)
	cliService := provideModelsCLIService(wireStandardCLIHTTPProtocol, wireModelsPullCLIHTTPProtocol, invocationOperation, compositionScopeProvider, outputFileSystem, inputFileReader, wireRuntimeArtifactClock)
	service2 := provideProvidersCLIService(service)
	v173 := wire6.NewRequestPreparation()
	sessionService := provideSessionsCLIService(wireStandardCLIHTTPProtocol, v173)
	localSessionsCLIService := provideLocalSessionsCLIService(v170)
	payloadFileReader := provideSubmitPayloadReader()
	wireExtendedCLIHTTPProtocol, err := provideExtendedCLIHTTPProtocol(source)
	if err != nil {
		return nil, err
	}
	submitWorkOperation := provideSubmitWorkOperation(payloadFileReader, wireExtendedCLIHTTPProtocol)
	factoryRequestBatchPreparation := work.NewFactoryRequestBatchPreparation()
	submitBatchOperation := provideSubmitBatchOperation(wireExtendedCLIHTTPProtocol, factoryRequestBatchPreparation)
	flattenFactoryConfigOperation := provideFlattenFactoryConfigOperation(v32)
	expandFactoryConfigOperation := provideExpandFactoryConfigOperation(v32)
	service3 := wire2.NewCLIService(operatorsettingsService)
	configureInitOperation, err := provideConfigureInitOperation(operatorsettingsService, service3)
	if err != nil {
		return nil, err
	}
	installPackagedFactoryOperation := provideInstallPackagedFactoryOperation(packagedFactoryCatalogOperations, packagedFactoryInstallationOperations)
	cliInstallPackagedFactoryOperation := provideInstallPackagedFactoryCLI(installPackagedFactoryOperation)
	queryFactoryOperation := provideQueryFactoryOperation(wireStandardCLIHTTPProtocol)
	v174 := provideCurrentFactoryPointerReader(namedPathResolver)
	listFactoriesOperation := provideListFactoriesOperation(v3, v174)
	v175 := provideSubmittedDefinitionValidationOperation(validationOperations)
	validateFactoryOperation, err := provideValidateFactoryOperation(v175, authoredFactorySourceLoader)
	if err != nil {
		return nil, err
	}
	v176 := provideNamedFactoryPersistenceOperation(v32)
	createFactoryFromFileOperation := provideCreateFactoryFromFileOperation(v176, authoredFactorySourceLoader)
	replaceFactoryCurrentOperation := provideReplaceFactoryCurrentOperation(wireStandardCLIHTTPProtocol)
	updateFactoryFromFileOperation := provideUpdateFactoryFromFileOperation(v176, authoredFactorySourceLoader)
	deleteFactoryOperation := provideDeleteFactoryOperation(v)
	listRequestPreparation := work.NewListRequestPreparation()
	listWorkOperation := provideListWorkOperation(wireStandardCLIHTTPProtocol, listRequestPreparation)
	listHumanApprovalsOperation := provideListHumanApprovalsOperation(wireStandardCLIHTTPProtocol)
	showHumanApprovalOperation := provideShowHumanApprovalOperation(wireStandardCLIHTTPProtocol)
	wireWatchCLIHTTPProtocol, err := provideWatchCLIHTTPProtocol(source)
	if err != nil {
		return nil, err
	}
	v177 := provideWatchReconnectWait(timerSource)
	watchWorkOperation := provideWatchWorkOperation(wireWatchCLIHTTPProtocol, v177)
	showWorkOperation := provideShowWorkOperation(wireStandardCLIHTTPProtocol)
	moveWorkOperation := provideMoveWorkOperation(wireExtendedCLIHTTPProtocol)
	v178 := provideWorkVisualizationOperation()
	visualizeWorkOperation := provideVisualizeWorkOperation(v178)
	v179 := provideListWorkerSessionsOperation(wireStandardCLIHTTPProtocol)
	v180 := provideShowWorkerSessionOperation(wireStandardCLIHTTPProtocol)
	wireStreamingCLIHTTPProtocol, err := provideStreamingCLIHTTPProtocol(source)
	if err != nil {
		return nil, err
	}
	v181 := provideReadWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireStreamingCLIHTTPProtocol)
	v182 := provideStreamWorkerSessionOperation(wireStreamingCLIHTTPProtocol)
	wireLocalWorkerSessionsBoundary, err := provideLocalWorkerSessionsBoundary(workersessionsService)
	if err != nil {
		return nil, err
	}
	cliIDGenerator := provideWorkerSessionsCLIIdentityGenerator()
	executionFileReader := provideWorkerSessionsCLIExecutionFileReader()
	v183 := provideInvokeWorkerSessionOperation(wireStreamingCLIHTTPProtocol, wireLocalWorkerSessionsBoundary, cliIDGenerator, executionFileReader)
	v184 := provideContinueWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary, cliIDGenerator)
	v185 := provideInterruptWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary, cliIDGenerator)
	pauseWorkerSessionOperation := providePauseWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	resumeWorkerSessionOperation := provideResumeWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	cancelWorkerSessionOperation := provideCancelWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	terminateWorkerSessionOperation := provideTerminateWorkerSessionOperation(wireStandardCLIHTTPProtocol, wireLocalWorkerSessionsBoundary)
	runtimeFactory := provideFactoryVisualizationFactory()
	v186 := wire10.NewRuntimeSinkOwner()
	factoryStatusProjector := factory.NewFactoryStatusProjector()
	httpAdapter := http.NewAdapter(providersessionsService)
	handler := http.NewHandler(httpAdapter, logger)
	requestPreparation := provideFactorySessionHTTPRequestPreparation(v173)
	runtimeMetricsQuery, err := provideFactoryVisualizationMetricsQuery(loggingLogger)
	if err != nil {
		return nil, err
	}
	priceTableReader, err := provideProviderPriceTableReader()
	if err != nil {
		return nil, err
	}
	costsQuery, err := provideCostsQuery(priceTableReader, operatorsettingsService, runtimeMetricsQuery, loggingLogger)
	if err != nil {
		return nil, err
	}
	workerOwnerRecoveryOperation := wire5.NewWorkerOwnerRecoveryOperation(v10)
	v187 := provideWorkerWorkAttributionReader(v10, v49, v170)
	wireHttpRuntimeBinding, err := provideHTTPRuntimeBindingWithMetrics(factoryStatusProjector, handler, contentPreparation, v175, invocationWorkTypeService, requestPreparation, runtimeMetricsQuery, costsQuery, workersessionsService, workerOwnerRecoveryOperation, v10, source, v158, v187)
	if err != nil {
		return nil, err
	}
	runnerFactory := provideLifecycleRunnerFactory()
	v188 := wire6.NewLifecyclePlanOperation()
	runtimeRunnerBuilder, err := provideRunRuntimeRunnerBuilder(v170, edges2, runtimeFactory, v186, wireHttpRuntimeBinding, runnerFactory, v188)
	if err != nil {
		return nil, err
	}
	v189 := provideResponsePresentation()
	directJavaScriptHost, err := provideDirectJavaScriptHostAdapter(v175, invocationWorkTypeService, requestPreparation, starter, runnerFactory, logger, workerOwnerRecoveryOperation)
	if err != nil {
		return nil, err
	}
	managedRunnerFactory := provideManagedRunnerFactory()
	lifecycleRunnerBuilder, err := application.NewLifecycleRunnerBuilder(managedRunnerFactory)
	if err != nil {
		return nil, err
	}
	directJavaScriptRunOperation, err := run.NewDirectJavaScriptRunOperation(v170, v59, directJavaScriptHost, openingPresentationOwner, lifecycleRunnerBuilder)
	if err != nil {
		return nil, err
	}
	mockWorkersConfigFileSystem := provideWorkersMockWorkersConfigFileSystem(edges2)
	mockWorkersConfigDiagnosticsLoader, err := provideWorkersMockWorkersConfigDiagnosticsLoader(mockWorkersConfigFileSystem)
	if err != nil {
		return nil, err
	}
	sessionStartRequestFactory := provideSessionStartRequestFactory()
	selectionFactory, err := provideRunSelectionFactory(runtimeRunnerBuilder, v172, v189, directJavaScriptRunOperation, singleWorkTargetPreparation, mockWorkersConfigDiagnosticsLoader, sessionStartRequestFactory, openingPresentationOwner, v186)
	if err != nil {
		return nil, err
	}
	remoteInvocationOperation := provideRemoteInvocationOperation(wireStandardCLIHTTPProtocol)
	operations := provideACPCLIService(operatorsettingsService, service, idGenerator)
	chatsessionsService, err := provideChatSessionsService(eventsService, loggingLogger, source)
	if err != nil {
		return nil, err
	}
	catalogPathsService, err := wire4.NewCatalogPathsService(effectiveFactoryCatalogOperation, v, v4, loggingLogger)
	if err != nil {
		return nil, err
	}
	factoryTargetCatalogService, err := provideChatSessionsFactoryTargetCatalogService(operatorsettingsService, catalogPathsService, loggingLogger)
	if err != nil {
		return nil, err
	}
	wireAcpServerResolveHomeDir := provideACPServerResolveHomeDir(edges2)
	v190 := provideChatSessionsResponseBridge(chatsessionsService, v170, eventsService, loggingLogger)
	responseBridge := provideACPServerResponseBridge(v190)
	v191, err := provideACPWireRecorder(edges2, acpWireLogSettings, reserver, wireRuntimeArtifactClock, wireAcpServerResolveHomeDir)
	if err != nil {
		return nil, err
	}
	factorySessionStartResolver := provideACPServerFactorySessionStartResolver(wireAcpServerResolveHomeDir, v, defaultsResolver, runtimeArtifactRootResolver)
	server := provideACPServer(loggingLogger, chatsessionsService, factoryTargetCatalogService, v170, eventsService, wireAcpServerResolveHomeDir, responseBridge, v191, factorySessionStartResolver)
	operation := provideMetricsCLI()
	costReportOperation := provideCostsReportCLI()
	cliOperation := provideCostsCLI()
	serverstopOperation := provideServerStopCLI()
	commandOperations := cli.CommandOperations{
		ObserveCLI:                        cliObserver,
		NamedFactoryCatalog:               v,
		CompleteFactoryNames:              factoryNamesOperation,
		CompletePackagedFactoryNames:      packagedFactoryNamesOperation,
		CompleteSelectedFactorySignature:  selectedFactorySignatureOperation,
		ResolveNamedFactoryRoots:          namedFactoryRootsResolver,
		ResolveNamedFactoryCandidatePaths: namedFactoryCandidatePathsResolver,
		ResolveCurrentFactoryDir:          v4,
		ResolveFactoryConfigRoot:          factoryConfigRootResolver,
		LoadFactoryConfigFile:             factoryConfigFileLoader,
		WorkRequestFileLoader:             requestFileLoader,
		PrepareSingleWorkTarget:           singleWorkTargetPreparation,
		PrepareInvocationInput:            invocationInputPreparation,
		BuildTerminalLogger:               loggerBuilder,
		RunDefaults:                       v7,
		BatchInputFileSystem:              batchInputFileSystem,
		RunInputPathInspector:             pathInspector,
		RunDirectoryCreator:               directoryCreator,
		BrowserOpener:                     opener,
		ResolveOperatorDefaults:           defaultsResolver,
		LoadOperatorConfig:                configLoader,
		FactorySessions:                   v170,
		ModelsCLI:                         cliService,
		ProvidersCLI:                      service2,
		SessionsCLI:                       sessionService,
		LocalSessionsCLI:                  localSessionsCLIService,
		SubmitWork:                        submitWorkOperation,
		SubmitBatch:                       submitBatchOperation,
		FlattenFactoryConfig:              flattenFactoryConfigOperation,
		ExpandFactoryConfig:               expandFactoryConfigOperation,
		InitFactory:                       v125,
		ConfigureInit:                     configureInitOperation,
		InstallPackagedFactory:            cliInstallPackagedFactoryOperation,
		QueryFactory:                      queryFactoryOperation,
		ListFactories:                     listFactoriesOperation,
		ValidateFactory:                   validateFactoryOperation,
		CreateFactoryFromFile:             createFactoryFromFileOperation,
		ReplaceFactoryCurrent:             replaceFactoryCurrentOperation,
		UpdateFactoryFromFile:             updateFactoryFromFileOperation,
		DeleteFactory:                     deleteFactoryOperation,
		ListWork:                          listWorkOperation,
		ListHumanApprovals:                listHumanApprovalsOperation,
		ShowHumanApproval:                 showHumanApprovalOperation,
		WatchWork:                         watchWorkOperation,
		ShowWork:                          showWorkOperation,
		MoveWork:                          moveWorkOperation,
		VisualizeWork:                     visualizeWorkOperation,
		ListWorkerSessions:                v179,
		ShowWorkerSession:                 v180,
		ReadWorkerSession:                 v181,
		StreamWorkerSession:               v182,
		InvokeWorkerSession:               v183,
		ContinueWorkerSession:             v184,
		InterruptWorkerSession:            v185,
		PauseWorkerSession:                pauseWorkerSessionOperation,
		ResumeWorkerSession:               resumeWorkerSessionOperation,
		CancelWorkerSession:               cancelWorkerSessionOperation,
		TerminateWorkerSession:            terminateWorkerSessionOperation,
		LocalWorkerSessions:               wireLocalWorkerSessionsBoundary,
		LocalWorkerSessionControls:        wireLocalWorkerSessionsBoundary,
		OpenRunSelection:                  selectionFactory,
		RemoteInvocation:                  remoteInvocationOperation,
		ResponsePresentation:              v189,
		ACP:                               operations,
		ACPServer:                         server,
		RuntimeMetricsQuery:               runtimeMetricsQuery,
		MetricsCLI:                        operation,
		MetricsCostReportCLI:              costReportOperation,
		CostsCLI:                          cliOperation,
		ServerStopCLI:                     serverstopOperation,
	}
	v192 := provideSessionListPreparation(v170)
	v193 := provideCommandDiagnostics()
	sessionResolvedHandlers := provideSessionResolvedHandlers(localSessionsCLIService, sessionService, v192, v193)
	factoryConfigInitHandler := provideFactoryConfigInitHandler(queryFactoryOperation, listFactoriesOperation, createFactoryFromFileOperation, updateFactoryFromFileOperation, deleteFactoryOperation, replaceFactoryCurrentOperation, validateFactoryOperation, flattenFactoryConfigOperation, expandFactoryConfigOperation, configureInitOperation, cliInstallPackagedFactoryOperation, namedFactoryRootsResolver, v193)
	commandFactory := provideCLICommandFactory(commandOperations, sessionResolvedHandlers, factoryConfigInitHandler)
	stdioOpener := stdio.NewOpener()
	wireMcpServerBuilder := provideMCPServerBuilder(workingDirectory, operatorsettingsService, service, fileSystem, homeDirectoryResolver)
	stdioHandler, err := provideStdioHandler(v170, recordingsService, lifecycleRunnerBuilder, runnerFactory, stdioOpener, wireMcpServerBuilder, v173, workflowPreviewOperation)
	if err != nil {
		return nil, err
	}
	v194 := provideSystemInitializationInspectPath(edges2)
	systeminitializationService, err := provideSystemInitializationService(v32, packagedInstallationFileSystem, packagedInstallationDirectoryCreator, packagedFactoryCatalogOperations, operatorsettingsService, v194, loggingLogger)
	if err != nil {
		return nil, err
	}
	systemInitializationOperation := provideSystemInitializationOperation(systeminitializationService)
	initializer, err := application.NewInitializer(stdioHandler, systemInitializationOperation)
	if err != nil {
		return nil, err
	}
	providerRegistry, err := provideProviderRegistry(edges2, service)
	if err != nil {
		return nil, err
	}
	processLifecycle, err := provideApplicationProcessLifecycle(service, modelsService, eventsService, v170, wireLocalWorkerSessionsBoundary, factoryRuntimeMetricsOwner)
	if err != nil {
		return nil, err
	}
	workerRecordingReader, err := provideWorkerRecordingReader(v10)
	if err != nil {
		return nil, err
	}
	processFactorySessionsCapability, err := provideFactorySessionsCapability(v170)
	if err != nil {
		return nil, err
	}
	processRuntimeMetricsQueryCapability, err := provideRuntimeMetricsQueryCapability(runtimeMetricsQuery)
	if err != nil {
		return nil, err
	}
	processRuntimeCostsQueryCapability, err := provideCostsQueryCapability(costsQuery)
	if err != nil {
		return nil, err
	}
	process, err := application.NewProcessWithRuntimeCosts(commandFactory, initializer, providerRegistry, processLifecycle, server, workerRecordingReader, processFactorySessionsCapability, processRuntimeMetricsQueryCapability, processRuntimeCostsQueryCapability)
	if err != nil {
		return nil, err
	}
	return process, nil
}

// wire.go:

var platformSet = wire11.NewSet(
	provideProcessLogger, wire11.FieldsOf(new(edges.Edges), "Clock"),
)

var apiSet = wire11.NewSet(http.NewAdapter, http.NewHandler, stdio.NewOpener, provideHTTPRuntimeBindingWithMetrics)

var servicesSet = wire11.NewSet(
	provideProvidersService,
	provideEventsService,
	provideWorkerRecordingWriter,
	provideWorkerSessionRecorder, wire5.NewWorkerControlOperationStore, wire5.NewWorkerRestartInputStore, wire5.NewWorkerOwnerRecoveryOperation, provideWorkerRecordingReader,
	provideWorkerWorkAttributionReader,
	provideWorkerSessionsService,
	provideWorkerHistorySnapshotBudget,
	provideWorkerAttemptOpener,
	provideApplicationProcessLifecycle,
	provideProviderRegistry,
	provideFactorySessionProviderIdentityResolver, wire6.NewRequestPreparation, wire6.NewLiveChangeCoordinator, wire6.NewIdentity, wire6.NewResponseStreams, wire6.NewSessionRegistry, wire6.NewResponseStreamRegistry, wire6.NewSessionState, wire6.NewInvocationAuthority, wire6.NewInvocationOwner, wire6.NewInvocationTelemetry, wire6.NewInvocationSpecialCase, provideInvocationWorkPolicy, wire6.NewScopeControl, wire6.NewRecordedHistory, wire6.NewProcessDurableScope, provideProcessDurableExecution, wire6.NewScopeActivation, provideInvocationWorldStateProjector, wire6.NewStreamObserver, wire6.NewStreamManager, wire11.Bind(new(wire6.StreamManager), new(*wire6.GatewayStreams)), provideFactorySessionHTTPRequestPreparation, factory.NewFactoryStatusProjector, factory.NewSessionResultProjectionOperation, provideOperatorSettingsFileSystem,
	provideOperatorSettingsCreateTemporaryFile,
	provideOperatorSettingsProviderCatalog,
	provideOperatorSettingsLogger,
	provideChatSessionsService, wire2.NewDocumentService, wire2.NewResolutionService, wire2.NewService, wire2.NewCLIService, provideOperatorSettingsDocumentPreserver,
	provideOperatorSettingsIDGenerator,
	provideChatSessionsFactoryTargetCatalogService,
	provideACPServerFactorySessionStartResolver,
	provideACPServerResolveHomeDir,
	provideChatSessionsResponseBridge,
	provideACPServerResponseBridge,
	provideACPServer,
	provideACPWireRecorder,
	provideOperatorConfigDecoder,
	provideOperatorConfigDiagnosticsDecoder,
	provideOperatorConfigEncoder,
	provideSystemInitializationInspectPath,
	provideOperatorConfigLoader,
	provideOperatorBackendScopeEnsurer,
	provideDurableOpening,
	provideAPIServerStarter,
	provideRuntimeHostOperation,
	provideProcessRuntimeFactory, wire6.NewLifecyclePlanOperation, provideFactoryVisualizationFactory,
	provideResponsePresentation, wire10.NewRuntimeSinkOwner, wire6.NewOpeningPresentationOwner, provideWorkContentStagingService, wire.NewContentPolicy, wire.NewContentPreparation, wire.NewRequestContentBridge, wire.NewRequestPolicy, wire.NewRequestPreparationService, work.NewSingleWorkTargetPreparation, work.NewListRequestPreparation, work.NewFactoryRequestBatchPreparation, wire.NewInvocationInputPolicy, wire.NewInvocationInputAdapter, provideWorkSessionResolver, wire.NewStateAccess, provideWorkSnapshotReader,
	provideWorkersMockWorkersConfigFileSystem,
	provideWorkersMockWorkersConfigDiagnosticsLoader,
	provideRuntimeArtifactClock,
	provideRuntimeArtifactIDGenerator,
	provideRuntimeArtifactPathReserver,
	provideRuntimeMetricsCoordination,
	provideRuntimeMetricsRetentionFileSystem,
	provideRuntimeArtifactRootResolver,
	provideRuntimeLoggerFactory,
	provideRuntimeLogOwner,
	provideRuntimeMetricsOwner,
	provideManagedRunnerFactory,
	provideModelAssetHTTP,
	provideModelAssetMakeDirectories,
	provideModelAssetInspectPath,
	provideModelAssetResolveHomeDirectory,
	provideModelAssetWriteFile,
	provideModelAssetRenamePath,
	provideModelAssetRemovePath,
	provideModelAssetReadFile,
	provideModelAssetReadDirectory,
	provideModelAssetCreateFile,
	provideModelAssetOpenFile,
	provideModelAssetResolveEnvironment,
	provideModelHostHTTP,
	provideModelRuntimeInspectFile,
	provideModelRuntimeTempDirectory,
	provideModelAssetEndpoints,
	provideModelAssetCoordination,
	provideModelHostClock,
	provideModelNow,
	provideModelRuntimeRunner,
	provideModelRuntimeTempFile,
	provideModelHostLauncher,
	provideModelOrderedRuntimeEvidence,
	provideModelRuntimeEvidenceSource,
	provideModelHostSymlinks,
	provideModelHostProtocol,
	provideModelHostCompatibility,
	provideModelBackendArtifactResolver,
	provideModelAssetRevision,
	provideModelRuntimeScopes,
	provideModelAssets,
	provideModelSlotFacts,
	provideModelHostLogger,
	provideModelHostMetrics,
	provideModelSlotCoordinator,
	provideModelRuntimeHost,
	provideModelInvocationRuntime,
	provideModelResourceLimiter, wire7.NewInertInvocationArtifactFileSystem, wire7.NewInvocationArtifactRegistrar, wire7.NewExecutionDeadline, provideModelInference,
	provideModelsService,
	provideModelScopedLocalExecution, wire7.NewCatalogReadinessQuery, wire7.NewCatalog, wire7.NewSlotState, wire7.NewHostLeases, provideModelAssetHostPlatform,
	provideFactorySessionsWorkingDirectory,
	provideFactorySessionDirectoryInspection,
	provideFactorySessionResolveLogicalTargetSymlinks,
	provideFactorySessionContractFixtureReader,
	provideFactorySessionInvocationInputReader,
	provideFactorySessionReplayRecordingReader,
	provideRecordingOpenFile,
	provideRecordedSessionInventory,
	provideFactorySessionInitialWorkReader,
	provideFactorySessionResolveHomeDirectory,
	provideFactorySessionIDGenerator,
	provideFactorySessionRuntimeInstanceIDGenerator,
	provideFactorySessionResponseEventIDGenerator,
	provideFactorySessionResponseEventRetentionLimits,
	provideFactorySessionCursorPersistenceFileSystem,
	provideFactorySessionCursorCreateTemporaryFile,
	provideFactorySessionCursorStoreFactory,
	provideFactorySessionRuntimePersistenceFileSystem,
	provideFactorySessionRuntimePersistenceStoreFactory,
	provideFactorySessionSyncWaitScheduler,
	provideModelInvocationArtifactExporter,
	provideModelInvocationTimeout,
	provideModelInvocationOperation,
	provideModelsCLIComposition,
	provideModelsCLIInputFileReader,
	provideModelsCLIOutputFileSystem,
	provideWorkService,
	provideWorkDurabilityReader,
	provideWorkRequestIDGenerator,
	provideWorkSubmittedFileReader,
	provideWorkSubmittedFilePathInspector,
	provideWorkContentHostPlatform,
	provideContentMaterializer,
	provideFactoryInvocationPolicyPorts,
	provideWorkersInferenceMediaFileReader,
	provideDecisionEnvelopeService,
	provideInvocationInterpolationService,
	provideInvocationOutputShapingService,
	provideInvocationWorkTypeService,
	provideQuorumPolicyService,
	provideWorkPropagationPolicyService,
	provideWorkstationExecutionPolicyService,
	provideTTSObservabilityService,
	provideAutomationHostedClock,
	provideAutomationHostedHTTPClient,
	provideAutomationHostedSecretResolver,
	provideAutomationHostedCheckpointStore,
	provideAutomationsCursorFileSystem,
	provideAutomationsHostedPollers,
	provideAutomationsClock,
	provideAutomationsScriptPollers,
	provideAutomationsOwner, wire8.NewCursorScopes, wire8.NewSourceLifecycle, wire8.NewReconciliation, wire8.NewCron, wire8.NewFilesystemWatchers, provideAutomationsCommandRunner,
	provideAutomationsRoot, wire11.Bind(new(automations.Service), new(automations.Root)), wire6.NewRuntimeAssembly, wire6.NewGateway, wire6.NewRuntimeModelInvocation, provideRuntimeModelFactoryConfigReader,
	provideRuntimeModelWorkerExecution,
	provideFactorySessionReconnectValidator, wire6.NewSessionHost, wire6.NewNamedFactoryActivator, wire6.NewKeyedDefinitionActivationGateway, provideSessionCheckpointStoreFactory,
	provideFactorySessionsCapability,
	provideFactoryVisualizationMetricsQuery,
	provideRuntimeMetricsQueryCapability,
	provideProviderPriceTableReader,
	provideCostsQuery,
	provideCostsQueryCapability,
	provideFactoryWebhookHTTPClient,
	provideFactoryWebhookSecretResolver,
	provideFactoryWebhookClock,
	provideFactoryWebhookDeadLetterAppender, wire9.NewService, providePortableRecordingWriter,
	provideOrchestrationJavaScriptExecution,
	provideOrchestrationCompilation, wire3.NewJavaScriptCheckpointSummaries, wire6.NewRuntimeBackedExecution, provideFactorySessionReplayInputs,
	provideRecordingClock,
	provideRecordingSnapshotWriter,
	provideRecordingPublication,
	provideRecordingReadFile, wire5.NewRuntimeLedgerRouter, wire5.RuntimeLedger, wire5.NewProjectionService, wire5.NewRecordingLifecycleOwner, wire5.NewCanonicalLedgerOwner, wire5.NewArtifactsExportOwner, wire5.NewReplayOwner, wire5.NewHistoricalQueryOwner, wire5.NewRecordingFlushTickerFactory, wire4.FactorySnapshotJSONDecoder, provideRecordingsRoot,
	provideRecordingsRuntimeScopeService,
	provideReplayArtifactStorage,
	provideFactoryRuntimeIDGenerator,
	provideFactoryRuntimeDirectories,
	provideFactoryRuntimeInputs,
	provideFactoryRuntimeInputDirectoryWalker,
	provideFactoryRuntimeWorkflowSources,
	provideFactoryRuntimeWorkflowSourceResolveSymlinks,
	provideFactoryRuntimeWorkflowHome,
	provideFactoryDefinitionPortableFileSystem,
	provideFactoryDefinitionLoadingFileSystem,
	provideFactoryDefinitionClock,
	provideFactoryDefinitionVersionFileSystem,
	provideFactoryDefinitionPackagedGoalPromptFileSystem,
	provideFactoryDefinitionPortableBundledFileInspection,
	provideFactoryDefinitionRequiredToolPathLookup,
	provideFactoryDefinitionRequiredToolVersionProbe,
	provideFactoryDefinitionRequiredToolChecker,
	provideFactoryDefinitionPersistenceFileSystem,
	provideFactoryDefinitionDirectoryReplacementStore,
	provideFactoryDefinitionNamedPathFileSystem,
	provideFactoryDefinitionNamedPathResolver,
	provideFactoryDefinitionNamedFactoryCatalogFileSystem,
	provideFactoryDefinitionPackagedInstallationFileSystem,
	provideFactoryDefinitionPackagedInstallationDirectoryCreator,
	providePackagedFactoryInstallation,
	provideFactoryDefinitionAuthoredReaderFileSystem,
	provideFactoryDefinitionAuthoredWriterFileSystem,
	provideFactoryDefinitionScaffoldFileSystem,
	provideFactoryDefinitionScaffoldOutput,
	provideFactoryDefinitionInputInboxSentinelEnsurer,
	providePortableBundledFilesMaterializer,
	providePortableBundledFileWritesValidator,
	providePortableBundledFilesCopier,
	providePortableBundledFileSourceResolver,
	providePortableBundledFilesApplier,
	provideFactoryStarterWorkApplier,
	providePortableBundledDocsPruner,
	provideFactoryDefinitionLoader,
	provideFactoryRuntimeClockResolver,
	provideFactoryRuntimeMetricsClock,
	providePprofCommandLineReader,
	provideFactoryRuntimeProviderOverride,
	provideFactoryRuntimeSubmissionRecorder,
	provideFactoryRuntimeDispatchRecorder,
	provideFactorySessionInvocationMetricsRecorder,
	provideFactoryRuntimeProviderCommandRunner,
	provideFactoryRuntimeScriptCommandRunner,
	provideFactoryRuntimeSessionLoggerFactory,
	provideWorkersRetryRandomSource,
	provideWorkersWorkstationFileSystem,
	provideWorkersProviderTemporaryFileSystem,
	provideAgyPTYAllocator,
	provideWorkersMockCommandRunnerFactory,
	provideWorkerCommandRunnerAdapter,
	provideFactoryDefinitionsRuntimeRouter,
	provideFactoryDefinitionsRoot,
	provideFactoryScaffoldInitializer,
	provideEditableFactoryValidator,
	provideInitialFactorySnapshotFactory, wire3.NewRuntimeFactory, wire3.NewOutboxOpening, wire3.NewDefinitionMapper, provideRuntimePreparationWorkstationLoader,
	provideRuntimePreparation,
	provideRuntimeRequestInvocationFiles,
	provideRuntimeRequestPrompts,
	provideRuntimeRequestTemplateFields,
	provideRuntimeRequestArtifactFiles,
	provideRuntimeRequestProgress,
	provideRuntimeRequestLogger, wire3.NewWorkstationRequestExecutor, provideFactoryRuntimeAssembly,
	provideInitialRuntimeActivation, wire3.NewSidecarOpening, provideFactoryRuntimeRoot,
	provideRuntimeOrchestration,
	provideRuntimeDispatchPlanning, wire3.NewLifecycle, wire3.NewInstanceHost, wire3.NewRuntimeStopOperation, provideLoadedFactorySourceFactory,
	provideLoadedFactoryLoader,
	provideReplayArtifactLoader,
	provideReplayRuntimeConfigDecoder, wire6.NewRoot, wire6.NewRuntimeInputLoading, wire6.NewHistoricalReplayBehavior, wire11.Bind(new(factorysessions.Service), new(*wire6.Root)),
)

var providerSessionServiceSet = wire11.NewSet(
	provideProviderSessions,
)

var factorySessionsServicesSet = wire11.NewSet(
	provideJavaScriptWorkflows,
)

var factoryDefinitionsServicesSet = wire11.NewSet(
	provideFactoryDefinitionCompilation,
	provideFactoryDefinitionRuntimeSnapshot,
	provideFactoryDefinitionValidationOwner,
	provideOrchestratorDefinitionValidator,
	provideFactoryDefinitionValidationService,
	provideFactoryDefinitionValidator,
	provideDefinitionValidationOperation,
	provideSubmittedDefinitionValidationOperation,
	provideAuthoredFactorySourceLoader,
	provideJavaScriptWorkflowDefinitions,
	provideWorkflowPreviewOperation,
	provideNamedFactoryCatalog,
	provideLoadedFactorySnapshotCapturer,
	provideFactoryScaffoldCommandInitializer,
	provideFactoryDefinitionPersistence,
	provideNamedFactoryPersistenceOperation,
	provideEffectiveFactoryCatalogDiscovery,
	provideEffectiveFactoryDefinitionNormalizer,
	provideEffectiveFactoryCatalogOperation,
	provideEffectiveFactoryDefinitionsService, wire4.NewCatalogPathsService, wire4.NewCatalogService,
)

var workerServiceSet = wire11.NewSet(
	provideStatelessWorkersService,
	provideWorkersAgentToolFileSystem,
	provideWorkersWorktree,
	provideWorkersWorktreeRelease,
	provideWorkersFactoryDocsFileSystem,
	provideWorkerProcessEnvironment,
	provideWorkerCurrentWorkingDirectory,
)

var cliCommandOperationsSet = wire11.NewSet(
	provideCLIObserver,
	provideNamedFactoryRootsResolver,
	provideNamedFactoryCandidatePathsResolver,
	provideBatchInputFileSystem,
	provideRunInputPathInspector,
	provideRunDirectoryCreator,
	provideBrowserOpener,
	provideCurrentFactoryDirectoryResolver,
	provideFactoryConfigRootResolver,
	provideFactoryConfigFileLoader,
	provideWorkRequestFileLoader,
	provideTerminalLoggerBuilder,
	provideLiveRecordingTargetPlanner,
	provideRecordingsCLIAdapter,
	provideCLIRunDefaults,
	provideSubmitPayloadReader,
	provideOperatorDefaultsResolver,
	provideStandardCLIHTTPProtocol,
	provideModelsPullCLIHTTPProtocol,
	provideMetricsCLI,
	provideCostsCLI,
	provideCostsReportCLI,
	provideServerStopCLI,
	provideRemoteInvocationOperation,
	provideExtendedCLIHTTPProtocol,
	provideWatchCLIHTTPProtocol,
	provideStreamingCLIHTTPProtocol,
	provideSubmitWorkOperation,
	provideSubmitBatchOperation,
	provideListWorkerSessionsOperation,
	provideShowWorkerSessionOperation,
	provideReadWorkerSessionOperation,
	provideStreamWorkerSessionOperation,
	provideWorkerSessionsCLIIdentityGenerator,
	provideWorkerSessionsCLIExecutionFileReader,
	provideContinueWorkerSessionOperation,
	provideInterruptWorkerSessionOperation,
	providePauseWorkerSessionOperation,
	provideResumeWorkerSessionOperation,
	provideCancelWorkerSessionOperation,
	provideTerminateWorkerSessionOperation,
	provideLocalWorkerSessionsBoundary, wire11.Bind(new(workersessions.LocalInvokeBoundary), new(*localWorkerSessionsBoundary)), wire11.Bind(new(workersessions.LocalControlBoundary), new(*localWorkerSessionsBoundary)), provideInvokeWorkerSessionOperation,
	provideSessionsCLIService,
	provideSessionListPreparation,
	provideCommandDiagnostics,
	provideSessionResolvedHandlers,
	provideFactoryConfigInitHandler,
	provideLocalSessionsCLIService,
	provideModelsCLIService,
	provideProvidersCLIService,
	provideFlattenFactoryConfigOperation,
	provideExpandFactoryConfigOperation,
	provideConfigureInitOperation,
	provideACPCLIService,
	provideInstallPackagedFactoryOperation,
	provideInstallPackagedFactoryCLI,
	provideQueryFactoryOperation,
	provideCurrentFactoryPointerReader,
	provideListFactoriesOperation,
	provideFactoryNameCompletionOperation,
	providePackagedFactoryNameCompletionOperation,
	provideSelectedFactorySignatureCompletionOperation,
	provideValidateFactoryOperation,
	provideCreateFactoryFromFileOperation,
	provideReplaceFactoryCurrentOperation,
	provideUpdateFactoryFromFileOperation,
	provideDeleteFactoryOperation,
	provideListWorkOperation,
	provideListHumanApprovalsOperation,
	provideShowHumanApprovalOperation,
	provideWatchReconnectWait,
	provideWatchWorkOperation,
	provideShowWorkOperation,
	provideMoveWorkOperation,
	provideWorkVisualizationOperation,
	provideVisualizeWorkOperation, wire11.Struct(new(cli.CommandOperations), "*"),
)

// BundleSet is the one canonical provider set used by the single public bundle
// injector. It constructs only inert command and service initializers.
var BundleSet = wire11.NewSet(
	platformSet,
	apiSet,
	servicesSet,
	providerSessionServiceSet,
	factorySessionsServicesSet,
	factoryDefinitionsServicesSet,
	workerServiceSet,
	cliCommandOperationsSet,
	providePackagedFactoryDefinitions,
	provideSerializedFactoryConfigReader,
	provideCanonicalFactoryConfigReader,
	providePackagedFactoryCatalog,
	provideSystemInitializationService,
	provideSystemInitializationOperation, wire11.Bind(new(factorydefinitions.Persistence), new(factorydefinitions.PackagedFactoryPersistence)), wire11.Bind(new(process.ACPServer), new(acp.Server)), provideLifecycleRunnerFactory,
	provideWorkStopSummaryProjector,
	provideSessionStartRequestFactory, application.NewLifecycleRunnerBuilder, provideRunRuntimeRunnerBuilder,
	provideRunSelectionFactory,
	provideInvocationOperation,
	provideMCPServerBuilder,
	provideStdioHandler,
	provideDirectJavaScriptHostAdapter, run.NewDirectJavaScriptRunOperation, application.NewInitializer, provideRunInvocationOperation,
	provideModelsCLIInvocationOperation,
	provideCLICommandFactory, application.NewProcessWithRuntimeCosts, wire11.Bind(new(process.Initializer), new(*application.Initializer)), wire11.Bind(new(process.CommandFactory), new(cli.CommandFactory)),
)
