package customer_lifecycles_test

import "testing"

// TestReviewFailureRecoveryJourneys owns its immutable fixture until all customer scenarios finish.
func TestReviewFailureRecoveryJourneys(t *testing.T) {
	initializeFactoryreviewfailureroutingFixture(t)
	t.Parallel()
	resetfactoryreviewfailurerouting1State()
	t.Run("TestEscalatePlanFailure_ConsumesFailedPlanSoRestoredIdeaIsNotReescalated", testFactoryreviewfailureroutingEscalatePlanFailure_ConsumesFailedPlanSoRestoredIdeaIsNotReescalated)
	t.Run("TestMergedPRRoute_CompletionAndUnmergedLimits", testFactoryreviewfailureroutingMergedPRRoute_CompletionAndUnmergedLimits)
	t.Run("TestReviewRetirement_RequiresMatchingCompletedTask", testReviewRetirement_RequiresMatchingCompletedTask)
	t.Run("TestMergedPRRoute_AuthoredFactoryValidateOnly", testFactoryreviewfailureroutingMergedPRRoute_AuthoredFactoryValidateOnly)
	t.Run("TestProjectLead_ContinueDecisionKeepsProjectWaitingWithoutEscalation", testFactoryreviewfailureroutingProjectLead_ContinueDecisionKeepsProjectWaitingWithoutEscalation)
	t.Run("TestProjectLoopback_ProposalOutcomes", testProjectLoopbackProposalOutcomes)
	t.Run("TestProjectLoopback_F4BusyLead", testProjectLoopbackBusyLead)
	t.Run("TestProjectLoopback_F5SequentialOrigins", testProjectLoopbackSequentialOrigins)
	t.Run("TestProjectReport_CarriesTheExactFailedChildWorkID", testFactoryreviewfailureroutingProjectReport_CarriesTheExactFailedChildWorkID)
	t.Run("TestProjectLeadWake_CompletedChildWakesOnlyItsOwnLeadOnce", testFactoryreviewfailureroutingProjectLeadWake_CompletedChildWakesOnlyItsOwnLeadOnce)
	t.Run("TestProjectLeadWake_FailedChildWakesOnlyItsOwnLeadOnce", testFactoryreviewfailureroutingProjectLeadWake_FailedChildWakesOnlyItsOwnLeadOnce)
	t.Run("TestProjectLeadWake_AgentDecisionFailureWakesOnlyItsOwnLeadOnce", testFactoryreviewfailureroutingProjectLeadWake_AgentDecisionFailureWakesOnlyItsOwnLeadOnce)
	t.Run("TestProjectLeadWake_ChildrenFinishingWhileLeadIsBusyQueueOneWakeEach", testFactoryreviewfailureroutingProjectLeadWake_ChildrenFinishingWhileLeadIsBusyQueueOneWakeEach)
	t.Run("TestReviewFailureRouting_ManualMigrationDispatchesExactReviewOnce", testFactoryreviewfailureroutingReviewFailureRouting_ManualMigrationDispatchesExactReviewOnce)
	t.Run("TestReviewFailureRouting_RejectionReturnsOneCorrectionToSameOwner", testFactoryreviewfailureroutingReviewFailureRouting_RejectionReturnsOneCorrectionToSameOwner)
	t.Run("TestReviewFailureRouting_ReviewedTaskCompletesAfterFailedIdea", testFactoryreviewfailureroutingReviewFailureRouting_ReviewedTaskCompletesAfterFailedIdea)
	t.Run("TestReviewFailureRouting_FailedIdeaRequiredBeforeReviewedTaskCompletion", testFactoryreviewfailureroutingReviewFailureRouting_FailedIdeaRequiredBeforeReviewedTaskCompletion)
	t.Run("TestReviewFailureRouting_ReviewedTaskCompletesBeforeDependentProjectCycleDispatchesOnce", testFactoryreviewfailureroutingReviewFailureRouting_ReviewedTaskCompletesBeforeDependentProjectCycleDispatchesOnce)
	t.Run("TestReviewFailureRouting_ReviewedTaskCompleteRejectsStaleSameNameReview", testFactoryreviewfailureroutingReviewFailureRouting_ReviewedTaskCompleteRejectsStaleSameNameReview)
	t.Run("TestReviewFailureRouting_ReviewedTaskCompleteRejectsMismatchedCompletionIdentityOrName", testFactoryreviewfailureroutingReviewFailureRouting_ReviewedTaskCompleteRejectsMismatchedCompletionIdentityOrName)
	t.Run("TestReviewFailureRouting_ReviewedTaskCompleteRejectsUnauthorizedReviewEvidenceKeepsFeedbackActionable", testFactoryreviewfailureroutingReviewFailureRouting_ReviewedTaskCompleteRejectsUnauthorizedReviewEvidenceKeepsFeedbackActionable)
	t.Run("TestReviewFailureRouting_ReviewedTaskCompleteReplayIsExactlyOnce", testFactoryreviewfailureroutingReviewFailureRouting_ReviewedTaskCompleteReplayIsExactlyOnce)
	t.Run("TestWorkPayload_ReachesWorkerPromptForNormallyAdmittedIdea", testFactoryreviewfailureroutingWorkPayload_ReachesWorkerPromptForNormallyAdmittedIdea)
	t.Run("TestWorkPayload_ReachesWorkerPromptForIdeaAdmittedWithExplicitState", testFactoryreviewfailureroutingWorkPayload_ReachesWorkerPromptForIdeaAdmittedWithExplicitState)
	t.Run("TestWorkPayload_ReachesWorkerPromptForIdeaReleasedByDependsOnGate", testFactoryreviewfailureroutingWorkPayload_ReachesWorkerPromptForIdeaReleasedByDependsOnGate)
	t.Run("TestWorkPayload_IsReturnedByWorkRead", testFactoryreviewfailureroutingWorkPayload_IsReturnedByWorkRead)
	t.Run("TestWorkPayload_IsRecordedInWorkRequestEvent", testFactoryreviewfailureroutingWorkPayload_IsRecordedInWorkRequestEvent)
	t.Run("TestWorkPayload_NonASCIIRoundTripsByteExact", testFactoryreviewfailureroutingWorkPayload_NonASCIIRoundTripsByteExact)
}
