package customer_lifecycles_test

import "testing"

// TestFactoryEligibilityJourneys owns its immutable fixture until all customer scenarios finish.
func runFactoryEligibilityJourneys(t *testing.T) {
	t.Parallel()
	initializeOrchestrationpetriguardsFixture(t)
	t.Run("TestGuardSameNameMismatchRemainsUndispatched", testOrchestrationpetriguardsGuardSameNameMismatchRemainsUndispatched)
	t.Run("TestGuardWorkerErrorProducesOneFailedOutcome", testOrchestrationpetriguardsGuardWorkerErrorProducesOneFailedOutcome)
	t.Run("TestGuardTimeoutDiagnosticProducesFailedOutcome", testOrchestrationpetriguardsGuardTimeoutDiagnosticProducesFailedOutcome)
	t.Run("TestGuardPartialCompletionPreservesIndependentOutcome", testOrchestrationpetriguardsGuardPartialCompletionPreservesIndependentOutcome)
	t.Run("TestGuardConcurrentSessionsKeepResponsesKeyed", testOrchestrationpetriguardsGuardConcurrentSessionsKeepResponsesKeyed)
	t.Run("TestGuardCancellationStopsGatedDispatchAndHostReuse", testOrchestrationpetriguardsGuardCancellationStopsGatedDispatchAndHostReuse)
	t.Run("TestGuardEmptyInputGuardListRemainsValid", testOrchestrationpetriguardsGuardEmptyInputGuardListRemainsValid)
	t.Run("TestGuardUnknownDefinitionReturnsValidation", testOrchestrationpetriguardsGuardUnknownDefinitionReturnsValidation)
	t.Run("TestGuardDuplicateStateDefinitionReturnsValidation", testOrchestrationpetriguardsGuardDuplicateStateDefinitionReturnsValidation)
	t.Run("TestGuardWorkRequestIDIsIdempotent", testOrchestrationpetriguardsGuardWorkRequestIDIsIdempotent)
	t.Run("TestGuardCleanupReleasesEarlyExitSessionAndAllowsReuse", testOrchestrationpetriguardsGuardCleanupReleasesEarlyExitSessionAndAllowsReuse)
	t.Run("TestLogicalRoundTripFactoryBoundaryProvesProductiveRejectionsSurvive", testOrchestrationpetriguardsLogicalRoundTripFactoryBoundaryProvesProductiveRejectionsSurvive)
	t.Run("TestLogicalRoundTripFactoryBoundaryStopsUnbalancedRoute", testOrchestrationpetriguardsLogicalRoundTripFactoryBoundaryStopsUnbalancedRoute)
	t.Run("TestLogicalRoundTripFactoryBoundaryRecordReplayPreservesTerminalProjection", testOrchestrationpetriguardsLogicalRoundTripFactoryBoundaryRecordReplayPreservesTerminalProjection)
	t.Run("TestDependsOnSecondaryJoinedInput", testOrchestrationpetriguardsDependsOnSecondaryJoinedInput)
}
