package customer_lifecycles_test

import "testing"

// TestFactorySessionLifecycleParityJourneys owns its immutable fixture until all customer scenarios finish.
func runFactorySessionLifecycleParityJourneys(t *testing.T) {
	t.Parallel()
	t.Run("TestCrossEmptyFactorySessionHasZeroWorkAndLeavesHostUsable", testOrchestrationpetricrossCrossEmptyFactorySessionHasZeroWorkAndLeavesHostUsable)
	t.Run("TestCrossMalformedFactoryOpenReturnsValidationAndNoSessionRoute", testOrchestrationpetricrossCrossMalformedFactoryOpenReturnsValidationAndNoSessionRoute)
	t.Run("TestCrossExplicitSessionsKeepKeyedLifecycleAndStatusState", testOrchestrationpetricrossCrossExplicitSessionsKeepKeyedLifecycleAndStatusState)
	t.Run("TestCrossCancelGatedJavaScriptSessionPreservesAnotherSession", testOrchestrationpetricrossCrossCancelGatedJavaScriptSessionPreservesAnotherSession)
	t.Run("TestCrossLifecycleRequestIDIsIdempotent", testOrchestrationpetricrossCrossLifecycleRequestIDIsIdempotent)
	t.Run("TestCrossCleanupReleasesEarlyExitSessionAndAllowsReuse", testOrchestrationpetricrossCrossCleanupReleasesEarlyExitSessionAndAllowsReuse)
	t.Run("TestPetriAndJavaScriptSessionsShareLifecycleControls", testOrchestrationpetricrossPetriAndJavaScriptSessionsShareLifecycleControls)
	t.Run("TestPetriAndJavaScriptSessionsExposeCompatibleStatusFacts", testOrchestrationpetricrossPetriAndJavaScriptSessionsExposeCompatibleStatusFacts)
}
