package customer_lifecycles_test

import "testing"

// TestFactorySessionLifecycleJourneys owns its immutable fixture until all customer scenarios finish.
func TestFactorySessionLifecycleJourneys(t *testing.T) {
	t.Parallel()
	resetsessionslifecycle0State()
	initializeSessionslifecycleFixture(t)
	t.Run("TestFactorySessionCreateListShowDelete", testSessionslifecycleFactorySessionCreateListShowDelete)
	t.Run("TestFactorySessionListMultipleSessions", testSessionslifecycleFactorySessionListMultipleSessions)
	t.Run("TestFactorySessionMissingShowAndDeleteFail", testSessionslifecycleFactorySessionMissingShowAndDeleteFail)
	t.Run("TestAPIOpenListGetAndCloseFactorySession", testSessionslifecycleAPIOpenListGetAndCloseFactorySession)
	t.Run("TestAPIFactorySessionNotFoundUsesTypedError", testSessionslifecycleAPIFactorySessionNotFoundUsesTypedError)
	t.Run("TestAPIMultipleFactorySessionsRemainIsolated", testSessionslifecycleAPIMultipleFactorySessionsRemainIsolated)
	t.Run("TestFSCP01StartOpenIdentityStatusModeMatrix", testSessionslifecycleFSCP01StartOpenIdentityStatusModeMatrix)
	t.Run("TestFSCP01InvokeLifecycleAndResultOutcomeMatrix", testSessionslifecycleFSCP01InvokeLifecycleAndResultOutcomeMatrix)
	t.Run("TestFactorySessionOpenReturnsFolderAndTargetDiagnostics", testSessionslifecycleFactorySessionOpenReturnsFolderAndTargetDiagnostics)
	t.Run("TestFactorySessionValidateOnlyReturnsTargetWithoutAdmission", testSessionslifecycleFactorySessionValidateOnlyReturnsTargetWithoutAdmission)
	t.Run("TestCLIRemoteRunStartsDurableSessionOnSelectedServer", testSessionslifecycleCLIRemoteRunStartsDurableSessionOnSelectedServer)
	t.Run("TestCLILocalAndRemoteRunSuccessParityThroughRootProcess", testSessionslifecycleCLILocalAndRemoteRunSuccessParityThroughRootProcess)
	t.Run("TestCLILocalAndRemoteRunDomainFailureParityThroughRootProcess", testSessionslifecycleCLILocalAndRemoteRunDomainFailureParityThroughRootProcess)
	t.Run("TestCLILocalAndRemoteRunCancellationParityThroughRootProcess", testSessionslifecycleCLILocalAndRemoteRunCancellationParityThroughRootProcess)
	t.Run("TestCLIRemoteRunTransportFailureKeepsStreamsAndExitObservable", testSessionslifecycleCLIRemoteRunTransportFailureKeepsStreamsAndExitObservable)
}
