package customer_lifecycles_test

import "testing"

// TestCLISessionResumeJourneys owns its immutable fixture until all customer scenarios finish.
func TestCLISessionResumeJourneys(t *testing.T) {
	t.Parallel()
	resettransportclisessionresume2State()
	initializeTransportclisessionresumeFixture(t)
	t.Run("TestCLIResumeSmokeLane_NonResumeTerminalSessionShowPreservesShippedCLIReadSemantics", testTransportclisessionresumeCLIResumeSmokeLane_NonResumeTerminalSessionShowPreservesShippedCLIReadSemantics)
	t.Run("TestCLIResumeSmokeLane_RetiredDispatchCommandLeavesRESTReadAvailable", testTransportclisessionresumeCLIResumeSmokeLane_RetiredDispatchCommandLeavesRESTReadAvailable)
	t.Run("TestCLIResumeSmoke_InterruptedJavaScriptFactorySessionResumesThroughSharedSessionCommands", testTransportclisessionresumeCLIResumeSmoke_InterruptedJavaScriptFactorySessionResumesThroughSharedSessionCommands)
	t.Run("TestCLIResumeSmoke_DurableResumeContinuityPreservesCompletedChildDispatchesWithoutReplay", testTransportclisessionresumeCLIResumeSmoke_DurableResumeContinuityPreservesCompletedChildDispatchesWithoutReplay)
	t.Run("TestCLIResumeSmoke_TerminalSessionResumeReturnsTypedRejectionAndPreservesSessionRead", testTransportclisessionresumeCLIResumeSmoke_TerminalSessionResumeReturnsTypedRejectionAndPreservesSessionRead)
	t.Run("TestCLIResumeSmoke_RunningSessionResumeReturnsTypedNoOpAndPreservesSessionRead", testTransportclisessionresumeCLIResumeSmoke_RunningSessionResumeReturnsTypedNoOpAndPreservesSessionRead)
}
