package customer_lifecycles_test

import "testing"

// TestCLIFactoryDiscoveryJourneys owns its immutable fixture until all customer scenarios finish.
func TestCLIFactoryDiscoveryJourneys(t *testing.T) {
	t.Parallel()
	resettransportclirootdiscovery1State()
	initializeTransportclirootdiscoveryFixture(t)
	t.Run("TestManifestProjectedRepresentativeHandlersAcceptCanonicalInputs", testTransportclirootdiscoveryManifestProjectedRepresentativeHandlersAcceptCanonicalInputs)
	t.Run("TestCurrentFactoryFailsBeforeProductActivation", testTransportclirootdiscoveryCurrentFactoryFailsBeforeProductActivation)
	t.Run("TestServerCurrentFactoryFailsBeforeProductActivation", testTransportclirootdiscoveryServerCurrentFactoryFailsBeforeProductActivation)
	t.Run("TestRunScopedSiteMissingCurrentFactoryFailsBeforeProductActivation", testTransportclirootdiscoveryRunScopedSiteMissingCurrentFactoryFailsBeforeProductActivation)
	t.Run("TestServerNonTTYReadinessGatesBrowserAndCancellationJoinsOwnedServer", testTransportclirootdiscoveryServerNonTTYReadinessGatesBrowserAndCancellationJoinsOwnedServer)
	t.Run("TestServerBindExhaustionWritesDeclaredErrorWithoutResidualEffects", testTransportclirootdiscoveryServerBindExhaustionWritesDeclaredErrorWithoutResidualEffects)
	t.Run("TestCurrentFactoryRunsToIdleWithoutStartingServer", testTransportclirootdiscoveryCurrentFactoryRunsToIdleWithoutStartingServer)
	t.Run("TestLocalRunDisclosesHomeBeforeSystemInitializationAccess", testTransportclirootdiscoveryLocalRunDisclosesHomeBeforeSystemInitializationAccess)
	t.Run("TestServerDisclosesHomeBeforeSystemInitializationAccess", testTransportclirootdiscoveryServerDisclosesHomeBeforeSystemInitializationAccess)
	t.Run("TestCurrentFactoryRunScopedServerStopsAtIdleAndSiteOpensAfterReadiness", testTransportclirootdiscoveryCurrentFactoryRunScopedServerStopsAtIdleAndSiteOpensAfterReadiness)
	t.Run("TestContinuousRunScopedServerKeepsListenerUntilCancellation", testTransportclirootdiscoveryContinuousRunScopedServerKeepsListenerUntilCancellation)
}
