package customer_lifecycles_test

import "testing"

// TestCLIWorkerModeJourneys owns its immutable fixture until all customer scenarios finish.
func TestCLIWorkerModeJourneys(t *testing.T) {
	t.Parallel()
	resetworkerstransportsclirunmodes3State()
	initializeWorkerstransportsclirunmodesFixture(t)
	t.Run("TestCLIRunPartialResponseStreamHasOneFailedTerminal", testWorkerstransportsclirunmodesCLIRunPartialResponseStreamHasOneFailedTerminal)
	t.Run("TestCLIRunEventPresentationsCorrelateWorkDispatchWorkerAndPrimary", testWorkerstransportsclirunmodesCLIRunEventPresentationsCorrelateWorkDispatchWorkerAndPrimary)
	t.Run("TestCLIRunTimeoutRecoversOnSameProcess", testWorkerstransportsclirunmodesCLIRunTimeoutRecoversOnSameProcess)
	t.Run("TestCLIRunCancellationRecoversOnSameProcess", testWorkerstransportsclirunmodesCLIRunCancellationRecoversOnSameProcess)
	t.Run("TestCLIRunEmptyPrimaryAndSelectorRecovery", testWorkerstransportsclirunmodesCLIRunEmptyPrimaryAndSelectorRecovery)
	t.Run("TestCLIRunStdinBoundaryUsesInclusiveWorkPayloadLimit", testWorkerstransportsclirunmodesCLIRunStdinBoundaryUsesInclusiveWorkPayloadLimit)
	t.Run("TestCLIRunPresentationModesCharacterization", testWorkerstransportsclirunmodesCLIRunPresentationModesCharacterization)
	t.Run("TestCLIRunFailurePresentationModesCharacterization", testWorkerstransportsclirunmodesCLIRunFailurePresentationModesCharacterization)
	t.Run("TestCLIRunSuccessPrimaryResultTextJSONAndNDJSON", testWorkerstransportsclirunmodesCLIRunSuccessPrimaryResultTextJSONAndNDJSON)
	t.Run("TestCLIRunFailureOmitsFalseSuccessPrimaryResult", testWorkerstransportsclirunmodesCLIRunFailureOmitsFalseSuccessPrimaryResult)
}
