package customer_lifecycles_test

import "testing"

// TestCLIWorkerLifecycleJourneys owns its immutable fixture until all customer scenarios finish.
func TestCLIWorkerLifecycleJourneys(t *testing.T) {
	t.Parallel()
	resetworkerstransportsclirunlifecycle1State()
	resetworkerstransportsclirunlifecycle3State()
	resetworkerstransportsclirunlifecycle4State()
	initializeWorkerstransportsclirunlifecycleFixture(t)
	t.Run("TestCLIRunCleanInvocationCompletesWithoutDashboardStartup", testWorkerstransportsclirunlifecycleCLIRunCleanInvocationCompletesWithoutDashboardStartup)
	t.Run("TestCLIRunToFilePreservesExactPromptAndRejectsBeforeProviderDispatch", testWorkerstransportsclirunlifecycleCLIRunToFilePreservesExactPromptAndRejectsBeforeProviderDispatch)
	t.Run("TestCLIRunWorkerReasoningEffortOverrideReachesCodexCommand", testWorkerstransportsclirunlifecycleCLIRunWorkerReasoningEffortOverrideReachesCodexCommand)
	t.Run("TestCLIRunUnsupportedWorkerReasoningEffortRejectsBeforeProviderDispatch", testWorkerstransportsclirunlifecycleCLIRunUnsupportedWorkerReasoningEffortRejectsBeforeProviderDispatch)
	t.Run("TestCLIRunServerAttachedInvocationTargetsExistingFactorySession", testWorkerstransportsclirunlifecycleCLIRunServerAttachedInvocationTargetsExistingFactorySession)
	t.Run("TestCLIRunCleanInvocationFailurePreservesPublicError", testWorkerstransportsclirunlifecycleCLIRunCleanInvocationFailurePreservesPublicError)
}
