package contracts

import factorysessions "github.com/portpowered/infinite-you/pkg/services/factory_sessions"

type ExecutionOpeningFileSystem = factorysessions.ExecutionOpeningFileSystem
type DirectoryInspection = factorysessions.DirectoryInspection
type CursorPersistenceFileSystem = factorysessions.CursorPersistenceFileSystem
type CursorPersistenceTemporaryFile = factorysessions.CursorPersistenceTemporaryFile
type CursorPersistenceCreateTemporaryFile = factorysessions.CursorPersistenceCreateTemporaryFile
type RuntimePersistenceFileSystem = factorysessions.RuntimePersistenceFileSystem
type InvocationMetricsRecorder = factorysessions.InvocationMetricsRecorder
