// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/services/models/internal/backends/localai/backend_subset.proto

package localai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthMessage) Reset() {
	*x = HealthMessage{}
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthMessage) ProtoMessage() {}

func (x *HealthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthMessage.ProtoReflect.Descriptor instead.
func (*HealthMessage) Descriptor() ([]byte, []int) {
	return file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescGZIP(), []int{0}
}

type ModelOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	NBatch        int32                  `protobuf:"varint,4,opt,name=NBatch,proto3" json:"NBatch,omitempty"`
	ModelFile     string                 `protobuf:"bytes,21,opt,name=ModelFile,proto3" json:"ModelFile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelOptions) Reset() {
	*x = ModelOptions{}
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelOptions) ProtoMessage() {}

func (x *ModelOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelOptions.ProtoReflect.Descriptor instead.
func (*ModelOptions) Descriptor() ([]byte, []int) {
	return file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescGZIP(), []int{1}
}

func (x *ModelOptions) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelOptions) GetNBatch() int32 {
	if x != nil {
		return x.NBatch
	}
	return 0
}

func (x *ModelOptions) GetModelFile() string {
	if x != nil {
		return x.ModelFile
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ToolCallDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,4,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallDelta) Reset() {
	*x = ToolCallDelta{}
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallDelta) ProtoMessage() {}

func (x *ToolCallDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallDelta.ProtoReflect.Descriptor instead.
func (*ToolCallDelta) Descriptor() ([]byte, []int) {
	return file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallDelta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallDelta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallDelta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallDelta) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type ChatDelta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ReasoningContent string                 `protobuf:"bytes,2,opt,name=reasoning_content,json=reasoningContent,proto3" json:"reasoning_content,omitempty"`
	ToolCalls        []*ToolCallDelta       `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatDelta) Reset() {
	*x = ChatDelta{}
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDelta) ProtoMessage() {}

func (x *ChatDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDelta.ProtoReflect.Descriptor instead.
func (*ChatDelta) Descriptor() ([]byte, []int) {
	return file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescGZIP(), []int{4}
}

func (x *ChatDelta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatDelta) GetReasoningContent() string {
	if x != nil {
		return x.ReasoningContent
	}
	return ""
}

func (x *ChatDelta) GetToolCalls() []*ToolCallDelta {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type PredictOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=Prompt,proto3" json:"Prompt,omitempty"`
	Images        []string               `protobuf:"bytes,42,rep,name=Images,proto3" json:"Images,omitempty"`
	Videos        []string               `protobuf:"bytes,45,rep,name=Videos,proto3" json:"Videos,omitempty"`
	Audios        []string               `protobuf:"bytes,46,rep,name=Audios,proto3" json:"Audios,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,52,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictOptions) Reset() {
	*x = PredictOptions{}
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictOptions) ProtoMessage() {}

func (x *PredictOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictOptions.ProtoReflect.Descriptor instead.
func (*PredictOptions) Descriptor() ([]byte, []int) {
	return file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescGZIP(), []int{5}
}

func (x *PredictOptions) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PredictOptions) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *PredictOptions) GetVideos() []string {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *PredictOptions) GetAudios() []string {
	if x != nil {
		return x.Audios
	}
	return nil
}

func (x *PredictOptions) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Tokens        int32                  `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	PromptTokens  int32                  `protobuf:"varint,3,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	ChatDeltas    []*ChatDelta           `protobuf:"bytes,8,rep,name=chat_deltas,json=chatDeltas,proto3" json:"chat_deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescGZIP(), []int{6}
}

func (x *Reply) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Reply) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *Reply) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Reply) GetChatDeltas() []*ChatDelta {
	if x != nil {
		return x.ChatDeltas
	}
	return nil
}

var File_pkg_services_models_internal_backends_localai_backend_subset_proto protoreflect.FileDescriptor

const file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDesc = "" +
	"\n" +
	"Bpkg/services/models/internal/backends/localai/backend_subset.proto\x12\abackend\"\x0f\n" +
	"\rHealthMessage\"Z\n" +
	"\fModelOptions\x12\x14\n" +
	"\x05Model\x18\x01 \x01(\tR\x05Model\x12\x16\n" +
	"\x06NBatch\x18\x04 \x01(\x05R\x06NBatch\x12\x1c\n" +
	"\tModelFile\x18\x15 \x01(\tR\tModelFile\"<\n" +
	"\x06Result\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"g\n" +
	"\rToolCallDelta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x04 \x01(\tR\targuments\"\x89\x01\n" +
	"\tChatDelta\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12+\n" +
	"\x11reasoning_content\x18\x02 \x01(\tR\x10reasoningContent\x125\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x16.backend.ToolCallDeltaR\ttoolCalls\"\xf0\x01\n" +
	"\x0ePredictOptions\x12\x16\n" +
	"\x06Prompt\x18\x01 \x01(\tR\x06Prompt\x12\x16\n" +
	"\x06Images\x18* \x03(\tR\x06Images\x12\x16\n" +
	"\x06Videos\x18- \x03(\tR\x06Videos\x12\x16\n" +
	"\x06Audios\x18. \x03(\tR\x06Audios\x12A\n" +
	"\bMetadata\x184 \x03(\v2%.backend.PredictOptions.MetadataEntryR\bMetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\x05Reply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x05R\x06tokens\x12#\n" +
	"\rprompt_tokens\x18\x03 \x01(\x05R\fpromptTokens\x123\n" +
	"\vchat_deltas\x18\b \x03(\v2\x12.backend.ChatDeltaR\n" +
	"chatDeltasB[ZYgithub.com/portpowered/infinite-you/pkg/services/models/internal/backends/localai;localaib\x06proto3"

var (
	file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescOnce sync.Once
	file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescData []byte
)

func file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescGZIP() []byte {
	file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescOnce.Do(func() {
		file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDesc), len(file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDesc)))
	})
	return file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDescData
}

var file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_services_models_internal_backends_localai_backend_subset_proto_goTypes = []any{
	(*HealthMessage)(nil),  // 0: backend.HealthMessage
	(*ModelOptions)(nil),   // 1: backend.ModelOptions
	(*Result)(nil),         // 2: backend.Result
	(*ToolCallDelta)(nil),  // 3: backend.ToolCallDelta
	(*ChatDelta)(nil),      // 4: backend.ChatDelta
	(*PredictOptions)(nil), // 5: backend.PredictOptions
	(*Reply)(nil),          // 6: backend.Reply
	nil,                    // 7: backend.PredictOptions.MetadataEntry
}
var file_pkg_services_models_internal_backends_localai_backend_subset_proto_depIdxs = []int32{
	3, // 0: backend.ChatDelta.tool_calls:type_name -> backend.ToolCallDelta
	7, // 1: backend.PredictOptions.Metadata:type_name -> backend.PredictOptions.MetadataEntry
	4, // 2: backend.Reply.chat_deltas:type_name -> backend.ChatDelta
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_services_models_internal_backends_localai_backend_subset_proto_init() }
func file_pkg_services_models_internal_backends_localai_backend_subset_proto_init() {
	if File_pkg_services_models_internal_backends_localai_backend_subset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDesc), len(file_pkg_services_models_internal_backends_localai_backend_subset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_services_models_internal_backends_localai_backend_subset_proto_goTypes,
		DependencyIndexes: file_pkg_services_models_internal_backends_localai_backend_subset_proto_depIdxs,
		MessageInfos:      file_pkg_services_models_internal_backends_localai_backend_subset_proto_msgTypes,
	}.Build()
	File_pkg_services_models_internal_backends_localai_backend_subset_proto = out.File
	file_pkg_services_models_internal_backends_localai_backend_subset_proto_goTypes = nil
	file_pkg_services_models_internal_backends_localai_backend_subset_proto_depIdxs = nil
}
