package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunClassifiesEquivalentOwnershipEdgesBySourceClass(t *testing.T) {
	root := fixtureRepository(t, map[string]string{
		"pkg/services/factory_runtime/doc.go": "package factory_runtime\n",
		"pkg/platform/runtimeinput/config.go": `package runtimeinput
import runtime "github.com/portpowered/infinite-you/pkg/services/factory_runtime"
var _ runtime.Service
`,
		"pkg/platform/runtimeinput/config_test.go": `package runtimeinput
import runtime "github.com/portpowered/infinite-you/pkg/services/factory_runtime"
var _ runtime.Service
`,
	})

	var stdout, stderr bytes.Buffer
	err := run(config{root: root}, &stdout, &stderr)
	if err == nil {
		t.Fatal("run() error = nil, want production and test-only violations")
	}
	out := stderr.String()
	for _, want := range []string{
		"pkg/platform/runtimeinput/config.go",
		"pkg/platform/runtimeinput/config_test.go",
		"[class=production]",
		"[class=test-only]",
		"violation counts: production=1 test-only=1",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("run() stderr = %q, want %q", out, want)
		}
	}
	if got, want := err.Error(), "[agent-factory:ownership-boundary] found 2 new violation(s) and 0 stale baseline entries"; got != want {
		t.Fatalf("run() error = %q, want %q", got, want)
	}
}

func TestScanClassifiesInitializerMappingAndPeerEdgesBySourceClass(t *testing.T) {
	root := fixtureRepository(t, map[string]string{
		"pkg/services/factory_runtime/doc.go":                 "package factory_runtime\n",
		"pkg/services/factory_sessions/doc.go":                "package factory_sessions\n",
		"pkg/services/factory_runtime/internal/engine/doc.go": "package engine\n",
		"pkg/initializer/coordinate.go": `package initializer
import runtime "github.com/portpowered/infinite-you/pkg/services/factory_runtime/internal/engine"
var _ runtime.Service
`,
		"pkg/initializer/coordinate_test.go": `package initializer
import runtime "github.com/portpowered/infinite-you/pkg/services/factory_runtime/internal/engine"
var _ runtime.Service
`,
		"pkg/transports/mapping/process.go": `package mapping
import "os/exec"
var _ = exec.Command
`,
		"pkg/transports/mapping/process_test.go": `package mapping
import "os/exec"
var _ = exec.Command
`,
		"pkg/services/factory_sessions/consume.go": `package factory_sessions
import engine "github.com/portpowered/infinite-you/pkg/services/factory_runtime/internal/engine"
var _ engine.Service
`,
		"pkg/services/factory_sessions/consume_test.go": `package factory_sessions
import engine "github.com/portpowered/infinite-you/pkg/services/factory_runtime/internal/engine"
var _ engine.Service
`,
	})

	findings := scanFixture(t, root)
	assertClassifiedFindingPair(t, findings, ruleInitializerServiceImplementation)
	assertClassifiedFindingPair(t, findings, ruleMappingProcess)
	assertClassifiedFindingPair(t, findings, rulePeerServiceImplementation)
}

func TestScanIgnoresGeneratedOwnershipSources(t *testing.T) {
	root := fixtureRepository(t, map[string]string{
		"pkg/services/factory_runtime/doc.go":                 "package factory_runtime\n",
		"pkg/services/factory_sessions/doc.go":                "package factory_sessions\n",
		"pkg/services/factory_runtime/internal/engine/doc.go": "package engine\n",
		"pkg/platform/runtimeinput/generated_test.go": `// Code generated by ownership test. DO NOT EDIT.

package runtimeinput
import _ "github.com/portpowered/infinite-you/pkg/services/factory_runtime"
`,
		"pkg/services/factory_sessions/generated_test.go": `// Code generated by ownership test. DO NOT EDIT.

package factory_sessions
import _ "github.com/portpowered/infinite-you/pkg/services/factory_runtime/internal/engine"
`,
	})

	findings := scanFixture(t, root)
	for _, item := range findings {
		if strings.Contains(item.FilePath, "generated_test.go") {
			t.Fatalf("generated source produced ownership finding: %#v", item)
		}
	}
}

func TestTestOnlyBaselineIsExactClassBearingAndStale(t *testing.T) {
	const (
		sourcePath = "pkg/platform/runtimeinput/config_test.go"
		target     = modulePath + "/pkg/services/factory_runtime"
		source     = `package runtimeinput
import runtime "github.com/portpowered/infinite-you/pkg/services/factory_runtime"
var _ runtime.Service
`
	)

	t.Run("active exact test-only entry passes", func(t *testing.T) {
		root := fixtureRepository(t, map[string]string{
			"pkg/services/factory_runtime/doc.go": "package factory_runtime\n",
			sourcePath:                            source,
		})
		writeBaseline(t, root, baselineEntryForClass(rulePlatformDomainImport, sourcePath, target, testOnlySourceClass))
		var stdout, stderr bytes.Buffer
		if err := run(config{root: root}, &stdout, &stderr); err != nil {
			t.Fatalf("run active test-only baseline: %v; stderr=%s", err, stderr.String())
		}
		if !strings.Contains(stdout.String(), "1 deletion-only baseline") {
			t.Fatalf("stdout = %q, want active baseline summary", stdout.String())
		}
		if !strings.Contains(stdout.String(), "violation counts: production=0 test-only=0") {
			t.Fatalf("stdout = %q, want zero class-separated violation counts", stdout.String())
		}
	})

	t.Run("stale test-only entry is labeled and blocking", func(t *testing.T) {
		root := fixtureRepository(t, map[string]string{
			"pkg/services/factory_runtime/doc.go": "package factory_runtime\n",
		})
		writeBaseline(t, root, baselineEntryForClass(rulePlatformDomainImport, sourcePath, target, testOnlySourceClass))
		var stdout, stderr bytes.Buffer
		err := run(config{root: root}, &stdout, &stderr)
		if err == nil || !strings.Contains(stderr.String(), "stale baseline") {
			t.Fatalf("run stale test-only baseline err=%v stderr=%q", err, stderr.String())
		}
		for _, want := range []string{
			"[class=test-only]",
			"violation counts: production=0 test-only=1",
		} {
			if !strings.Contains(stderr.String(), want) {
				t.Fatalf("stderr = %q, want %q", stderr.String(), want)
			}
		}
	})

	t.Run("test-only entry must declare its class", func(t *testing.T) {
		root := fixtureRepository(t, map[string]string{
			"pkg/services/factory_runtime/doc.go": "package factory_runtime\n",
			sourcePath:                            source,
		})
		writeBaseline(t, root, baselineEntryFor(rulePlatformDomainImport, sourcePath, target))
		var stdout, stderr bytes.Buffer
		err := run(config{root: root}, &stdout, &stderr)
		if err == nil || !strings.Contains(err.Error(), "requires an explicit class") {
			t.Fatalf("run missing test-only class err=%v, want explicit-class diagnostic", err)
		}
	})

	t.Run("wildcard and duplicate entries are rejected", func(t *testing.T) {
		root := fixtureRepository(t, map[string]string{
			"pkg/services/factory_runtime/doc.go": "package factory_runtime\n",
			sourcePath:                            source,
		})
		wildcard := baselineEntryForClass(rulePlatformDomainImport, sourcePath, target+"/*", testOnlySourceClass)
		writeBaseline(t, root, wildcard)
		var stdout, stderr bytes.Buffer
		err := run(config{root: root}, &stdout, &stderr)
		if err == nil || !strings.Contains(err.Error(), "cannot contain wildcards") {
			t.Fatalf("run wildcard baseline err=%v, want exact-identity diagnostic", err)
		}

		root = fixtureRepository(t, map[string]string{
			"pkg/services/factory_runtime/doc.go": "package factory_runtime\n",
			sourcePath:                            source,
		})
		entry := baselineEntryForClass(rulePlatformDomainImport, sourcePath, target, testOnlySourceClass)
		writeBaseline(t, root, entry, entry)
		err = run(config{root: root}, &stdout, &stderr)
		if err == nil || !strings.Contains(err.Error(), "duplicate entry") {
			t.Fatalf("run duplicate baseline err=%v, want duplicate diagnostic", err)
		}
	})
}

func TestCreateBaselineRecordsSourceClass(t *testing.T) {
	const sourcePath = "pkg/platform/runtimeinput/config_test.go"
	root := fixtureRepository(t, map[string]string{
		"pkg/services/factory_runtime/doc.go": "package factory_runtime\n",
		sourcePath: `package runtimeinput
import runtime "github.com/portpowered/infinite-you/pkg/services/factory_runtime"
var _ runtime.Service
`,
	})
	var stdout, stderr bytes.Buffer
	if err := run(config{root: root, createBaseline: true}, &stdout, &stderr); err != nil {
		t.Fatalf("create test-only baseline: %v; stderr=%s", err, stderr.String())
	}

	data, err := os.ReadFile(filepath.Join(root, baselineFile))
	if err != nil {
		t.Fatalf("read created baseline: %v", err)
	}
	var recorded baseline
	if err := json.Unmarshal(data, &recorded); err != nil {
		t.Fatalf("decode created baseline: %v", err)
	}
	if len(recorded.Entries) != 1 || recorded.Entries[0].Class != string(testOnlySourceClass) {
		t.Fatalf("created baseline entries = %#v, want one explicit test-only entry", recorded.Entries)
	}
}

func TestOwnershipFindingKeysIncludeSourceClass(t *testing.T) {
	production := finding{Rule: rulePlatformDomainImport, FilePath: "pkg/platform/runtimeinput/config.go", Target: "target", Class: productionSourceClass}
	testOnly := production
	testOnly.Class = testOnlySourceClass
	if findingKey(production) == findingKey(testOnly) {
		t.Fatalf("finding keys collapsed source classes: %q", findingKey(production))
	}

	productionEntry := baselineEntry{Rule: production.Rule, FilePath: production.FilePath, Target: production.Target, Class: string(production.Class)}
	testOnlyEntry := productionEntry
	testOnlyEntry.Class = string(testOnly.Class)
	if entryKey(productionEntry) == entryKey(testOnlyEntry) {
		t.Fatalf("baseline keys collapsed source classes: %q", entryKey(productionEntry))
	}
}

func assertClassifiedFindingPair(t *testing.T, findings []finding, rule string) {
	t.Helper()
	var production, testOnly int
	for _, item := range findings {
		if item.Rule != rule {
			continue
		}
		switch item.Class {
		case productionSourceClass:
			production++
		case testOnlySourceClass:
			testOnly++
		default:
			t.Fatalf("rule %q has invalid source class: %#v", rule, item)
		}
	}
	if production != 1 || testOnly != 1 {
		t.Fatalf("rule %q class counts = production:%d test-only:%d; findings=%#v", rule, production, testOnly, findings)
	}
}

func baselineEntryForClass(rule, filePath, target string, class boundarySourceClass) baselineEntry {
	return baselineEntry{
		Rule: rule, FilePath: filePath, Target: target, Class: string(class),
		Stage: baselineStage, DeletionGate: deletionGates[rule],
	}
}
